### ISSUE TITLE
Lighting changes when rendering resolution changes

### ISSUE THREAD

**Issue by Anthony-Gaudino** [buddhi1980/mandelbulber2#101]
When I render an image with different dimensions the lighting seems to change.

1920x1080:

![1920x1080](https://cloud.githubusercontent.com/assets/2439728/16178574/adac10aa-3622-11e6-8558-a708929c28ac.png)

960x540:

![960x540_original](https://cloud.githubusercontent.com/assets/2439728/16178576/c8f0254a-3622-11e6-9993-f4ad321de012.png)

Comparison:
![comparison](https://cloud.githubusercontent.com/assets/2439728/16178674/94be0dac-3625-11e6-8cf1-dab223ff5549.png)

It seems like if that area on the lower resolution render has less shadows or different lighting intensity.

I don't know if after changing rendering resolution I must also change some lighting setting, or if I'm actually wrong and the rendering is correct.

**Comment by buddhi1980** [comment]
It's not the lighting problem, and I have to say that it behave in correct way. When you increase image resolution then the program adapts accuracy of light rays calculation to current resolution. So in high resolution minimum detail size gets to be much smaller, so shadows of these thin details are less visible.

**Comment by Anthony-Gaudino** [comment]
Is there any way to make the images equivalent?
Same lighting conditions on different rendering resolutions?

I'm asking this because it would be used to train a neural network to upscale images, please see: nagadomi/waifu2x#121

**Comment by mclarekin** [comment]
My random thoughts (and I may have made wrong assumptions)  :-

To me, the issue is kind of fractal specific, I think I notice it more when
the fractal  has a lot lot of fine texture, so when I increase the
resolution I gain more fine detail from the fractal formula, this then
casts more shadow and the image can appears less shiny.

 An algorithm that can alter shadow strength in respect to resolution may
assist, but the result may vary dependent on the individual fractal.

**Comment by Anthony-Gaudino** [comment]
@mclarekin, I took into account the fractal resolution as described here: http://wiki.mandelbulber.com/index.php?title=Tips_and_Tricks

The fractal details don't seem to have changed, only lighting.

----

After tinkering with the settings, it seems that activating the `Non-DE shading mode` and using the `Multiple rays with light map` ambient occlusion seems to basically solve the problem, but also greatly increases rendering time.

![de_mrao1](https://cloud.githubusercontent.com/assets/2439728/16234129/edcb196c-37a6-11e6-9e0e-422a7bfe0a18.png)
![de_mrao2](https://cloud.githubusercontent.com/assets/2439728/16234136/f4439ddc-37a6-11e6-8ae2-4c3cbe2146a5.png)

**Comment by buddhi1980** [comment]
Implemented rendering engine cannot guarantee 100% the same results for every resolution. Rendering is based on numeric methods which always gives a little different results depends on calculation step and boundary value. Many of algorithms are also simplified to get reasonable rendering time. All of that cause that small differences.
If you need exactly the same image with different resolution, my recommendation will be to render image in very high resolution and and downscale the image to needed lower resolution. Then you can test your upscaling algorithms and compare results with high resolution master image.

There is one thing which could be helpful for you, if you need low detail images for experiments. You can render image with reduced detail level parameter (rendering engine tab) abd get image like this one:
![low detail](https://cloud.githubusercontent.com/assets/11696990/16236461/c7adef70-37d8-11e6-9fc8-b28bb5726268.jpg)

**Comment by Anthony-Gaudino** [comment]
I know that it won't be 100%, but it would be much closer to how real life works compared to downscaling the image.

Resizing introduces imperfections and artifacts, see the cornell box 512x512px comparison on nagadomi/waifu2x#121 and you will notice that the edges of the box look much better on the rendered image than the downsized one.

----

I liked the result after I changed the settings, the only problem is the increase in rendering time, reducing the fractal details has low impact on rendering time.
