### ISSUE TITLE
Positioning of textures

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#104]
Implementation of following mouse click sequence to position the texture:
- Indicate point where top left corner should be placed
- Then indicate top right corner to set horizontal scaling 
- Finally indicate bottom left corner to set vertical scaling

**Comment by mclarekin** [comment]
same as this ?
https://mail.google.com/mail/u/0/#sent/155b472786c62386?compose=155c947a0b1b60c2

The weird thing is I thought that when I tested this some months ago I
could move the texture.



also refer
https://mail.google.com/mail/u/0/#inbox/155154e0488c5be8?compose=155c947a0b1b60c2
where I raised some possible enhancements like:

 colorTextureFromImage should have it's own orientation controls,
independent of the other textures

inclusion of alpha channel




On Sun, Jul 10, 2016 at 2:34 AM, Krzysztof Marczak <notifications@github.com

**Comment by mancoast** [comment]
@buddhi1980 @mclarekin 
Any updates? I want to test this feature.

**Comment by mclarekin** [comment]
What happened here was a coding bug that was fixed by Krzystof, quote:
The weird thing is I thought that when I tested this some months ago I
could move the texture.



but I added some other possible enhancements relating *only to* the
colorTextureFromImage.  What it means is you can use a primitive object
(most commonly a flat plane) and apply a jpg to it and position it where
you want it. Similar to flat background.  It is a nice to have enhancement.

**Comment by mclarekin** [comment]
flat plane,, ??? oops I meant rectangle.   refer
https://mail.google.com/mail/u/0/#inbox/155154e0488c5be8?
compose=155c947a0b1b60c2

**Comment by mancoast** [comment]
Does this feature require action?
Does the placement of jpg rectangles function in current state of art?
I want to test this ASAP. high value

**Comment by mclarekin** [comment]
I need to test it out again to remind myself.

Does the placement of jpg rectangles function in current state of art?
Yes, Material Manger implementation made this possible,  but it it is not
independent of the other texture controls.

Additionally we want to be  able to use .png with alpha channel. I cannot
remember if this part has been implemented

I suggest you check out the current state, it is a lot of fun

**Comment by mancoast** [comment]
top o' line; State o' Art; Mandelbulber Fractals

**Comment by zebastian** [comment]
Is this still todo, or is this redundant?

**Comment by mclarekin** [comment]
Yes there are things here to evaluate for implementation.

I need to go though them all and cleraly list what has yet to be evaluated.

**Comment by mclarekin** [comment]
there was a bug, it was fixed.

the rest is enhancements

 I  will close and start new issue for enancements
