### ISSUE TITLE
Some sliders are jumping under Win 10

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#105]
This is example of jumping slider reported by taurus

![image](https://cloud.githubusercontent.com/assets/11696990/16708412/1e44174c-45f3-11e6-9fd5-b9566028b104.png)

**Comment by mclarekin** [comment]
Is this the same thing as Dials and Sliders in Ubuntu that we were looking
at just prior to release?

On Sun, Jul 10, 2016 at 2:36 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
@mclarekin , it's not he same problem

Bug fix is done. It has to be tested under different systems.

**Comment by buddhi1980** [comment]
Fixed
