### ISSUE TITLE
Enabled Distributed Render: Allow Client to connect to multiple servers

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#106]
Hello,

I aim to start a dialogue describing the exact requirements to enable support for multiple servers within a single client instance.

Looking forward to working with you!

**Comment by mclarekin** [comment]
Hi mancoast

I am not a programmer, just an apprentice fractal formula coder so I look
forward to watching you guys working together..

It is so good to see help and feedback coming in, thanks

Graeme

**Comment by buddhi1980** [comment]
This feature is already implemented. There is NetRender option, which allows to connect multiple computers to main one and render together the same image or animation.

**Comment by zebastian** [comment]
I think @mancoast wants one client <-> multiple servers.
right now we only support one server <-> multiple clients.
IMHO thats really hard to implement and brings not that much gain on this level.
@mancoast do you have a specific use case / server client setup in which this feature would be suitable?

**Comment by mancoast** [comment]
Hello,
I am rendering 8k equiractangular animations using xeon phi k1om for VR goggles. Cross compilation for k1om native application was difficult, but no issues remain. Currently I am using a python driver with multiprocessing.queue to distribute sets of 10 frames across each xeon phi board. Ideally, I would like to enable a c++ solution that distributes render frames using a similar fashion. I am seeing a ~10-15 minutes of spin up time each time the headless application is launched on a k1om board.

Thanks!

**Comment by zebastian** [comment]
xeon phi compilation sounds exciting! Can you give us more information how you compiled, so we can add this to the README?
~10-15 minutes spin up time is pretty long, i think you are starting mandelbulber on each node for every frame, which is unnecessay.
If the program runs in client mode it should continiously wait for something todo.
I am assuming you are using linux nodes with xeon phis and having one controller which distributes the jobs.
on each node you can start the program with:
```mandelbulber2 -n --host 192.168.123.1```
with 192.168.123.1 ip address of master node.
On the controller you can render with:
```mandelbulber2 -n --server path/to/animation.fract```
The mandelbulber2 instances on the nodes will stay 'alive' till you stop them on the nodes.
No need for any mediating infrastructure software.
Is this the way you tried?
Please explain if i am getting something wrong...

**Comment by mancoast** [comment]
I will prepare an extensive PDF for documentation. The 240 cores for k1om crush render time, but the objective is to simplify compilation and technically communicate feasibility. It is feasible.

**Comment by mclarekin** [comment]
I would be interested sometime n the future to see how fast some standard
images are rendered with your the 240 cores, sounds really impressive.

**Comment by mancoast** [comment]
Hello,

The "--server" and "-n" arguments establish the targeted distributed behavior.

Placed all the dependencies and system setup info here:
https://github.com/mancoast/KNC-Lib/

The k1om build script is here:
https://raw.githubusercontent.com/mancoast/mandelbulber2/k1om/build.bot.sh


Thanks!
-coast

**Comment by zebastian** [comment]
You are welcome,

I added "Centos 7 Intel MIC K1OM Development" to the trophy chapter in the README on TESTED ON
https://github.com/buddhi1980/mandelbulber2/commit/658bbe768bc5329f6d2334305e4e3dafa21a5832

BTW: You can also contact us on fractalforums here http://www.fractalforums.com/mandelbulber
Cheers!
