### ISSUE TITLE
Old_settings importer defect

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#108]
Msvc changes introduced problems
http://www.fractalforums.com/bug-reporting-b231/still-issues-importing-v1-21/msg94704/#new
Mandelbox_ not hanfled properly.

**Comment by buddhi1980** [comment]
We need to patch 2.08 code to release bug fix (2.08-2).

**Comment by zebastian** [comment]
I created a new branch for the fixes: 
https://github.com/buddhi1980/mandelbulber2/commit/8b2157d56ea634c74c2a7c6d99dc616125046d1d
bugfixes can be done there. Since the whole code base has changed, these changes cannot be merged with master and have to be done twice for master too and commited by hand.

**Comment by buddhi1980** [comment]
Works properly in 2.08-2 branch
