### ISSUE TITLE
Statistics are not calculated properly

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#111]
Example: 

![image](https://cloud.githubusercontent.com/assets/11696990/17080234/c94a252a-5127-11e6-9c68-936024984ada.png)

**Comment by mclarekin** [comment]
Yes, it has been confusing me :)

On Sun, Jul 24, 2016 at 8:50 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
Fixed
