### ISSUE TITLE
Re-look at length of formula names

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#112]
Consider options to make formula names shorter.

**Comment by buddhi1980** [comment]
What do you think to add another field with short name? Then in combo box (fractal selection) will be long name, but on hybrid tabs will be short one.

**Comment by mclarekin** [comment]
That is a good way. , better than shortening the list names.
The only other way is to place the formula UI's slots vertically down the screen but retaining horizontal labelling (if I described that well?). 

Over to you decide.  

I don't really expect many users to experiment with nine tabs ,so it is just a minor problem

**Comment by mancoast** [comment]
I want to rename the formulas using Oxford English word bank with "brot" suffix ==> ****brot's
http://www.nytimes.com/2010/10/17/us/17mandelbrot.html
@mclarekin What are your thoughts?

**Comment by mclarekin** [comment]
Example, as I am not quite sure what you mean ?  what would be msltoe
Juliabulb be called?


Anything is OK by me as long as Krzyzstof is happy as he has been in the
Fractal scene longer than me, (I try to use the name used by the author).


But  I think it would be good to  relook at all the naming, as some
fractals&transforms could be named better and the length is a problem

ie smooth mandelbox -> mandellbox smooth

transform fabs add constant V2 , i now know should have been transform
Tglads fold

all transforms could be simply T_  instead of Transform_

Screenshot shows that I can only see 2  or 3  slots without reducing the
render window.

Those are my random thoughts :)

**Comment by zebastian** [comment]
T_ instead of Transform_ 
--> Thats a great idea
Also it would be good to unify the writing style (underscore vs no underscore vs whitespace, what to write in capital letters, etc)
In general i would do a full rename only where it 
- makes the formula way more readable
- puts a wrong formula name in correct context
- for relatively new formulas

Since a lot of people are using the formulas often and got used to the formula names, this may confuse some.
When we change a formula name completely, the internal name may also change. When this is the case, also the xxx.ui file, the xxx.png file has to be renamed.

**Comment by mclarekin** [comment]
M3D uses _,  T_is better :)

These are random thoughts,

There is future proofing the project.  Are we likely to have to eventually
implement a  few dropdown menu lists? There could be Mandlebulbs  as a List
Title, and in the list we could have Mbulb Multi, Mbulb 4, users would
automatically  associate Mbulb with Mandelbulb. The list size is currently
not too big, but I think that at least the transforms should be separated
from the formulas and become search-able by typing  the first letter after
T_.  If we had a list entitled Transforms then T_ will be associated with
Transforms.








On Sat, Jan 14, 2017 at 10:21 PM, Sebastian Jennen <notifications@github.com

**Comment by mancoast** [comment]
All Great ideas!

for fractal naming convention, consider Bristorbrot by Doug Bristor.
If I make a formula, consider Coastalbrot by Rob Pancoast.
etc.., etc...

**Comment by mclarekin** [comment]
I think we need to retain the names given by the formula authors. And I am
not sure if ...brot is right for linear folding types.  However, these sort
of decisions I leave to Krzysztof.

The formulas that I have implemented are  all existing formulas.  I have
only created some new transforms and variations to existing formulas.
Transform names need to reflect what the transform does.

But I do await the first Coastalbrot :)

**Comment by zebastian** [comment]
@mclarekin 
do we still want the shortname, or are the names in the list now short enough with the new naming convention?

**Comment by mclarekin** [comment]
I think the new naming convention has made a big improvement.

I suggest we can close this issue

**Comment by zebastian** [comment]
Alright
