### ISSUE TITLE
Frame rate enhancement

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#113]
Implement being able to choose different frame rates between keyframes.

**Comment by mancoast** [comment]
Is it safe to assume that the requirements for this enhancement involve major rework and revision?
What milestone do you have in mind @buddhi1980 ?

**Comment by zebastian** [comment]
suggestion: 
the "seconds per frame" setting is the lower and upper bound of the render of a frame:
- upper bound (already present)
--> when the timeout of the upper bound is reached stop the rendern, when not yet finished.
- lower bound (new)
--> when the rendering is faster than "seconds per frame" wait till rest of time of "seconds per frame" is reached and then proceed with the next frame

This way we can achieve a stable frame rate, which makes flight control more easy. This is now a topic since the rendering is becoming so fast lately, that more often you can get under the lower bound of the rendering :-)

@buddhi1980 / @mclarekin / @mancoast What do you think?

**Comment by mclarekin** [comment]
"This way we can achieve a stable frame rate, which makes flight control
more easy."

Sounds sensible. I still have yet to test out flight animation properly.

This reminds me has anyone checked out    issue #484   item e) for
reproducibility

"I have first frame to render 145 and last frame to render 185. I want to
change last frame to 205. When i enter 2, the first frame to render resets
to 2. Can this be reproduced?





# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
anim_keyframe_dir C:\Users\Graeme\mandelbulber\animation\pk 60\;
camera 0 -10 0;
camera_distance_to_target 10;
camera_rotation 0 0 0;
camera_top 0 0 1;
flight_last_to_render 0;
formula_1 67;
formula_2 1002;
formula_3 1065;
fov 0.5;
fractal_rotation 0 -54 0;
frames_per_keyframe 60;
hdr true;
hybrid_fractal_enable true;
image_height 800;
keyframe_first_to_render 1;
keyframe_last_to_render 187;
main_light_alpha 0;
main_light_beta 0;
mat1_coloring_palette_size 250;
mat1_coloring_random_seed 535927;
mat1_is_defined true;
mat1_metallic true;
mat1_surface_color_palette ba7a76 a500a2 ffc4a8 1d00c2 c6fd63 6fc374 593bf1
965823 e44ad6 9e2b00 9ed34b 9bfbfa caaef9 78668b a7947d dbe4be 006244
726ee1 98ae00 c4fc50 d590a1 ffe44f ffffff c376b5 660063 a2bc45 71edc2
0ef3fc ff78ff 3263ff 7948c0 392749 b4bdab ff445d aac656 c82c5e 00d5a2
67b1c6 591b24 24142c 2205c4 d3ff69 88777a 0015e5 003b58 726468 56876d
dce4b1 6ab93c 5d2610 5aa37d e0ffe4 add677 00510c c4697a 7d46ff 8d7b53
f749db 714489 8e4fb2 c67257 54d730 ff917a 9c9ebc 0ed189 542093 ff482f
0f4164 21d14c 49f3d2 ab3f94 99ffb7 112c1c bdc500 5b0000 64c2af 171d68
d64755 ffc7a8 ff5e65 a8e30b 2effd4 a0ffff 01ccdb 00b5d0 62e464 720a63
a7c200 ff7352 ff999b 6a3eff e47fb3 59ffff 39d236 d88335 407032 ce9739
e1fadb 62ab00 7b700e 449ad3 009f53 52ffbb b08daa 0f000f 3b4700 ffd5e6
75d200 bb82ff a22800 ca5913 c35dbf 94b849 c67e45 6d4af7 0ebba1 4cbb80
ffd617 81c82e 9dbe26 490f26 47218d 007ea2 273cd7 8ff941 8037cc 64e726
cdd16d 4f4600 5d0900 ffff86 228ecb 999e7a 007f00 546ec2 b1e597 77dcb4
3d9105 7b9599 ffff4e 06ca4b 883044 ff462f fa36d3 38ff41 88e029 ebffea
6c8a12 69d3af 6e3f7e 85298a ffffff 4e2d52 d2c6d2 9488c8 4a2fe2 a80000
dfecb2 7c1100 0017d6 4c6464 de0022 b00000 8263ff 616067 346df8 1897e1
9a24c5 c6a8ba a7af47 080087 4cba47 6b6e95 637a9c caabe5 88cf2b 3c180b
615489 f8caf9 6e6129 00c409 002636 305ba6 93ec67 51997b 498a6c e65860
783e25 8bede4 29342b 94678e 9effff 5cd889 009600 4aa085 fd6c8a 674b99
70df48 ffd6ff 82fd92 e1eb00 ab378c 432f28 1e2748 531d90 948b85 406bc5
000c68 007303 932e81 a6bf85 ffffca b3b7ff 494f14 6effc7 9fdf35 ff8af2
b47d58 3e4e35 c5025b 294700 457a1e 665848 2643c6 75876f f4c734 0ae79a
327beb 000067 926099 17d6e6 6ea3ff bdffcc 0e4f60 d3cd68 6b520d 2414c0
164e4c 8168ca aedec9 99be52 ac49ff 6a3aff 5bfff6 b330e3 009536 b6fbff
656722 9dcbff 842c61;
mat2_is_defined true;
mat2_surface_color 2300 d800 2300;
primitive_sphere_1_enabled true;
primitive_sphere_1_material_id 2;
primitive_sphere_1_radius 2;
raytraced_reflections true;
view_distance_max 27.43938382754794;
[fractal_1]
IFS_rotation_enabled true;
transf_constant_julia_mode true;
transf_constant_multiplier_100 0 0 0;
transf_rotation_enabled true;
transf_stop_iterations_D 1;
[fractal_2]
IFS_rotation_enabled true;
transf_rotation 180 0 0;
[fractal_3]
IFS_rotation_enabled true;
transf_function_enabledz false;
transf_offset_111 0 0 0;
[fractal_4]
IFS_rotation_enabled true;
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;fractal1_transf_rotation_x;fractal1_transf_rotation_y;fractal1_transf_rotation_z;fractal0_transf_constant_multiplier_100_x;fractal0_transf_constant_multiplier_100_y;fractal0_transf_constant_multiplier_100_z;fractal0_transf_offset_000_x;fractal0_transf_offset_000_y;fractal0_transf_offset_000_z;fractal0_transf_rotation_x;fractal0_transf_rotation_y;fractal0_transf_rotation_z;main_mat1_coloring_palette_offset;main_mat2_surface_color_R;main_mat2_surface_color_G;main_mat2_surface_color_B;fractal2_transf_offset_111_x;fractal2_transf_offset_111_y;fractal2_transf_offset_111_z;main_primitive_sphere_1_radius;fractal2_transf_offset_000_x;fractal2_transf_offset_000_y;fractal2_transf_offset_000_z;main_fractal_rotation_x;main_fractal_rotation_y;main_fractal_rotation_z;main_DE_factor
0;0;-10;0;0;0;0;0;0;1;90;0;0;0;0;0;0;0;0;0;0;0;0;8960;55296;8960;0;0;0;2;0;0;0;0;-54;0;1
1;0;-7.071067811865476;-7.071067811865476;0;0;0;0;-0.7071067811865481;0.7071067811865469;90;0;0;0;0;0;0;0;0;0;0;0;0;8960;55296;8960;0;0;0;1.75;0;0;0;0;-54;0;1
2;0;-6.123233995736767e-16;-10;0;0;0;0;-1;6.123233995736766e-17;90;0;0;0;0;0;0;0;0;0;0;0;0;8960;55296;8960;0;0;0;1.5;0;0;0;0;-54;0;0.7
3;0;7.071067811865475;-7.071067811865476;0;0;0;-8.65956056235494e-17;0.7071067811865481;0.7071067811865469;90;0;0;0;0;0;0;0;0;0;0;0;0;8960;55296;8960;0;0;0;1.25;0;0;0;0;-54;0;0.7
4;0;10;-1.224646799147353e-15;0;0;0;0;0;1;0;0;0;0;0;0;0;0;0;0;0;0;0;8960;55296;8960;0;0;0;1;0;0;0;0;-54;0;0.7
interpolation;morphLinear;morphLinear;morphLinear;morphLinearAngle;morphLinear;morphLinear;morphLinearAngle;morphLinear;morphLinear;morphLinear;morphLinear;morphLinear;morphLinearAngle;morphLinear




On Mon, Jul 23, 2018 at 12:52 AM, Sebastian Jennen <notifications@github.com
