### ISSUE TITLE
QSystemTrayIcon for messaging and simple control

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#122]
IMHO: It would be nice to have a notification tray to show messages (Render finished / error occured)
This could also be used for simple control (Render / Render animation / Stop)
This way the program can be monitored and controlled without the main window. 
This may be useful for time consuming tasks, like rendering animation / big images.
Qt makes it fairly easy to implement: http://doc.qt.io/qt-5/qsystemtrayicon.html

What do you think?

**Comment by buddhi1980** [comment]
Good idea. I see this is not platform dependent.

**Comment by zebastian** [comment]
yes, i already did a small test under ubuntu16.4 which showed just fine. 
most linux /  windows / osx should support it. thats only a place to show data and controls reduntantly for comfort. So there should be no harm, if a system does not support it.

**Comment by zebastian** [comment]
now it is pretty much, how i have imagined it, do you have some ideas for enhancing it?

**Comment by buddhi1980** [comment]
Can you add option to notify also when rendering single image is finished?

**Comment by zebastian** [comment]
good idea, I added notification for image render: https://github.com/buddhi1980/mandelbulber2/commit/032b59742c07faf2a325c253633aa9d6acb2fabe

**Comment by zebastian** [comment]
done for the time being (2.0.9)
