### ISSUE TITLE
Update Bristorbrot formula

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#127]
Use this code got from Doug Bristor:

```
/** 
* Bristorbrot formula 
* for mandelbulber_v2 // fractal_formulas.cpp
* 
* including 4D parameter 
* double w = fractals.GetFractal(fractalIndex)->transformCommon.offset0; // compute_fractal.cpp
* @reference https://code.google.com/archive/p/fractaldimension/
* by Doug Bristor
* *** constant is added outside the function ******
*/
/** --- short hand ----
double neww = w * ( 2.0 * z.x + z.y + z.z);
z = CVector3(z.x * z.x - z.y * z.y - z.z * z.z - w * w , z.y * (2.0 * z.x - z.z - w) , z.z * (2.0 * z.x + z.y - w) );
w = neww;
*/
void BristorbrotIteration(CVector3 &z, double &w, sExtendedAux &aux)
{
aux.r_dz = aux.r_dz * 2.0 * aux.r;
double newx = z.x * z.x - z.y * z.y - z.z * z.z - w * w;
double newy = z.y * (2.0 * z.x - z.z - w);
double newz = z.z * (2.0 * z.x + z.y - w);
w = w * ( 2.0 * z.x + z.y + z.z); 
z.x = newx;
z.y = newy;
z.z = newz;
}
```

**Comment by mclarekin** [comment]
I assume I will create new formula Bristorbrot 4D, not update existing.

On Sat, Aug 20, 2016 at 5:13 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
a) Committed a draft, it is hacked to work around

 double w = fractals.GetFractal(fractalIndex)->transformCommon.offset0;
// compute_fractal.cpp

and will only work in slot 1 if in hybrid mode.

b) other 4D formulas currently use w, so should they each have an
individual initial_w.?

c) It should be eventually written as a z4D CVector4, so can have
other  4D transforms in the 4D loop.

**Comment by mclarekin** [comment]
Bristorbrot4D

Krzysztof,   could you set up

double w  = fractals.GetFractal(fractalIndex)->transformCommon.offset0;

by installing an "initial w" spinbox in  Global Parameters (or preferably
on the actual formula UI).

I will then get back to this formula after I do some more pseudo klienian
stuff.

**Comment by buddhi1980** [comment]
You will have w-axis initial value on both places like Julia constant

**Comment by buddhi1980** [comment]
Modification done. It will also works properly with booleans
