### ISSUE TITLE
Feature Request: Support Seamless 16:9 (1.78:1) Equirectangular Aspect Ratio

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#128]
Greetings!

These resolutions are optimal for video editing software and streaming services.

4K UHD resolution of 3840 pixels × 2160 lines, aspect ratio 16:9 (1.78:1), 8.3 megapixels
8K UHD resolution of 7680 pixels × 4320 lines, aspect ratio 16:9 (1.78:1), 33.2  megapixels

Thanks,
coast

**Comment by buddhi1980** [comment]
It's a good idea. I will change aspect ratio from fixed 2:1 to be taken from image resolution. This change will affect only equirectangular projectiion

**Comment by buddhi1980** [comment]
Done. Now image is seamless in every resolution when equirectangular perspective is selected
