### ISSUE TITLE
description field in settings file

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#131]
- add a description field to the settings. This will be saved with the settings and displayed inside the fractal tab.
- should be saved to the top of the settings file, so the file can explan itself, example:

```
# Mandelbulber settings file
# version 2.09
# only modified parameters
[description]
This settings file is based on a simple mandelbox and illustrates the use of the animation renderer.
The keyframes can be rendered image by image and stitched together to a video.
More description....   
More description....   
[main_parameters]
ambient_occlusion_mode 1;
ambient_occlusion_quality 3;
aux_light_colour_1 5400 cd00 e800;
aux_light_colour_2 7e00 f500 de00;
aux_light_enabled_1 true;
```

**Comment by buddhi1980** [comment]
What you think about displaying this description as a popup window? Or as a additional tab in Fractal Tab?
I would not use fractal tab, because there is already a lot of stuff.

**Comment by zebastian** [comment]
maybe at the top of "global parameters" in a resizable textbox?
this would be a nice feature for people sharing their settings in textform, so that you can see at the top what the settings are about (and for yourself after digging out settings that are 6 months old :) )
