### ISSUE TITLE
DE Function notification popup is incomplete

### ISSUE THREAD

**Issue by capn-damo** [buddhi1980/mandelbulber2#133]
Render Engine tab, Distance Estimation Function dropdown box includes "Delta DE Pseudo Kleinian" but the notification popup doesn't include it, or a description.

**Comment by zebastian** [comment]
@buddhi1980 when we are doing ui round up for next version can you also update this tooltip?

**Comment by zebastian** [comment]
missing description has been added in this commit: https://github.com/buddhi1980/mandelbulber2/commit/ec7aef9aa6d004117dc0011635dc349c921839a3
