### ISSUE TITLE
How I install mandelbulber2 under linux ?

### ISSUE THREAD

**Issue by BogusCurry** [buddhi1980/mandelbulber2#136]
Hello ;D
I have download the file for linux and now ?

When I run the file install in the console, comes this 
`qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
make: *** Keine Regel, um »clean« zu erstellen.  Schluss.
mv: Aufruf von stat für »makefiles/mandelbulber2“ nicht möglich: Datei oder Verzeichnis nicht gefunden
Executable file does not exist. Probably the program was not compiled properly.`

So I hope you can help me ?

Greetings

Bogus

**Comment by buddhi1980** [comment]
Please read included README file

**Comment by buddhi1980** [comment]
If you cannot find README, it's also here: https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/deploy/README

**Comment by zebastian** [comment]
@BogusCurry please reopen if you still experience any issue / or the explanation in README has been unclear somehow.
