### ISSUE TITLE
To move .mandelbulber to mandelbulber folder under Linux

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#138]
There would be good to have mandelbulber work dir as a not hidden folder. Some of items like undo, mandelbulber.ini can stay in .mandelbulber folder
This can be a task for 2.10

**Comment by zebastian** [comment]
buddhi: We will keep this hidden .mandelbulber folder only for mandelbulber.ini, undo, queue, toolbar and thumbnails. Settings, images, materials, slices, textures should be located in new non-hidden folder ("mandelbulber" without dot). This change will only touch Linux and OSX. We should add procedure to detect if .mandelbulber folder is already moved and ask user to confirm if he agree to move files to new folder.

**Comment by zebastian** [comment]
@buddhi1980 
do we still need any of the following folders?

result &= CreateFolder(systemData.dataDirectory + "keyframes");
	result &= CreateFolder(systemData.dataDirectory + "paths");
	result &= CreateFolder(systemData.dataDirectory + "undo");
	
do we want to separate [default image / animation images] folder?

**Comment by buddhi1980** [comment]
It's a good question. We don't need them anymore. They were used only in old Mandelbulber.
About image and animation_images folder it could be good to separate them

**Comment by zebastian** [comment]
> About image and animation_images folder it could be good to separate them
I have the same opinion on this. Having the single image renders together with the animation renders is annoying, when post processing animation renders, looking for single renders in a huge bulk of animation images, etc
What do you think about a folder named "animation" where both flight and keyframe images are stored?

**Comment by buddhi1980** [comment]
"animation" folder will be all right

**Comment by zebastian** [comment]
all done with this latest commit: 8950253b1b90e1259d23a6ec50f4d34d04b4c9ef

**Comment by buddhi1980** [comment]
Switching from .mandelbulber to mandelbulber folder shoudl work also in CLI mode

**Comment by mancoast** [comment]
@buddhi1980 Is this 2.10 or 2.11?

**Comment by zebastian** [comment]
@buddhi1980 
Do we still want this for cli? I dont want to bloat the code with a backward compatibility feature anybody hardly ever uses. 
CLI module is in general not really interactive so a user may be more confused to see the question box, than rather stick with the old all .mandelbulber folder thing in old version. Even more a problem, if the program has already been built in in some scripted environment, which assumes no necessary user input.

**Comment by zebastian** [comment]
What are your thoughts on this?

**Comment by mancoast** [comment]
@zebastian 
Can we finish this in 4 weeks?
Will this break for people that had the system operational in the legacy folder?
Is it possible to support both legacy and future folder system?

**Comment by buddhi1980** [comment]
agree with @zebastian . We can close it
