### ISSUE TITLE
To divide render_window.ui to several smaller UIs

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#139]
Actually compilation of render_window.ui consumes a lot of memory. 
There would be good to divide all docks into separate UI files (QWidgets). It could be done similar to cMaterialEditor
This will be first thing which I'm going to do after release of v2.09

**Comment by zebastian** [comment]
Greate idea!

**Comment by zebastian** [comment]
i think this is all done, or do you want to do anymore related to this issue?

**Comment by buddhi1980** [comment]
It's done
