### ISSUE TITLE
Decimal separator on Windows

### ISSUE THREAD

**Issue by jeroenrijckaert** [buddhi1980/mandelbulber2#14]
Some languages like Dutch use a comma for decimal separator symbol. For most programs, the language settings from Windows are used. For example in both M$ Excel and LibreOffice Calc I can use the numerical part of my keyboard to enter numbers pretty fast. The key "Del / dot" below the number 3 is automatically recognized as a comma.

Mandelbulber seems to make chaos on the way fields are entered. Some need a comma, some need a dot. Basically I can't really use the numerical part of the keyboard because of this. It would be nice if all numerical fields can be used in the same way, in the normal way software behaves under M$ Windows.

**Comment by buddhi1980** [comment]
I will work on it. You are right, that it's messy.

**Comment by buddhi1980** [comment]
This problem touched also Linux. Should be correct now, but need more testing because of big number of changes in code.

**Comment by jeroenrijckaert** [comment]
My personal (Linux) PC is still broken. Only got access to a Linux machine over the internet, so compiling for Linux is still possible. But using the UI is very, very slow. Laptop at home is not mine, but from work. Not allowed to install anything on this device, but I think I found a way to install and then remove some registry keys to make it look like a portable installation. I would love to test the newest version, but don't know how to cross compile on Linux for target win64. How do you compile for Windows? And would it be easy to create a portable standalone version (no installer)?

**Comment by jeroenrijckaert** [comment]
Been testing the last few days. All numerical fields now have the same way of showing the numbers. In my case with the Dutch locale I see commas ","

But when entering the numbers with the numerical part of the keyboard, there are still dots instead of commas. Seems that the input method is not connected to the local settings for language/keyboard. Maybe an easy hack would be to allow both signs as decimal inputs. But then again it might confuse some other users.

**Comment by buddhi1980** [comment]
I have check this under Windows Vista with Polish localization. It uses also commas. But I can't reproduce your problem. Dot key from numpad types commas in all types of edit fields, so it's correct.

**Comment by buddhi1980** [comment]
I'm closing this issue because of lack of feedback.
