### ISSUE TITLE
Create Visual Documentation for all Gamepad controls (Keymap)

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#144]

**Comment by mancoast** [comment]
Hello,

The gamepad functionality works with both windows and centos7.
http://doc.qt.io/qt-5/qtgamepad-index.html
I tested using the wireless xbox360 controller.

Similar to the current implementation, lets consider rework of the dual joystick controller input towards a semi-standardized gaming key-map.  The main changes would be to the right joystick.


1.) The left and right triggers control the roll.
double	buttonL2() const
double	buttonR2() const

2.) look (yaw & pitch) on the left joystick
double	axisLeftX() const
double	axisLeftY() const

3.) move (Shift X axis and Shift Y axis) on the right joystick
double	axisRightX() const
double	axisRightY() const

4.) Start button to pause/resume flight
bool	buttonStart() const

5.) select button to disable mouse input
bool	buttonSelect() const

6.) buttons A and B vary the movement speed
bool	buttonA() const
bool	buttonB() const

**Comment by buddhi1980** [comment]
If it works for you, please do and commit that changes. I still cannot test qtgamepad (maybe my joypad is not compatible). I'm waiting for qt5.7 in Debian. Maybe then it will start working.

**Comment by zebastian** [comment]
@mancoast 
points 1, 2, 3 and 6 are already implemented as you described.?
point 4 and 5 are good ideas
you can find it in the sourcecode in function
void cDockGamepad::ConnectSignals()
in the file
mandelbulber2/qt/dock_gamepad.cpp

I trust your opinion on this. If you want to make any changes how the buttons behave, just go ahead.
If you want to add new functionality (points 4 and 5) just implement a new slot function in dock_gamepad.cpp and connect the signals to it in the ConnectSignals. If you want I can also help you in implementation in any way.

**Comment by zebastian** [comment]
ok, now i see its mostly about the documentation :)
what do you think about using the following drawing (public domain):
http://opengameart.org/content/generic-gamepad-template
We can add arrows with short descriptions to it and put it in the hover box...

**Comment by mancoast** [comment]
the graphic looks good, we can use it as a baseline.
I am almost done with the required changes to the codebase.

It would be amazing if we could implement a negative z axis speed to move the camera backwards during flight animation.

Then we could use the directional pad as a gear shifter :)

**Comment by mancoast** [comment]
Left trigger =  reverse speed
Right trigger = forward speed
Left Joystick = Look
Right Joystick = Move
Shoulder Buttons = Roll
Start = Pause

More functions still being developed, however primary flight control now very natural relative to the gaming industry.

Did we want to add a Help menu dialogue that display the visual keymap?

**Comment by mancoast** [comment]
Thanks @zebastian!
