### ISSUE TITLE
check include headers

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#147]
- replace with forward declarations where possible
- use smaller includes (eg <QString> instead of <QCore>)

this way we can
- leverage (re)compilation time
- reduce interdependability

About Headers and Includes:
http://www.cplusplus.com/forum/articles/10627/
I found this article really interesting and there seems to be a couple of things we can apply to the project.
What do you think about this?

**Comment by buddhi1980** [comment]
It's really good idea. I will try with some of classes to test it.

**Comment by buddhi1980** [comment]
Works very well. You were right about reduction of interdependability
I have added also one small include just for enumCalculationMode which eliminated including of whole "fractal.h"

There is much more places to use forward declarations, so feel free to use them more.

**Comment by buddhi1980** [comment]
In commit https://github.com/buddhi1980/mandelbulber2/commit/4fccecc0f461627999b18ad27244a543418d2b80 there is much more forward declarations

**Comment by zebastian** [comment]
really cool, glad you are into this.
i am still looking for some tool to analyse the hierarchy tree and find the critical parts.
Did you do the changes completely by hand, or did you analyse it in some way?

**Comment by buddhi1980** [comment]
Everything by hand. I'm removing includes and add forward declarations in header files. Then I compile the program and eliminate errors.

**Comment by buddhi1980** [comment]
In Eclipse there is the tool to analyze include dependency, but the structure was too complicated to get useful information from it (too many cross including)

**Comment by buddhi1980** [comment]
I have finished changes in the code. Now it compiles much faster and needs much less memory for compilation. 
There is still a field for improvements. Some of definitions of structs, enums or functions could be in separate files.

**Comment by mancoast** [comment]
? is this related to automoc.cpp removed in https://github.com/buddhi1980/mandelbulber2/commit/b76a0770c780c73133a0389729917721cc15dc64

**Comment by buddhi1980** [comment]
I cannot see any relation with automoc.cpp until it's not generated when qmake is used

**Comment by zebastian** [comment]
this is still an issue, the includes should be ordered and unnecessary includes removed, i will look into this, if i need help, i will assign me some :)

**Comment by mancoast** [comment]
This issue requires deep analysis.  I figure we require a few release cycles to hammer out all the details.

**Comment by zebastian** [comment]
now all header includes are in one ordered format.
cmake and qmake on linux checked, hopefully msvc is fixed now, looks promising:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.826-master

@buddhi1980 what do you think about the new format? https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/animation_flight.cpp#L41

Please reopen, if i should change anything about it.

I think thats it for now here. ... finally :)
