### ISSUE TITLE
libtiff denying saving of really large images

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#148]
see also problem reported here by smurfboard: http://www.fractalforums.com/bug-reporting-b231/2-09-2-'zlib-cannot-deal-with-buffers/
program is crashing when trying to write 16bit tiff files, message: "zlib cannot deal with buffers this size" , image size is 16000x28000 pixels, i have 32gb memory.

Maybe tiff saving can be leveraged in memory consumption or saving can be "streamed" instead of total allocation.

**Comment by buddhi1980** [comment]
Here is the aswer: http://www.awaresystems.be/imaging/tiff/faq.html#q8

The format uses 32bit offsets, and as such, it is limited to 4 gigabytes. Many implementations handle these offsets using signed integers, and thus support files of up to 2 gigabytes, but the only real limit resulting from the format specification is 4 gigabytes.

**Comment by buddhi1980** [comment]
Fixed by commit https://github.com/buddhi1980/mandelbulber2/commit/cfe4ed01494575d5ac74758f3e96a6db700db5c6

I'm going to release 2.09-3 with this bugfix

**Comment by mclarekin** [comment]
can you include this replacement text with V2.09.3

transformCommon.benesiT1EnabledFalse = container->Get<bool>("transf_
benesi_T1_enabled_false");
transformCommon.benesiT1MEnabledFalse = container->Get<bool>("transf_
benesi_T1M_enabled_false");

I had them switched

**Comment by buddhi1980** [comment]
@mclarekin , I can add this change to 2.09-3

**Comment by buddhi1980** [comment]
@mclarekin , I'm not sure what I should change here. In 2.09-2 transformCommon.benesiT1MEnabledFalse didn't exist. 
You have added TransformScaleVaryVCLIteration() formula just 7 days ago, so it's not included in 2.09 at all.
Here is your change: https://github.com/buddhi1980/mandelbulber2/commit/38e14a97bf16dd71a3e613472623da621080a6f4#diff-048e74ab08be3a31d1abc425824bb60d

**Comment by mclarekin** [comment]
my mistake, I thought I had made the change before V2.09 release,    but I
now see it was done after.  :)

**Comment by buddhi1980** [comment]
I had one surprise here. When program was compiled with mingw32, then 'long int' type was only 32-bit size (PNG and TIFF failed under Windows10).
**There is always needed to use int64_t or uint64_t to be sure that variable will have 64-bit size.**
Latest commit solved this problem (https://github.com/buddhi1980/mandelbulber2/commit/63a14a6b050b5f9af240ba73c4ea5e8b4a6b6876)
The program was tested under Win10 and everything seams to work properly (tested image of resolution 16000x28000)
Tomorrow I'm going to publish new packages.
