### ISSUE TITLE
Wrong aspect ratio of image on NetRender client when stereo top-bottom is used.

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#149]
Bug was reported here: http://www.fractalforums.com/releases-b233/mandelbulber-v2-2-09/msg96899/#msg96899

"My test image is rendering now and I think I see a bug. I am rendering stereoscopic in top-bottom mode via netrender on a 4-core host and 8-core client. The image from the host is correct, but the image from the client is being stretched. I can see the image on the client screen is flattened to 2:1 aspect, though it should be 1:1. This image data is being cropped to the left side...
Ok that's weird. I stopped the render to see if stereo was enabled on the host, it was, I restarted the render and it's fine now, the host image is in 1:1 aspect."

**Comment by buddhi1980** [comment]
I cannot reproduce this bug. Maybe it's already fixed (???)

**Comment by mancoast** [comment]
@buddhi1980 Does this bug still exist?  I cannot reproduce using my systems and latest build.
