### ISSUE TITLE
Gamepad integration for flight animation

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#15]
feature request:
- evaluating library for gamepad recognition and input (SDL2 looks promising)
- generalization of input for flight control
- for playstation / xbox like controllers maybe:

left joystick: yaw / pitch

right joystick: move orthogonal to view direction

buttons: start / pause / accelerate / deccelerate / roll right / roll left

**Comment by buddhi1980** [comment]
As usual, we need to check if it will be multiplatform solution. It's not a native support from Qt, so I can expect some difficulties. We can also decide to implement it only under Linux (still can use #ifndef WIN32).

**Comment by zebastian** [comment]
sdl2 should be available for windows / osx / linux / android
should even run with emscripten.
but of course cross compiling could be an issue.

licence is zlib, so it is "freer" than gpl and should be compatible

documentation is not so great, and only C like function available

https://www.libsdl.org/download-2.0.php


This one is probably better:
http://www.phoronix.com/scan.php?page=news_item&px=qt-gamepad-development

http://code.qt.io/cgit/qt-labs/qtgamepad.git/

example:
http://code.qt.io/cgit/qt-labs/qtgamepad.git/tree/examples/simple/gamepadmonitor.cpp

i have not made any tests so far.
