### ISSUE TITLE
Autorefresh and resolution lock problems

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#150]
Problem reported here: http://www.fractalforums.com/bug-reporting-b231/minor-gui-glitches/msg97106/#msg97106

"when auto-refresh is turned on, even changes in postprocessing values like brightness, contrast, gamma lead to an instant re-render. I think that's not useful.
when connection between resolution and detail level is active, the resolution buttons act strange. I had several issues like a change of aspect ratio or false doubleing. A reproducible example: turn the detail level to 2 @ 1280x720 (connection activated) then try a 4k resolution of 3840x2160 with fixed 16:9 aspect. It leads to 3839x2159. Only with free aspect you can adjust the right resolution. I assume this is unwanted."

**Comment by mclarekin** [comment]
BTW My current status,  is that auto-refresh always causes crash in release
mode, but seldom crashes in debug mode


0x444c40                   48 8b 07        mov    (%rdi),%rax
0x444c43  <+0x0003>        8b 10           mov    (%rax),%edx
0x444c45  <+0x0005>        85 d2           test   %edx,%edx
0x444c47  <+0x0007>        75 17           jne    0x444c60
<_ZN7QStringD2Ev+32>
0x444c49  <+0x0009>        ba 08 00 00 00  mov    $0x8,%edx
0x444c4e  <+0x000e>        be 02 00 00 00  mov    $0x2,%esi
0x444c53  <+0x0013>        48 89 c7        mov    %rax,%rdi
0x444c56  <+0x0016>        e9 05 16 ff ff  jmpq   0x436260
<_ZN10QArrayData10deallocateEPS_mm@plt>
0x444c5b  <+0x001b>        0f 1f 44 00 00  nopl   0x0(%rax,%rax,1)
0x444c60  <+0x0020>        83 fa ff        cmp    $0xffffffff,%edx
0x444c63  <+0x0023>        74 0b           je     0x444c70
<_ZN7QStringD2Ev+48>
0x444c65  <+0x0025>        f0 83 28 01     lock subl $0x1,(%rax)
0x444c69  <+0x0029>        0f 95 c2        setne  %dl
0x444c6c  <+0x002c>        84 d2           test   %dl,%dl
0x444c6e  <+0x002e>        74 02           je     0x444c72
<_ZN7QStringD2Ev+50>
0x444c70  <+0x0030>        f3 c3           repz retq
0x444c72  <+0x0032>        48 8b 07        mov    (%rdi),%rax
0x444c75  <+0x0035>        eb d2           jmp    0x444c49
<_ZN7QStringD2Ev+9>

**Comment by buddhi1980** [comment]
@mclarekin, unfortunately I can't reproduce this problem at all. I have tried under Debian and Ubuntu and auto-refresh works very well (tried hundreds of refreshes and didn't crashed even one time). I have used additionally valgrind tool to check if there is any invalid read or write to memory, but nothing suspicious was found.

**Comment by mclarekin** [comment]
Maybe I will do a complete reinstall, and see if some of my problems will
go away:)

**Comment by buddhi1980** [comment]
This bug is already fixed. It was corrected during UI reorganization.

**Comment by buddhi1980** [comment]
Fixed. Now any change of brightness, gamma, contrast and HDR disables auto-refresh function.
