### ISSUE TITLE
LimitsToBoundingBox 

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#151]
for voxel export may be helpful to automatically calculate the bounding box of the fractal and set it as limits.
This way the voxel export contains all of the fractal without a border.

**Comment by zebastian** [comment]
mostly done with this commit: https://github.com/buddhi1980/mandelbulber2/commit/0440f418653cfe242582191d93784aa4cab8950c

TODO: user defined bounding box max value

**Comment by buddhi1980** [comment]
It's nice feature, but not always works properly. Try with ABoxSurface or Mandelbox with scale=2.0

**Comment by mancoast** [comment]
3d print

**Comment by mancoast** [comment]
step or iges file support

**Comment by zebastian** [comment]
@buddhi1980 see latest commit for mandelbox, sometimes there is a fractal surface far away from the desired object, now the user can set the most outer possible value manually.
@mancoast what do you mean with "step or iges"?

**Comment by mancoast** [comment]
Greetings gents,
Imagine solid 3d Computer-aided-drafting models as an output from mandulbulber. Please correct me if my interpretation is wrong, but I envision limits to bounding box as scooping out subsection of the fractal.  If we can enable export of voxels of this subsection into generic STEP [ISO 10303-21]
or IGES [ASME Y14.4] 3D Computer-aided-drafting file formats, then we use the voxels in solid mechanical designs. Specifically, I want to import a fractal into the unreal engine map editor. 

https://wikipedia.org/wiki/ISO_10303-21
https://wikipedia.org/wiki/IGES

Thanks,
Coast

**Comment by buddhi1980** [comment]
Do STEP and IGES formats support point clouds?

**Comment by mancoast** [comment]
Greetings,

These formats absolutely support point clouds! I use SolidWorks everyday for mechanical and electrical design and majority of suppliers provide their mechanical data in STEP format. This is the standard for industrial inter-operation, design, and 3d printing for rapid prototyping.  

Thanks,
Rob

**Comment by buddhi1980** [comment]
@mancoast , are you able to implement this functionality into Mandelbulber?

**Comment by mancoast** [comment]
I will investigate and write requirements document. 
I have not used step file writer in c++. We need to determine optimal STEP file library and then determine implementation strategy.  STEP files are plaintext portable mechE CAD.

**Comment by buddhi1980** [comment]
If you look for ready to use libraries, you have to remember about compatibility with GNU GPL V3 license.

**Comment by buddhi1980** [comment]
@zebastian, there is missing parameter:
`Warning: Set(): element ' "limit_outer_bounding" ' doesn't exists `

**Comment by mancoast** [comment]
Does this library with BSD3 look OK?

stepcode - import, export, ISO 10303 STEP
licensed under the 3-clause BSD license
maintained by the National Institute of Standards and Technology
https://github.com/stepcode/stepcode/blob/master/COPYING

**Comment by buddhi1980** [comment]
The 3-clause BSD is compatible with GNU GPL, so we can use it.

**Comment by zebastian** [comment]
@buddhi1980 regarding missing parameter:

I missed the changes in initparameters.cpp in that commit, fixed with latest commit.

**Comment by zebastian** [comment]
IMHO: feature is finished sufficiently, if you have any points open on this, please reopen.
