### ISSUE TITLE
Different coloring in boolean mode

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#152]
I am not getting the same coloring on these two "identical" boolean fractals?? h'mmm??

# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operators true;
camera 0 -4.551766297196777 0;
camera_distance_to_target 4.551766297196777;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
check_for_bailout_3 false;
DE_factor 0.7;
flight_last_to_render 0;
formula_1 107;
formula_2 107;
formula_material_id_1 2;
formula_material_id_2 2;
formula_position_1 -1 0 0;
formula_position_2 1 0 0;
fractal_rotation 0 -90 0;
julia_c -11 -14 -11;
keyframe_last_to_render 0;
mat2_is_defined true;
raytraced_reflections true;
view_distance_max 12.32211740951778;
[fractal_1]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;
[fractal_2]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;

**Comment by buddhi1980** [comment]
You are right. There is something wrong here. I will look into the code to find the problem.
By the way, when you post settings use ``` mark (triple back quote character) at the beginning and at the end. Then it will be posted like below.

```
# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operators true;
camera 0 -4.551766297196777 0;
camera_distance_to_target 4.551766297196777;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
check_for_bailout_3 false;
DE_factor 0.7;
flight_last_to_render 0;
formula_1 107;
formula_2 107;
formula_material_id_1 2;
formula_material_id_2 2;
formula_position_1 -1 0 0;
formula_position_2 1 0 0;
fractal_rotation 0 -90 0;
julia_c -11 -14 -11;
keyframe_last_to_render 0;
mat2_is_defined true;
raytraced_reflections true;
view_distance_max 12.32211740951778;
[fractal_1]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;
[fractal_2]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;
```

**Comment by buddhi1980** [comment]
I know where is the problem. There are two line in settings which should be ignored:
```
check_for_bailout_2 false;
check_for_bailout_3 false;
```
I have to find why `check for bailout` has any influence in boolean mode

If you delete that two lines from settings file, the result will be correct.

**Comment by buddhi1980** [comment]
Fixed. Now colors are the same.
@mclarekin, please check if now works properly.

**Comment by mclarekin** [comment]
image now renders correctly, cool! thanks

On Fri, Nov 11, 2016 at 9:46 PM, Krzysztof Marczak <notifications@github.com
