### ISSUE TITLE
DE issue in hybrid mode

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#153]

**Comment by mclarekin** [comment]
two identical formulas in hybrid mode,  if you uncheck slot 1, the DE changes from analytical to  "DE unknown"

# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operators true;
camera 0 -4.551766297196777 0;
camera_distance_to_target 4.551766297196777;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
check_for_bailout_3 false;
DE_factor 0.7;
flight_last_to_render 0;
formula_1 107;
formula_2 107;
formula_material_id_1 2;
formula_material_id_2 2;
formula_position_1 -1 0 0;
formula_position_2 1 0 0;
fractal_rotation 0 -90 0;
julia_c -11 -14 -11;
keyframe_last_to_render 0;
mat2_is_defined true;
raytraced_reflections true;
view_distance_max 12.32211740951778;
[fractal_1]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;
[fractal_2]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;

**Comment by buddhi1980** [comment]
@mclarekin, have you posted correct settings here? They are the same like for issue #152

**Comment by mclarekin** [comment]
yep . I had two problems with that .fract.  Is it reproducible?

On Fri, Nov 11, 2016 at 9:54 PM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
I cannot reproduce it now that I have restarted QT and pulled and built

**Comment by mclarekin** [comment]
I can reproduce it

# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operators true;
camera 0 -4.551766297196777 0;
camera_distance_to_target 4.551766297196777;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
check_for_bailout_3 false;
DE_factor 0.7;
flight_last_to_render 0;
formula_1 107;
formula_2 107;
formula_material_id_1 2;
formula_material_id_2 2;
formula_position_1 -1 0 0;
formula_position_2 1 0 0;
fractal_enable_1 false;
fractal_rotation 0 -90 0;
julia_c -11 -14 -11;
keyframe_last_to_render 0;
mat2_is_defined true;
raytraced_reflections true;
view_distance_max 12.32211740951778;
[fractal_1]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;
[fractal_2]
transf_function_enabledM false;
transf_function_enabledX_false true;
transf_scaleD_1 0;

**Comment by buddhi1980** [comment]
I confirm. Now it's reproducible. I will try to find where is the problem.

**Comment by buddhi1980** [comment]
DE type is selected properly, but is displayed in wrong way. For boolean fractals it should not be displayed at all, because every slot can have different DE function. There will be displayed "n/a" (not applicable)
