### ISSUE TITLE
using  dot(z) for some bailout checks

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#154]
test if/where bailout termination using dot(z) will enhance render speed by the removal of some sqrt() functions. I still have yet to test this in openCL, but I have recently noticed  some .frags that do the bailout check that way. 

In some hybrid loop setups,  the checking for bailout option on the UI's can be used as  an additional tweak.  If a user wants more than one bailout check enabled in the loop, then the  removal of some sqrt() will be even more beneficial.

**Comment by mclarekin** [comment]
I have been using this in openCL,  I think we evaluate the implementation in MandelbulberV2 for linear types and maybe other cases.  

Here is example my .frag version
z * = scale;
DE *= scale; 
r2=z.x*z.x+z.y*z.y+z.z*z.z + z.w * z.w; // bailout criteria,
	}
float r = sqrt(r2);
return (r - offsetD) / fabs(DE);

**Comment by zebastian** [comment]
i substituted some z.Length() with z.Dot(z) in this commit:
https://github.com/buddhi1980/mandelbulber2/commit/5d66070b542a9ca6375af0fa6a47f3689b69506c.
I could only detect minor performance impact, but still a good idea.

**Comment by mclarekin** [comment]
You are doing  good work Sebastian, thanks. I have been hoping that you
guys would find time to tidy the formulas up

A while ago I tested in OpenCL for when both r and rr are required in a
formula, i found that

r = length();   rr = r * r, was very very slightly  slower than   rr =
dot(z,z);  r = sqrt(rr)  i.e a decimal of a second slower sort of thing

what I am more interested in is the difference in bailout check.
I.e.  dot(z,z) > bailout,  compared to   length(z) > bailout.. The
performance impact of this for a 50 plus iteration formula, when doing
animation may be greater.???  It seems to now be the standard way of doing
bailout checks in other programs.


BTW. I will be working in OpenCL for a while, so fractal.cpp is all yours
to play with with no risk of merge problems.:)

**Comment by zebastian** [comment]
You are welcome!

When you are doing opencl stuff, you can maybe check the preliminary output of the automatic opencl code generation. In mandelbulber2/tools/populateUiInformation.php now the formulas of fractal_formulas.cpp are taken and automatically converted to the opencl form into the folder: /mandelbulber2/opencl/formula, here is an example: https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/opencl/formula/fractal_mandelbulb.cl
You can run the script on the command line with:
```php mandelbulber2/tools/populateUiInformation.php nondry```
to generate the missing formulas, i havent put these on git yet, since the kernel header is still wrong, and the formulas are completely untested (and the converter has still some known issues)

**Comment by mclarekin** [comment]
All to tricky for me lol.
The Mandebulb Iteration example looks perfectly converted to me.!!

But here are questions:
Was the  conversion to "mad" automatically generated?
Will we be able to use doubles with the new openCL?
And if so, can_we/should_we mix doubles and floats, because many parameters
only need single precision?
Or will we have the choice of doubles or floats? (I think quaz0r  once sent
me a  piece of code, that in theory switched between the two in OpenCL)

We can "swizzle" and we can "clamp"  in openCL, I am wondering whether
we will be updating the OpenCL formulas to use these functions?

**Comment by buddhi1980** [comment]
I would avoid doubles at all. They are extremely slow in compare with floats (about 10-20 times) and doesn't work properly on many GFX cards (when kernel code is complex).

**Comment by mancoast** [comment]
Looks awesome, we can use vTune to profile the openCL when ready.

**Comment by zebastian** [comment]
>All to tricky for me lol.

Never mind, i will come back, when the opencl formulas are testable in Mandelbulber v2

>But here are questions:
>Was the conversion to "mad" automatically generated?

Yes, craziest regex i have written so far!

>Will we be able to use doubles with the new openCL?

Yes, i will try to make it something like:
```
#ifdef OPENCL_DOUBLE_PRECISION
// double precision code
#else
// single precision code
#endif
```
both versions will be auto generated.
@buddhi1980 i think AMD is now capable of of using double with half of flops of float computation, so this might be a reasonable option.

>And if so, can_we/should_we mix doubles and floats, because many parameters
>only need single precision?

The OPENCL_DOUBLE_PRECISION is selectable by the user, so we can make it up to him to balance precision against performance.

>We can "swizzle" and we can "clamp" in openCL, I am wondering whether
>we will be updating the OpenCL formulas to use these functions?

clamp is definetely a win (for the c++ and the opencl code), I can add it to the lookup
What does "swizzle" do?

**Comment by mclarekin** [comment]
swizzle  is GLSL word for swaps  and part vectors

like p.xy *= scale * q.xy;

and  p.xyz = p.yzx

Double accuracy is for deep zooming, but unless it proves to be faster than
the existing c++ code it is a "nice to have but maybe not essential."
3Dickulus tried to get me to test doubles in Fragmentarium but it was
beyond my ability, but it did seem like I should have been able to as
openGL4.0 and better, supports doubles, http://blog.hvidtfeldts.net/
index.php/2012/07/double-precision-in-opengl-and-webgl/). and these were my
two GPU specs for my laptop.

AMD Radeon R9 M265X    openGL 4.5 openCL 1.2
Intel(R) HD Graphics 4600  OpenCL 1.2 and OpenGL 4.0.

I wonder if it it feasible to run openCL on both GPUs (and  also my CPU?)
together on a render.??




I also wonder about the pros & cons of to using doubles for z.xyz and w,
and floats for most parameters??

**Comment by mancoast** [comment]
tabled for opencl.
please re-open if required.

**Comment by mancoast** [comment]
I close issues because majority of these 'issues' do not cover bugs, instead features.
The negative connotation of the work 'issue' annoys me when we stack valuable features by the dozen and call them issues.  I wish GITHUB would rename 'issues' to 'tasks', lol

**Comment by buddhi1980** [comment]
Because Github doesn't have tool to report "wishes" we use "issues". So please don't close them. Enhancement report is also an issue, because it describes lack of functionality or performance.

**Comment by mancoast** [comment]
Maybe I should write them a nice handwritten letter, lol
