### ISSUE TITLE
Implement make package for k1om bins

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#155]
required for Release for Xeon PHI

**Comment by mancoast** [comment]
Lets try to get this software on the KNC catalog and get more devs.
https://software.intel.com/en-us/xeonphionlinecatalog

**Comment by mancoast** [comment]
Greetings,

I want to include k1om RPM for simple installation on KNC co-procs.
1.) The deliverable is a single RPM
2.) The RPM includes all mandelbulber binary, and all supporting libraries' binaries
3.) The entire process will be automated via bash scripting
4.) The Intel compiler version and MPSS stack version will be reflected in the RPM package name

Thanks,
coast

**Comment by zebastian** [comment]
here is how the packages are done under debian:
https://packages.debian.org/search?searchon=sourcenames&keywords=mandelbulber2
maybe this will help you along.

**Comment by mancoast** [comment]
These K1OM packages require Intel Stack Support for Visual Studio Continuous Integration Service.

Reference:
https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/628773

**Comment by mancoast** [comment]
Qt5Multimedia support for k1om confirmed:
https://github.com/buddhi1980/mandelbulber2/commit/9e86f738b689c4c5d4127832355536ef9860372c

**Comment by mancoast** [comment]
https://github.com/nemequ/icc-travis
I see that it is possible to install icc using travis.

I will get this rolling ASAP

**Comment by zebastian** [comment]
cool, you can make it a new "build flavor" in travis

**Comment by mancoast** [comment]
REFERENCE:
https://github.com/appveyor/ci/issues/1276
http://help.appveyor.com/discussions/suggestions/1185-intel-parallel-studio

**Comment by mancoast** [comment]
Almost there:
https://ci.appveyor.com/project/mancoast/icc-ci/build/1.0.1.0.0.7.36-master

**Comment by mancoast** [comment]
https://ci.appveyor.com/project/mancoast/gsl/build/artifacts
cross of library gsl complete for k1om. require qt png jpeg

**Comment by mancoast** [comment]
https://codereview.qt-project.org/#/c/185313/

**Comment by mancoast** [comment]
target stack: 2017 Intel® MPSS 3.8.1 and Intel® Parallel Studio 2017.1

**Comment by mancoast** [comment]
We are almost ready for k1om build-package inclusion in next release.

Let us target K1om Offload for WIN64 Build using "Additional Options for MIC Offload Compiler".
This requires include directory and other MIC specifications at MSVC C++/GODE GEN [ICC] dialogue.
The msbuild project references includes and libraries from KNC-Nug-icc171-k1om-mpss38-1.0.777.5.
This alternative resolves: mesh_export.cpp(35): lgebra.hpp(48): catastrophic error: *MIC* cannot open source file "gsl/gsl_sys.h"
Host systems requires MPSS3.8.1 for Windows Installation.
