### ISSUE TITLE
Implement Benchmark via CLI as option "--benchmark"

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#158]
the program should have a benchmarking option so the program can generate comparable data about the rendering performance of a system.
This data may be interesting for comparing:
compilers / compiler versions / compiler flags / cpus / ...

best way may be on the cli as an option "--benchmark"

**Comment by mancoast** [comment]
I really like this Idea.
its ideal for the continuous integration on travis and appveyor

**Comment by mclarekin** [comment]
Benchmarking is cool.

**Comment by mancoast** [comment]
Greetings,

I will begin analysis of requirements for our bench test.
I want the benchmark to cover many different settings files, and I want timing data foreach setting.
Any thoughts or requests?

Thanks,
coast

**Comment by zebastian** [comment]
there is a benchmarking macro already in the qtest environment: 
 	QBENCHMARK_ONCE
see here for more info: http://doc.qt.io/qt-5/qtest.html
I think this would be the best / easiest to use.

**Comment by zebastian** [comment]
is implemented with https://github.com/buddhi1980/mandelbulber2/commit/7c7765910c2cbbf106eb78cf435e3fbe4f14f5b5
right now i think this is done.
please reopen, if new test cases should be added or issues occur with the implementation...

**Comment by mancoast** [comment]
looks great, i will test it out
thanks!
