### ISSUE TITLE
Memory leaks and undefined behaviour

### ISSUE THREAD

**Issue by rikardfalkeborn** [buddhi1980/mandelbulber2#167]
Edit: Updated to latest commit: ~~47b0768d49bc3194e36531b1fa99646929a55af3~~ c086dbdcffde9fa10161a6bc3c846a8e97fc03fa. Memleaks are pretty much gone (Valgrind reports one possible when using gcc, but it's spurious so maybe it's a false one), and some UB remains.

I get a couple of memory leaks and undefined behaviour warnings when running the test suite with valgrind, and address sanitizer (ASAN) and undefined behaviour sanitizer (UBSAN). The results are somewhat different when compiling with Clang and Gcc.

The results have been obtained on Arch Linux, x86-64, with clang 3.9.0, gcc 6.2.1, valgrind 3.12 and QT 5.7.0, on the latest git tree (commit 47b0768d49bc3194e36531b1fa99646929a55af3). I used the debug build to get line numbers.

Since some of the logs are quite long, I'm attaching them as files instead of just pasting them here.
[clang-debug-sanitize.txt](https://github.com/buddhi1980/mandelbulber2/files/636615/clang-debug-sanitize.txt)
[clang-debug-valgrind.txt](https://github.com/buddhi1980/mandelbulber2/files/636614/clang-debug-valgrind.txt)
[gcc-debug-sanitize.txt](https://github.com/buddhi1980/mandelbulber2/files/636617/gcc-debug-sanitize.txt)
[gcc-debug-valgrind.txt](https://github.com/buddhi1980/mandelbulber2/files/636616/gcc-debug-valgrind.txt)

### How to reproduce with clang and sanitizers
```bash
cd mandelbulber2/mandelbulber2/Debug
qmake-qt5 'QMAKE_CFLAGS+=-fsanitize=address,undefined -fno-omit-frame-pointer' 'QMAKE_CXXFLAGS+=-fsanitize=address,undefined -fno-omit-frame-pointer' QMAKE_LFLAGS+=-fsanitize=address,undefined -spec linux-clang mandelbulber.pro
make PREFIX=/usr all
UBSAN_OPTIONS=print_stacktrace=1 ./mandelbulber2 --test
```
### How to reproduce with clang and valgrind
```bash
cd mandelbulber2/mandelbulber2/Debug
qmake-qt5 -spec linux-clang mandelbulber.pro
make PREFIX=/usr all
valgrind --leak-check=full ./mandelbulber2 --test
```
### How to reproduce with gcc and sanitizers
```bash
cd mandelbulber2/mandelbulber2/Debug
qmake-qt5 'QMAKE_CFLAGS+=-fsanitize=address,undefined -fno-omit-frame-pointer' 'QMAKE_CXXFLAGS+=-fsanitize=address,undefined -fno-omit-frame-pointer' QMAKE_LFLAGS+=-fsanitize=address,undefined -spec linux-g++ mandelbulber.pro
make PREFIX=/usr all
UBSAN_OPTIONS=print_stacktrace=1 ./mandelbulber2 --test
```
### How to reproduce with gcc and valgrind
```bash
cd mandelbulber2/mandelbulber2/Debug
qmake-qt5 -spec linux-g++ mandelbulber.pro
make PREFIX=/usr all
valgrind --leak-check=full ./mandelbulber2 --test
```

**Comment by psyriccio** [comment]
How to reproduce this? I am using manddelbulber on ArchLinux (led him a dog life), 
everything seems to be ok. but i didnt run any kind of scrcial tests, only rendering, f***ing hard rendering )

![1_089](https://cloud.githubusercontent.com/assets/2860234/20769430/ea80ea76-b752-11e6-823e-ca09b3d5f7fc.png)
![1_085](https://cloud.githubusercontent.com/assets/2860234/20769429/ea802122-b752-11e6-9954-61ee98b04155.png)

**Comment by rikardfalkeborn** [comment]
The steps to reproduce are the first three or so lines in the text files. Sorry, I should've been more clear about that.

**Comment by zebastian** [comment]
@rikardfalkeborn thanks for the detailed output!
@psyriccio, these are only warnings about lost memory, not crashes.
As long as the program does not loose too much memory to get out of memory, you wil be fine, but these leaks happening is a good sign for something in the code going wrong. That should definitely be addressed.  Its something about the PNG loading and saving. (that is written in pure C code :( ). 
I will take a good look at the logs and see what we can do about it in the next days, 
btw: your htop looks ridiculously awesome. I am glad you got 32G of swap in case you run out of your 32G physical RAM :D

**Comment by psyriccio** [comment]
@zebastian its server, in other time he eats much more memory than mandelbulber-rendering :D

**Comment by zebastian** [comment]
what is the server doing, when it is not rendering with mandelbulber?

**Comment by psyriccio** [comment]
@zebastian its a grid-compute node, it runs a lot of java/scala services

**Comment by zebastian** [comment]
@buddhi1980 can you take a look?
if you invoke mandelbulber with argument "--test" and check for memory leaks you get the output mentioned by  rikardfalkeborn. I just cleaned the test running, which now should always work fine with animations.
When test run under debugger runs too slow, you can also temporarely deactivate test case for examples by putting an return right to the top of the method.
There are some issues with saving a file as PNG which i can't quite put my finger on whats going wrong...

**Comment by rikardfalkeborn** [comment]
I believe I have a fix for the png related leaks. Basically a call to png_create_write_struct should be followed by a call to png_destroy_write_struct (same for read struct). #169 seems to fix this.

**Comment by rikardfalkeborn** [comment]
I updated logs run on 47b0768d49bc3194e36531b1fa99646929a55af3.

**Comment by zebastian** [comment]
@buddhi1980 
in dof.cpp line 566 intDiff overflows
```
int intDiff = (1.0 - sizeCompare) * 500;
intDiff *= intDiff;
```
make it long?

**Comment by buddhi1980** [comment]
I have just fixed dof.cpp overflow issue

**Comment by mancoast** [comment]
Greetings,

I am curious to explore support of valgrind on CI server.
Has the topic of valgrind on CI server been previously documented?

Thanks,
coast

**Comment by buddhi1980** [comment]
I think it's to slow for Cl severs. By the way it's always better to run just one particular test case with valgrind, because of very slow processing of the program.

**Comment by mancoast** [comment]
It makes sense that the hardware requirements prevent Valgrind from mixing with the CI.
Thanks!

**Comment by zebastian** [comment]
i added valgrind mandelbulber --test to the readme in tools, so this should be done before releases...

**Comment by buddhi1980** [comment]
There is a problem with valgrind and --test option. It takes too long to perform tests and watchdog is triggered (It was run on Intel i7 @3950MHz)

There was used following command:
```
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=val.log ./mandelbulber2 --test
```

```
QFATAL : Test::renderExamplesWrapper() Test function timed out
FAIL!  : Test::renderExamplesWrapper() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 300952ms
********* Finished testing of Test *********
```

```
==9505== Memcheck, a memory error detector
==9505== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==9505== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==9505== Command: ./mandelbulber2 --test
==9505== Parent PID: 22907
==9505== 
==9505== 
==9505== Process terminating with default action of signal 6 (SIGABRT)
==9505==    at 0x8CB8FDF: raise (raise.c:58)
==9505==    by 0x8CBA409: abort (abort.c:89)
==9505==    by 0x6983540: qt_message_fatal (qlogging.cpp:1682)
==9505==    by 0x6983540: QMessageLogger::fatal(char const*, ...) const (qlogging.cpp:793)
==9505==    by 0x41AB688: QTest::WatchDog::run() (qtestcase.cpp:905)
==9505==    by 0x699CD87: QThreadPrivate::start(void*) (qthread_unix.cpp:368)
==9505==    by 0x7AC6463: start_thread (pthread_create.c:333)
==9505==    by 0x8D6E9DE: clone (clone.S:105)
```
