### ISSUE TITLE
Needed autosave

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#17]

**Comment by zebastian** [comment]
time interval based, with reload on startup?

**Comment by buddhi1980** [comment]
Wow! you are very fast. I just wanted to correct description of this issue where by mistake published it.
So...
I want to discuss way how to implement, because we have several options:
1. Time base - user can lost last several minutes of work. Sometimes when you experiment with parameters even one minute can be critical, because you will be not able to find the same parameters.
2. After every press of Render button - this would slow down the program before rendering
3. Hybrid - to save settings e.g. about 5s after pressing render. Settings can be saved in background thread.
4. ... other if you have more concepts...

**Comment by zebastian** [comment]
1. i agree 5 minutes is a long time, when you get the segfault at 4:59 :)
2. would be a good position, but slowdown on render start is worst time for user experience
3. something like that would be good
4. maybe we can integrate this in the gUndo class, like
on
every 10th gundo store
timer in gundo every 2 minutes, if undo store occured in this period

**Comment by buddhi1980** [comment]
Finally I will implement autosave inside cUndo class. It's good place for it. First I will try with solution #2 and measure how much time it takes to save settings (especially when there is a lot of primitives and animation frames). If it will be longer than 10ms then I will try with solution #4.
Now I'm preparing cUndo class to store animation frames and keyframes

**Comment by buddhi1980** [comment]
It takes about 3ms to do autosave for regular fractal. About 3.5ms when there was 50 primitives. 32ms when there was 2000 frames of flight animation. When that times are so short I think is not reasonable to make it complicated. Even 50ms shouldn't be noticeable by user.

**Comment by zebastian** [comment]
Did you try with SSD, or HDD?
I agree, timing for autosave is negligible, when it is that fast.

**Comment by buddhi1980** [comment]
It was regular HDD (file size was 0.35MB). Most of time consumed preparation of text for setting file.

**Comment by buddhi1980** [comment]
Code with auto-recovery is already commited. You can check in log file how much time it takes on your PC.

**Comment by zebastian** [comment]
I tried SSD and it took ~6ms (file size was 0.24MB). good result!
