### ISSUE TITLE
Precompiled GSL nuget for appveyor

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#170]
Hello,

Can we please prepare a nuget package for GSL for windows builds?
A nuget package for GSL removes one nuisance variable from our CI servers.
(Minimize variability between builds for CI benchmark)

Thanks,
coast

**Comment by zebastian** [comment]
definitely that would be great. I already checked, but there seem to be no prepared package yet. Do you know how to do that and publish to nuget?

**Comment by mancoast** [comment]
I will investigate the nuget process.
need a refresher, but ive done it before

**Comment by zebastian** [comment]
Thanks, glad you are into this.

**Comment by mancoast** [comment]
xpost: https://github.com/ampl/gsl/issues/13
xpost: http://lists.gnu.org/archive/html/help-gsl/2016-12/msg00012.html

**Comment by mancoast** [comment]
https://www.nuget.org/packages/gsl-msvc14-x64/2.2.1.2477

**Comment by mancoast** [comment]
Greetings,

appveyor config updated to use GSL nuget; please review
@zebastian, what is required to re-enable appveyor CI?

Thanks,
coast

**Comment by zebastian** [comment]
Hi Robert, just send you an invitation for appveyor. There you can login with github and Start manual builds of the current State.

**Comment by mancoast** [comment]
@zebastian Got invitation, I will investigate.
Is it possible to enable GIT hook to always trigger Appveyor build foreach new commit?

**Comment by mancoast** [comment]
@buddhi1980 I believe we need access to the githooks for buddhi/mandelbulber2

Every time you push changes into repo <-- not operational?
or
click the New build button
or
use chron table * * * * * for build schedule <-- temp workaround

![image](https://cloud.githubusercontent.com/assets/7040493/21295716/2f0c2a46-c529-11e6-8bff-98899a1e9921.png)

**Comment by buddhi1980** [comment]
I have tried to install your nuget gsl package in Visual Studio 2015. I'm getting this error:

> Could not install package 'gsl-msvc14-x64 2.2.1.2577'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mancoast** [comment]
I will investigate whats going on here.

**Comment by mancoast** [comment]
resolved with https://github.com/ampl/gsl/pull/17

**Comment by mancoast** [comment]
@buddhi1980 We need to get the "Continuous" essence of our "Continuous Integration" operational on Appveyor.  What are your thoughts on triggering an Appveyor build with every new commit?
