### ISSUE TITLE
Define Permanent Visual Studio Solution File for CI & MSBuild Agents

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#179]
We need a Visual Studio Solution File in the repo.
VS Solution File makes great use of Nugets and gets more Windows developers involved.

**Comment by buddhi1980** [comment]
For that there would be good to have nuget for libsgl. This is one missing part.
libpng and zlib is already in Nuget. QtCreator has libs prepared also for MSVC++ 2015, so it's also well prepared.

**Comment by mancoast** [comment]
Fantastic! I will get the process initiated for the GSL nuget.
Also, I have contacted Intel/Microsoft requesting support for Intel Stack on Microsoft CI.
We need Intel Compiler for Continuous Integration of Xeon-Phi Co-procs.

**Comment by mancoast** [comment]
Greetings,

@buddhi1980 Can we place the Visual Studio Solution File in the root of the folder structure?
I will generalize the Visual Studio Solution File and add to the code-base.
Reference: https://www.nuget.org/packages/gsl-msvc14-x64/2.2.1.2577

Thanks,
coast

**Comment by buddhi1980** [comment]
I would prefer if you put it into mandelbulber2/mandelbulber2/msvc folder. But if there is no other way than root folder, please do this as it is needed.

**Comment by zebastian** [comment]
@buddhi1980 like the idea to put one folder for each build system, so now we get msvc / qmake / cmake. 
@mancoast cool that we can use the nuget package. Is this also available for win32?

**Comment by mancoast** [comment]
Greetings,

We can rework the CMAKE generated VS Solution/Projects to meet any specifications.
I will put all msvc stuff in folder "mandelbulber2/mandelbulber2/msvc".
I would also like to setup Build System folder(s) for Intel Stack with Xeon and Xeon PHI.
Im thinking at "mandelbulber2/mandelbulber2/icc/" and  "mandelbulber2/mandelbulber2/icc-k1om/".

@zebastian - gsl nugets:
https://www.nuget.org/packages/gsl-msvc14-x86/
https://www.nuget.org/packages/gsl-msvc14-x64/

Syntax for CLI NuGet.exe Install:
nuget install gsl-msvc14-x86 -Version 2.2.1.2577
nuget install gsl-msvc14-x64 -Version 2.2.1.2577

Reference message to help-gsl:
http://lists.gnu.org/archive/html/help-gsl/2016-12/msg00018.html

Thanks!
Coast

**Comment by mancoast** [comment]
@buddhi1980 : can I have permissions to setup VSO builds using GIT Hooks to your REPO? As the Owner, only you have these permissions:
![image](https://cloud.githubusercontent.com/assets/7040493/21367971/4da7ef0c-c6ce-11e6-90c3-26375d3c66ac.png)

This functionality enables official Visual Studio Online Continuous Integration Services.  The Visual Studio Online services provide another set of automated Build and Test operations.  In my opinion, "Continuous Integration" translates to "Automatically Build and Test foreach GIT commit"


**Decision Point: Enable Visual Studio Online Continuous Integration Services**
![image](https://cloud.githubusercontent.com/assets/7040493/21371438/66b432f6-c6df-11e6-9519-05b57c7c9054.png)


STEP 1: Nugets
![image](https://cloud.githubusercontent.com/assets/7040493/21371329/b64e5ea0-c6de-11e6-85b2-49570f7173aa.png)


STEP 2: Solution
![image](https://cloud.githubusercontent.com/assets/7040493/21371358/e475877c-c6de-11e6-8f5c-f0423fd411de.png)


STEP 3: Batch
![image](https://cloud.githubusercontent.com/assets/7040493/21371366/f382caf4-c6de-11e6-90b1-a4676f281ca5.png)

**Comment by buddhi1980** [comment]
Sounds good.  Today afternoon I will try to configure it.  But to do this I need access to mandelbulber.visualstudio.com

**Comment by mancoast** [comment]
No problem, I will get the invite sent to your email ASAP.

**Comment by mancoast** [comment]
@buddhi1980 
The VS solution file now completely compiles and links.
We are ready to enable Visual Studio Online Continuos Integration
