### ISSUE TITLE
Program crashes when rendering of keyframe animation is stopped and then started again.

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#18]
Program crashes when rendering of keyframe animation is stopped and then started again.
The problem is located probably in cMorph class.

To reproduce error:
- create several keyframes
- start rendering of animation
- stop it until first frame is finished
- start rendering again

Then you will get following call stack:

```
38 QListData::size() qlist.h:96 0x000000000042831d	
37 QList<cMorph::sMorphParameter>::size() qlist.h:137 0x000000000048ea60	
36 cMorph::findInMorph() morph.cpp:58 0x000000000048a1a0	
35 cKeyframes::GetInterpolatedFrame() keyframes.cpp:59 0x0000000000483ca7	
34 cKeyframes::GetInterpolatedFrameAndConsolidate() keyframes.cpp:74 0x0000000000483ff9	
33 cKeyframeAnimation::RenderKeyframes() animation_keyframes.cpp:455 0x00000000004390b5	
32 cKeyframeAnimation::slotRenderKeyframes() animation_keyframes.cpp:169 0x0000000000436b0f	
31 cKeyframeAnimation::qt_static_metacall() moc_animation_keyframes.cpp:130 0x0000000000575941	
30 QMetaObject::activate() qobject.cpp:3681 0x00007ffff5e2f09d	
29 QMetaObject::activate() qobject.cpp:3547 0x00007ffff5e2f507	
28 QAbstractButton::clicked() moc_qabstractbutton.cpp:297 0x00007ffff6e676d2	
27 QAbstractButtonPrivate::emitClicked() qabstractbutton.cpp:542 0x00007ffff6bd29a5	
26 QAbstractButtonPrivate::click() qabstractbutton.cpp:535 0x00007ffff6bd3619	
25 QAbstractButton::mouseReleaseEvent() qabstractbutton.cpp:1140 0x00007ffff6bd37d4	
24 QWidget::event() qwidget.cpp:8316 0x00007ffff6b15778	
23 QApplicationPrivate::notify_helper() qapplication.cpp:3499 0x00007ffff6ad712c	
22 QApplication::notify() qapplication.cpp:3066 0x00007ffff6adcc0c	
21 QCoreApplication::notifyInternal() qcoreapplication.cpp:935 0x00007ffff5dffe8b	
20 sendSpontaneousEvent() qcoreapplication.h:240 0x00007ffff6adb39a	
19 QApplicationPrivate::sendMouseEvent() qapplication.cpp:2539 0x00007ffff6adb39a	
18 QWidgetWindow::handleMouseEvent() qwidgetwindow.cpp:507 0x00007ffff6b345b7	
17 QWidgetWindow::event() qwidgetwindow.cpp:179 0x00007ffff6b369c3	
16 QApplicationPrivate::notify_helper() qapplication.cpp:3499 0x00007ffff6ad712c	
15 QApplication::notify() qapplication.cpp:3282 0x00007ffff6adc600	
14 QCoreApplication::notifyInternal() qcoreapplication.cpp:935 0x00007ffff5dffe8b	
13 sendSpontaneousEvent() qcoreapplication.h:240 0x00007ffff6346df3	
12 QGuiApplicationPrivate::processMouseEvent() qguiapplication.cpp:1748 0x00007ffff6346df3	
11 QGuiApplicationPrivate::processWindowSystemEvent() qguiapplication.cpp:1549 0x00007ffff6348665	
10 QWindowSystemInterface::sendWindowSystemEvents() qwindowsysteminterface.cpp:579 0x00007ffff632d64f	
9 userEventSourceDispatch() qeventdispatcher_glib.cpp:78 0x00007ffff0132450	
8 g_main_dispatch() gmain.c:3122 0x00007ffff41f7c3d	
7 g_main_context_dispatch() gmain.c:3737 0x00007ffff41f7c3d	
6 g_main_context_iterate() gmain.c:3808 0x00007ffff41f7f20	
5 g_main_context_iteration() gmain.c:3869 0x00007ffff41f7fcc	
4 QEventDispatcherGlib::processEvents() qeventdispatcher_glib.cpp:426 0x00007ffff5e58277	
3 QEventLoop::exec() qeventloop.cpp:212 0x00007ffff5dfd5d2	
2 QCoreApplication::exec() qcoreapplication.cpp:1188 0x00007ffff5e0521c	
1 main() main.cpp:128 0x0000000000486493
```

**Comment by zebastian** [comment]
reproduction worked. on re-keyframe-render the morph[i] still exists, but dataSets are empty / broken.
The destructor of cKeyframes gets called just before new rendering starts.
If I comment out all occurences of gUndo.Store(gPar, ...
in animation_keyframes.cpp, the problem is gone. 

So it is probably a bad free in undo class?

**Comment by buddhi1980** [comment]
I found that source of the problem is that cMorph class has no copy constructor. So it's not safe to copy that objects when we have inside two other objects:
gsl_interp_accel *interpolationAccelerator;
gsl_spline *splineAkimaPeriodic;

This problem is more visible when you change
	QList<cMorph*> morph
to
	QList<cMorph> morph;
in Keyframes class.

Then there is visible when destructor is called for cMorph class if there is used morph.append(cMorph());
Destructor is called because it deletes local copy of cMorph(). So it deletes also memory areas. So then copy of cMorph object which is inside morph list has no memory allocated for gls objects,

The same happens in cUndo class.

So we need copy constructor in cMorph class which will copy the data from gls structures and create memory areas.

**Comment by zebastian** [comment]
thanks for the info.
I made a fix, which hopefully solves the problem.
I started with copy constructor of histogram and adopted it for animation and morph.

I dont know how to copy gsl structs and i am not sure if this should be done.
Right now morph just allocates these new on copy.
please feedback on 81f98946a766a66e204636f9893f7815258f6612 if there is something wrong with this approach, since i am not all that sure about it :)

**Comment by buddhi1980** [comment]
Now is ok.
