### ISSUE TITLE
Gamepad function requires v2 coordinate system

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#184]
Is it possible to display a warning message on event of both "use gamepad" and "v1 coordinates" ?

**Comment by mancoast** [comment]
How do we want to implement this warning message?

**Comment by buddhi1980** [comment]
Would be better to prepare this function to work with old coordinate system. It's just only the mater of swapping of vertical axis when old coordinate system is used. Exactly like it is done for arrow buttons.

**Comment by mancoast** [comment]
Sounds like a plan; I will investigate and implement as needed

**Comment by mancoast** [comment]
@buddhi1980 @zebastian 
I think should be repaired if we want to release 2.10 with stable gamepad controls.
What do you guys think?

**Comment by buddhi1980** [comment]
@mancoast, You wrote:

> I will investigate and implement as needed

So, what is the action? Do you need any help?

**Comment by mancoast** [comment]
@buddhi1980 I do not have time to focus on C++.  I require HDL which is why I opened the FPGA Project here.  Can you please tackle this gamepad bug?

**Comment by zebastian** [comment]
imho "v1 coordinates" is legacy which should be contained and does not cause too much conditional code in current development.
maybe just put an info into the qgamepad UI which says "(does not work properly with v1 coordinates)"?

**Comment by zebastian** [comment]
I can do this, if you agree...

**Comment by mancoast** [comment]
Please do, I am time constraint at the moment

**Comment by zebastian** [comment]
DONE
