### ISSUE TITLE
Rendering issue between V2.08 and V2.09-3

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#187]
http://www.fractalforums.com/bug-reporting-b231/

rendering problems (maybe DE)

**Comment by mclarekin** [comment]
I went looking for differences between 2.08 and 2.09. I commented out this and it seemed to fix it, but I will change it back and @ Krzysztof to consider the issue
//				if ((z - lastZ).Length() / r < 0.1 / fractals.GetBailout(sequence))
//				{
//					out->maxiter = false;
//					break;
//				}

**Comment by mclarekin** [comment]
well that is where the issue is for the three linear types. But I think the mandelbulb_ genBoxFold hybrid problem is a separate issue

**Comment by mclarekin** [comment]
same issue for the hybrid. I get a mandelbulb but not the same as the posted image??

**Comment by mclarekin** [comment]
r < 0.1  maybe should be a lot smaller, i tried something like 0.0000001 and it seemed to be OK.

**Comment by mclarekin** [comment]
Summary so far. the linear types may just require a  r < .00000000?, but I can only part fix the bulb hybrid.

**Comment by mancoast** [comment]
is this a floating point precision issue?

**Comment by buddhi1980** [comment]
No. This the problem with additional bailout function which detects if z series are convergent. This is needed for pseudo cleinian fractals. On FF I have posted temporary workaround for this.
Finally in need to switch of this condition when in the sequence there is no any pseudo-kleinian formula. This will solve this problem permanently.
When I have implemented it I haven't found any side effects of additional bailout condition. This is first time when I see it. But it's important to fix it.

**Comment by mclarekin** [comment]
On a similar topic, the Jos Leys/Knighty Klienian I have been coding
checks whether every second z is similar. This is to catch  a  2 cycle
loop.


 it also has a different DE calc:

DE=min(DE,min(y,Clamp_y)/max(DF,Clamp_DF));

I have yet to get it to work.:)

On Sat, Dec 24, 2016 at 6:03 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
I guess this is "DE being an estimation" thing, but as you zoom in the
triangles turn into circles

# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
bailout 10000;
camera -3.721094598305427 -1.209056926535307 0.8316467632710378;
camera_distance_to_target 4.000000000000003;
camera_rotation -72 -11.99999999999997 0;
camera_top 0.1977357683661733 0.06424824579191735 0.9781476007338057;
check_for_bailout_2 false;
DE_factor 0.7;
flight_last_to_render 0;
formula_1 115;
formula_2 1061;
formula_3 7;
formula_stop_iteration_2 1;
fractal_enable_2 false;
fractal_enable_3 false;
hybrid_fractal_enable true;
image_width 600;
keyframe_last_to_render 0;
mat1_is_defined true;
use_default_bailout false;
view_distance_max 16.89498855211867;
[fractal_1]
Cpara_enabledCurves false;
Cpara_enabledLinear false;
transf_addition_constantA_000 -1 -0.8 0;
transf_function_enabledM false;
transf_function_enabledS_false true;
transf_minR2_p25 0.85;
transf_scale 0.8;
transf_start_iterations_A 1;
[fractal_2]
Cpara_enabledParab_false true;
Cpara_iterA 2;
Cpara_para00 -0.367232;
Cpara_paraA -0.085227;
Cpara_parab_slope 0.8;
transf_scale 0.747619;

**Comment by buddhi1980** [comment]
Fixed by commit https://github.com/buddhi1980/mandelbulber2/commit/a6938de8317ed2af13accf3c2a432a2f4866aea9
Need to be checked if works properly in all cases.
