### ISSUE TITLE
Possibility to Rework Automoc

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#188]
Greetings,

I am struggling with Automoc and Visual Studio.
Is it possible to rework the project to link without Automoc?

REF:
http://doc.qt.io/qt-5/cmake-manual.html
https://cmake.org/cmake/help/v2.8.11/cmake.html#prop_tgt:AUTOMOC

Qt moc preprocessor
Using the Meta-Object Compiler (moc)
http://doc.qt.io/qt-5/moc.html
"Among other things, meta-object code is required for the signals and slots mechanism, the run-time type information, and the dynamic property system."

Thanks,
coast

**Comment by buddhi1980** [comment]
Can you use qmake.exe to create .moc files?
You already have this here: /mandelbulber/mandelbulber2/msvc14-x64/packages/bulbqt-msvc14-x64.5.7.0.10077/build/native/bin/qmake.exe
I hope It should create all moc files if you use standard mande.bulber.pro file.

**Comment by mancoast** [comment]
Resolved using nuget binaries with https://github.com/buddhi1980/mandelbulber2/commit/4ee771c9e58acc1a69ea3e96a1b0486b6cfa5c1f

@buddhi1980 
Thanks for the suggestion
