### ISSUE TITLE
Implement nullptr in place of NULL

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#192]
http://stackoverflow.com/questions/13816385/what-are-the-advantages-of-using-nullptr

**Comment by mancoast** [comment]
Ok I will proceed with the implementation.  There's going to be many changes for ARM support.  However, Visual Studio enables lazy mancoast coding by simply removing all the Squiggles:
![image](https://cloud.githubusercontent.com/assets/7040493/21582819/47b66054-d035-11e6-8d6c-8e6a95f5b29e.png)

**Comment by mancoast** [comment]
resolved with https://github.com/buddhi1980/mandelbulber2/commit/d3561f0731849b2cf0302ec90e862cd494b60739

**Comment by zebastian** [comment]
cant wait to see mandelbulber run on win ARM 8)

**Comment by mancoast** [comment]
We need some iOS/Droid/Windows App Store Entrys.
