### ISSUE TITLE
IOS and Android Mobile App

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#197]
https://github.com/benlau/qtci

This above repo looks promising, however I also see this:
http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-windows-x86-android-5.7.1.exe.mirrorlist

I would much prefer to build/deploy the android app using MSVC.

@buddhi1980 @zebastian what are you thoughts?

**Comment by zebastian** [comment]
hi robert,

i already took a look at qt for android, there is a good explanation here on how to do it in qtcreator: http://doc.qt.io/qt-5/androidgs.html
however i never managed to get it to work (something about uitools not present), so i disregarded android support as too complicated and gave up. this was still with 5.5 i think, so maybe something changed about it, i dont know.

If you can build the android / iOS App anyhow, i dont have a strong feeling how it should be done. reproducability is not a concern, since no one wants to build the app on its own, but download it from the corresponding stores.

if you can get it done, you are officially a magician :D

**Comment by mancoast** [comment]
Challenge accepted.  Im guessing CMAKE will drastically simplify the procedure.

**Comment by mancoast** [comment]
https://msdn.microsoft.com/en-us/library/dn707591.aspx

**Comment by mancoast** [comment]
I want this app to visualize using microphone.

**Comment by mancoast** [comment]
build for iOS/droid requires Visual C++ Cross-Platform Mobile
"Platform defining, cross-platform, new trendy applications such as Facebook Moments, Dropbox, Office, Skype, popular games (e.g. Fruit Ninja, Clash of Clans, EA Sports titles) are all written in cross-platform C++."

requires cross of libs:
qt gsl png jpeg

REF:
https://blogs.msdn.microsoft.com/vcblog/2016/01/25/top-10-reasons-to-use-visual-studio-for-c-android-development/
https://www.visualstudio.com/vs/cplusplus-mdd/
https://www.visualstudio.com/vs/android/
https://msdn.microsoft.com/en-us/library/dn707591.aspx

**Comment by buddhi1980** [comment]
Our application is already written in cross-platform c++. This is thanks to Qt. Could you explain what is missing here?
If you stop using Microsoft tools then everything will start to be cross-platform :rofl: 
Try Qt Creator instead and start learning about Qt For Android

All libraries which you mentioned are already prepared for different platform and easy to cross-compile.
As you already observed all releases of Mandelbulber for Windows were compiled under Linux.
There is also version for OSX maintained by bermarte.
The application also works on RasbPi with ARM processors.

Only missing piece is Android, but I don't think that this application is correct for mobile devices. It will drain battery in 15 minutes. Another thing is UI which should be completely different for mobile devices.

**Comment by mancoast** [comment]
Greetings @buddhi1980 ,

I agree that the Mandelbulber2 code base satisfies the requirement of "written in cross-platform C++".  The plan here is to leverage Appveyor Continuous Integration Services with Visual C++ Cross-Platform Mobile tools.  ****

For iOS and Droid we require cross compilation of qt5, gsl, png, jpeg using Visual C++ Cross-Platform Mobile tools.

Given adequate schedule, these libraries will be cross compiled and released as NuGets.
We can them implement iOS and Droid Architectures for our Visual Studio Solution Platforms.

The scope of this Issue (https://github.com/buddhi1980/mandelbulber2/issues/197) now includes build-packages on Appveyor Continuous Integration Services.  My thought is to implement iOS and Android using tools with which I feel most comfortable.

Thanks,
coast

**Comment by mancoast** [comment]
![image](https://cloud.githubusercontent.com/assets/7040493/22398807/5c86266c-e55d-11e6-93b7-a06f1f540391.png)

**Comment by mancoast** [comment]
requires https://github.com/buddhi1980/mandelbulber2/issues/225

**Comment by mancoast** [comment]
Scope is now well defined.  Moving forward to implement an initiative as project.
