### ISSUE TITLE
audio testing - crash with main_aux_light_intensity_1

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#204]
steps to reproduce:

1. load example: flight_anim_menger sponge_3.fract
2. export flight to keyframes
3. click on "Anim By Sound" in row of main_aux_light_intensity_1

**Comment by buddhi1980** [comment]
Thanks. I can reproduce this problem.

**Comment by buddhi1980** [comment]
Thanks. I can reproduce this problem

**Comment by zebastian** [comment]
i could not find the problem yet, so i thought you can better fix it.
i am doing more testing right now...

**Comment by buddhi1980** [comment]
Fixed. @zebastian, would you test it to be sure if now everything works properly?

**Comment by zebastian** [comment]
fixed now :)
