### ISSUE TITLE
audio testing - crash on close while playing

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#205]
steps to reproduce:

1. click on "Anim By Sound"
2. select an audio file
3. hit play button -> music starts playing
4. close dialog while playing

**Comment by buddhi1980** [comment]
This is because of temporary ugly implementation of player based on QAudioPlayer. Now I'm working on that.

**Comment by zebastian** [comment]
crash does not hjappen, when after step 3 the audio has been stopped.

**Comment by zebastian** [comment]
btw: cool feature to play the audio in the dialog!

**Comment by buddhi1980** [comment]
Fixed by commit https://github.com/buddhi1980/mandelbulber2/commit/7a35790b6c52f32c75f35134602f1af133adf1c7

**Comment by zebastian** [comment]
error is fixed, some other minor issues:
- while playing an audio select new audio, audio of last file will keep no playingand slider is moving in new animation diagram. -> maybe rather stop playing on select of new audio
- while playing audio -> press audio track delete: audio keeps on playing slider in animation diagrom moved through nothing. -> maybe rather stop playing on click audio track delete

button enhancement:
click on play button: 
disable play button, enable stop button 
click on stop button:
enable play button, disable stop button

**Comment by zebastian** [comment]
one more thing:
when the audio has been played completely, another click on play should start the audio again.
right now you have to fitrst click stop and then play to replay the audio.

**Comment by buddhi1980** [comment]
Should be possible to fix with void QAudioOutput::stateChanged(QAudio::State state). I will do this.

**Comment by buddhi1980** [comment]
Corrected. Now when playing of audio is finished, play button is enabled.

**Comment by zebastian** [comment]
perfect
