### ISSUE TITLE
audio - add click frequency of interest

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#206]
nice to have would be click and drag in frequency spectrum to select frequency of interest.
But that can also be done in next release...

**Comment by zebastian** [comment]
for next release

**Comment by buddhi1980** [comment]
You have assigned yourself to this enhance. Are you going to implement it or should I do this?

**Comment by zebastian** [comment]
i would be glad if you could do it. 
maybe also add the position indicator (white line in audio animation diagram) to the other two diagrams?

**Comment by buddhi1980** [comment]
OK. I will do it.

**Comment by zebastian** [comment]
great, thanks!

**Comment by buddhi1980** [comment]
Done
