### ISSUE TITLE
Possinle issue wih materials color

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#208]
I started to make a primitives animation.

At first both sphere and water were default grey, even though "use color from palette " was ticked.

I then loaded a water.fract to give the primitive a water a color, it remained grey.

Saved as a preset, and reloaded program, the water was now blue, the sphere remained grey.
 
Made single color red and unticked "use color from palette ". and the sphere became red.

Ticked "use color from palette " and the sphere remained red.

That was the state when I copied  the settings below.

Is this reproducible? Or am I doing something wrong.

```
# Mandelbulber settings file
# version 2.09
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
camera_distance_to_target 2.761725137257712;
flight_last_to_render 0;
fractal_enable_1 false;
keyframe_last_to_render 0;
mat2_coloring_palette_offset 6.59;
mat2_is_defined true;
mat2_name sphereCol1;
mat2_surface_color ff00 0000 0000;
mat3_fresnel_reflectance true;
mat3_is_defined true;
mat3_name water;
mat3_reflectance 1;
mat3_specular_width 0.161;
mat3_surface_color 2300 4800 6800;
mat3_use_colors_from_palette false;
primitive_sphere_1_enabled true;
primitive_sphere_1_material_id 2;
primitive_sphere_1_radius 0.3;
primitive_water_1_enabled true;
primitive_water_1_material_id 3;
raytraced_reflections true;
[fractal_1]
IFS_rotation_enabled true;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;
```

**Comment by buddhi1980** [comment]
Use color from palette doesn't work with primitive objects. It is already written in tooltip for this option.

**Comment by mclarekin** [comment]
Well that was getting close to the mythical stupid question :)
