### ISSUE TITLE
Windows 32 Bit Appveyor Build Failing without any Console Messages

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#209]
@buddhi1980 can you please cancel appveyor build 17
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.17-master

We need to Cancel Build 17 and let the build Queue continue.
I will open Support Request with Appveyor.

REFERENCE:
http://help.appveyor.com/discussions/problems/5946-windows-32-bit-appveyor-build-failing-without-any-console-messages

**Comment by buddhi1980** [comment]
cancelled

**Comment by buddhi1980** [comment]
I have just added you to collaborators list with admin rights.

**Comment by mancoast** [comment]
good to go
thanks!
