### ISSUE TITLE
Wrong directory path in PlayerWidget

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#21]
PlayerWidget takes path for animation frames only from FlightAnimation. It doesn't consider setting in keyframe animation tab

**Comment by zebastian** [comment]
should be ok with ee6a2c94cf70fe9724cad109022dc9a32c4abfa3

**Comment by buddhi1980** [comment]
It was far from ok, but now should be ok :smile:

**Comment by zebastian** [comment]
I had good intentions :D, thanks for cleaning up
