### ISSUE TITLE
possible issue with last frame to render 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#210]
frames per keyframe 500 , 4 keyframes,  and last frame to render is showing 1000.
Click -  Reset to default , now  last frame to render shows 180. Use slider and it slides up to 1500, the correct number.

So may be just slider spin-box configurations,  or maybe that plus another bug.

refer  my recent replies  on email "v.2.10 summary"

**Comment by mancoast** [comment]
@buddhi1980 @mclarekin any updates?  Can we still reproduce this bug? Will this be fixed for 2.11?

**Comment by mclarekin** [comment]
bump to 2.12, it awaits me getting back onto animation.

**Comment by zebastian** [comment]
fixed in latest commit, please reopen, if any more issues with the frame range occur...

**Comment by mancoast** [comment]
if the slider is set to 0, can we render all?
