### ISSUE TITLE
CRASH  materials parameter issue,  when add to keyframe animation,

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#211]
if primitive shape and fractal have the same material assigned to them, then if you try to add  color Palette offset parameter to key frame animation = crash.

**Comment by buddhi1980** [comment]
In my computer it doesn't crash but produces serious errors. So I can confirm that there is something wrong here.

```
PID: 10031, time: 229.649546060, Warning: Get(): element ' "_mat2_coloring_palette_offset" ' doesn't exists 
PID: 10031, time: 229.649973139, Warning: Get(): element ' "_mat2_coloring_palette_offset" ' doesn't exists 
PID: 10031, time: 229.650366764, Warning: cAnimationFrames::ContainerSelector(QString containerName, const cParameterContainer *params, const cFractalContainer *fractal): wrong container name "" (../src/animation_frames.cpp:241, static const cParameterContainer* cAnimationFrames::ContainerSelector(QString, const cParameterContainer*, const cFractalContainer*)
PID: 10031, time: 229.650731744, Critical: cAnimationFrames::AddFrame(const cParameterContainer &params, const cFractalContainer &fractal): Wrong container name: "" (../src/animation_frames.cpp:72, void cAnimationFrames::AddFrame(const cParameterContainer&, const cFractalContainer&, int)
PID: 10031, time: 229.651388379, Warning: cParameterContainer::GetAsOneParameter(QString name): element ' "_mat2_coloring_palette_offset" ' doesn't exists 
```

**Comment by buddhi1980** [comment]
I happens when in animation is used material which was previously loaded using "Load material..." option. Then there is no container name assigned to material parameters. When material is created using "New material" option, everything works properly.
Name of parameter in keyframe animation has missing prefix ```main```. Full parameter name should be ```main_mat2_coloring_palette_offset``` instead of ```_mat2_coloring_palette_offset```
Now I need to find where this assignment is missing.

**Comment by buddhi1980** [comment]
Fixed. @mclarekin, Please check if now it works properly.
