### ISSUE TITLE
Disable tooltips

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#213]
Enhancement for V2,11

Disable tooltips in program settings.

**Comment by zebastian** [comment]
i will look into this for the next release...

**Comment by zebastian** [comment]
hmm, i thought this would be a quick fix, but i have found no solution for this in the net.
This can be compiled into the code with QT_NO_TOOLTIP, but thats pretty much useless.
Also the tooltip event can be intercepted by each qwidget and not shown depending on user preference, but this seems too much work for little gain. Sadly there is no easy QApplication flag AFAIK.
I reschedule this for later, so we can look again...

**Comment by buddhi1980** [comment]
You are right. There is no easy solution for this.

**Comment by buddhi1980** [comment]
Finally found solution. Added eventFilter for tooltips in qApplication
```
bool RenderWindow::eventFilter(QObject *obj, QEvent *event)
{

	if (event->type() == QEvent::ToolTip && !gPar->Get<bool>("display_tooltips"))
	{
		{
			return true;
		}
	}
	else
	{
		return QMainWindow::eventFilter(obj, event);
	}
}
```

**Comment by mclarekin** [comment]
cool! well done

**Comment by zebastian** [comment]
:D finally
