### ISSUE TITLE
Enable Appveyor Build-Package with Gamepad Functionality

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#215]
Greetings,

I have been testing the latest builds from Visual Studio, and it appears that the gamepad does not function for Windows.

REFERENCE:
https://github.com/buddhi1980/mandelbulber2/commits/master/mandelbulber2/qt/dock_gamepad.cpp

I have been building all the commits from the History of dock_gamepad.cpp.
The last commit that functions correctly on my Windows Systems is a7ecca500022a4150266f2d138286759d1cbf598

Any thoughts/suggestions?

I insist that we assure operation of gamepad for windows before release of 2.10.
To test, please use Microsoft Xbox 360 Controller or Xbox One Controller with Windows 7 or 8 or 10.

http://lists.qt-project.org/pipermail/development/2017-January/028538.html

http://lists.qt-project.org/pipermail/interest/2017-January/025940.html

Thanks,
coast

**Comment by mancoast** [comment]
As of commit 9049b913ed395e14d3265f51294d597d3484f178
the gpad functions when using CMAKE and MSBUILD.
The gpad does not function when using the MS Solution file in root of project.
This issues requires further investigation of build logs.

**Comment by buddhi1980** [comment]
Unfortunately I cannot help you in this topic, because I don't have any compatible gamepad. I have very old (but very good) Logitech Dual Action.

**Comment by mancoast** [comment]
I have narrowed the scope of this issue to include either the bulbqt nuget, or the visual studio solution/projects.  The cmake build for windows function properly.

**Comment by mancoast** [comment]
I will repair this build system, but not within the time constraint of 4 weeks.  Bumped to 2.12.

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/3b29add031f3f8149f0754ec1a272557117290f4
