### ISSUE TITLE
Play sound controls freeze

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#216]
Occasionally the play sound & stop buttons  become non-responsive. Currently it seem a random bug, I will continue to monitor it.

**Comment by buddhi1980** [comment]
I cannot reproduce this one. I have tried about 100 times to play sound and it didn't happen.

**Comment by mclarekin** [comment]
It has only happened once, and I have used this a lot over the last fews
weeks with no problems. I will continue to monitor this minor issue.

On Sun, Jan 29, 2017 at 2:54 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
I push play  sound,   
pause option appears and stop is red.  Good.

THEN it soon changes to Play Sound green ,  Stop is grey. This happens automatically ie no user imput.

**Comment by mancoast** [comment]
I cannot replicate issue with latest build.
@mclarekin can you still reproduce this issue using latest dev build?

**Comment by mclarekin** [comment]
Rob, I will check next time I am in Anim by Sound, but I think we  still
did have intermittent problems with the play pause stop controls last time
I used it.

**Comment by mancoast** [comment]
@mclarekin Any updates? I tried on Windows 10, not able to reproduce the crash.  I will close issue, please re-open if bug still exists.

**Comment by mclarekin** [comment]
Last time I tested audio it still happens. It is not a crash just
intermittent  non functioning controls. I would leave it open  and await
me getting back on to audio stuff.
