### ISSUE TITLE
Changes of animation interpolation type are not consistent

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#221]
There is possible to get different interpolation type in the animation table when keyframes are added/inserted after change of interpolation type.

![image](https://cloud.githubusercontent.com/assets/11696990/22404165/d8d331dc-e62b-11e6-9616-b1384c66c57b.png)

**Comment by buddhi1980** [comment]
@mclarekin , can you test it if this problem is permanently solved?

**Comment by buddhi1980** [comment]
@mclarekin, have you tested it?

**Comment by mclarekin** [comment]
Tested ok.
