### ISSUE TITLE
windows build: application hangs indefinitely when closed while rendering an image. 

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#224]
Basically, if we are using windows build, we need to improve stability of application exit.  If one clicks the render button, immediately followed by the exit button, the application crashes, and we have to force quit using task manager. An end user most likely expects a clean and quick exit from application given any conditions or state. This bug is easy to reproduce, and prevents systemwide shutdown if mandelbulber is not explicitly and carefully closed. 
Thanks,
Coast

**Comment by buddhi1980** [comment]
This is something which I would like to debug with msvc. It never happens with mingw builds. With msvc I have observed the same behavior when material are edited. I suppose there are some problems with multiple threads running at the same time.

**Comment by buddhi1980** [comment]
I have done a lot of trials to get similar issue. Without success. 
Can you write steps (in details) how to reproduce this problem? 
Which build do you use? Launched from Visual Studio Solution or from Appveyor?
If it happens, can you get call stack (backtrace)?

**Comment by mancoast** [comment]
This occurs with either a debug using visual studio or with the appveyor zip artifacts. I will investigate and provide precise documentation/stack trace.

**Comment by mancoast** [comment]
latest build - can not reproduce.
