### ISSUE TITLE
spelling cleanup

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#229]
known words to the program should be added to .spelling/mandelbulber.dic
any misspellings should be fixed in the code, including:
- simple misspellings: refference -> reference
- not camelCased words: filename -> fileName
since this may break some translation strings, this should be scheduled for next release.
I can do this on my own, but help would be appreciated :)

**Comment by mancoast** [comment]
@zebastian Shall we implement lint scan for continuous integration?

**Comment by zebastian** [comment]
I don't think this is necessary. 
i thought about these non critical checks some time, i see three possible scenarios:
**hard**: commits will only be accepted, if each and every kind of check succeeds. This way the code base is always "perfect" in all checked dimensions, but it will also cause newcomers / non-pedants to fail pushing commits, because the rules are too oppressive -> not working

**medium**: implement checks in after-push-jobs (CI), this way every violation to each rule will be propagated and can be handled in time. But we dont want messages for every little thing spamming our mail-in, the commiter might not even be interested to fix and if he does every commit would be followed by a small cleanup commit. -> also not so good

**soft** (current state): automatized scripts to run checks "every now and then": since most of the code always follows current rules, the code is almost completely clean all the time. Every month or so i cleanup the fresh code / formula changes with current ruleset (just running scripts from tools folder). This way new commiters are not bothered, the commit log is not clobbered and the code base stays relatively good most of the time.

IMHO thats the best way for the structure of the project and should also account for spell-checking.
