### ISSUE TITLE
-nogui does not work (-ip too?)

### ISSUE THREAD

**Issue by networkpanic** [buddhi1980/mandelbulber2#23]
compiled successfully on our cluster, unable to start without gui :-(

Log file name: /root/.mandelbulber_log.txt
Detected 8 CPUs
Default data directory: /root/.mandelbulber/
Fatal: QXcbConnection: Could not connect to display 
(qxcbconnection.cpp:322, QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, const char*))
Aborted

logfile
PID: 29490, time: 0.009065, Mandelbulber version, value = 2.05
PID: 29490, time: 0.009145, Mandelbulber compilation date, value = Sep  5 2015 11:07:42
PID: 29490, time: 0.009218, CPUs detected, value = 8
PID: 29490, time: 0.009266, Default data directory, value = /root/.mandelbulber/
PID: 29490, time: 0.009307, Decimal point, value = .
PID: 29490, time: 0.009391, Prepare QApplication

my servers are headless, i am unable to start a gui there

i know it is possible to redirect X but i want to play with mandelbulber on a massive setup ;-)

**Comment by zebastian** [comment]
Hi Martin,

yes nogui is not implemented yet, and you need to have an xserver in some way. You could try to use Xvfb or some other Kind virtual /dev/null frame buffer.
If you get this working in some way, please add a small howto to this issue as a workaround.
Btw: i started a little cli support in the code under system.cpp but this is worse than alpha. Anyway client connection to Server under cli might work.
Good luck ;)

**Comment by zebastian** [comment]
And you need to uncomment 2 lines in Main.CPP to activate cli

**Comment by networkpanic** [comment]
oh sry, i had to look into sources first^^

atm a rendering runs, i install x11-common and forwarded X via ssh, 
rendering speed is ok (an example @10240 × 4320 21:9	43.5 megapixels)

distributed opencl rendering would be a great thing ;-) 
then we could deploy it via docker on multiple GPU nodes to get the real rendering fun ;-)

**Comment by networkpanic** [comment]
rendering finished :-)
logging the rendertime anywhere would be nice

**Comment by zebastian** [comment]
cool, that this works headless.
opencl will be the next big step, this will boost rendering in orders of magnitude.
what kind of setup are you using?
if you have good ideas for new features and are good at coding, you can fork and make a pull request.
Otherwise there is also a feature request part in the forum:
http://www.fractalforums.com/mandelbulber/

**Comment by networkpanic** [comment]
my coding experience is beginner, can help testing or translating
as soon cli mode works without a workaround i could create dockerfiles to deploy a scalable render cluster
hope we archieve gl shader rendering speeds anytime^^

cpu power per frame is too high to render animations in hd with a high framerate
i did a test with mandelbulber (one) on a quad core colocation host, a 2 minute rendering took 20 days (1080p@60fps)
with glsl on a multigpu system its possible to render fractals in realtime with much more then 60fps^^

**Comment by networkpanic** [comment]
oh, my setup

workstation is running kubuntu 15.10 and the host i used to test network rendering was a debian8

**Comment by zebastian** [comment]
animation render is quite time consuming (not to say almost impossible).
looking forward for gpu based rendering too, this will be exciting.

good setup! maybe we see some of your work at fractal forums... :)
Cheers!

**Comment by zebastian** [comment]
cli mode and queue is now almost finished.
if you pull the current base and build it, you will get a big toolset of options with --help.
If you are interested it would be great if you can help us test the application.
Just use cli options in combination and see if the program fails, gives weird cli output, renders wrong, something like that...
