### ISSUE TITLE
To allow detaching main image to separate window

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#231]
This will allow to have rendered image on separate display.

**Comment by mancoast** [comment]
Can we bump priority of this feature?

thanks, coast

**Comment by buddhi1980** [comment]
I agree with you to prioritize it, but I'm not going to implement it in 2.10. This enhancement needs quite a lot changes in main window. RenderedImageWidget is not located in detachable dock.

**Comment by mancoast** [comment]
Sounds good, thanks! This instantly improves design efficiency.


On Sat, Feb 11, 2017 at 3:19 PM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
Will be possible :smiley: 

![image](https://cloud.githubusercontent.com/assets/11696990/23278173/e288a114-fa10-11e6-8a20-17f52dc73db1.png)

**Comment by buddhi1980** [comment]
It's done. Can you test if it works properly?

**Comment by mancoast** [comment]
Tested, works very well. 👏
![image](https://cloud.githubusercontent.com/assets/7040493/23335018/c0466acc-fb79-11e6-953a-66e270923d07.png)

**Comment by mancoast** [comment]
Confirmed, thoroughly tested on CENTOS7 and WIN64 and WIN32
