### ISSUE TITLE
When mouse functions as "move the camera" with the cursor, rename to "move camera and move target"

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#232]
This label should respect settings from navigation panel. There are 3 possibilities:
- move camera and target
- move camera
- move target
Displayed label by the cursor should based on this selection

**Comment by mancoast** [comment]
move camera ||
move target ||
move camera & move camera

@buddhi1980 Any Thoughts about including "move" foreach noun [direct object] to be precisely clear?
