### ISSUE TITLE
Swapping of fractal tabs could cause loading of formulas to wrong slot

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#233]
To be confirmed:
I have played with swapping of fractal tabs, and then when I loaded fractal from toolbar, I have observed that loaded fractal appeared on wrong fractal tab.

**Comment by buddhi1980** [comment]
It is reproducible. I have similar issue on my PC in home. 
Steps to reproduce:
- change first formula to e.g. KIFS
- swap first and second fractal tabs
- load menger sponge from toolbar
Then you will see that Menger Sponge is on first tab (which is correct), but on second tab there is Mandelbulb (where should be "None")

**Comment by buddhi1980** [comment]
Fixed. Default values of parameters were moved with slots when there were swapped. Default for first slot is Mandelbulb. That's why Mandelbulb appeared on second tab.

**Comment by mclarekin** [comment]
Excellent, that bug had been confusing me for months, then the newer bug, that also caused Mandelbulbs to appear,   made it even more confusing. This should be the end of mysterious Mandelbulb occurrences.
