### ISSUE TITLE
To change name of "Fractal" tab to "Objects"

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#237]
There is suggestion to change name of "fractal" tab to "Objects" and "Fractal/Formulas" to "Objects/Fractals"

What you think about this proposal?

**Comment by mclarekin** [comment]
I have no preference.

On Sat, Feb 11, 2017 at 7:49 AM, Krzysztof Marczak <notifications@github.com

**Comment by zebastian** [comment]
i agree to both points.
That would be consistent with the code since the generalization of all stuff to objects.

**Comment by zebastian** [comment]
if nobody holds anything against this, i can change this accordingly...

**Comment by mancoast** [comment]
You da man
