### ISSUE TITLE
Playing of sond doens't work under Win10

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#238]
The sound was properly loaded, but "Play sound" function didn't work under Win10. Nothing happened after pressing this button.
Tested mingw64 version.

**Comment by zebastian** [comment]
neither does the appveyor (msvc) version work

**Comment by buddhi1980** [comment]
I cannot get this problem under Win10 on my PC. It plays sound very well. The problem existed only on computers in planetarium.
Needs more testing...

**Comment by mancoast** [comment]
Can we build these xcompile binaries using travis?

On Sat, Feb 11, 2017 at 4:15 PM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
I works also under Windows Vista.

@mancoast, do you want executables for testing?

**Comment by mancoast** [comment]
The cross-compiled MINGW build of mandelbubler 2.10 Confirmed functional using Windows 10 && Windows Server 2016.

All functionality provided via LibSound and QT.  

@buddhi1980 cannot reproduce, thoroughly tested using clean Operating System builds.

**Comment by buddhi1980** [comment]
Closed, because not reproducible
