### ISSUE TITLE
Increase default UI font size from 9 point

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#239]
![image](https://cloud.githubusercontent.com/assets/7040493/22846416/5ea712aa-efb5-11e6-9668-657e7f6742e4.png)

**Comment by mclarekin** [comment]
My two cents. I work with a laptop screen so 12 font is what I use.

I guess the default should suit the most common size screen the majority of
users have.???

**Comment by zebastian** [comment]
I am with graeme,

i often use my tiny e130 lenovo netbook and the default font size of 9 is working perfectly fine. Increasing it to 14 makes the ui unmanagable since there is not enough space.

**Comment by buddhi1980** [comment]
Some of people uses this application on 720p displays, so if we increase default font size, then the application will not fir into the screen size. I use 10 points font on 1440p 27inch display.
This is the reason why font size is customizable. I would only improve icons sizes for 4k displays. Maybe would be good to have another set of icons with double size.

**Comment by buddhi1980** [comment]
What you think to use QRect rec = QApplication::desktop()->screenGeometry() to get screen resolution and change default font size base in it?

**Comment by mancoast** [comment]
@buddhi1980 I like your idea to adjust font size given screen geometry dimensions.
REF:
https://developers.google.com/speed/docs/insights/UseLegibleFontSizes

**Comment by mancoast** [comment]
Any feeback on this method:
small+meduim+large
Small Font: res < 1920x1080 => default font 9pt
Medium Font: 1920x1080 < res < 3840x2160 => default font 12pt?
Large Font: res > 3840x2160 => default font 14pt

**Comment by buddhi1980** [comment]
I did many changes which should automatically adapt fonts and ui elements size to screen resolution and screen DPI. Could you test it on different displays?
Before you start testing, do right click on UI Font Size and reset it to default value.

**Comment by zebastian** [comment]
just tested on 11,6" inch lenovo e130 which produces 8px font, looks good on this device:
![bildschirmfoto von 2017-03-18 16-00-11](https://cloud.githubusercontent.com/assets/7888201/24073201/0f811a12-0bf4-11e7-8ac5-7ba61f40ddc6.png)

**Comment by buddhi1980** [comment]
Thanks. This is very small display. Do you have access to any laptop with 4K display? They have big pixel density.

**Comment by zebastian** [comment]
on full HD on 24" display its 9px font, also looking good:
![screenshot from 2017-03-18 16-24-02](https://cloud.githubusercontent.com/assets/7888201/24073413/ac625708-0bf7-11e7-8be8-c2208e912bf5.png)
Thats my biggest display...

**Comment by mancoast** [comment]
I will test 4k displays asap. Thanks, coast

**Comment by buddhi1980** [comment]
27'' 2560x1440 display. Font size 14px
![image](https://cloud.githubusercontent.com/assets/11696990/24074121/d88c1d54-0c02-11e7-8de2-6b95b8c0db9c.png)

**Comment by mancoast** [comment]
Smooth Operation,  Well done!

**Comment by mancoast** [comment]
confirmed CENTOS7 && WIN10

**Comment by buddhi1980** [comment]
@mancoast , can you provide a screenshot?

**Comment by mancoast** [comment]
When I have physical access to test again, I will record a screenshot

**Comment by mancoast** [comment]
When I first opened the system, the font size matched my last configuration for 14pt font.
14pt font on 3840x2160:
![untitled2-14pt](https://cloud.githubusercontent.com/assets/7040493/24302289/835be26c-1088-11e7-8fb1-e6064458d3bb.png)




The 'reset to default' function on the 'font size' does not operate.
With windows 10 and 3840x2160 resolution, 'reset to default' function on the 'font size' == 50 pt!
![untitled-50pt](https://cloud.githubusercontent.com/assets/7040493/24302322/9a15c0b8-1088-11e7-9a24-a1c4c65f1819.png)




After playing around with different font sizes, I like 22 pt font for windows 10 and 3840x2160 resolution:
![untitled3-22pt](https://cloud.githubusercontent.com/assets/7040493/24302345/b0b89174-1088-11e7-8ba2-6a1ace32c4b9.png)

**Comment by mancoast** [comment]
greetings @buddhi1980 

In summary, we have unexpected behavior occurrence with 3840x2160 resolution.
This unexpected behavior occurred on Windows 10.  I have not  yet retested on CENTOS7.

The system will reset the default font size as 50pt.
I doubled checked the same procedure on 1920x1080,  and the default font was 9pt and it looked good.

thanks,
coast

**Comment by buddhi1980** [comment]
@mancoast. In the system Control Panel what font scale was set? 100% or bigger? What was the size of the screen?  17 inch laptop? All of there information are really important to analyze test results.

**Comment by mancoast** [comment]
This is on a 65" display.  The font scale is 100%
![image](https://cloud.githubusercontent.com/assets/7040493/24317639/87488eb0-10cf-11e7-9f3c-74e042b32506.png)

Aslo, the icons for the examples are huge!
![image](https://cloud.githubusercontent.com/assets/7040493/24317646/aecb5ae4-10cf-11e7-94d6-6d0472ccc484.png)

**Comment by buddhi1980** [comment]
This strange, because for such a big display DPI value should be very low. Was this 65" display a main display, or it was as secondary connected to laptop?

**Comment by mancoast** [comment]
This system has one 4k display.  I will further test with the msvc debugger.

**Comment by mancoast** [comment]
@joffnerd Do you want to join our fractal community and help test this issue?  This code is written using C++, instead of C#, but there still exists Visual Studio projects.  We need intelligent testers.

**Comment by buddhi1980** [comment]
I have added screen resolution and DPI output to console and mandelbulber_log.txt file. @mancoast, if you can repeat test on that 4k display will be great. 
In log file should be something like this (about 5th line)
```PID: 17271, time: 0.107369163, Info: Screen resolution QRect(0,0 2560x1440) Screen DPI 96```
I need this to check if Windows reports screen DPI in correct way.

**Comment by mancoast** [comment]
Thanks for the updates!  @buddhi1980 I will retest this ASAP and post screen shot.

**Comment by buddhi1980** [comment]
Please post mandelbulber_log.txt, too.

**Comment by mancoast** [comment]
no problemo. shoudl have access to the hardware soon

**Comment by buddhi1980** [comment]
I have found final and good solution for font and UI element sizes. Now it uses systemwise font settings.
Font size is defined not in pixels but in point. This is hardware independent method (the same font size will have bigger pixel size on high resolution display)
When application is launched there is checked what is default system font size (in point) and used as a application default fount size. Then it calculates pixel font size based on selected font size in preferences dialog to calculate size of UI elements (arrows, thumbnails). 
Now it reacts in correct way if system font scaling is changed and screed DPI is high.

@zebastian, @mclarekin, @mancoast, please check if everything looks well on your display (when default font size is selected)

I hope this is last approach for this topic.

**Comment by mclarekin** [comment]
Seems OK.  On loading  latest commit, the default which was 11,  I suspect
that most users with my size screen would keep the default.

Old font 12 is equal to new font 9  (which is what I have it set to on the
attached image), which is OK and will be my default. Arrows could be
smaller??

**Comment by mclarekin** [comment]
These weird things always happen to me :)

Diagonal split toolbar thumbnails when toolbar icon size = 55


Test case
font set to 9.

toolbar icon sizes:

60 ok

56 ok
55 diagonal split
54 ok
43 ok
42 0k

25 ok

**Comment by mclarekin** [comment]
And ...

this may be unrelated :

Procedure ->

load mandelbulber

then do a lot of testing/changing  the toolbar icon size

i hear cpu surging

i notice mandelbulber is using 2.2 gb

mandelbulber is in theory inactive as i have not changed the icon size for
a minute, but it is still surging  randomly through a range of 6 to 39% cpu
usage.

close program, and cpu usage stopped.




I will wait and see if happens again.

**Comment by buddhi1980** [comment]
I confirm problem with toolbar icons. They are not displayed collect when size is not multiply of 4.

**Comment by mancoast** [comment]
Looks good with WIN10 x64 1920x1080 
Tested https://github.com/buddhi1980/mandelbulber2/commit/768ba9d1f65cae5968cdaa9ddf12c473771fa057 

![image](https://cloud.githubusercontent.com/assets/7040493/24631506/96bdf2ba-188e-11e7-96ca-cc4e243554c8.png)

**Comment by mancoast** [comment]
By default, windows 10 scales 300% when UHD display connected.
In my opinion the default sizes look better.
![4k_test-300](https://cloud.githubusercontent.com/assets/7040493/24633752/24731370-1898-11e7-9b10-6382aac98ea9.png)


When using 4K with 100% scaling, all applications looked tiny, not just mandelbulber.
![4k_test](https://cloud.githubusercontent.com/assets/7040493/24633753/2473138e-1898-11e7-837f-22843fc39117.png)

I think we are good to go.

**Comment by buddhi1980** [comment]
@mclarekin I have fixed problem with "diagonal split" of toolbar icons. Increased CPU load after changing toolbar icon size could be caused just by rendering of these icons. They are rendered with antialiasing, so it takes some time. If you any items which are long too render you need to wait some time to finish all. There is used only 1 CPU core for each icon.

@mancoast , Thank you for testing it with 4K display. Now it looks very well. As I see font height and UI elements size are like in Windows Settings window. I think this issue can be closed.

**Comment by mclarekin** [comment]
Increased CPU load after changing toolbar icon size could be caused just by
rendering of these icons

Yep, i currently have 150 toolbar icons. :)

**Comment by mclarekin** [comment]
In  save_settings,  the file name font  is a bit small on a laptop screen.
Attached image has the main UI font = 12.

**Comment by buddhi1980** [comment]
@mclarekin , you haven't attache any image. To attach image you need to do it from Github (not by email)

**Comment by mclarekin** [comment]
![filesave](https://cloud.githubusercontent.com/assets/12769564/24735744/827287fc-1ad8-11e7-835b-39bb04c00bfb.jpg)

**Comment by buddhi1980** [comment]
Unfortunately there is no straight way to change font size in QFileDialog. This is probably system dependent.
