### ISSUE TITLE
Rename "Program Settings" to "Program Preferences"

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#240]
This removes recurrence of word "settings" improving intuition and reducing ambiguity.
I like to reserve "settings" forall "*.fract" files.
"options" listed as synonym of "settings"

Any thoughts?

**Comment by mclarekin** [comment]
Yes, program options or even preferences

**Comment by zebastian** [comment]
"preferences" brings it to the point, in the code its also the preferences_dialog

**Comment by mancoast** [comment]
"Preferences" sounds optimal, i will adjust

**Comment by mancoast** [comment]
resolved:
https://github.com/buddhi1980/mandelbulber2/commit/e14a9f02e89eec63f0c23f6f4c5b1c372ccc2c75
