### ISSUE TITLE
Fractal Example Animations synchronized to Audio for Planetarium Projector - Spitz SciDome XD

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#241]
Demonstration support request for Spitz SciDome XD
https://www.spitzinc.com/planetarium/scidome/scidome-xd/

**Comment by mancoast** [comment]
@buddhi1980 @mclarekin @zebastian Any thoughts regarding design of this visual demonstration?  I want to include new feature https://github.com/buddhi1980/mandelbulber2/issues/234 [rotate backdrop imagery]

**Comment by buddhi1980** [comment]
Who requested support for it? This is quite bit topic and normally this kind of animations are not made for free.

**Comment by mancoast** [comment]
I am trying to get free [copyleft] alumni access to OSU Planetarium:
https://planetarium.osu.edu/private-groups

**Comment by zebastian** [comment]
basic setting is pretty clear:
full dome projection in desired resolution (also stereosopic), try to get specification for the projector player software first, to get a good result.
Then "only" do an animation  and render it in the desired format. :)

**Comment by mancoast** [comment]
Spitz support request created. We require SciDome XD PDF Datasheet.

**Comment by mclarekin** [comment]
Any thoughts regarding design of this visual demonstration?

Random thoughts:

To do a good visual demonstration requires  a lot experimentation and
practice ( and maybe some enhancements.)  I have only just started
learning, and I lack the computer power to get fast results to learn from.
I would say that all of us would need to spend sometime getting a good
understanding and trialling various things. I can picture how everything
can work in theory, but in practice there is some skill required.

My intuition says that the choice of music is very important, especially
for pitch following melody lines.

Slow orchestral  music would probably be one choice, but getting
instrument tracks would be difficult.

A solo piano piece ( Steve Sink???) would be good for demonstrating pitch.
And "would lend itself"  (some weird English for Krzysztof) to a fast
rendered single fractal demonstration of movement and color (i.e. Palette
can be "designed" to suit the animating parameter variations).

The possibilities are infinite, I have tried of lot of weird parameters
mixes like DOF to sound. Flat Background Brightness to sound.There is so
much yet to experiment with. (BTW I could not  cause a crash :)  )

The best demonstrations would encompass several fractals in a situation
where they only come to life with certain parts of the music.
Demonstration to include at least  : coloring, lighting, morphing ,
flying,, zooming. (It would be so much easier without sound  LOL)

Is there any existing animation that could be converted to use Anim by
Sound?


But the bottom line is, to construct a good visual demonstration would take
a lot of learning, time and commitment, (when OpenCL is implemented this
task would become  easier.)
Ideally what is needed is a new intelligent team member passionate about
Anim By Audio, who can take ownership of the project.


.

**Comment by mancoast** [comment]
Greetings @mclarekin 

computer power to get fast results - opencl priority #1, for now we use k1om.
Slow orchestral music would probably be one choice, but getting instrument tracks would be difficult.
lets review samples committed into public domain from https://github.com/buddhi1980/mandelbulber2/issues/252 and https://github.com/buddhi1980/mandelbulber2/commit/627f9c19346b68ba74230f38d12878b3d45b0d53 to focus on pitch following melody lines.


Lets make a list of requirements to specify mandelbulber vision.

1.) flight animation recorded with gamepad. [XBOX360 Controller]
2.) Rotate backdrop imagery from audio.
3.) Color reaction from audio via Palette Offset.
4.) Rock and Roll reaction from audio using Main Camera Top Z.

Any thoughts?

thanks,
coast

**Comment by mclarekin** [comment]
Any thoughts?

Early days still. I need to get  my mind back into audio mode again.

But I will  soon work on a demonstration of color offset reaction using the
existing pitch mode.

There are several ways of doing this, including writing some experimental
conditional code which may make it easier.

Fortunately it is all simple maths.

**Comment by mancoast** [comment]
@buddhi1980 Can you supply the command line arguments to override perspective to full_dome when using headless system?

**Comment by buddhi1980** [comment]
```mandelbulber2 --override perspective_type=3#sweet_spot_vertical_angle=60 settings.fract```

There are two overrides:
1. perspective type changed to 3 (which is fulldome)
2. sweet spot angle = 60, because you don't want to watch animation at zenith. It's better to move sweet spot to the front.

**Comment by mancoast** [comment]
works great, thanks!
