### ISSUE TITLE
Enable Windows QtMultimedia & MP3 Support using Windows Media Foundation

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#243]

**Comment by mancoast** [comment]
REF:
http://doc.qt.io/qt-5/qtmultimedia-windows.html

**Comment by mancoast** [comment]
i would prefer we wait until mp3 patent expires.  Then we can request mp3 support within the libsndfile code.  

https://github.com/buddhi1980/mandelbulber2/issues/249 reduces severity.
libsndfile nuget enables loading of compressed audio formats

**Comment by buddhi1980** [comment]
It has to be open until problem is not solved. We have no deadline for it.

**Comment by zebastian** [comment]
mp3 works on latest version of windows binary.
btw: mp3 still not incorporated into https://github.com/erikd/libsndfile/issues/258 
Is this still an issue?

**Comment by mclarekin** [comment]
does this mean change manual comment on cannot use mp3 for audio anim when
installed on Windows

**Comment by buddhi1980** [comment]
@zebastian we don't need support of mp3 files by libsndfile until it's properly supported by QtMultimedia. 
@mclarekin I will update User Guide
