### ISSUE TITLE
Document Instructions for creation of Visualization from audio file (Add to HELP / release notes / feature list)

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#244]

**Comment by mancoast** [comment]
@buddhi1980 @zebastian We already have one fantastic PDF for Deployment on our HELP menu.

REF: http://www.fractalforums.com/mandelbulber/mandelbulber-animation-by-sound/
I will propagate documentation to new repo - https://github.com/buddhi1980/mandelbulber_doc

Thanks @mclarekin [Anim By Sound Multiple tracks tutorial v0.80.pdf](https://github.com/buddhi1980/mandelbulber2/files/768872/Anim.By.Sound.Muliple.tracks.tutorial.v0.80.pdf)

**Comment by zebastian** [comment]
Oh yes, sure.
In the long run we should try to incorporate both existing help documents into the latex repository, so we can maintain it in the long term.

**Comment by mancoast** [comment]
No problemo, I will convert existing doc to Latex using Pandoc.

**Comment by mancoast** [comment]
dOCUMENTATION mERGED
ref https://github.com/buddhi1980/mandelbulber2/issues/195
rEQUIE hELP mENU

https://github.com/buddhi1980/mandelbulber_doc/releases/download/2.10.0.9.2/Mandelbulber.End.User.Manual.2.10.0.9.2.Pre-Release.pdf
