### ISSUE TITLE
Rework Help Menu and Rework Manual

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#245]
@buddhi1980 

I will rework the manual content to release quality.  Please describe steps required to move the "User Manual" action out of "About" menu and into a new "HELP" menu on main render window to the right of "About" menu. 

Thanks!
coast

**Comment by buddhi1980** [comment]
I will take care about creating new menu. You can focus on the document.

**Comment by mancoast** [comment]
Sounds great, thanks!

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber_doc/commit/bad79d387ed7619565f3a90bd4f97ff88115d7b9

@buddhi1980 @zebastian Please review User Manual Build 2.10.0.9.4
[handbook2.10.0.9.4.pdf](https://github.com/buddhi1980/mandelbulber2/files/785511/handbook2.10.0.9.4.pdf)

**Comment by mclarekin** [comment]
Random comments:
 - there is a Polish screenshot at end of 5.7, hmmm?? I thought we had
removed all the Polish?
- formatting looks a bit weird in places
- font seems big. but maybe that is the way I have pdf's  set up in Ubuntu
- maybe swap 8 and 9 making Q & A last chapter

**Comment by mclarekin** [comment]
- font seems big. but maybe that is the way I have pdf's  set up in Ubuntu
OK I see if I change zoom tot 150% i get an approx A4 size on my screen.

- sidepane does not show section numbers?

**Comment by mancoast** [comment]
Coversion to Latex from ODT requires analysis.
Current state meets requirements of this Issue.
We can resume tracking of PDF User Manual in new repo.
