### ISSUE TITLE
Load example settings does not allow user to reopen same example easily

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#246]
Load_example_settings does not allow user to reopen same example easily.  It operates differently  to load_settings.

Example user opens an example, tweaks it, then decides to reopen and start again. Open is greyed out.

**Comment by mancoast** [comment]
Greetings @mclarekin 
Can you please attach some screen shots so I can reproduce the issue.

Thanks,
coast

**Comment by mancoast** [comment]
So we open up an example and change stuff around.
We cannot revert back to the last save.

@buddhi1980 The Main Menu requires a "Revert" option found on many text editors.
![image](https://cloud.githubusercontent.com/assets/7040493/24483046/903b5e38-14c3-11e7-9c54-32da6d822343.png)

**Comment by mclarekin** [comment]
Change milestone to V2.13, as this is really minor.  A revert option would
do it but there is probably another way. To reproduce simply open a saved
file, then open it again, then do the same with an example setting file and
you should see the difference.

**Comment by mclarekin** [comment]
It has been a long time since i last checked, it appears to work correctly now
