### ISSUE TITLE
Animation By Sound Table ( and the audio selector UI chart) with animVal = paraVal + soundVal

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#251]
enable sight of the calculated values from Animation By Sound Dialogue

Please consider inserting two new rows foreach "Audio Loaded" parameter.
Imagine the animation table with animVal = paraVal + soundVal, (Three rows required for maximum design intuition)

![image](https://cloud.githubusercontent.com/assets/7040493/23228366/45509430-f90a-11e6-97e7-4473fac9171f.png)

![image](https://cloud.githubusercontent.com/assets/7040493/23228383/4f61b6ac-f90a-11e6-9624-505ad4d9f3b1.png)

**Comment by mclarekin** [comment]
Random first two thoughts are:

A) click on parameter from the list of parameters
this opens the parameter's tab,  where there is the three rows paraVal,
soundVal, animVal (and maybe interpolation type and remove 'parameter' from
animation options.)
also on this tab Enable Anim by Sound, which will open the audio selector
dock.

alternatively

B)Open AnimBySound, and have the three rows displayed below the bottom
chart.

 I am currently thinking that B) would be a better approach, as you need to
be able to edit paraVal while you are tweaking soundVal in the Audio
Selector UI. At present I have to keep opening and closing the Audio
Selector UI when I want to adjust the paraVal.

Implementing the ACCEPT button allows for more possible varaitions of A)
and B).


Currently we have to use our brains  to figure out the mathematical result
of what soundVal will do to the final animVal.

Being able to see the numbers would be good for users.

**Comment by mancoast** [comment]
@mclarekin 
Great input, thank!  I agree that displaying these three values, the three rows paraVal,
soundVal, animVal, make designing fractals with less effort extremely efficient.
Sometimes want to to use our brains, sometimes we want to turn them off 🔥

**Comment by mclarekin** [comment]
we can consider implementing a  checkBox for each parameters to use anim by
sound

I am thinking it would be desirable when working with audio, to be able to
simply turn on or off the soundVal effect of a parameter from the Keyframe
animation table.

**Comment by mancoast** [comment]
Greetings,

Please provide hint/instructions for implementation of this feature.

Thanks,
coast

**Comment by buddhi1980** [comment]
This is very complicated to implement, because there is needed to reorganize animation table. 
By the way it doesn't make sense to display audio animation as values in keyframe animation, because audio is applied for every frame (in table we have only keyframes). This would be very confusing for users.
The solution which I have in mind is to add charts for final animation patch in animation table (needed to completely new table widget) or in Audio Selector window (much easier to do).

**Comment by buddhi1980** [comment]
To turn off AnimBySound for given parameter you can use "Enable animation by sound" checkbox:

![image](https://cloud.githubusercontent.com/assets/11696990/23568851/d576db6a-005c-11e7-8b73-a0f451d313cd.png)

**Comment by mancoast** [comment]
@buddhi1980 The recent enhancement of export from 'anim by sound keyframe' to 'anim by sound flight path' enables this feature.  This offers added value by provided the charted path values.  Additionally we need the animation offsets.  Ideally the end user needs to be able to hand tune in Spreadsheet.  The user requires both the original flight path data recorded before audio.   Secondly, the end user needs the offset data for the audio waveform.  What are your thoughts>

**Comment by mancoast** [comment]
low value, tabled for after opencl
