### ISSUE TITLE
Require Mandelbulber to generate dome masters, and from there any planetarium with a fulldome system should be able to compile the appropriate playback media.

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#253]
the fulldome community has developed an intermediate output mode called "dome masters", from which the appropriate media file can be compiled for any system. Here's where you'll find that spec: http://www.imersa.org/afdi-dome-standards-group

**Comment by buddhi1980** [comment]
I think mandelbulber already renders full dome animations according to this standard. It's nothing new for me. The way how Mandelbulber render images/animations was already discussed with 3 different Planetariums in Poland. When I compare what is generated by mandelbulber and what is written in this standard, everything looks correct.

**Comment by mancoast** [comment]
Awesome news! I will further investigate. Thanks!

**Comment by mancoast** [comment]
@buddhi1980 the fulldome perspective type for Mandelbulber is fully compliant with generation of sequences of frames of Dome Master.

Please review the standard for **metadata** for distribution of sequences of frames.
Specification of Dome Master / Dome Original Metadata by Association of Fulldome Innovators (AFDI).
http://www.imersa.org/images/standards/AFDI%20standards%20v1.0.pdf

What are your thoughts regarding generation of metadata for complete compliance with Association of Fulldome Innovators (AFDI)?

Thanks,
coast

**Comment by mancoast** [comment]
after additional research, it is my opinion that we do not require.
