### ISSUE TITLE
Implement the Tetrix for mandelbulber examples deployed with build package

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#254]
##### System information (version)

- mandelbulber2 => 2.10
- Operating System / Platform => all
- Compiler => all

##### Detailed description

This is request for Tetrix for mandelbulber examples fract settings files.

##### Steps to reproduce

3 faces = triangle => Sierpiński sieve => Tetrix 
http://mathworld.wolfram.com/Tetrix.html
implement the Tetrix for mandelbulber

**Comment by mancoast** [comment]
@buddhi1980 
Is it feasible to tune any of the current fractal formulas to generate the tetrix?
I require an infinitely recursive 3D model of the tetrix for another project.

Thanks!
coast

**Comment by buddhi1980** [comment]
We don't have any formula which can generate this shape.

**Comment by mancoast** [comment]
ok I will try to document the requirements. thanks!

**Comment by buddhi1980** [comment]
Now I look that Sierpinski3D formula is quite similar and there is some small chance that it could be adapted. But there is no guaranty.

**Comment by mancoast** [comment]
@buddhi1980 thanks for the hint 

I have tried to explore the Sierpinski3D, but have not figured out the tetrix configuration.

@mclarekin historically, have you ever rolled up the tetrix with mandelbulber?

**Comment by mclarekin** [comment]
@mclarekin <https://github.com/mclarekin> historically, have you ever
rolled up the tetrix with mandelbulber?

no

**Comment by buddhi1980** [comment]
Actually there is unknown escape-time implementation of this fractal and also unknown distance estimation.
