### ISSUE TITLE
OpenCL Engine

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#255]
port existing code for preparing and running the render kernel in cpp from mandelbulber v1 to existing code base

**Comment by mancoast** [comment]
@zebastian @buddhi1980 Is it feasible to accelerate mesh export with openCL?
This might be a low hanging fruit with high value.

![image](https://cloud.githubusercontent.com/assets/7040493/23774995/72572782-04f4-11e7-9e79-2cc671c21678.png)

**Comment by buddhi1980** [comment]
There is some chance it use OpenCL to calculate voxels needed for mesh export. Transformation to mesh from voxels wont be possible. But calculation of voxels takes about 90% of total computing time. Converting to mesh is realitevely fast. So potentially OpenCL will speed up this about 5-10 times.

**Comment by buddhi1980** [comment]
By the way calculation of 5000x5000x5000 mesh is crazy :smile: Even 16GB of RAM would be not enough to load such a object.

**Comment by mancoast** [comment]
We really should see 100kx100kx100k exports menger sponge for study of antenna theory.
The self similar structures receive multiple wavelengths!

**Comment by buddhi1980** [comment]
Why you use maxiter=10000? This is enormous value for such a fractal. It increases calculation time without any benefit.

**Comment by mancoast** [comment]
lol honestly i was just trying to max it all out without crashing.
What is the purpose of the maxiter?
Is that the iterations of self similar pattern recursion?

**Comment by buddhi1980** [comment]
This like in mandelbrot fractal. It limits number of calculated fractal iterations.

**Comment by mancoast** [comment]
ok, so good operation requires the x,y,z bounds >> iterations.
In other words, we need to take many samples per iteration (at least 5-10) to actually see that deep into the 3D solid model after its exported.

**Comment by mancoast** [comment]
@buddhi1980 imagine an antenna that detects 10,000 different wavelengths all based on the size of the smallest cube in the 10,000th iteration.

**Comment by buddhi1980** [comment]
At 10000th iteration the smallest cube size (if menger sponhe sah size 1m x 1m x 1m) is 1.0 / 1631350185342625874303256729181154716812132453582537993934820326191825730814319078748015563084784830967325204522323579543340558299917720385238147914536811250145319235516622439102542362884355668655965964501201417744827552999037327442544642575123553734186738760781361993722561687286201650480559317405990952046166850066311892691157177345225585062696852625187913986708508047253964093373024341015218691432891735457685445727419556221801333774562850247067305942699911420254077317598819984248727618368529938892782529678644025299944478569418367532352170443219578580627012338838293177019899084130086150699610894478206501516341034489494580933768915680768667346256303816479219066534012434413398076320559436475496345156407234050260637779058511412381491900163717703445738501993906023292519447111423589297856532241562834414218484289208346622787576050127600980153070303752583915789387574119249770530046969106245436992679597545634023677773435466713907260157496983431276965355718439614758707126044394794486223574445971120447306293776415377003021033218363553181817345661802274597505531321259851442958754554729653460959719483603654687049177192762521435295750345494840363582234572877488517580950015845183738941379809532971199309210141742840677432612645000546788873654625494865860248449453593888865654274697742436838533549608316492131860193497702509578037010430798027635685735034920586607837180606554239353610167340201798095159894698066433039150584580367424834887807101041291866733582384989962348621505030405257778984851241026383481171923694931142341182358531640508530616493667113745698539428567732477177504605097086552089359615168701715385575519734819965907019295477130834762711105247113447632598636283858595955220964538208905518287185486674463373753321752488011840178759509406085571701014408713649553241854424148943708007471615840489591413645180203244670796105875763334569169674329386962374541087005185159067285934706121257344657204508846546061682608257973168600458521828433345239615773003630637942182243581800150590520391820920696966232670695262351242738024046878411453510149673398340124021984004895673368930962032161379375715672756246165193339754026679596386592159091332206057267334984925330339787424238196077533718273003778369870874878173841974769888032160118631050633286970493130307683944479096833930630127337101408724806094685179369797311443270675928854607762283100252680055484969686771028094594660366959379735464213662223119269502732122951191295294032087976312315176055595949696116314145568827884294958728839910027369188001877414756889265018615206533521911307258241769961690199553024993773521909978675895489253436583523584315611279972816412346121981734390478240251711160320657533052785075256464299531806498590081555797994588593112435130325281125525429579708228194665879870597907749246984964418316658595084495316472689614616829780817839847045156132052618054231084074484310746936895970772683660847181706059877173017075544647344077403137122743765104842160622475752708595851594727315102740066294816111128477782810353149948891367280078316788805117715542728510386173665806940479769590075882046523867397088266016228510759922141874365700687253784267788370880751585039769181243388056177265236484729701950802584896483388322516566898693508127459629398312186404627726859040158020905998850051126247016715049526190813668869386132408155904633628896303709031203352240072236088249492818280907540691431995704492750442079727811783767743144697908575643299075358258810244024061103908451640108994886843335374844410463973407451916506763294141934798562443556734207281591075448412381291748731293828067040322818881300397838408133224248464657141757440485296267516561610152736742565486950871200178839384617178045745596304576494356596488751839648129615990247199673550885429296453679677940437723096572336162518203079829773478585460606032341909164671113867849092884010744992345683476376311422600077031693124366669942569482818115504884316138083206784548056975845775109064099600724201825540062727690818808260179552016705470132780236698974708283548110554387844688989623069609188164354747615499857401590739605947868497857418048679891843864316461854135168925837904232648766947973338471299675425170380
8037828636599654447727795924596382283226723503386540591321268603222892807562509801015765174359627788357881606366119032951829868274617539946921221330284257027058653162292482686679275266764009881985590648534544939224296689791195355783205968492422636277656735338488299104238060289209390654467316291591219712866052661347026855261289381236881063068219249064767086495184176816629077103667131505064964190910450196502178972477361881300608688593782509793781457170396897496908861893034634895715117114601514654381347139092345833472226493656930996045016355808162984965203661519182202145414866559662218796964329217241498105206552200001

**Comment by mancoast** [comment]
LOL this would literally be the first real use case scenario for executing mandelbulber operations on BOINC

**Comment by mancoast** [comment]
please support animation rendering and mesh export with opencl.

**Comment by zebastian** [comment]
animation rendering will use opencl out of the box, as soon at is implemented for the still frames. 
mesh export will need extra work, this will come later...

**Comment by mancoast** [comment]
Mesh export == $$$ for connecting our fractal community to the solid modeling communities.
We could generate awesome content for unreal4 engine!

**Comment by mancoast** [comment]
Solid strategy for the GPU support.  This will elevate the system to the next level of modernization with support for current and future hardware.

**Comment by zebastian** [comment]
mesh export moved to here: https://github.com/buddhi1980/mandelbulber2/issues/346
Rest of this issue has been realized more or less with current opencl implemenation, new points can be opened in new issue...
