### ISSUE TITLE
Install initial w parameter value on each 4D fractal UI

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#257]
Install initial w parameter value on each 4D fractal UI so that is easier to tweak

**Comment by buddhi1980** [comment]
How it should work with hybrids? Initial value is only one which is applied before iterations. Do you wan to have this only for booleans?

**Comment by mclarekin** [comment]
The current problem is having to open another tab to tweak or view the
initial_w value. But I cannot find a good solution

Solution A. Maintaining global initial w
Relocate global initial_w to "somewhere"  more accessible. But the existing
options are not good - like the render window or next to auto refresh in
the Navigation dock.
*(BTW I wonder if "Render Stop Undo Redo Auto refresh " should be on the
render window not the navigation dock. This would make space available in
the top right hand corner)*

Or put Initial_w  in a new small dock if the preset toolbar can be shortened


Solution B. On the formula UI
This is the temporary code we had previously,  where "w" was declared as 0
prior to the iteration loop.  The initial w value is introduced in the
first line of formula code   if ( i == 0) then  z.w  = w +
transf.common.initialW;
But this only works if the formula is starting at iteration 0.


Solution C.  Option for each slot to enable  it's own Initial Conditions.
Major amount of work involved, but could include pre transforms &  domain
change code. But I would suggest that this sort of stuff maybe more suited
to users of openCL custom formulas.


Summary,. The current location of initial_w is not good, but I have not got
a satisfactory solution.




On Sun, Feb 26, 2017 at 9:47 PM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
There is initial w valu for each formula in boolean mode. As there is no better proposed solution as actual, I'm closing this issue.
