### ISSUE TITLE
Enhance audio data within fractal settings file. 

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#260]
##### System information (version)

- mandelbulber2 => 2.10
- Operating System / Platform => All
- Compiler => All

##### Detailed description
Add new features to enhance animation from audio data. 
Enable animation on computer nodes without loading audio file.

**Comment by mancoast** [comment]
Add sha1 for audio file. 
Add parameter offset data. 
Enable full render without loading audio file.

**Comment by buddhi1980** [comment]
Can you add more explanation:
> Enable animation on computer nodes without loading audio file.
What you mean here? Do you mean NetRender nodes? They already don't need audio data.
> Add sha1 for audio file.
Why we need sha1 for audio files?
> Add parameter offset data
Do you mean time offset? Time offset is really needed.
> What you mean by "full render"? Full render of animation?

**Comment by mancoast** [comment]
When using an audio file for animation, its important to use the same file for multiplexeing the stills with the audio file.  (ex. ffmpeg or Adobe)  SHA1 hash within the fractal settings file enables verification before multiplexing.

Next, Within the settings files, we need to store animVal = paraVal + soundVal foreach parameter animated by an audio file.  This is important for animating audio file that do not exist in public domain.

These two requirements enable animation on computer nodes without libsndfile for ogg and non-wav formats.

**Comment by mancoast** [comment]
This is closely linked to https://github.com/buddhi1980/mandelbulber2/issues/251 .
@buddhi1980 @zebastian What is required for this functionality? 
We need to be able to hand tune the audio FFT offset data to render animations.

**Comment by buddhi1980** [comment]
There is needed free time... I will start thinking about these enhancements when I finish with many older requests.

**Comment by mancoast** [comment]
Greetings!

I request we prioritize this issue because I would like to really master the animation by sound.
To master the animation by sound we need to be able to track our fractal design changes with plain-text edits for fine tuning the parameters.

Thanks! 
coast

**Comment by mclarekin** [comment]
> Next, Within the settings files, we need to store animVal = paraVal + soundVal foreach parameter animated by an audio file. This is important for animating audio file that do not exist in public domain.

Not that I need to understand what you guys are discussing , but -

would this mean  data for every parameter being animated  at each frame,  to be stored in the .fract file? If so it could be an Option of Save, rather than the default as files would get big??

would it be animVal, paraVal & soundVal, or just paraVal & soundVal??

**Comment by mancoast** [comment]
Initially I was thinking that we could store an audio sample foreach keyframe, but the audio data requires many samples per keyframe.  This issue requires further analysis and strategy.  
@mclarekin I agree that this is way to much data to store in the .fract settings file. 

@buddhi1980 how many audio samples/second do we need to create smooth linkage between audio and video?

**Comment by buddhi1980** [comment]
We need the same number of audio samples as total frame number.

**Comment by mancoast** [comment]
Excellent, I will work out the details for some alternatives for us to crush this barrier.
Thanks!

**Comment by buddhi1980** [comment]
I have added possibility to export keyframe animation with sound animated frames to Flight Animation. In Flight Animation editor you can edit every frame and save all frames to settings file. To render this animation as Flight Animation, audio files will no longer needed.

**Comment by mancoast** [comment]
I will test asap.

**Comment by mancoast** [comment]
REF https://github.com/mancoast/mandelbulber2/commit/46e893d2de05b030b54cffb0e025a4c3efc0e973
The flight data export did not operate as expected.  
The resulting flight animation does not match the keyframe animation.
Also, the data in the flight animation export produced multiple invalid frames that crash/render incorrectly and produce tiny png files.  This is reproducible with different keyframe animations.
```
verify all png frames are > 1kb
##Render malfunction##
root@coast77 coast]# rm -rf '/home/mandelbulber2/render/frame_00006.png' '/home/mandelbulber2/render/frame_00153.png' '/home/mandelbulber2/render/frame_00217.png' '/home/mandelbulber2/render/frame_00810.png' '/home/mandelbulber2/render/frame_00811.png' '/home/mandelbulber2/render/frame_00812.png' '/home/mandelbulber2/render/frame_00813.png' '/home/mandelbulber2/render/frame_01696.png' '/home/mandelbulber2/render/frame_01704.png' '/home/mandelbulber2/render/frame_01714.png' '/home/mandelbulber2/render/frame_01790.png' '/home/mandelbulber2/render/frame_01866.png' '/home/mandelbulber2/render/frame_01890.png' '/home/mandelbulber2/render/frame_01918.png' '/home/mandelbulber2/render/frame_01934.png' '/home/mandelbulber2/render/frame_02900.png' '/home/mandelbulber2/render/frame_02990.png' '/home/mandelbulber2/render/frame_02994.png' 
```
I am seeing this in the console:
![screenshot from 2017-03-25 12-02-25](https://cloud.githubusercontent.com/assets/7040493/24325565/c3da952e-1171-11e7-9cd0-7a2505030420.png)
```

[root@coast77 coast]# sudo -s
Intel(R) Parallel Studio XE 2017 Update 1 for Linux*
Copyright (C) 2009-2016 Intel Corporation. All rights reserved.
[root@coast77 coast]# ssh mic5 '/home/mandelbulber2/mandelbulber2/tools/DOE//..//..//..///../build-mic/mandelbulber2/mandelbulber2 --never-delete --nogui --format png16alpha --no-cli-color "/home/mandelbulber2/mandelbulber2/tools/DOE//..//..//..//mandelbulber2/deploy/share/mandelbulber2/examples/Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/icoastahedron.fract" --output /home/mandelbulber2/mandelbulber2/tools/DOE//..//..//..///render/ --flight --res 320x240'
QIconvCodec::convertToUnicode: using Latin-1 for conversion, iconv_open failed
QIconvCodec::convertFromUnicode: using Latin-1 for conversion, iconv_open failed
Mandelbulber 2.10
Log file name: /root/.mandelbulber_log.txt
Detected 240 CPUs
Default data hidden directory: /root/.mandelbulber/
Default data public directory: /root/mandelbulber/
Warning: File not found anywhere
((null):0, (null))
Warning: defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.audiodecode"
(/home/KNC-Lib/qt5/qtmultimedia/src/multimedia/qmediaserviceprovider.cpp:437, QMediaService *QPluginServiceProvider::requestService(const QByteArray &, const QMediaServiceProviderHint &))
Critical: cAudioTrack::error QAudioDecoder::ServiceMissingError
((null):0, (null))
Warning: File not found anywhere
((null):0, (null))
Warning: defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.audiodecode"
(/home/KNC-Lib/qt5/qtmultimedia/src/multimedia/qmediaserviceprovider.cpp:437, QMediaService *QPluginServiceProvider::requestService(const QByteArray &, const QMediaServiceProviderHint &))
Critical: cAudioTrack::error QAudioDecoder::ServiceMissingError
((null):0, (null))
Frame 218 of 4700 Done 11.11%, elapsed: 43.1s, estimated to end: 6m 14.9s [   ]
Rendering image: Done 0.00%, elapsed: 16.3s, estimated to end: n/a [          ]

```

**Comment by buddhi1980** [comment]
I have just tested it and confirm that there is something wrong.

**Comment by buddhi1980** [comment]
Problem fixed. Now animation should be properly exported.

**Comment by mancoast** [comment]
Confirmed fully operational.
k1om enabled without libsndfile for visualization.
