### ISSUE TITLE
make mandelbulber source citable

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#261]
what do you think about adding support to make the code citable?

https://guides.github.com/activities/citable-code/

**Comment by mancoast** [comment]
Greetings!

@buddhi1980 Please enable this automatic service for the shared repo.
Here's a sample I create in ~5 minutes - https://zenodo.org/record/345185#.WLjVcDsrKUk .
Citations within code are valuable for science!

Zenodo requires GIT HOOKS, similar to APPVEYOR or TRAVIS.
Zenodo requires and OAUTH token from you @buddhi1980 

thanks,
coast

**Comment by buddhi1980** [comment]
I have just configured everything. It will start working after next release.

**Comment by mancoast** [comment]
Thanks!

**Comment by zebastian** [comment]
Cool, thanks!
