### ISSUE TITLE
Recent Files option

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#262]
Implement a recent files option for loading.  Like having the last 6 saved file names, linked to their folder locations.

**Comment by zebastian** [comment]
yes good idea, i often would have liked the idea.
Would be great to have it for next release.

**Comment by buddhi1980** [comment]
Good work, but It should add path to recent files also when settings are saved

**Comment by zebastian** [comment]
thanks, good point. added in last commit

**Comment by zebastian** [comment]
should be good now
@mclarekin can you check if anything is missing, close if OK

**Comment by mclarekin** [comment]
It is good!! Closed.
