### ISSUE TITLE
Purge All non-functional http references from source/repo.

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#263]
It's time to class things up for citable code for science.
I suggest we follow embedded systems archetype:
We need to protect the typesetting of the machine language.
We need to purge all non function http references.
We need to build a bibliography for internal references to external http references.

**Comment by mancoast** [comment]
@buddhi1980 @zebastian Within the QT .ui files, it possible to reference strings from a .h header file?  I would like to convert all the url's to strings in a header.

**Comment by buddhi1980** [comment]
Which strings or url's do you mean?

**Comment by mancoast** [comment]
What are your thoughts regarding conversion of the Bibliography.md to Bibliography.h .

https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/deploy/share/mandelbulber2/doc/Bibliography.md

**Comment by mancoast** [comment]
@buddhi1980 @zebastian I want to proceed with removal of http links from comments.  Please tell me now if we do not wish to pursue this code clean-up.

**Comment by buddhi1980** [comment]
Give me an example which links you want to remove

**Comment by mancoast** [comment]
Reference Line 43 below.  We can instead use a local Bibliography.h

mandelbulber2/src/common_math.cpp
41	//********** Random ******************************
42	// reference:
43	// http://csg.sph.umich.edu/abecasis/class/2006/615.14.pdf
44	// Park-Miller Generator Without any Divisions

**Comment by buddhi1980** [comment]
This kind of referenced I would like to keep in the code

**Comment by mancoast** [comment]
that is ambiguous answer as both common_math.cpp and Bibliography.h are both in the code.
1.) we can use Bibliography.h for local strings foreach http links.
2.) we keep non-functioning http links in-line with functioning code.

It is my opinion that inline http references are clutter/lint

**Comment by buddhi1980** [comment]
In bibliography.md we have just a list of external references. But this information is not useful when there is no connection between reference and the code. 
If the reference is in comment in the code there is very visible information for us from were algorithm was taken. If you put this information in another file how you would like to manage links between reference ad code?

**Comment by mancoast** [comment]
For representation of the links, we simply use static strings that hold the value of the links.
for example: MB_R77 = "http://csg.sph.umich.edu/abecasis/class/2006/615.14.pdf";
Then we reference our internal MB strings references.
This keeps things nice and orderly via standardization.

**Comment by buddhi1980** [comment]
But why to make it complicated?
If we talk about standardization we can standardize way how references are written in the code. But I will not agree to move references out of the code. We can make separate list in https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/deploy/share/mandelbulber2/doc/Bibliography.md but in the code it has to be duplicated.

**Comment by mancoast** [comment]
I think there is a miscommunication here.
I will use a PR for review before merging any changes.

**Comment by zebastian** [comment]
we also need the direct references in fractal_formulas.* for the tools/* scripts to recognize the URLs and put them in the ui files.
I am with krzysztof: Better to keep the URLs directly in the code.

**Comment by mancoast** [comment]
Let me clear up the miscommunication.  

First, we always have the opportunity to do nothing.  That is our null option.
Now there also exists an alternative option.

Picture this if you will: 
The new altertive requires conversion of Bibliography.md to Bibliography.h
=>
common_math.cpp and Bibliography.h are both in the code.
==> We develop a file, Bibliography.h, to include anytime we need to reference the www.
Rather than using comments and other non-functional references in common_math.cpp
===>
We can use functional references to the c++ strings that we serialize as references in Bibliography.h
====>
This adds value by increasing standardization across source files and providing a new mechanism for including additional www references.

=

Cleaner code

**Comment by mancoast** [comment]
tabled for later
