### ISSUE TITLE
Openning in material editor instead of fractal tab

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#264]
whenever I open a saved file, it opens in material editor when I think it should open in the fractal tab.

also if i am in fractal tab with auto-refresh on, I change a fractal parameter, then decide i do not like it, I hit undo and it goes back to material editor tab instead of fractal tab.

**Comment by mancoast** [comment]
Greetings @mclarekin 

Lets confirm the unexpected behavior for this issue.
As I understand, this occurs when one opens a fractal settings file from the file menu:
Upon valid load of fractal settings file, the GUI is switching context to the 'Material Editor'?

![image](https://cloud.githubusercontent.com/assets/7040493/23825694/701aa9b2-065c-11e7-95b0-bdc3bb303aef.png)

**Comment by mclarekin** [comment]
yep, I confirm that is the problem

**Comment by mclarekin** [comment]
would suggest to fix now,  not V2.13.

**Comment by mclarekin** [comment]
this is linked to the other problem, that when editing in fractal tab and click undo,   then program also switches to material editor

**Comment by buddhi1980** [comment]
I will try to correct it in 2.11

**Comment by buddhi1980** [comment]
I have fixed it. Now Material Tab appears only when is changed selection of current material in Material Manager.
Please let me know if now is better.

**Comment by mclarekin** [comment]
It works well

On Thu, Mar 16, 2017 at 5:21 AM, Krzysztof Marczak <notifications@github.com
