### ISSUE TITLE
Simplify Frame Index Number System

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#265]
- Operating System / Platform => all

Problem reported by paigan0 on FractalForums

When rendering animations, which is 98% of what I do, the v 1.21 lets you know which keyframe you're currently rendering from and what fraction or percentage of the keyframe.  In version 2.x, if I have a bad frame, and it's frame #7459 of 7800, which keyframe do I need to go in and change? Was it #16 or 17...let's see, it's 150 frames per keyframe, divide the total by that, to get 95.4%--wait, which keyframe is that, though? I literally could not exactly tell you sometimes without getting out a calculator. 

Version 1.21 tells you what keyframe and how far along it you're rendering, so if you need to change a keyframe, it's really easy to know which one. Can we bring that back, please?

Problem reported here:
http://www.fractalforums.com/feature-requests/keyframe-and-percentage-indicator/new/#new

**Comment by mancoast** [comment]
REF: https://github.com/buddhi1980/mandelbulber2/issues/235
related to frame && keyframe displays juxtaposed on GUI
