### ISSUE TITLE
add color support for mesh export

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#266]

**Comment by mancoast** [comment]
Im excited for this functionality

**Comment by buddhi1980** [comment]
Done

See this (in MeshLab):

![image](https://cloud.githubusercontent.com/assets/11696990/23832530/5444a636-0736-11e7-83d6-d5fb91732ee5.png)

**Comment by mancoast** [comment]
N3xt level.  Now we are building a system with manufacturing value.

**Comment by zebastian** [comment]
nice, thank you krzysztof!

**Comment by zebastian** [comment]
here another example: 
![colored mesh example](https://cloud.githubusercontent.com/assets/7888201/23833679/3e939cda-0749-11e7-9d7d-7eb29ae9b458.png)
