### ISSUE TITLE
size_t does not meet the requirements for openmp2.0 

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#268]
##### System information (version)

- mandelbulber2 => 2.11
- Operating System / Platform => Windows X64
- Compiler => ALL

##### Detailed description

size_t does not meet the requirements for http://www.openmp.org/wp-content/uploads/cspec20.pdf
given win64 ==> size_t ~= unsigned long long 

##### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/7040493/23729985/f03b771a-0432-11e7-8f99-45759a3effa5.png)

![image](https://cloud.githubusercontent.com/assets/7040493/23730051/58dacdac-0433-11e7-9fb0-d8cd27c818f4.png)

**Comment by mancoast** [comment]
@buddhi1980 I will test out new visual studio 2917.  Hopefully new VS supports openMP3.0.
signed or unsigned integer type as for loop iterator.

http://www.openmp.org/wp-content/uploads/spec30.pdf
![image](https://cloud.githubusercontent.com/assets/7040493/23730576/2966926a-0436-11e7-97a6-5d81b1ef44b9.png)
https://github.com/buddhi1980/mandelbulber2/commit/799f436fbbdf636582172534f8d7efb279e995c2

**Comment by mancoast** [comment]
@zebastian This is broken again.  I can fix it, but we need to understand why.
marchingcubes.h(132): error C3016: 'kk': index variable in OpenMP 'for' statement must have signed integral type (compiling source file C:\projects\mandelbulber2\mandelbulber2\src\mesh_export.cpp) 

*Visual Studio requires a signed integral type.*

**Comment by buddhi1980** [comment]
I hope latest commit https://github.com/buddhi1980/mandelbulber2/commit/9d487b20bf8708a7c9952aef75569de78abec2f8 fixes this problem

**Comment by zebastian** [comment]
Thanks for the fix :)

**Comment by mancoast** [comment]
muchos gracias!
