### ISSUE TITLE
Fix clang build for travis continuous integration

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#269]
##### System information (version)

- mandelbulber2 => 2.11
- Operating System / Platform => OSX
- Compiler => clang 

##### Detailed description

Fix clang build for travis continuous integration.
marchingcubes.h:41:10: fatal error: 'omp.h' file not found.

##### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/7040493/23730428/3bea3794-0435-11e7-9733-a33bf34190e4.png)

**Comment by mancoast** [comment]
https://github.com/vgteam/vg/pull/382/files

**Comment by mancoast** [comment]
hmmm, is it possible to use the boneyard?

https://github.com/Homebrew/homebrew-core/commit/c57e307

**Comment by buddhi1980** [comment]
actually ```include <omp.h>``` is not needed here. We can remove this line. However openmp will not work under osx (but program will be compiled properly)
It was needed only when omp_set_lock() was used.

**Comment by mancoast** [comment]
@buddhi1980 It is time to reach out to the openmp user group / mailing list.  Would you like me to message or do you want honors?

**Comment by buddhi1980** [comment]
Why we need to contact with openmp group?

**Comment by mancoast** [comment]
I want omp to work in mac labs for education and human ecology department

**Comment by buddhi1980** [comment]
First I would like to confirm where is the problem. This is the reason why I hesitate to bother people responsible for openmp

**Comment by mancoast** [comment]
I understand the hesitation, but we have a huge backlog.  At openmp, They would probably be intrigued by our use case scenario and have very valuable insight. The openmp usergroup exists for open-source projects like mandelbubler.

**Comment by buddhi1980** [comment]
Last osx build is successful, without any warning about unknown #openmp pragma 
The question is if openmp really works.

**Comment by mancoast** [comment]
travis build succeeds, I dont have hardware to test at this moment.
we can open new issue to verify openmp travis build.
