### ISSUE TITLE
cOMPETE IN 3D MODELING CONTEST

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#270]
https://3dx-us.com/3dx-model-showdown

We have an excellent opportunity for a little friendly competition here.
Unlimited entries by deadline of deadline March 22
1st entry ==> https://3dx-us.com/models/mandelbulber2-engineering-sample-outputply

**Comment by buddhi1980** [comment]
Something from me: https://3dx-us.com/models/pseudo-kleinian-fractal

**Comment by mancoast** [comment]
Does the network rendering speed up the mesh export?
?I havent experimented with those two elements.

**Comment by buddhi1980** [comment]
No, NetRender doesn't speed up mesh export

**Comment by mancoast** [comment]
btw the kleinian looks awesome. Im Thinking about cleaning up the default bulb and adding serious metadata in solidworks for my final entry.  Ill bet that kleinian would look amazing with photoreal metadatas for CAM renderings

**Comment by mancoast** [comment]
maybe in the future the networked labs can render the meshes
