### ISSUE TITLE
slow boot up time due to icon loading

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#272]
The program takes quite long to bootup right now (from 5 to 10 seconds). This is caused by populateItemsFromFractalList, which will be called 9 times and each time it loads ~100 icons.

possible ways to improve:
- implement a cache to only load the icons once
- use qt internal qrc file to bulk load all images at once

I am unsure what is the best way, any opinions?

**Comment by buddhi1980** [comment]
The best will be to use internal cache. 
I would not use qrc file for it, because it will be much to big (gcc will consume a lot of memory to compile resources)

**Comment by buddhi1980** [comment]
In cFormulaComboBox we can create static QMap<QString, QIcon> container to store icons with access by file name. If item won't be in QMap, then will be loaded, uncompressed and added as Icon to QMap. 
I can try to do it.

**Comment by zebastian** [comment]
Thats a good idea.
i would be glad, if you could do it.
Cheers!

**Comment by buddhi1980** [comment]
Done.
