### ISSUE TITLE
Determine Target FPGA Vendor and consider continuous integration of FPGA design tools.

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#274]
We use C++ to code the algorithm.
We use Hardware Description Language to code hardware!

Altera Quartus
Xilinx Vivado
https://www.altera.com/products/design-software/overview.html
https://www.xilinx.com/products/design-tools/vivado.html

**Comment by mancoast** [comment]
I require upgrade of k1om boards to pci-express fpga.

**Comment by mancoast** [comment]
Coprocessor x100 Product Family, Knights Corner, k1om
Server Vertical Segment Processor Number **5110P**
Status: End of Life; Lithography: 22 nm; TDP: 225 W

We require the new FPGA Accelerator to exceed the k1om acceleration.

**Comment by buddhi1980** [comment]
You have no time to fix gamepads coordinates issue and you are going do stuff like this?

**Comment by mancoast** [comment]
I am electrical engineer, not software engineer. Software is cool, but I play with hardware.

**Comment by buddhi1980** [comment]
I am automation engineer, not software engineer :) I'm programming PLCs and work with much bigger electric hardware

**Comment by mancoast** [comment]
The new FPGA's are PCI express.  We can crush a custom accelerator in no time.
Essentially, FPGA Accelerated Compute Node using Heterogeneous C-based modeling and hardware design with FPGA for Mandelbulber OpenCL.

**Comment by zebastian** [comment]
@buddhi1980 you certainly got my promotion as a software engineer ;)
@mancoast Maybe its possible to use altera fpga with the new opencl code: https://www.altera.com/products/design-software/embedded-software-developers/opencl/overview.html
But thats out of my scope, would be highly interesting to see, if this works and how it performs.

**Comment by mancoast** [comment]
I have opened multiple support tickets with altera.
Everyone OK if we proceed with Altera (Intel FPGA) ?

Checkout this free online training for more info:
https://www.altera.com/support/training/course/oopnclimageproc.html

**Comment by mancoast** [comment]
Statrix 10
