### ISSUE TITLE
enhancements to fog

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#275]
evaluate controls for fog, such as position, extent,  primitive shapes bounding the fog,  layers and varying the density.

Assume raymarching reflections to not be enabled when using this enhancement.

After openCL,  is may also be practical to implement IQ clouds.

**Comment by mclarekin** [comment]
also investigate fog based on cumultive DE

**Comment by mclarekin** [comment]
investigate fog options for boolean mode and/or primitives

**Comment by buddhi1980** [comment]
Clouds are implemented. To make them defined as a primitive shapes will require a lot of code and will be low benefits. Now there are implemented flat shape for clouds and density of clouds based on distance from fractal.
