### ISSUE TITLE
Completely Rework the GUI

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#277]
EDIT:
I would like to see a mode for "fun".
I want a slider switch to go from "fun" mode into "advanced" mode

When the system initiates, we need to hide 90% of the GUI for "fun" mode.
Given OpenCL support, we need to enable users to launch, then play.

The GUI requires massive simplification engineering.
We need to make it easier to use.
Any thoughts/suggestions?

**Comment by buddhi1980** [comment]
We need professional UI designer in our team.

**Comment by mancoast** [comment]
Agreed, we need more people from the community to join in the action

**Comment by mclarekin** [comment]
One enhancement could be to have a row that is a warning panel, which tells me what non default functions are on.  These are the functions I sometime forget I have on,

julia, max iters, boolean, hybrid, ray marching reflections,  mouse click is not on move camera option.

**Comment by mclarekin** [comment]
and alert me when max view distance has become > 100.

**Comment by mancoast** [comment]
Remove the overload!
There exist far too many controls in the main window.
To simplify, convert the 'docks' to 'windows'.
This enables use of 'task manager' to toggle windows, etc..

**Comment by buddhi1980** [comment]
Most of modern applications are single window (MS Word, Blender, Qt Creator, Chrome, Eclipse, Visual Studio, AudoCAD...). We can consider making docks convertable to windows like main image widget.

**Comment by mancoast** [comment]
Agreed, I would much prefer the ribbon.  Let us consider The dock --> window conversion as our baseline alternative. Given time we will converge on a better alternative. Can QT support a ribbon?

**Comment by buddhi1980** [comment]
Qt doesn't support it. Ribbon is not a cross-platform thing and even on Windows is very difficult to code.

**Comment by buddhi1980** [comment]
Closed because of lack of input and support from other developers.
