### ISSUE TITLE
refactoring folder structure

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#280]
a couple of folders could be rearranged, renamed or removed in order to clean up the project and make the intention more clear, here is a list open for discussion:

@mancoast
[x] 3rdparty -> *delete*
[x] mandelbulber2/mandelbulber2.sln -> mandelbulber2/msvc2014
[x] mandelbulber2/NuGet.config -> mandelbulber2/msvc2014

__regarding qmake:__
[x] check new pro files in qmake and specify as build path in scripts
[x] mandelbulber2/Debug -> *delete*
[x] mandelbulber2/Release -> *delete*
[x] mandelbulber2/qmake/debug.pro -> *create*
[x] mandelbulber2/qmake/common.pri -> *create*
    (contains common qmake-pro stuff for debug.pro and mandelbulber2.pro)

[x] mandelbulber2/data -> *delete*?
@buddhi1980 put into another place, maybe deploy/data?

__formula related:__
[x] mandelbulber2/qt_data/formula_and_transform_images -> mandelbulber2/formula/img
[x] mandelbulber2/qt_data/*.ui -> mandelbulber2/formula/ui/*.ui
[x] mandelbulber2/opencl/formula -> mandelbulber2/formula/opencl
[x] mandelbulber2/language/qt_data_* -> mandelbulber2/language/formula_*

__In a later step...__
[ ] mandelbulber2/qt -> mandelbulber2/ui # this will take some time

**Comment by mancoast** [comment]
@zebastian the 3rd party refs have been removed.
The windows build relies on the solution in the root of repo.
This requires rework and careful re-testing when we change.

**Comment by buddhi1980** [comment]
Agree with almost all. 
mandelbulber2/data/mandelbulber_1.21_defaults.fract is still needed to import old setting files. But we can move it to another place.

@mancoast , most of all mentioned changes need reworks. We can do them step by step, but all should be   done. Root folder should be as clean as it is possible. 

I'm not sure if have enough time to do all in v2.11. They will need a lot of testing (build and installation scrips in different enviroments). Now I would focus on finishing up changes and testing for new release. We need also to do more documentation in mandelbulber_doc. I would propose to do all these changes in v2.12

**Comment by mancoast** [comment]
It's a solid plan.  I am ready for experimentation of 2.12

**Comment by zebastian** [comment]
Yes, i know this breaks existing CIs and annoys package maintainers used to the old way, but in the long run we are probably better off.
I wont fumble in your msvc files, take your time and apply changes when you are confident about it.
I can do the formula related changes (no backward compatibility issues)
and the qmake changes (this means trouble :/ )

**Comment by zebastian** [comment]
@buddhi1980 you are right. We are pretty close to next Version, so bettet to move it to the next release

**Comment by mancoast** [comment]
Lets make these moves ASAP.
Build is sem-broken: now is the time

**Comment by buddhi1980** [comment]
Works very well. I have no issues to use new structure in Eclipse. What you think to add two more files: mandelbulber-opencl.pro and debug-opencl.pro?

**Comment by buddhi1980** [comment]
I have removed Debug and Release folders and added mandelbulber-opencl.pro and debug-opencl.pro in qmake directory.
Now we need to upgrade all scrips and tools

**Comment by zebastian** [comment]
@buddhi1980 thanks, good idea. 
Just refactored the other scripts, should be proper now.

**Comment by mancoast** [comment]
We ready to close this one?

**Comment by zebastian** [comment]
Yes, done for th time being. If we decide to move mandelbulber2/qt to mandelbulber2/ui we can open a new issue
