### ISSUE TITLE
Application Crash on Entry

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#281]
##### System information (version)

- mandelbulber2 => dev branch
- Operating System / Platform => WIN64
- Compiler => MSVC14

##### Detailed description

Application Crash on Entry

##### Steps to reproduce
Compile via Visual Studio.
Launch Debugger:
![image](https://cloud.githubusercontent.com/assets/7040493/24839413/c1755956-1d27-11e7-829c-52a96c708dc9.png)

**Comment by buddhi1980** [comment]
It happens only with MSVC bulds. On Linux works properly. I have the same with my MSVC14 compiler. 

What I found it happens only when QPixmap tries to load JPG files. With PNG works properly. Is there possible that there is something wrong with NuGet for libjpg?

**Comment by mancoast** [comment]
This only happens for debug builds.
Occurs for debug x64 and win32.
I have tired different nugets without success.
I recently finished a fresh compilation of all libs from source, except QT5.

This looks like a QT5 widgets bug, not libjpg.

**Comment by mancoast** [comment]
https://wiki.qt.io/Qt_5.9_Release
Test 5.9 release May/June 2017

**Comment by mancoast** [comment]
We need to test a rollback to 5.7 with a new release of bulbqt.
We update bulbqt with a roll back-forth to next version usage of qt5.7.
Given incompletion, we compile the LTS qt5.9rc:
https://blog.qt.io/blog/2017/05/11/introducing-long-term-support-qt-5-9/

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/4787945482e6ad0d3f788002a4f9103e4ce0f85b
