### ISSUE TITLE
add coordinate arrows

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#283]
in the render image widget there could be a checkbox to toggle the coordinate system visible in the image (x-y-z arrow with names)
taurus has requested this feature, see also issue on fractalforums: http://www.fractalforums.com/feature-requests/coordinate-arrows/

**Comment by mancoast** [comment]
![image](https://cloud.githubusercontent.com/assets/7040493/25628006/98f09dca-2f32-11e7-8ed4-18b0d7a30653.png)
