### ISSUE TITLE
Save Images From Benchmark into TIMESTAMPED Folder

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#285]
Please save all images as png into a new folder.
This new folder should reflect the initial launch time of the benchmark.
We must validate the imagery when considering time.

**Comment by mancoast** [comment]
@zebastian @buddhi1980 How Do we implement this?  Please provide directions.

**Comment by zebastian** [comment]
for what purpose do you want to have the tested rendered images?

**Comment by mancoast** [comment]
Essentially, I want to do a full factorial experiment.  I will not put my name on render time data, without prior inspection of the output.  Its for quality assurance.

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber_doc/issues/2

**Comment by mancoast** [comment]
Please help me generate the artifacts required for engineering whitepaper.  We can then co-author the manual [whitepaper].

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/1fa2442ea04f1719c51f1ffbf4f47b30d871d902
