### ISSUE TITLE
Add Intense and Precise Logging foreach example of Benchmark

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#286]
Start Time
Filename
End Time
Features render: **critical**
We must list the key features when parsing and example for benchmark.
Consider things such as reflections, SSAO, etc...
What makes the render slow?
What makes the render fast?

We need to document ALL of these things and include in manual.

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/d99dedeed353f56f7c1aab373ea9bd74d4ecc19c adds timing data to the benchmark loop

@zebastian @buddhi1980 we require a method to extract and summarize the features from settings file
any ideas?

**Comment by zebastian** [comment]
what do you mean by features? like "uses reflection" ?

**Comment by zebastian** [comment]
I should have read the whole issue first :)
We can put this into settings: 
```QStringList AnalyzeSettings() ```
which creates a report on the most crucial settings

**Comment by mancoast** [comment]
That is a sound solution. Then we can analyze the timing stats from all the examples to compare the features and how they correlate to different settings on CPU vs GPU.

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/42e6e5ecc8d1ae585eb12416d46e6db5e2e96924
raw printout of non-default settings, analyze can be done outisde of the bulb using text processor
