### ISSUE TITLE
saving tiff images with double extension

### ISSUE THREAD

**Issue by taurus66** [buddhi1980/mandelbulber2#288]
##### System information (version)

- mandelbulber2 => v2.10
- Operating System / Platform => win 10 64bit
- Compiler => windows binary

##### Detailed description

saving tiff images fails or has double extension
##### Steps to reproduce

behaviour when saving tiff images on my system has two possible results:

- saving tiff with pattern "name" (no extension written) saves nothing - at least I can't find a new file in desired path
- saving tiff with pattern "name.tiff" saves an image "name.tiff.tiff"

**Comment by buddhi1980** [comment]
Thanks for reporting this problem. I have just fixed it.
