### ISSUE TITLE
 add fract file to target on Animation / flight in Render Queue 

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#289]
see request by paigan on fractalforums: http://www.fractalforums.com/feature-requests/animation-file-save-in-render-queue/msg101347/#new
@buddhi1980 any reason not to add fract file?

**Comment by mancoast** [comment]
Does there exist the possibility to morph between .fract files placed in the Render Queue?

**Comment by zebastian** [comment]
@mancoast No, there is no morphing between queue elements. That would not be intended.
Render queue can also hold animations as items and there is no morphing between different animations. IMHO: Queue is already confusing and messy enough :)
