### ISSUE TITLE
wrong resolution specification doesn't generate any error message

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#29]
if there is used following parameter
--res 800
it doesn't generate any error message. It should inform that there is missing image height

**Comment by zebastian** [comment]
added error message: a78b5e5c2514e3a84189b9bdf223efe820e105d9, error message is generic and occurs if split(x) != 2.
but it gives info about exact format WIDTHxHEIGHT, which should be sufficient.

**Comment by buddhi1980** [comment]
Tested. Works OK
