### ISSUE TITLE
add news file to help menu

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#290]
for users upgrading their mandelbulber version it could be helpful to have the news handy.
Maybe put these under:
[Menu] > Help > News
could be a simple popup with a QLabel containing the full NEWS content

**Comment by buddhi1980** [comment]
Good idea

**Comment by mclarekin** [comment]
And maybe add release dates next to the version numbers in the news

**Comment by zebastian** [comment]
alright, will do...

**Comment by zebastian** [comment]
all done
