### ISSUE TITLE
There is huge memory leak when stereoscopic animation is rendered

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#291]
- mandelbulber2 => 2.11
- Operating System / Platform => Windows 10 (probably also Linux)
- Compiler => mingw

##### Detailed description

There is huge memory leak when stereoscopic animation is rendered. It could be generated by saving of separate left/right eye images

##### Steps to reproduce

To render stereoscopic animation and save frames in separate left/right images

It has to be fixed before 2.11 will be released

**Comment by zebastian** [comment]
Maybe its in files.cpp SaveImage:

you create
cImage *leftImage = new cImage(1, 1, true);
cImage *rightImage = new cImage(1, 1, true);

and probably those are not freed after use?
Can you check, i dont have a linux right now...

**Comment by buddhi1980** [comment]
Thanks for the tip. I will correct it

**Comment by buddhi1980** [comment]
Fixed and checked with valgrind (commit https://github.com/buddhi1980/mandelbulber2/commit/02ace6e89bce32b4abf9b2067688a6deea02b438)
