### ISSUE TITLE
Cast a shadow on invisable primitives

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#292]
Evaluate implementing option to cast shadow on invisible primitives.

Allowing for alpha channel transparent .png with both fractal and fractal shadow

**Comment by buddhi1980** [comment]
Probably this is what you requested
![image](https://user-images.githubusercontent.com/11696990/90334122-8458f900-dfcb-11ea-8563-f9e90a0a5057.png)

It is just tested and only hard coded. I will do permanent implementation.

**Comment by mclarekin** [comment]
only if you want to, it was for superimposing fractal with shadow on to a floor in a photo.

**Comment by buddhi1980** [comment]
Option added in commit https://github.com/buddhi1980/mandelbulber2/commit/57d9636efc5dbe1135c5e551cbd27cb6deebf7bc
(see primitives tab)
