### ISSUE TITLE
Queue crash

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#293]
Reported by paigan0 at Fractal Forums

> I had three files sitting in my queue folder from v 2.10, all animations. The icons screenshots will display, the window looks normal, and then the entire system will crash every time. Every single time. 
> 
> I had to copy and paste the fract file over to another place from the queue and then run it in the main program. The queue window is hosed forever for me. Mandelbulber will crash. I tried even deleting out the Q files, but Mandelbulber still thinks they're there, just won't show their icon. So I put them back. Icons back. Mandelbulber waits for about 15 seconds and then crashed. Every single time.

**Comment by zebastian** [comment]
hmm, its the DisplayCrossHair function on the rendered_image_widget in the queue, which tries to do a params->Get<double>(...) and this params seems to be a null pointer.

I am not sure how to best address this...

**Comment by buddhi1980** [comment]
Good catch! I will try to correct it.
