### ISSUE TITLE
Build fail on archlinux

### ISSUE THREAD

**Issue by acidhunter** [buddhi1980/mandelbulber2#294]
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat '/tmp/mandelbulber2-git/src/mandelbulber2/mandelbulber2/qt_data': No such file or directory
==> ERROR: A failure occurred in package().
Aborting...
Removing intermediate container 0b4a2bd1e28c
The command '/bin/sh -c aurget mandelbulber2-git' returned a non-zero code: 2##### System information (version)

- mandelbulber2 => from git master
- Operating System / Platform => arch linux

##### Detailed description

build fail on a clean arch setup, also inside a fresh build container

##### Steps to reproduce

yaourt -Sy mandelbulber-git

https://aur.archlinux.org/packages/mandelbulber2-git/?comment_id=594548

**Comment by acidhunter** [comment]
compiling the 2.11 release works

**Comment by acidhunter** [comment]
got it, the PKBUILD need a change at line 46

Old:
cp -ra "${srcdir}/${_pkgname}/${_pkgname}/qt_data" "$pkgdir/usr/share/${_pkgname}/qt_data"

has to be changed to:
cp -ra "${srcdir}/${_pkgname}/${_pkgname}/formula" "$pkgdir/usr/share/${_pkgname}/formula"

reported it to the aur maintainer

**Comment by buddhi1980** [comment]
Don't use source code from git master repository to release aur packages. This code can have partially implemented features (like file structure transition which is ongoing). Fresh source code from git you can you only for your own development and testing. For package deployment you should use only tagged versions from Releases (https://github.com/buddhi1980/mandelbulber2/releases)

By the way, can you write information in README file, which packages are needed to build mandelbulber on Arch? This would help users.

**Comment by acidhunter** [comment]
there are seperate aur packages, mandelbulber2 and mandelbulber2-git
the mandelbulber2 PKBUILD builds the tagged release, mandelbulber2-git will build from source

i reported this to the package mantainer, its not a mandelbulber issue

**Comment by mancoast** [comment]
Thanks @acidhunter 
Arch is solid OS.
