### ISSUE TITLE
Support USE_OPENCL pre-processor definitions for *optional* build

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#296]
Need to compile with OpenCL.

Also, Need to compile without OpenCL.

**Comment by buddhi1980** [comment]
it's already implemented. To compile the program with OpenCl code, you need to use qmake with following option:

```qmake mandelbulber.pro "CONFIG+=opencl"```

I'm not sure if your question is about using qmake or implementation of it in msvc

**Comment by mancoast** [comment]
No question, just stating some basic requirements. I noticed you were already doing these pre-processor definitions, so it's now documented in the project/milestone.
