### ISSUE TITLE
AppVeyor is too slow

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#298]
There are too many jobs defined in AppVeyor, which causes very long delay of tests.
I would keep only first 4 jobs (Release)

**Comment by mancoast** [comment]
I will take a look at disabling some of the builds.
We use appveyor for k1om,; the (3) k1om builds usually take ~3hrs.
Also, we use appveyor for CPP Core Guidelines Analysis; the (3) Analysis builds take ~3hrs.

We have a very advanced, autonomous system in operation.

Why do you want to remove these features?

**Comment by buddhi1980** [comment]
Because AppVeyor has 1 day backlog all the time. It doesn't help us to see potential problems, when we have about 10 commits per day. 
Another issue is configuration of email notifications. I cannot find way to get notification only when status is changes (from build OK to failing or opposite). 
When information is not up-to-date and like a spam you just start to not read these emails.

**Comment by buddhi1980** [comment]
CPP Core Guidelines Analysis we can keep for only one architecture (x64). Should be enough.

**Comment by mancoast** [comment]
Sounds good, we can proceed with 1 build for k1om, and 1 build for CPP Core Guidelines Analysis.
This should dramatically reduce the build backlog for days with many commits to the git repo.

**Comment by mancoast** [comment]
builds disabled
https://github.com/buddhi1980/mandelbulber2

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/ed6b2523ee0b0fcaceab9c7fb9b3c0d77ae3627c
