### ISSUE TITLE
Vectorization: SIMD Processing Within a Work-group

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#304]
https://software.intel.com/en-us/node/540511

REF:
https://software.intel.com/en-us/intel-opencl

**Comment by buddhi1980** [comment]
Vectorization is done by OpenCL compiler. We don't need to write explicit vector code. If there is used proper data alignement, the code will be vectored. In mentioned document there is written:

> The vectorization module enables you to benefit from vector units without writing explicit vector code. Also you do not need the for loops within kernels to benefit from vectorization. For better results, process a single data element in the kernel, and let the vectorization module take care of the rest. To get more performance gains from vectorization, make you OpenCL code as simple as possible.

**Comment by zebastian** [comment]
@mancoast please close or comment

**Comment by mancoast** [comment]
I will test and recreate issue if needed. Plz feel free to close.

**Comment by zebastian** [comment]
Aleight
