### ISSUE TITLE
Cross-compile Travis

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#308]
Please implement the cross-build in travis CI.

**Comment by buddhi1980** [comment]
It would take too long to compile. Travis will need to compile qt libraries and all another libraries like gsl, png, vorbis, libsnd.... On my fast PC it takes about haf hour.

**Comment by mancoast** [comment]
Does there exist precompiled solutions for the libraries on which we depend?
Ideally we move all compilation operations to the cloud for further automation and integration.

**Comment by buddhi1980** [comment]
Unfortunately there is no official mingw64 build for Qt libraries. This is the biggest part of compilation.

**Comment by mancoast** [comment]
Thanks for the info.
Let's table this issue for later.
I will close for now, and investigate when time permits.
