### ISSUE TITLE
OPENCL: Support multi-GPU systems

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#309]
I wish to render using my Intel CPU (opencl enabled) and (2) geforce 760 that are not configured in SLI.
Please enable support for complete usage of all available opencl devices from a single mandelbulber instance.

**Comment by mancoast** [comment]
https://software.intel.com/sites/landingpage/opencl/optimization-guide/Using_Multiple_OpenCL_Devices.htm

shared_context = clCreateContextFromType(prop, CL_DEVICE_TYPE_ALL, …);
Shared context does not imply any “shared queue”.
create a separate queue per device

**Comment by mancoast** [comment]
@buddhi1980 Please support multiple opencl devices, we need multiple queues.

There is a design architecture choice here:

1.) devices represent independent streams of computation: no shared data.
ex. each opencl device renders a different frame.

2.) devices represent dependent streams: shared data.
ex. use every opencl device for (1) frame with unlimited resolution.

Thanks,
coast

**Comment by buddhi1980** [comment]
Second option is a good option because it will work for still images and animations.
@mancoast , you are only one of us who has hardware capable to test multi-GPU systems. Would be good if you will try to implement it. I will assist you and help as much as I can.
Unfortunately without hardware I was not able to write code for it. Making code without ability to test it is hery hard.

**Comment by mancoast** [comment]
I will make it happen. Yesterday I was able to render a 20k 3gb Mandelbulb png in 400 seconds with OpenCL.

**Comment by zebastian** [comment]
rescheduled for 2.13, since this is a really big topic...

**Comment by mancoast** [comment]
Good plan, I am excited to get back at it here soon.

**Comment by mancoast** [comment]
![image](https://user-images.githubusercontent.com/7040493/47612089-ca854700-da49-11e8-8dd4-0e521ae9533e.png)

**Comment by mancoast** [comment]
@buddhi1980 thanks!

**Comment by phroiland** [comment]
Do you have a branch I can test this on?

I can alternate just fine between my two RX Vega 64s.

Would love to run them simultaneously.

Have additional AMD cards as well.

**Comment by mclarekin** [comment]
Hi Johann

This is maybe what you want

https://www.youtube.com/watch?v=kiVJcglwVHA

  start watching at 3:40
