### ISSUE TITLE
render queue processing only first element

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#31]
right now render queue stops after successfully rendering first element from list.

**Comment by zebastian** [comment]
fixed with this commit 2da62f1c234910aa32a4e4f4a99d4888225b3bdd

**Comment by buddhi1980** [comment]
Now it deletes item from queue even if it's not finished. I'm correcting this now.

**Comment by buddhi1980** [comment]
Now it need to be tested, but first I have to fix issue #36

**Comment by buddhi1980** [comment]
Tested.
