### ISSUE TITLE
rewrite Iteration functions with z and w to z4d

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#310]
All 4d formulas should use consistently z4D var, instead of z and w

**Comment by mancoast** [comment]
Does the usage of z4D from z and w affect the final rendered imagery?

**Comment by buddhi1980** [comment]
What we can try is to have the same interface for all fractal formulas (3D and 4D and all another specific types). We can put all variables like 'i' or 'c' to sExtendedAux. Then will be easier to simplify iteration loop in CPU and GPU code. Maybe will be possible to use function pointers.
I need to check how will work 3D formulas with 4D variables.

**Comment by mancoast** [comment]
The standardization is an improvement to the code quality and readability.  I am all for the change, however will this affect the final render or will this rework adjust how the identical data is oriented?

**Comment by zebastian** [comment]
These changes may not affect the final render and the render time, its only readability.
The compiler should take it from there, but we need to test this in the wild (especially if we put 3d values in 4d containers)

**Comment by buddhi1980** [comment]
I have just did quick test with Mandelulb and Mandelbox formulas. Everything works very well. 4D computation doesn't slow down rendering. I will do conversion of all formulas.

**Comment by buddhi1980** [comment]
It will take several hours, because many changes has to be done manually (inside the formula code), but it is worth it.

**Comment by buddhi1980** [comment]
@zebastian , can you stop changing fractal_cormulas.cpp for several hours? I will have troubles to merge changes. I will let you know when I finish.

**Comment by zebastian** [comment]
OK, i wait for the changes. 
Let me know, if you need any help

**Comment by buddhi1980** [comment]
1000 lines changes. 1st phase done. Now all formulas are calculated using 4D algebra.
Now my brain is already :fire:, so if you have any changes to commit, you can do this now.
I will continue tomorrow (but first I will let you know). Or if you want, you can standardize interfaces of formula functions. But you have to be careful with 'c' and 'aux.c' because one is passed by value and second by reference. It makes big difference in calculation result.

**Comment by buddhi1980** [comment]
All changes done. Now all formulas use 4D algebra and functions have the same parameter set. @zebastian, now you can continue your work

**Comment by buddhi1980** [comment]
Now would be interesting to add function pointers to fractal formulas into sFractalDescription (fractal_list.cpp) and call functions by function pointer without switch() statement. What you think?

**Comment by buddhi1980** [comment]
The pointer could be defined as 	```void (*fractalFormulaFcn)(CVector4 &, const sFractal *, sExtendedAux &);```

**Comment by buddhi1980** [comment]
I will do it. First basic test work. It will reduce 800 lines of code!

**Comment by buddhi1980** [comment]
Done. Now there is 700 lines of code less. I think it's good starting point to implement hybrid loop in OpenCl kernel. Now should be much easier.

**Comment by mancoast** [comment]
nicely implementation! these function pointers aid F(x) to marching cubes/

**Comment by mclarekin** [comment]
I completed the updating of 3D parameters that are added to a vec4. As it
is not an inline function.


With the 3D parameters (scale/ & constantMuliplier), that are multiplied by
a vec4,  there is already an inline function, so I am wondering if they
should remain as vec3 in fractal.h & cpp?
At present only some of these have been updated

**Comment by mancoast** [comment]
Please elaborate on file/line# of concern.

**Comment by mclarekin** [comment]
fractal.cpp 371

new code format           transformCommon.constantMultiplierB111 =
CVector4(container->Get<CVector3>("transf_constant_multiplierB_111"), 1.0);


old code format    transformCommon.constantMultiplierC111 =
container->Get<CVector3>("transf_constant_multiplierC_111");

a) I was wondering if updating these parameters into a CVector4 container
is necessary as we have :


algebra.hpp 384
    inline CVector4 &operator*=(const CVector3 &v)
    {
        x *= v.x;
        y *= v.y;
        z *= v.z;
        w *= 1.0;
        return *this;
    }


b) also I was wondering if  an inline vec4 + vec3 was worth having?

    inline CVector4 &operator+=(const CVector3 &v)
    {
        x += v.x;
        y += v.y;
        z += v.z;
        w += 0.0;
        return *this;
    }


But I do not know enough about programming to be confident.

**Comment by zebastian** [comment]
Is this still a thing?
@mclarekin Do you still need any new methods in algebra about CVector* classes.
Do you still need a 
 inline CVector4 &operator+=(const CVector3 &v)
?
Your example seems alright, but if you are uneasy with changes there let me know what you need.

**Comment by mclarekin** [comment]
I will have to remember what I was taking about. Whether we needed them or
that I just noticed that those combinations were missing. I will check.

BUT, on a similar subject. I did not update these to CVector4 because I was
unsure if there would be any problem with them being used in a 3D matrix.
Is is safe for these to be updated to CVector4???

    CVector3 rotation; // vec3s
    CVector3 rotation2;
    CVector3 rotation44a; //.........................
    CVector3 rotation44b; //..........................

**Comment by mclarekin** [comment]
a) I was wondering if updating these parameters into a CVector4 container
is necessary as we have :
algebra.hpp 384
    inline CVector4 &operator*=(const CVector3 &v)
    {
        x *= v.x;
        y *= v.y;
        z *= v.z;
        w *= 1.0;
        return *this;
    }

I can not remember what the above was about. So can ignore,

b) also I was wondering if  an inline vec4 + vec3 was worth having?

    inline CVector4 &operator+=(const CVector3 &v)
    {
        x += v.x;
        y += v.y;
        z += v.z;
        w += 0.0;
        return *this;
    }

The above has not been needed.

Is this still a thing?

No longer a thing.
