### ISSUE TITLE
broken GeneralizedFoldBoxIteration

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#315]
in non-opencl the formula produces empty space
in opencl code this formula crashes (probably related)

@buddhi1980 this was already happening before my latest commit, probably introduced with the unifications for z4d, can you take a look?

**Comment by buddhi1980** [comment]
I'm going to look what is wrong

**Comment by buddhi1980** [comment]
Fixed. There was used ```aux.i``` instead of ```i```
OpenCl version of GenFoldBox now also works.

**Comment by zebastian** [comment]
thanks!
