### ISSUE TITLE
Windows OpenCL Non-functional

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#316]
Greetings,

I am still seeing a blank render forall variations of input.
Changes to the opencl library nuget may be required.

Thanks,
coast

**Comment by buddhi1980** [comment]
Without this change in cl_platform.h it cannot work. MSVC compiler is DIFFERENT
Here is interesting discussion about this problem: https://social.msdn.microsoft.com/Forums/vstudio/en-US/8fac034b-6ba4-478d-9130-8f6a56de368f/why-does-msvc-inhibit-the-use-of-aligned-types-as-function-parameters?forum=vclanguage

**Comment by mancoast** [comment]
OK, We will proceed with modified headers for Intel OpenCL SDK 2016.3.
The files from the opencl-nug are pulled from Intel OpenCL SDK.
I will open a support issue with Intel to get the vanilla OpenCL SDK 2017 functional for our use case.
Thanks!

**Comment by mancoast** [comment]
windows opencl build confirmed functional
https://github.com/buddhi1980/mandelbulber2/commit/1fad449f3eec0290ed5e683d39a7c56ee499e3f4

**Comment by mancoast** [comment]
Now we see compilation issues with 32bit opencl build.
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.586-master/job/ewr3q8p1ujvyodeq
```
include\CL/cl.hpp(6005): error C2719: 'fillColor': formal parameter with requested alignment of 16 won't be aligned
```

**Comment by buddhi1980** [comment]
Forget about win32 builds. Win32 is legacy architecture, which we can abandon.

**Comment by mancoast** [comment]
I agree, your analysis.
Future state will omit opencl features *only* for windows 32bit.
Future state will support opencl features for Windows 64bit.

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/5839d6a6b36e43fd065d7b597fbe32152c7716c7
