### ISSUE TITLE
Record Flight Path requires OpenCL Support

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#317]
In the future state, the "Record Flight Path" experiences massive acceleration from OpenCL.
In the current state, the "Record Flight Path" function only renders (1) frame then stops.

**Comment by mancoast** [comment]
@zebastian @buddhi1980 Does there exist the possibility to compile the kernel **once** per flight?
To record a flight path we lower the resolution and maximize fps.

**Comment by buddhi1980** [comment]
Will be possible.  Now opencl rendering is implemented only for main rendering. Animation will be implemented soon.

**Comment by mancoast** [comment]
Is it possible to distribute (1) frame foreach OpenCL device to increase fps regarding multi-GPU support:?
Is it more efficient to use shared data across the different OpenCL devices?

What is easiest to implement and maintain?

https://github.com/buddhi1980/mandelbulber2/issues/309

**Comment by buddhi1980** [comment]
done in commit https://github.com/buddhi1980/mandelbulber2/commit/a69b60301d0b5e6278fb792e04753b5fd6b24f57

**Comment by mancoast** [comment]
Please enable (1) kernel compilation for the entire flight.
The kernel compilation between each frame is disruptive.

**Comment by mancoast** [comment]
resolved
https://github.com/buddhi1980/mandelbulber2/commit/bec3acbc9d8061623f6c02d0e0dbde7b34f2efeb

**Comment by buddhi1980** [comment]
Today evening I'm going to fix recompilation problem. It  will build kernel code only when souce  code is changed.

**Comment by mancoast** [comment]
Sounds like a plan, thanks!

**Comment by buddhi1980** [comment]
Problem with re-compilation solved in commit https://github.com/buddhi1980/mandelbulber2/commit/8dd34fd5a2e3b3f0d943424751a44578aac7e7e7

**Comment by mancoast** [comment]
works well, thanks!
