### ISSUE TITLE
flight / keyframe on cli request for delete previous

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#32]
flight / keyframe on cli request for delete previous not displaying correctly

**Comment by buddhi1980** [comment]
How to reproduce this bug?

**Comment by zebastian** [comment]
the message "animation already rendered" with question if image folder should be truncated looked messed up while ansi output of cli was in development.
however this problem solved itself and now it looks good.
So this issue is obsolete.
