### ISSUE TITLE
opencl: enable equirectangular

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#325]
These equirectangular frames work well will giga-pixels.
Please enable equirectangular for opencl.

**Comment by buddhi1980** [comment]
There is still 90% missing features. So it doesn't make sense to create issues like this one.

**Comment by mancoast** [comment]
Low hanging fruit with high value.

**Comment by mancoast** [comment]
bump

**Comment by buddhi1980** [comment]
Done
