### ISSUE TITLE
increase max value for GUI sliders for image resolution

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#326]
The current limit of ~65k is too low.
Please enable ~200k per slider.

**Comment by buddhi1980** [comment]
It has to be increased carefully. JPEG supports a maximum image size of 65,535×65,535 pixels!
Better would be to implement rendering of images in tiles.

**Comment by mancoast** [comment]
If PNG doesn't save well, and JPG has hard coded limits, Does there exist the possibility for 200k TIFF?

**Comment by mancoast** [comment]
@buddhi1980 @zebastian @mclarekin 
do we want to pursue this issue, or close.
There exists other tasks with higher value.
I vote we close and open new issue if recurs.
any thoughts?
