### ISSUE TITLE
Analyze failure modes of invalid input

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#329]
Required for https://github.com/buddhi1980/mandelbulber2/issues/278

**Comment by zebastian** [comment]
hey @mancoast, can you explain this, as i am not sure exactly what this means?
BTW: i love the mutagen idea!

**Comment by mancoast** [comment]
Greetings @zebastian 

In essence, we must view the whole system here and perform some analysis.
What type of input results in amazing renders?
Do some input combinations require GPU to render?
What makes the system fail to render?
What are the different types of failures that can occur? (system crash, solid color, blank screen. etc)
These are what I refer to as failure modes.
If we can identify possible modes of failure, then we can exclude them from the randomize function.
The objective is to enable "Randomize Design" button : https://github.com/buddhi1980/mandelbulber2/issues/278

Thanks,
coast
