### ISSUE TITLE
Operational OpenCL Benchmark

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#330]
critical for next alpha/beta release.
we require stats

**Comment by buddhi1980** [comment]
First it has to work in CLI mode. Step by step...

**Comment by mancoast** [comment]
Day by day,The openCL features grow more complete.

**Comment by mancoast** [comment]
hint plz

**Comment by mancoast** [comment]
ref: https://github.com/buddhi1980/mandelbulber2/issues/339 for cli requirement
ref: https://github.com/buddhi1980/mandelbulber2/issues/285 for Save Images From Benchmark

**Comment by mancoast** [comment]
@zebastian @buddhi1980 please enable CLI with opencl.  enable me to automate verification and validation.

**Comment by zebastian** [comment]
cli with mandelbulber already works basically.
Needs to be added to the test class...
