### ISSUE TITLE
request - User defined image size preset

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#331]
from Kyzai at FF
http://www.fractalforums.com/feature-requests/user-editable-image-size-presets/msg102533/#new

would it be possible to make the image size presets user editable in some way.

I have a 4k monitor, for which I like rendering desktop backgrounds, so just adding 3840 x 2160 as an option would be perfectly good too.

**Comment by mancoast** [comment]
Consider addition of two or three X,Y settings stored locally to easily implement this feature.
I agree with the added value.  It is easy to implement, and saves time for end user.

**Comment by mclarekin** [comment]
closed with commit https://github.com/buddhi1980/mandelbulber2/commit/98dfc2b626c84f83afafb24b9ef46070cb2f80cb
