### ISSUE TITLE
request - calc midpoint between two points

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#332]
from Kyzia at FF
http://www.fractalforums.com/feature-requests/measurement-request/msg102532/#new

In the Measurement Tab, I'd like the ability to select two points.  Once selected, in addition to giving their coordinates, the coordinates of the mid-point between the two would be shown. 
Also possibly the mid-point between each and the camera, if that wouldn't be overloading it.

The reason for requesting this : I'm starting to experiment with adding primitives to my compositions.  For example, starting with the Menger Prism and wanting to drop a sphere in the centre of one of the voids. 
To do the less than perfect example below, I had to start with hovering over two opposite corner points in turn, note the coordinates, and then stick them into Excel to calculate the mid-points I needed.

Thanks for your consideration, and for such a fantastic program.

**Comment by mancoast** [comment]
This request serves additional statistics and mathematics.
I vote to implement due to increased precision.
The animation engine benefits from increased precision.

**Comment by zebastian** [comment]
to be discussed...

**Comment by mclarekin** [comment]
helpful  for initial placement of a primitive between two surfaces.
My current work around is to place a temporary primitive surface , spanning
the empty area, grab a coordinate, then delete temporary primitive.
Once I had a spreadsheet set up to do the maths.

a) Simple set up would be click on two points and the program will give mid
point coordinates

b) More complex , click on two points and a line connecting them appears.
Click on midpoint symbol (midway on line) or click anywhere else along the
line for coordinates

c) same as b) but place a (maybe vertical ) plane between the points

**Comment by buddhi1980** [comment]
Added in commit https://github.com/buddhi1980/mandelbulber2/commit/c4133dc3cc735519e2b4884b972014f71a4765ed
