### ISSUE TITLE
request - option to align  plane or water  to camera view

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#333]
from Kyzia at FF
http://www.fractalforums.com/feature-requests/primitives-align-plane-water-to-view/msg102578/#new
Enable the ability to align the orientation of the plane or water primitives to the current camera view.  So, whatever the camera view is, the plane or water would appear horizontal.  When enabled, there would be a 'pitch' slider allowing to set the 'slope' of the plane towards or away from the camera

**Comment by mclarekin** [comment]
It is about the difficulty in aligning the primitive with the camera
horizontal axis.

example. Note this can be done by matching  primitives x and y rotation
with camera pitch and roll, with reversed pos neg.

then if the camera has a yaw value it becomes more difficult.

The scenario is when  you zoom into a location with the camera rotated,
and  decide to add water, it is complicated to get the water horizontal.

The users wants an option that automatically updates the primitives
rotations to align with camera horiz plane.

I avoid all this by rotating the fractal rather than the camera,  using the
rotations on the global parameters tab.




# Mandelbulber settings file
# version 2.11
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 0 -6.443533699500342 -2.135117734624872;
camera_rotation 0 23 12;
camera_top 0.2079116908177588 -0.3821927158637954 0.9003896138683281;
check_for_bailout_2 false;
file_background /home/carbuncle/mandelbulber/my textures/background.jpg;
file_envmap /home/carbuncle/mandelbulber/my textures/envmap.jpg;
file_lightmap /home/carbuncle/mandelbulber/my textures/lightmap.jpg;
flight_last_to_render 0;
formula_2 1071;
formula_3 1007;
fov 0.6;
fractal_enable_2 false;
fractal_enable_3 false;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_is_defined true;
mat1_surface_color aa00 0000 0000;
mat1_use_color_texture true;
mat1_use_colors_from_palette false;
primitive_rectangle_1_enabled true;
primitive_rectangle_1_height 12;
primitive_rectangle_1_rotation -23 -12 0;
primitive_rectangle_1_width 12;
raytraced_reflections true;
target 0 2.74666741078629e-07 0.6000001648000446;
view_distance_max 119.1498929717184;
[fractal_1]

**Comment by buddhi1980** [comment]
Added in commit https://github.com/buddhi1980/mandelbulber2/commit/427484a1d549b498a31a534b4da52f4f4dc2f4b5
