### ISSUE TITLE
add 	cl_int formula to sFractalCl

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#335]
@zebastian, there is needed to add in fractal_cl.h folowing lines:

typedef struct
{
	**cl_int formula;**
...
} sFractalCl;

and

inline sFractalCl clCopySFractalCl(sFractal &source)
{
	sFractalCl target;
	**target.formula = cl_int(source.formula);**
...
}

It has to be added to php script

**Comment by mancoast** [comment]
this is over my head bc of php noobiness.
@zebastian what are your thoughts?

**Comment by zebastian** [comment]
No Problem, i will do this tomorrow evening

**Comment by buddhi1980** [comment]
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/d7e99c1dee21b845cbc3f577a80143d260b45929
