### ISSUE TITLE
recheck all example files

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#337]
Since a couple of formulas have changed since the examples were introduced now a couple of them are broken.

We need to recheck all example settings and fix broken...

**Comment by mclarekin** [comment]
yep, it needs to be done, but maybe wait until all formulas are working in
openCL, then it would be a quicker exercise. ???

The aux->actualScale   seems to be now working correctly in openCL, but
there are other formula problems that need to be fixed in openCL

**Comment by zebastian** [comment]
@mclarekin OK we can wait till formulas are fixed.
Can you tell me, which make problems? I can look into this...

**Comment by mancoast** [comment]
If we update benchmark to save images we can automate this and generate good benchmark data. Thoughts?

**Comment by mclarekin** [comment]
maybe they are all fixed,!!!  I cannot find any now.

On Sun, Jul 23, 2017 at 12:03 AM, Sebastian Jennen <notifications@github.com

**Comment by mclarekin** [comment]
from all my broken settings files that i have tested so far, this is the
only one that still produces a different image in openCL . There may be a
problem with the transform??.



# Mandelbulber settings file
# version 2.11
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
aux_light_intensity_1 0.251189;
aux_light_position_1 0.7235588625406182 0.3540244095376709
0.2252483575354898;
aux_light_visibility 11.2202;
aux_light_visibility_size 0.0331131;
background_color_3 5500 aa00 ff00;
bailout 10;
camera 0 -2 0;
camera_distance_to_target 2;
camera_rotation 0 0 0;
camera_top 0 0 1;
DE_factor 0.6;
flight_last_to_render 0;
fog_color_1 1500 ff00 8200;
fog_color_2 3900 4600 0d00;
fog_color_3 7700 ab00 ff00;
formula_1 122;
formula_2 1062;
formula_stop_iteration_2 2;
gamma 0.6899999999999999;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
limit_max 1 2 1;
limit_min -1 -1 -1;
limits_enabled true;
main_light_alpha 42.88;
mat1_coloring_palette_offset 1.29;
mat1_coloring_palette_size 32;
mat1_coloring_random_seed 685826;
mat1_coloring_speed 0.09130000000000001;
mat1_fractal_coloring_algorithm 2;
mat1_fresnel_reflectance true;
mat1_is_defined true;
mat1_reflectance 1;
mat1_specular_width 0.149;
mat1_surface_color_palette ffa640 ff272a a19db2 7f005a dc7693 bcc744 2f8c55
4c7b47 a69647 314e3f b8f382 e8bbcc 00cf13 3a0075 0b3427 4068b6 1d332a
b9324f de53f9 ffabef 4a00c3 87ad44 7f8a81 2743f1 2a860a 65ffff 028056
d811b8 5a7249 9c94cd 52f791 c7066d;
mat1_transparency_index_of_refraction 7.96;
N 45;
reflections_max 2;
view_distance_max 17.71215464798802;
volumetric_fog_colour_1_distance 0.09458884533635686;
volumetric_fog_colour_2_distance 0.1891776906727137;
volumetric_fog_distance_factor 0.1891776906727137;
[fractal_1]
analyticDE_tweak_005 0.15;
transf_addition_constant_0777 1 0.056 1;
transf_folding_value 1.9;
transf_minimum_radius_05 1.9;
transf_offset 0.0625;
[fractal_2]
transf_constant_multiplier_000 -0.047458 0 3;
transf_function_enabledAx false;
transf_function_enabledAy false;
transf_function_enabledx false;
transf_function_enabledy false;
transf_scale_0 -0.1;

**Comment by mclarekin** [comment]
i have investigated this before but I have forgotten,   i think  exp2   to
native_exp2 was not the problem, it may be a copysign versus sign thing.
Somewhere I committed a fix for this, before i learnt about the php script
overwriting thing.

**Comment by mclarekin** [comment]
thanks Sebastian, i think all the php problems, that we have discovered,
are now fixed.

**Comment by mclarekin** [comment]
The difference, between c++ and openCL renders of this setting file, is
possibly due to the difference between single and double precision


# Mandelbulber settings file
# version 2.11
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 5.215394199108069 -5.232049260538845 1.727236752137692;
camera_distance_to_target 0.0003689234727079349;
camera_rotation -7.488909675798588 -27.91665904453493 -10.9406652186759;
camera_top -0.1282617376962634 0.4804925629141368 0.8675689157798007;
DE_factor 0.7;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 119;
formula_2 77;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_coloring_palette_offset 8.210000000000001;
mat1_is_defined true;
raytraced_reflections true;
target 5.215436686999753 -5.231726049534339 1.727064027054563;
view_distance_max 66.90097216566116;
[fractal_1]
IFS_rotation_enabled true;
mandelbox_scale 1;
mandelbox_vary_scale_vary -0.3;
[fractal_2]
Cpara_para0 31;
IFS_rotation_enabled true;
mandelbox_scale -1.5;
transf_function_enabledAy_false true;
transf_minimum_radius_05 0;
transf_offset_0 -1;
transf_rotation 4 8 -4;
transf_scale -1.5;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by buddhi1980** [comment]
First we should check all formulas with CPU. Some of them now works different than in 2.11. Then we can continue checking OpenCL formulas.

**Comment by zebastian** [comment]
BTW: the "test render examples to folder" - cli option is half ready. Will finish this later today,...

**Comment by mclarekin** [comment]
"test render examples to folder"

I will be very interested to find out which are different.

AboxMod2,  will be completely different in example and the formula icon
png.  Some other minor corrections may make some differences, depending on
what parameters were used in the examples.

 There are only two things outstanding things I have yet to complete in c++
:

a) I am still testing the old slot#1 based scale vary. If variable scale is
used on any box/surf type examples there maybe be some differences

b)  Mandelbulb-JuliaBulb formula I am about to complete.

**Comment by mancoast** [comment]
ref https://github.com/buddhi1980/mandelbulber2/issues/312 Autonomous SBS report of CPU - GPU

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/issues/339 Please enable CLI with opencl.
I will then recheck/upload all example files

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/28b6df0527591e7d89e0c81dc8ed1204f46bf633

benchmark now tests >300 examples.
