### ISSUE TITLE
Enable CLI features for headless opencl

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#339]

**Comment by mancoast** [comment]
any idea on schedule for this issue?
this feature is blocking other TODO's.
Please prioritize.

**Comment by zebastian** [comment]
basically done, still needs opencl functionality properly exposed through cli options and documentation.
Why is this feature blocking?

**Comment by mancoast** [comment]
We should remove the barrier so I can allocate some heavy resources towards testing.
The CLI enables automation and scripting of tests procedure/report generation for V&V.

**Comment by zebastian** [comment]
half way through, still missing are the TODO flags in the cli output of --help-opencl

**Comment by mancoast** [comment]
@zebastian you are crushing it; thanks!

**Comment by mancoast** [comment]
I am unable to enable/disable from cmd.
@zebastian is this ready for testing?

**Comment by zebastian** [comment]
yes it is, run on the cli with argument --help-opencl.
From there on it should be self explaining, let me know if something is unclear.
