### ISSUE TITLE
In .fractlist when mode is not specified it shoud use STILL by default

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#34]
It would be good if processing of .fractlist file (e.g. loaded from command line) use STILL mode as default, when it's not specified in a line with filename. Now when mode is not specified it generates error ""wrong format in line:..."
I will be good to change it, because will be possible to generate fractlist by just using 'ls' command

**Comment by zebastian** [comment]
regex was expecting whitespace, now whitespace is optional and pure filename is sufficient.
see also fix in commit: 89701efad73de6e7673c9df2c7cc9187a04646de

**Comment by zebastian** [comment]
just tested it with: 
cd /path/to/settingsfolder
find "$PWD" > queue.fractlist
and then 
mandelbulber /path/to/settingsfolder/queue.fractlist
works well now
