### ISSUE TITLE
opencl misc meta update

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#345]
a couple of files need to be changed for the first release of opencl:
- READMEs should contain section about opencl and required dependency
- make-package.sh needs to be adopted
- probably more...

**Comment by zebastian** [comment]
Still missing:
- OpenCL part
- documentation part (new pdf)
- rechecking of all packages
- appimage resource
- packages for other distros
- installation maybe do with make install (needs to be added to pro file)
- recombine mandelbulber.pro and mandelbulber-opencl.pro

**Comment by mancoast** [comment]
I would like to assist with documenting side-by-side renders of opencl vs cpu.
ideally, the images are the same

**Comment by zebastian** [comment]
done more or less, should open a new issue, if something needs to be done here...
