### ISSUE TITLE
fix openexr for travis

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#350]
Any thoughts?

**Comment by zebastian** [comment]
I wish i got a got a dollar for every minute i spent fumbling with compiling with openexr. 

in the travis ci build we install openexr with: 
brew openexr ilmbase
Then in the qmake/common.pri we append the include of the library with pkgconfig.
packagesExist(IlmBase){
        PKGCONFIG += IlmBase
        LIBS += -lIlmImf -lHalf
        DEFINES += USE_EXR
        message("Use IlmBase library for EXR files")
}

For Linux this works fine.  I dont know whats wrong here, any help appreciated. 

BTW: The next couple of days i will setup a virtual osx to test this and also refactor the osx README.

**Comment by mancoast** [comment]
my openexr pull request has been waiting almost 1 year, lol
https://github.com/openexr/openexr/pull/218

the images truly look amazing with the RGB information && information in the z-axis.
It would be a nice feature to support MultiResolution.
REF: https://github.com/openexr/openexr-images/blob/master/MultiResolution/README

**Comment by buddhi1980** [comment]
I also wish to have openexr working with mingw. Compilation process is quite strange, because it generates executable files which creates some parts of the code. This part of compilation fails.
@mancoast , if you really want to play with exr images, just run mandelbulber under Linux. I don't suppose to have quick solution for another platforms.

**Comment by mancoast** [comment]
OpenEXR operates correctly with MSVC build.
However, I am unfamiliar with how to use it.
Can the fractals benefit from EXR file format for stills, how about for vids?
Whats the big advantage?

**Comment by buddhi1980** [comment]
Just save image in EXR format and use it in programs like Blender where you can use different layers of image for texture properties. Thanks to half-float format the z-buffer is very accurate and images fit well to use as HDR textures. In general it's for advanced 3D graphics designers.

**Comment by mancoast** [comment]
tabled for later
