### ISSUE TITLE
2.12_alpha6_win64: Error during compilation of OpenCL program.

### ISSUE THREAD

**Issue by rconcept** [buddhi1980/mandelbulber2#351]
##### System information (version)

- mandelbulber2 => mandelbulber2-win64-2.12-alpha6
- Operating System / Platform => Windows 64 Bit 16GB RAM 
- GFX => NVIDIA GeForce GTX 960 / 2GB
- DirectX => 12.0

![mandelbulber_v2 12_a6_cl_compile_error](https://user-images.githubusercontent.com/15924913/29659737-76a2b7f8-88bf-11e7-86b8-3ba52fabd5ba.png)
![mandelbulber_v2 12_a6_cl_prefs](https://user-images.githubusercontent.com/15924913/29659747-7eab0518-88bf-11e7-99de-75e60f1f2b5b.png)

[mandelbulber_log.txt](https://github.com/buddhi1980/mandelbulber2/files/1248370/mandelbulber_log.txt)

##### Detailed description
Hi,
I can not CL render any fractal (tested a least 10 from the official examples). 
Every time I get the following error message:
"Error during compilation of OpenCL program."
See the attached screen captures and "mandelbulber_log.txt"

When I do the same with the last pre-release (alpha5), there is no error message.

##### Steps to reproduce
1. Open mandelbulber2-win64-2.12-alpha6
Before starting MandelBulber2, I deleted the config. dir: %HOMEDRIVE%%HOMEPATH%\mandelbulber

2. I left all the default setting, just enabled OpenCL rendering:
menu File->Program Preferences->OpenCL and check the checkbox
"OpenCL enable"

3. Click render
The following error pops up twice: "Error during compilation of OpenCL program":
Error in processing command line: Don't understand command line argument "v2\mandelbulber2-win64-2.12-alpha6\opencl\"!

**Comment by buddhi1980** [comment]
Thanks for the report.

This problem with spaces in file path is related to nvidia driver. It works properly with Intel and AMD. Fortunately there is workaround for it. I will try to implement it as soon as possible.

https://forums.khronos.org/showthread.php/8478-Putting-a-space-in-path-supplied-to-clBuildProgram()

Quick solution for you will bo to move the program to a folder where path doesn't contain any space like: D:\Graphics\Mandelbulber

**Comment by rconcept** [comment]
Thank you for your quick reply!
I removed the space (don't know how it got there, usually I never put spaces in my paths...),
and this resolved the problem.

**Comment by buddhi1980** [comment]
Issue is still not solved. Removing of spaces from path is just a workaround.

**Comment by buddhi1980** [comment]
It's much more difficult as I thought. I cannot use syntax like this:
```#include "INCLUDE_PATH_CL_DATA/defines_cl.h"```
This will not work as a macro.

Actually only way is to make auto-generated cl_kernel_include_headers.h at runtime. 
We can make file like this:

```
#include "INCLUDE_PATH_CL_DATA/defines_cl.h"

// custom includes
#include "INCLUDE_PATH_CL_DATA/opencl_typedefs.h"
#include "INCLUDE_PATH_CL_DATA/opencl_algebra.h"
#include "INCLUDE_PATH_CL_DATA/common_params_cl.hpp"
#include "INCLUDE_PATH_CL_DATA/image_adjustments_cl.h"
#include "INCLUDE_PATH_CL_DATA/fractal_cl.h"
#include "INCLUDE_PATH_CL_DATA/fractparams_cl.hpp"
#include "INCLUDE_PATH_CL_DATA/fractal_sequence_cl.h"
#include "INCLUDE_PATH_CL_DATA/material_cl.h"
#include "INCLUDE_PATH_CL_DATA/input_data_structures.h"
```
and then replace INCLUDE_PATH_CL_DATA with valid path using some function in in cOpenClEngineRenderFractal class. Then it can be append at the begining of programEngine byteArray.

Another solution probably would be to change current directory using
```bool QDir::​setCurrent(const QString & path)```
just only for the OpenCL kernel compilation time
I haven't tested this yet...

**Comment by buddhi1980** [comment]
@zebastian, I don't believe but it works very well (tested path with spaces under Win10). I have already tried the same but probably I did some mistake. I was focused on reported bug reports, maybe that's why I haven't tried this again.
Many thanks for fresh view of the problem.

**Comment by zebastian** [comment]
glad this helped. 
Sorry you were busy on this, since i introduced the problem in the first place.

**Comment by rconcept** [comment]
I tried [Zebastian's changes in yesterday's commit](https://github.com/buddhi1980/mandelbulber2/commit/12199c4ee6dd11a1f011ecb63101054035f5d0c7) and there are no more problems when there are spaces in the executable's path.

Thank you for your quick fixes!

**Comment by buddhi1980** [comment]
@rconcept , thanks for the feedback.
