### ISSUE TITLE
pasting julia values crashes mandelbulber

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#352]
Bug reported by taurus

> Here's annother one, that crashes mandelbulber reproducible on win 10. It does since several versions. When my memory is correct, since the julia preview was implemented (half-hearted, but that's a different story).
The background: I often process mandelbulber values externally (eg spreadsheets, csv), mostly for generating pseudo random fields for animations. I use them to find new/modified forms. Julia parameters are often used for external processing.

> The issue: When I copy/paste values to julia settintgs in main window (>objects>global parameters) the following happens. The first value I paste fits in ok and the julia preview refreshes (regardles if julia 1, 2 or 3). When I paste the second one (or only the decimal places) mandelbulber freezes and quits due to a program crash. there is no relation to the used fomula and/or combination. It allways happens after pasting the second value.
> 
> Since there is the option, to edit csv within a spreadsheet, the need to do so is rather seldom, but sometimes it occurs. Dunno which priority, you give it, but it is a real bug and not a thing, that does not work as expected.

http://www.fractalforums.com/bug-reporting-b231/pasting-julia-values-crashes-mandelbulber/

**Comment by buddhi1980** [comment]
I cannot reproduce this problem.

**Comment by zebastian** [comment]
I was able to reproduce this.
Hold on, i will give you instructions, how to get this behaviour...

**Comment by zebastian** [comment]
OK, got it:
1. go to objects tab > global parameters > enable julia mode
2. type in x value of 2 (julia preview starts rendering)
3. quickly (while rendering preview) right click the julia value and copy vector
4. observe crash :)

**Comment by buddhi1980** [comment]
OK, in this way it's reproducible. Thanks. I'm staring debugging.

**Comment by buddhi1980** [comment]
Fixed
