### ISSUE TITLE
formulas - copy paste error

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#353]
This looks like z.y should be z.z:

if (z.y != oldZ.z) aux.color += fractal->mandelbox.color.factor.z;

There are a couple of those in fractal_formulas.cpp
@mclarekin can you check?

**Comment by mclarekin** [comment]
thanks, fixed, I had forgotten to look for the rest of them :)



https://github.com/buddhi1980/mandelbulber2/commit/21fb78e5edfcb386964ffd2d00a44bb724ffbfae
