### ISSUE TITLE
Sensitivity of sliders

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#356]
AT  FF Timemit asked if Mandelbulber2 had this feature.

In Fragmentarium you can right click on a slider and change which decimal place the slider works on.

BTW And there is still the unsolved other problem with sliders and dials

**Comment by mancoast** [comment]
@mclarekin 
1.) click on a slider and select decimal place
2.) please describe/link other problem with sliders and dialss

**Comment by mclarekin** [comment]
you can click outside the dial and the dial will move to face that point,
but the spinbox value does not change.

similarly  it should be possible to click at a position along the length of
a slider,  and the slider moves to that point

**Comment by mancoast** [comment]
Is it cool if we close this issue and recreate two separate and new issues?

**Comment by mclarekin** [comment]
OK by me.

**Comment by zebastian** [comment]
with these two commits all topics in this issue are handled.
please reopen if any slider stuff is still open.
