### ISSUE TITLE
Discuss 2.12 Milestone.

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#358]
Any thoughts?

**Comment by mancoast** [comment]
The progress of our system is amazing!
The fractals render via graphics card are immaculate, and closely resemble the CPU rendered fractals.
Testing will reveal with certainty when a 2.12 release is ready.
I will test everything using the three primary platforms, {AMD, INTEL, NVIDIA}.
We could offer platform selection enumeration of AMD, INTEL, NVIDIA options?
@buddhi1980 @zebastian is it possible to implement a CLI option for platform selection given text strings of "AMD", or "INTEL", or "NVIDIA"?
Let me clarify, I want to test AMD, INTEL, and NVIDIA from the command line.
I want to test AMD and INTEL processors and graphics cards, so we must classify the difference.
NVIDIA is limited to GPU.

**Comment by zebastian** [comment]
The platform is not directly limited to the vendor, you can have multiple platforms for the same vendor.
On my laptop i have got 4 different platforms for my intel cpu and gpu:

![grafik](https://user-images.githubusercontent.com/7888201/30781827-86b02ea8-a126-11e7-9a7e-7b2a1858a8c6.png)

**Comment by zebastian** [comment]
@mancoast can we close this issue?
