### ISSUE TITLE
standardize color picker for all OS

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#359]
use option QColorDialog::DontUseNativeDialog to have always the same appearance of color dialog on every operating system.

**Comment by zebastian** [comment]
@mclarekin For me both pickers look the same on fedora.
Can you now check with newest commit if the color picker looks like this: 

![bildschirmfoto von 2017-09-17 11-05-27](https://user-images.githubusercontent.com/7888201/30519491-35c93f90-9b98-11e7-9061-4ad900270619.png)

**Comment by mclarekin** [comment]
yes looks very much like yours, but mine is in english LOL.

Thanks that how I like it :)

**Comment by zebastian** [comment]
Oh no, not in english! CRITICAL LANGUAGE BUG 🤣
