### ISSUE TITLE
resolve conversion from 'size_t' to 'int', possible loss of data

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#361]
There exists over 30 instances of warnings from conversion from 'size_t' to 'int', possible loss of data. 

REF:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.981-master/job/cyumth9i7oxmwj7m/messages

**Comment by mancoast** [comment]
@buddhi1980 @zebastian @mclarekin @lachs0r Please help me understand the warnings. I see they exists, but whhy?

**Comment by buddhi1980** [comment]
This warning doesn't mean that the program will lost the data all the time. It could only happen when value of size_t variable (64 bit) will be greater than 2147483648. In that places of code it will never happen. 
Example: int gridWidth = width / optimalJob.stepSizeX;
optimalJob.stepSizeX is size_t type. The result of operation will be always not greater than thousands. 
But the compiler doesn't know that.

Explicit conversions will make the code unreadable.

**Comment by zebastian** [comment]
we should consider making these "value must be in range" assumptions to be assertions, when these can be statically tested. This way we can remove checking overhead in Release binaries.

See for example here: https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/cimage.hpp#L111
If we run a PutPixelAlpha with an invalid x or y, that is a serious program issue and should be handled by an assertion.

**Comment by mancoast** [comment]
Great idea, assertions prevent crashes.

On Sat, Sep 30, 2017 at 11:45 AM, Sebastian Jennen <notifications@github.com

**Comment by mancoast** [comment]
done
https://github.com/buddhi1980/mandelbulber2/commit/3ef1cb7d676f31c98ed7282a9ba58c0564ed04bc
