### ISSUE TITLE
Changed rendering from line-by-line to rect-by-rect in CPU code.

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#363]
Greetings @buddhi1980 

Please enable rect-by-rect in CPU code.
Also, please enable the spiraling out from the center.

REF: https://github.com/buddhi1980/mandelbulber2/commit/da285c956a0f249d0a3739291280b7883ebbc8ec
https://github.com/buddhi1980/mandelbulber2/commit/0a45b8ec6505e2c43edd26d71e6d6740cf201f17

Thanks,
coast

**Comment by buddhi1980** [comment]
For CPU it will be less effective. Then won't be possible to have progressive rendering and effective scheduling between threads and over the network. 
For GPU rendering it was needed to optimize SIMD operations. It is not applicable for CPU with 8 cores.

**Comment by mancoast** [comment]
I understand the increased difficulty, however I feel that symmetry between CPU and GPU code increases SIMD operations to both CPU and GPU.  Is it possible?

**Comment by zebastian** [comment]
BTW: When your CPU already speaks OpenCL, you can also use the "tile rendering"

**Comment by mclarekin** [comment]
my two cents -

in the future consider having options, sometimes when fast exploring  or
aligning an image spinning in would be good.

**Comment by mancoast** [comment]
@buddhi1980 Please reconsider, I enjoy SIMD optimization, and this enables
