### ISSUE TITLE
bounding sphere

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#365]
http://www.fractalforums.com/feature-requests/bounding-sphere/
from Kyzia

"I've  been playing around with the bounding box feature in the Rendering  Engine tab, and achieved what I think are some decent results (like in this example), and it occurred to me that there could be some potential in having the option to set a spherical rather than cubic bound.I  hope this request is sufficiently self-explanatory, and I also  understand that there's a very long list of other stuff to be done."

**Comment by buddhi1980** [comment]
No there is possible to do intersections of fractals by primitive objects
