### ISSUE TITLE
Programs often hangs when animation previews are refreshed

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#368]
to reproduce:
- enable OpenCL
- refresh animation previews
- in mean time press render

I hangs very often. By "hangs" I mean:
- program stops rendering
- there is still possible to save settins
- there is not possible to close the program

**Comment by mancoast** [comment]
windows, osx, linux?

**Comment by buddhi1980** [comment]
All platforms

**Comment by mancoast** [comment]
I will investigate for all os

**Comment by buddhi1980** [comment]
Now I'm testing with editing and rendering long animation (under Linux). I haven't got any problem. Before latest fix it hanged very often.
