### ISSUE TITLE
Discuss MPI usage for Distributed Render

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#372]
Any thoughts on converting the netrender to use the highly standardized Message Passing Interface?

**Comment by zebastian** [comment]
Yes: No :-)
1. NetRender is already running quite stable, has the ability to send arbitrary data (future proof) 
and has some interesting goodies (full custom handshake protocol, compression, fast, ...). So there is no need to change.
2. MPI is designed for highly distributed systems, which effectively manages shared data and communication in complex setups.
But Mandelbulber is quite easy in two ways:
 - supports only simple Server-Client mode (Other infrastructural concepts are easier implemented on a higher level with other software).
 - has a relatively low memory foot print (lots of computation, little data), which makes sophisticated memory copy obsolote.

But you have a point regarding networking:
We should make Mandelbulber incorporatable into "Render Farm Manager" Software.
This way we can make Mandelbulber an enterprise sized rendering software, which can be monitored and effectively scheduled.
I took some time evaluating "open source render queue management software".
The most interesting one i found, which is still actively developed is: cgru/afanasy (http://cgru.info/afanasy/afanasy)
What do you guys think?

**Comment by mancoast** [comment]
AFANASY looks very interesting, I will close MPI issue. we should revisit render farm software in future
