### ISSUE TITLE
Info about missing OpenCL features

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#377]
In Preferences dialog / OpenCL would be good to add short information about missing OpenCL features. v2.12 will still have incomplete implementation of OpenCL, so users should be warn.
List of missing features:
- there is used only material no. 1
- texture mapping (including background)
- primitive objects
- HDR blur
- stereoscopic images
- NetRender
- boolean operators
- support for multiple GPUs
- voxel/mesh export

**Comment by zebastian** [comment]
ok like that, or should it be more present?

**Comment by mclarekin** [comment]
more present like h'mmmm

Sebastian making a popup_on_load message ,   with a don't show me again
function (i am trying to read your mind :)  )

**Comment by buddhi1980** [comment]
I think it should we written as a label on OpenCL tab. It's not visible as a tooltip, but it's very important information for users. What is your opinion?

**Comment by zebastian** [comment]
@buddhi1980 good idea: moved to qlabel
