### ISSUE TITLE
replace qWarning with WriteLog

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#378]
TODO

**Comment by buddhi1980** [comment]
qWaring and qCritical will stay in the code. They are already logged and additionally displayed in console output.

**Comment by mancoast** [comment]
I disagree, its feasible to further standardize how we log messages within the system.  the additional standardization is improvement.  we need all this information for benchmarking

**Comment by buddhi1980** [comment]
qWaring and qCritical calls WriteLog(), so it's standardized. Benefit of qWaring and qCritical is we have additional information which is not given by WriteLog(). It adds info about from which line of code the error/warning is generated. All warnings generated by Qt code are also logged by out WriteLog() function.

**Comment by mancoast** [comment]
awesome! the intel stack required modification/removal of Qinfo and I noticed the other qWarning and qCritical.  Given that qWarning and qCritical also write to the same log as WriteLog, then I agree that there is not need to modify.  Any ideas why Qinfo causes compilation errors with Intel?

**Comment by buddhi1980** [comment]
by the way cErrorMessage class (which display message boxes) also uses WriteLog()
