### ISSUE TITLE
OPENCL: Default Mode ==> FULL

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#379]
Greetings,

Please enable default opencl mode of "full" upon system initialization.

Thanks!
coast

**Comment by buddhi1980** [comment]
Why? "Fast" is the safest for chipper gfx cards. I'm not sure if all gfx cards can handle "full" engine.

**Comment by mancoast** [comment]
New users may be confused as to why the image is always purple.  However, if there exists possibility for no render, then safe is better. Perhaps detection of "fast" mode when user goes to change materials, similar to "more fractals..." dialogue: 
![image](https://user-images.githubusercontent.com/7040493/31145329-7134e44c-a851-11e7-8e66-f7d1ee1a6915.png)

**Comment by mclarekin** [comment]
@ K     "cheaper gfx cards"

@all.  User to save preferences. With cheaper gfx card, user saved
preference =  fast.

similarly,  user saved preference = AMD platform AMD device, then have GPU
enable button in main UI.  It is s.low to have to keep opening preference
dialogues to enable/disable GPU. For now I do this a lot when checking c++
versus openCL formulas. In future I will be changing between the two,
whenever I want to check the statistics

**Comment by mancoast** [comment]
opencl_enabled, opencl_mode, opencl_platform, opencl_device_type, opencl_device_list all confirmed functional and persistent between executions via parameter container.  This issue is no longer required.
