### ISSUE TITLE
"delete all images" button broken

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#380]
![image](https://user-images.githubusercontent.com/7040493/31145191-10e0ff9a-a851-11e7-8663-7846e1e06762.png)

Constantly asks me if I want to purge the output directory, never actually renders.
Any ideas?

**Comment by mancoast** [comment]
The "delete all images" button does not operate. the rendered frames never got deleted.

**Comment by buddhi1980** [comment]
It's because "Last frame to render" is zero. It looks like we still have this problem (issue #210)

**Comment by zebastian** [comment]
Its because the regex does not match anymore:
DeleteAllFilesFromDirectory(params->Get<QString>("anim_flight_dir"), "frame_?????.*");
its now 7 digits instead of 5.
My fault, i will handle this...

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/3b974fc605baf9463d6092ef95ba087c7dc60290

**Comment by mancoast** [comment]
great catch @zebastian I am starting my thorough testing, plan for many more github issues. also : http://wiki.qt.io/Visual_Studio_Add-in I can now finally see the text values of Qstring!
