### ISSUE TITLE
to substitute InstallJammer with another installer

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#383]
InstallJammer is no longer developed and supported. 
It still works fine, but in the future we may encounter compatibility issues on new Windows versions.

The goal is to find new solution to build installers. It has to be for free and without any major license limitations (like GPL)

**Comment by lachs0r** [comment]
On 2017 M10 7, Sat 09:37:07 CEST Krzysztof Marczak wrote:
> InstallJammer is no longer developed and supported.
> It still works fine, but in the future we may encounter compatibility issues
> on new Windows versions.
> 
> The goal is to find new solution to build installers. It has to be for free
> and without any major license limitations (like GPL)

NSIS.

**Comment by buddhi1980** [comment]
Looks nice. I hope it's still in active development.
Windows 10 is not listed as a compatible system:

> Compatible with all major Windows versions
> 
> You can create a single installer that is compatible with Windows 95, Windows 98, Windows ME, Windows NT, Windows 2000, Windows XP, Windows Server 2003, Windows Vista, Windows Sever 2008, Windows 7, Windows Server 2008R2, Windows 8, Windows Server 2012, Windows 8.1 and Windows Server 2012R2

**Comment by lachs0r** [comment]
On 2017 M10 7, Sat 10:01:59 CEST Krzysztof Marczak wrote:
> Looks nice. I hope it's still in active development.
> 
> Windows 10 is not listed as a compatible system:

Yeah, it is. Last release was two months ago. Plus, it’s highly unlikely that 
Microsoft will ever break the APIs etc. that are used by such installers.
I wouldn’t worry about that.

**Comment by mancoast** [comment]
Looks interesting. 

Do you want appveyor to build an installer?

**Comment by buddhi1980** [comment]
@mancoast , we can tey to use appveyor. Then windows builds will be fully automated. Can you add VC++ redistributes into installer package?

**Comment by mancoast** [comment]
No problemo, I will get the installer and msvc resist into appveyor.

**Comment by zebastian** [comment]
@mancoast: really cool. Installer works!
Some things i noticed, which may be configurable in the installer config:
- program should be put in Programs instead of Programs (x86)
- installer should show the license
- installer should ask for starting mandelbulber right away
- installer should ask creating desktop shortcut
- installer should ask for creating menu entry
- some fancy background :)

**Comment by mancoast** [comment]
Thanks, I agree with all the suggestions as well. We can get this stuff implemented ASAP.

**Comment by mancoast** [comment]
Looks like we also need to download and include the latest revision of the manual.

**Comment by zebastian** [comment]
for linux there is already a script to do that, but it might be hard to port it:
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/make-package.sh

```
DOCFILE="$(curl -s https://api.github.com/repos/buddhi1980/mandelbulber_doc/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4)"
...	
	echo $DOCFILE
	wget -O "$destNameLinux/usr/share/doc/mandelbulber2/Mandelbulber_Manual.pdf" $DOCFILE
...
```

**Comment by mancoast** [comment]
when we tag a release of the manual, it needs to be added upstream to the program repo.
all other changes complete in setup.iss

**Comment by zebastian** [comment]
still not ready, missing:

- installer should ask for starting mandelbulber right away
- installer should ask creating desktop shortcut
- vc redist

**Comment by mancoast** [comment]
these are all finished

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/04fbf8dd0ea2530c8d5d73759a57e71d23556b72
https://github.com/buddhi1980/mandelbulber2/commit/d842f68528b5a394174a04b0ba77f95740990521

**Comment by zebastian** [comment]
Oh cool, i did not see the latest commits.
Really nice :)

**Comment by buddhi1980** [comment]
I like how the installer works. @mancoast Good work!
I have already tested it on Win10. No problems observed.

Now I need to try this installer with older Windows (like Vista).

**Comment by buddhi1980** [comment]
Problems visible under windows Vista:
1. Program doesn't start because requires OpenCL.dll. This library should be optional (like it is done for mingw build - used 'clew'). This issue makes not possible to run app on any virtual machine.

2. It should be put in Start menu into group "Mandelbulber". Now it's "(default)". Maybe it's already fixed in latest commit, but Appveyor is still working. 

![image](https://user-images.githubusercontent.com/11696990/31628295-9440b2ea-b2b0-11e7-94e2-5506a4113d7a.png)

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/c463b05150f5a25d9642de0eddebf89f3c8f01ef fixes default start menu group.
the opencl.dll is a bigger task, lets make new github issue for that one.

**Comment by buddhi1980** [comment]
I have tested new version of installer. This time I have no remarks. If you solve the problem with OpenCL.dll, then msvc build will be used as an official win64 version.
Under Win10 the program works very stable. But I'm still going to do more testing.
By the way, OpenMP is supported by msvc compiler?

**Comment by buddhi1980** [comment]
I have just made new test of Installer on quite old Windows Vista. The
program is installed properly, but doesn't start because of missing
VCRUNTIME140.DLL. Robert, have you included MSVC redistributables to
installer package?

2017-10-16 21:00 GMT+02:00 mancoast <notifications@github.com>:

**Comment by buddhi1980** [comment]
I have just made new test of Installer on quite old Windows Vista where I have no Visual Studio. The program is installed properly, but doesn't start because of missing VCRUNTIME140.DLL. @mancoast , have you included MSVC redistributables to installer package?

**Comment by mancoast** [comment]
confirmed function in clean install of vista hyper-vm

**Comment by buddhi1980** [comment]
I can also confirm that now runs well on virtual machine with Vista
