### ISSUE TITLE
transf_rotation_vary_v1.cl error

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#385]
ubuntu,    AMD platform and i7 cpu,

- mandelbulber2 => 2.12 alpha
- Operating System / Platform => ubuntu
- Compiler => QT

"/usr/share/mandelbulber2/formula/opencl/", line 16: error:

a value of type "float3" cannot be used to initialize an entity of type "float"

REAL4 tempVC = (REAL4){fractal->transformCommon.rotation, 0.0f}; // constant to be varied
^

"/usr/share/mandelbulber2/formula/opencl/transf_rotation_vary_v1.cl", line 16: error: not enough initializer values

REAL4 tempVC = (REAL4){fractal->transformCommon.rotation, 0.0f}; // constant to be varied
^
c++ code
 CVector4 tempVC = CVector4(fractal->transformCommon.rotation, 0.0); // constant to be varied

**Comment by mclarekin** [comment]
Maybe one solution.       

        REAL3 rot3 = fractal->transformCommon.rotation;
        REAL4 tempVC = (REAL4){rot3.x, rot3.y, rot3.z, 0.0f}; // constant to be varied

**Comment by mclarekin** [comment]
proper solution maybe changing these rotations to CVector4's like  (plus other rotations)
	transformCommon.rotation = CVector4(container->Get<CVector3>("transf_rotation"), 1.0);
	transformCommon.rotation2 = CVector4(container->Get<CVector3>("transf_rotation2"), 1.0);
	transformCommon.rotation44a =
		CVector4(container->Get<CVector3>("transf_rotation44a"), 1.0); //...........................
	transformCommon.rotation44b =
		CVector4(container->Get<CVector3>("transf_rotation44b"), 1.0); //...........................

**Comment by mclarekin** [comment]
actually first solution could be 
    REAL3 rot3 = fractal->transformCommon.rotation;
    REAL4 tempVC = (REAL4){rot3.xyz, 0.0f}; // constant to be varied

and second solution needs to check that it does not affect the rot matrix

**Comment by zebastian** [comment]
was fixed with this commit: https://github.com/buddhi1980/mandelbulber2/commit/0e289fdb15ea50353516f0c7c234c0a68ab8c3e0
