### ISSUE TITLE
Unknown option: '-O' : when benchmarking, cannot use 'enable_opencl' CLI

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#386]
REF: https://github.com/buddhi1980/mandelbulber2/commit/7e6d6fbc94e84e69f62594fa7df2bf3dbd30c587

@zebastian Do you know if it is possible to enable and disable opencl from command line with benchmark?

Alternatively, if we can enable/disable opencl and silently exit, then script can launch benchmark after toggle.
![image](https://user-images.githubusercontent.com/7040493/31404270-8bf9b334-adc9-11e7-9629-cce2dc0b1b7a.png)

**Comment by buddhi1980** [comment]
You can change (override) parameter "opencl_mode" to "none" (0). It will disable OpenCL without deleting OpenCL memory objects.

**Comment by mancoast** [comment]
How do we run the benchmark with opencl? Can we make a simplified CLI option that auto selects first available GPU?
I cannot get the benchmark to run in opencl mode, benchmark works with CPU always:
![image](https://user-images.githubusercontent.com/7040493/31459571-910de480-ae91-11e7-8bc1-4124206fbdde.png)

**Comment by mancoast** [comment]
not required
