### ISSUE TITLE
QFATAL : Test::renderExamplesWrapper() Test function timed out

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#388]
Is it possible to increase the time limit for benchmark?
We must benchmark with difficulty of 100 or 200 to render all examples in CPU vs GPU.

![image](https://user-images.githubusercontent.com/7040493/31475572-8ea49d5e-aecf-11e7-848d-b375bef41a42.png)

**Comment by mclarekin** [comment]
have you edited/increased  your GPU time out TDR registry thingy. I am
assuming you are using windows

**Comment by mancoast** [comment]
Please explain again.  Do we need to modify the registry to use openCL for long operations?

**Comment by zebastian** [comment]
When Mandelbulber is run under Windows, the OS will monitor the GPU with a watchdog. When
the card becomes unresponsive for more than two seconds, the driver will shutdown and crash.
see also handbook for more info, and how to modify the registry:
https://github.com/buddhi1980/mandelbulber_doc/releases/download/untagged-67c69bfc54fe9e029000/handbook-compressed.pdf
chapter: Driver crash under Windows

**Comment by mancoast** [comment]
How do we mitigate this?  I would strongly recommend against windows release with this inconvenience present

**Comment by mclarekin** [comment]
I do not think mandelbulber installation should change the registry GPU
time out,  as from memory, microsoft warns there there may be some risk
involved. So it should be a users choice,

I suggest moving the fix out of troubleshooting and into  install openCL
for windows section, as I suspect that this will be a problem for a lot of
windows users in the future.

I have had to give this advice over the last few years for users of old
V1.12openCL, and now for V2.12 alpha (and Fragmentarium.)

We could supply some code to do it automatically if the users wishes to
proceed.??

We could approach microsoft  to reconfirm that risk exists (then we can
quote them)

We can advise users that so far we have never had any feedback about this
registry change causing any problems, ( but the sample group is very small)

Thats my two cents :)

**Comment by zebastian** [comment]
Manipulating the registry by default seems a bad idea to me. But this is a problem which most of the users are affected of, so you are right about making the solution more apparent. My ideas on possible solutions:
- Make the registry manipulation an optional checkbox (disabled by default) in the new installer
- Make the explanation more visible in the handbook
- Supply a batch script for the registry manipulation and link it somewhere in the program

@buddhi1980 what are your thoughts on this?

**Comment by buddhi1980** [comment]
> Make the registry manipulation an optional checkbox (disabled by default) in the new installer
This solution will not work for user who prefer standalone version. No installer - no option.

> Make the explanation more visible in the handbook
Nobody reads user manuals :)

> Supply a batch script for the registry manipulation and link it somewhere in the program
I like this idea. It could be implemented in Preferences dialog. 
I'm not sure about technical details. Probably it will need administrative privileges. 
I'm not an expert for Windows registry. I have never manipulate in it from an application.

**Comment by mancoast** [comment]
Can someone point me towards an article that explains the issue?  I can open a support issue with M$ and gather their input.

**Comment by buddhi1980** [comment]
http://www.acceleware.com/blog/Timeout-Detection-in-the-Windows-Display-Driver-Model-when-Running-CUDA-Kernels

http://developer.download.nvidia.com/NsightVisualStudio/2.2/Documentation/UserGuide/HTML/Content/Timeout_Detection_Recovery.htm

https://docs.microsoft.com/pl-pl/windows-hardware/drivers/display/tdr-registry-keys

**Comment by mancoast** [comment]
Oddly enough, I do not think the TDR causes test failure.
I never receive "Display driver stopped responding and has recovered" message.
Instead the output reads "Test Function Timed out"/
Does there exist an option to increase QTest timeout limit?

**Comment by buddhi1980** [comment]
We had understand your bug report in wrong way. So we should focus on increase timeout limit for QTest.

P.S. I have closed this issue by mistake.

**Comment by mancoast** [comment]
Thanks!
