### ISSUE TITLE
OpenCL render fails with error on Ubuntu with AMD graphics

### ISSUE THREAD

**Issue by insidetasmania** [buddhi1980/mandelbulber2#390]
System information 

- mandelbulber2 => 2.12-alpha7
- Operating System / Platform => Ubuntu 17.04 64 Bit 
- Processor 4x AMD A10-6800K APU with Radeon(tm) HD Graphics
- Compiler => Qt Creator

Detailed description
Render always fails with OpenCL turned 'on' in Preferences. Render works if OpenCL is 'off'. 
________________________________________________
Error: Error during compilation of OpenCL program
OpenCL build log:
<unknown>:0:0: in function fractal3D void (struct.sCLPixel
addrspace(1)*, i8addrspace(1)*, %struct.sClIConstants addrspace(2)*,
i32): unsuported call to function
__________________________________________________

OpenCL libs and dev packages are up to date. Clinfo shows a valid OpenCL system. Preferences>OpenCL> device is:
Clover, Mesa, OpenCL 1.1, Mesa 17.3.0-devel
Default device:
AMD Aruba (DRM 2.49.0 / 4.10.0-37-generic, LLVM 5.0.0)

**Comment by buddhi1980** [comment]
There is no chance to run it with OpenCL 1.1. You use open source and driver (Mesa) which has poor OpenCL implementation.  You should install amdgpu driver if your gfx card is supported by this driver.

**Comment by insidetasmania** [comment]
Thanks buddhi1980. The graphics is inside the processor so no card. I can put in a card but I would like to also use the inbuilt graphics for OCL.
