### ISSUE TITLE
Examples with missing ogg-files

### ISSUE THREAD

**Issue by rikardfalkeborn** [buddhi1980/mandelbulber2#392]
A few examples use ogg-files that are not checked into the repo:

> trying file: /usr/share/mandelbulber2//examples/Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/box-deuce-deuce.fract
> File D:/21LGv8Cf0us.ogg not found. Looking for the file in another locations
> Looking for the file at 21LGv8Cf0us.ogg
> Looking for the file at /usr/share/mandelbulber2/sounds/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/sounds/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/settings/21LGv8Cf0us.ogg
> QWARN  : Test::renderExamplesWrapper() File not found anywhere
> Not able to open input file using libSndFile: D:/21LGv8Cf0us.ogg Using QAudioDecoder insteadSystem error : No such file or directory.QSYSTEM: Test::renderExamplesWrapper() cAudioTrack::error QAudioDecoder::ResourceError
> File D:/21LGv8Cf0us.ogg not found. Looking for the file in another locations
> Looking for the file at 21LGv8Cf0us.ogg
> Looking for the file at /usr/share/mandelbulber2/sounds/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/sounds/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/21LGv8Cf0us.ogg
> Looking for the file at /home/travis/.mandelbulber/settings/21LGv8Cf0us.ogg
> QWARN  : Test::renderExamplesWrapper() File not found anywhere
> Not able to open input file using libSndFile: D:/21LGv8Cf0us.ogg Using QAudioDecoder insteadSystem error : No such file or directory.QSYSTEM: Test::renderExamplesWrapper() cAudioTrack::error QAudioDecoder::ResourceError
> trying file: /usr/share/mandelbulber2//examples/Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/menger-fatbackstrokin.fract
> File D:/dIOTV_ZtIwg.ogg not found. Looking for the file in another locations
> Looking for the file at dIOTV_ZtIwg.ogg
> Looking for the file at /usr/share/mandelbulber2/sounds/dIOTV_ZtIwg.ogg
> Looking for the file at /home/travis/.mandelbulber/sounds/dIOTV_ZtIwg.ogg
> Looking for the file at /home/travis/.mandelbulber/dIOTV_ZtIwg.ogg
> Looking for the file at /home/travis/.mandelbulber/settings/dIOTV_ZtIwg.ogg
> QWARN  : Test::renderExamplesWrapper() File not found anywhere
> Not able to open input file using libSndFile: D:/dIOTV_ZtIwg.ogg Using QAudioDecoder insteadSystem error : No such file or directory.QSYSTEM: Test::renderExamplesWrapper() cAudioTrack::error QAudioDecoder::ResourceError

Is this an oversight?

**Comment by mancoast** [comment]
still animating :), however, this song is not public domain, dIOTV_ZtIwg is youtube id

**Comment by mancoast** [comment]
21LGv8Cf0us is another youtube id, also not in public domain

**Comment by mancoast** [comment]
@buddhi1980 @zebastian @rikardfalkeborn Any suggestions for animating non-public audio? Perhaps I can add the youtube urls into the description of the example settings?
