### ISSUE TITLE
Toggle Timeout Detection and Recovery (TDR) of Windows Display Driver Model (WDDM)

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#393]
REF: [puget](https://www.pugetsystems.com/labs/hpc/Working-around-TDR-in-Windows-for-a-better-GPU-computing-experience-777/) and [M$](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys)

```
TdrLevel - Specifies the initial level of recovery. The default is to recover on timeout, which is represented by value 3.
KeyPath   : HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers
KeyValue  : TdrLevel
ValueType : REG_DWORD

```

We need to use QT framework to create two new help menu options
1.) disable TDR
ValueData : 0 - Detection disabled

2.) enable TDR
ValueData : 3 - Detection Enabled

3.) maybe we need to always re-enable TDR on system exit? <== any input?

**Comment by mancoast** [comment]
I am starting to see this issue now while benchmarking opencl at higher resolutions

**Comment by buddhi1980** [comment]
It should be not in help menu but in Preferences dialog on OpenCL tab.

**Comment by buddhi1980** [comment]
After short investigation I see that it should be some small external script or application. It needs administrator rights to change these registry entries and then restart of Windows to take effect.

**Comment by mancoast** [comment]
@buddhi1980 what are your thoughts for a menu option for the new batch script?
it requires and checks for admin rights, we can further modify for prompt to restart.
