### ISSUE TITLE
An observation - number of cpu cores used when rendering

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#396]
Using Mandelbulber 2.12-alpha7. Installed a 'CPU monitor' into the taskbar of an Xubuntu 17 system.

Interesting results on image renders. Initially one core of a 4 core CPU is used, then 2 cores are used for the rest of the render. They are not always the same 2 cores. That leaves 2 cores not involved in the render process.

**Comment by mclarekin** [comment]
@ TasManua17

May be something with your setup.   With  Ubuntu17.04   i7 HQ , I have all
eight  working  at  100% during rendering.

**Comment by buddhi1980** [comment]
Do you run the program with enabled OpenCL or not?

**Comment by TasMania17** [comment]
Thanks guys. OpenCl is enabled. After reading mclarekin's comment I installed 'beignet' and 'beignet-opencl-icd' which adds the Intel CPU to the OpenCL list. The CPU is OCL 2.0 and the Nvidia graphics is OCL1.2.
Looks like Mandelbulber2's OpenCL manages all of them when it is enabled.
On renders one core starts first and the other 3 kick-in later. Its faster now I think.
I should have posted this to FractalForums Mandelbulber page. I think I will do that to help others set-up OCL.

**Comment by mclarekin** [comment]
Initially one core of a 4 core CPU is used, then 2 cores are used for the
rest of the render
So this result was from using openCL on cpus not the gpu?


My 100% is in c++, I have been  meaning to install "beignet". Please send
your installation process.

My intermittent experience with  dev v2.12 and openCL, on my CPUs, is that
crashes are possible.

**Comment by mancoast** [comment]
@TasMania17 thanks for testing!

**Comment by buddhi1980** [comment]
If OpenCL is enabled and GPU is used then CPU just manages calculation taks, but all the heaviest calculations are done on GPU (which is fully utilized - e.g. 512 threads).
When OpenCL is disabled, then CPU is fully utilized (all physical and virtual cores are used).

**Comment by TasMania17** [comment]
At the first comment I had only GPU enabled in OpenCL. Now the Intel CPU is also listed. Here is a screenshot of Mandelbulber>Program Preferences>OpenCl 
![openclnvidiaintel](https://user-images.githubusercontent.com/32868462/31795176-87cc232e-b570-11e7-81f8-e5d459ab3a53.png)
I seem to be getting no crashes on rendering but have not had time to fully test.
I think just 'sudo apt-get install beignet' is all it takes to install.

**Comment by TasMania17** [comment]
At the first comment I had only GPU enabled in OpenCL. Now the Intel CPU is also listed. Here is a screenshot of Mandelbulber>Program Preferences>OpenCl
![openclnvidiaintel2](https://user-images.githubusercontent.com/32868462/31795706-98250fd6-b572-11e7-99ad-d699a95fcfe7.png)
I seem to be getting no crashes on rendering but have not had time to fully test.
I think just 'sudo apt-get install beignet' is all it takes to install.
In linux you can permanently change the CPU mode from 'powersave' to 'performance'
https://askubuntu.com/questions/929884/how-to-set-performance-instead-of-powersave-as-default

**Comment by TasMania17** [comment]
Update. In theory it doesn't make sense because there is no Intel GPU in my system. In practice installing 'beignet-opencl-icd' gives me a lot (unlimited) stability. Maybe there is a low level OpenCL driver involved?
I've just made a 9 object hybrid fractal on a machine with just 4Gig ram.
Also the Intel 'performance' mode seems to work on a PC, maybe not a notebook.

**Comment by mancoast** [comment]
that makes sense.  did you select the opencl cpu or gpu with the intel platform?  opencl might also detect and operate on cpu, without embedded graphics.

**Comment by mclarekin** [comment]
yep.

on my laptop, openCL intel platform works on my CPU.

With Intel platform my  i7 cpu is about as fast as my HD4600 embedded GPU.
 The AMD GPU is quite a bit faster

**Comment by mclarekin** [comment]
I have just been relooking at this.

 I note :

1)   reload from a crash,  enabling openCL, first render is slow  (  3.4
seconds compared to 0.8 seconds), I assume the program has not finished
some tasks (like the large amount of presets I have to load)


2)  Testing results on default -1.5 mbox.

AMD platform  AMD GPU           0.8    (first render 3.4)
AMD platform  intel i7  either crash or work
AMD platform i7 worked h,mmm but at the speed of the AMD GPU  (possible
changing selection problem)

intel  platform  intel i7     either crash or work     1.2
intel platform  HD4600 embedded either crash or work  1.6

**Comment by TasMania17** [comment]
Hi  mclarekin. I'm confused by "AMD platform intel i7".  Could you give a bit more detail on that system?

This page has a lot of info on the AMD OpenCL implementation.
[http://developer.amd.com/resources/articles-whitepapers/opencl-and-the-amd-app-sdk-v2-4/](url)
AMD say the OpenCL process starts with a 'just in time' (JIT) compiler which I guess is what one core on my system is doing to start with. Then its about queues, parallel processing and OpenCL 'kernels'. Hopefully application developers don't need to know whats inside every OpenCL installation  :)

At least the Intel drivers and runtimes are all on the same page.
[https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime](url)
My CPU is supported but not my operating system unfortunately.

**Comment by mclarekin** [comment]
Tas, this is my current understanding but i could be completely wrong

Some AMD  drivers can run openCL on intel cpus.

in Win10 with an embedded HD4600 gpu and the AMD r265x, I have four
combinations of platform and device, as both platforms can run openCL on
the i7.

I can also get an AMD driver to run openCL on my i7 in Ubuntu, albeit a
bit crashy.  I just cant get the amd driver to work on my AMD GPU :)

As my i7 is quad core, it is actually  slighly faster with opencl than the
HD4600 gpu

**Comment by mclarekin** [comment]
1)   reload from a crash,  enabling openCL, first render is slow  (  3.4
seconds compared to 0.8 seconds),

OK this is just compiling time, like the in old V1.21

**Comment by mancoast** [comment]
ok to close? I am satisfied with insight gained from issue

**Comment by mclarekin** [comment]
closed
