### ISSUE TITLE
Control color of random lights

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#398]
implement control over color of random lights

**Comment by mclarekin** [comment]
I am suggesting an option to be able to choose random lights of one color.

BTW there is also lots of other stuff that can be done with random lights and some maths, but they can be evaluated in the distant future :)

**Comment by mclarekin** [comment]
a) option to choose random light single color.
b) option for choosing, maybe 3 colors. Color of each light to be randomly assigned from the 3 colors chosen

**Comment by mclarekin** [comment]
c) light's color dependent on distance from the surface

**Comment by mclarekin** [comment]
a) option to choose random light single color.
**Implemented** https://github.com/buddhi1980/mandelbulber2/commit/103bea9a9dfd1c42af4c070af4b1dacb4dfa3dea

**Comment by mclarekin** [comment]
from luchansky
d) Can we add option for lights in a color range? R=(a, b), G=(c, d), B =(e, f)

**Comment by buddhi1980** [comment]
Implemented
