### ISSUE TITLE
ENABLE AUTOGEN CMAKE_AUTOUIC ==> ON

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#399]
I am seeing compilation errors in CENTOS with CMAKE and OPENCL build.
The add_definitions(-DUSE_OPENCL=1) does not propagate to the UI preprocessor.
Research has revealed that one solution is to replace deprecated usage of QT5_WRAP_UI with CMAKE_AUTOUIC.  Any thoughts?

Here is output from broken compilation:
```

[ 79%] Building CXX object CMakeFiles/mandelbulber2.dir/home/mandelbulber2/mandelbulber2/qt/fft_view.cpp.o
/opt/intel/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc   -DQT_CORE_LIB -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_TESTCASE_BUILDDIR=\"/home/build/mandelbulber2\" -DQT_TESTLIB_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DSHARED_DIR=\"/usr/local/share/mandelbulber2\" -DUSE_GAMEPAD=1 -DUSE_OPENCL=1 -I/home/build/mandelbulber2 -I/home/mandelbulber2/mandelbulber2/cmake -I/home/mandelbulber2/mandelbulber2/cmake/.. -I/home/mandelbulber2/mandelbulber2/cmake/../qt -isystem /opt/Qt5.7.0/5.7/gcc_64/include -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtCore -isystem /opt/Qt5.7.0/5.7/gcc_64/./mkspecs/linux-g++ -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtGui -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtNetwork -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtUiTools -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtTest -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtMultimedia -isystem /opt/Qt5.7.0/5.7/gcc_64/include/QtGamepad  -03 -g -fPIC -wd39,10006    -fPIC -std=gnu++11 -o CMakeFiles/mandelbulber2.dir/home/mandelbulber2/mandelbulber2/qt/fft_view.cpp.o -c /home/mandelbulber2/mandelbulber2/qt/fft_view.cpp
/home/mandelbulber2/mandelbulber2/qt/dock_navigation.cpp(221): error: class "Ui::cDockNavigation" has no member "label_opencl_mode"
  	ui->label_opencl_mode->setVisible(enabled);
  	    ^
```

Here is compilation output from attempts to use CMAKE_AUTOUIC:

```

AUTOGEN: error: The same ui_NAME.h file will be generated from different sources.
To avoid this error rename the source files.
ui_dock_animation.h : /home/mandelbulber2/mandelbulber2/qt/dock_animation.ui
ui_dock_animation.h : /home/mandelbulber2/mandelbulber2/src/dock_animation.ui
ui_dock_queue.h : /home/mandelbulber2/mandelbulber2/qt/dock_queue.ui
ui_dock_queue.h : /home/mandelbulber2/mandelbulber2/src/dock_queue.ui

```

**Comment by buddhi1980** [comment]
Yesterday I got the same errors when I tried to make clean build in Visual Studio 2017. I have no idea how to fix this. There is no similar error when application is build with qmake and gcc.

**Comment by buddhi1980** [comment]
When I checked dock_navigation.hpp then I saw that class Ui::cDockNavigation had member ui->label_opencl_mode.

About second problem
```
ui_dock_animation.h : /home/mandelbulber2/mandelbulber2/qt/dock_animation.ui
ui_dock_animation.h : /home/mandelbulber2/mandelbulber2/src/dock_animation.ui
```
Here is some problem with file location. dock_animation.ui shouldn't exist in src folder. It should be only in qt folder.

**Comment by mancoast** [comment]
did this start when we added opencl label to dock_animation?  can you provide steps to reproduce error in msvc, i have better chance to fix if I can recreate in visual studio.

**Comment by buddhi1980** [comment]
I have found where was the problem. All files from qt (ui_*.h, moc_*.h) ) folder weren't regenerated (I don't know reason why). I have deleted all these files and run compile again. Then the program was compiled properly.

**Comment by mancoast** [comment]
I think we need to rework the CMAKE_AUTOUIC property of the cmakelists.txt

**Comment by mancoast** [comment]
we need to upgrade/maintain cmake for the up and coming vcpkg

**Comment by mancoast** [comment]
QT5_WRAP_UI and the *.ui with matching *.h files in /qt/ directory are causing critical failures when attempting to build with CMAKE_AUTOUIC.  This exact issue simultaneously prevents direct build using xcodebuild.  REF: https://circleci.com/gh/mancoast/mandelbulber2/41

I am close to getting the circle CI system to generate an OSX installer for each commit to the repo, but this issue is blocking.  @buddhi1980 @zebastian @bermarte @mclarekin How do we want to proceed?  I strongly suggest we rework the source code file names to accommodate CMAKE_AUTOUIC and xcodebuild

**Comment by buddhi1980** [comment]
What changes in filenames are needed? What is wrong?

**Comment by mancoast** [comment]
I am currently investigating the issues, however this should be fairly easy to fix

**Comment by buddhi1980** [comment]
But before fix, please let us know what changes are you going to do with filenames.

**Comment by buddhi1980** [comment]
By the way why you got .ui files in ```/home/mandelbulber2/mandelbulber2/src/``` directory? They should be only in ```/home/mandelbulber2/mandelbulber2/qt/``` directory.

**Comment by mancoast** [comment]
We must use a pull request for this change.  btw, i meant /qt directory of the source.  something strange is happening because of :
```
filename conflicts with uic ==> 
"D:\GIT\mandelbulber2\mandelbulber2\qt\detached_window.ui"
"D:\GIT\mandelbulber2\mandelbulber2\qt\detached_window.h"
```

**Comment by mancoast** [comment]
there are 20 filename conflicts in total, where ui file and h file collide when using CMAKE_AUTOUIC

**Comment by buddhi1980** [comment]
What is the reason to use QT5_WRAP_UI instead of CMAKE_AUTOUIC? (ref: https://stackoverflow.com/questions/25875255/cmake-qt5-qt5-wrap-ui-not-generating-ui-header-files)

**Comment by mancoast** [comment]
I need to use CMAKE_AUTOUIC with cmake. The reasons why it’s broke. Are puzzling. I think it’s the same reason Xcode doesn’t not operate

**Comment by buddhi1980** [comment]
What I have just found probably CMAKE_AUTOUIC_SEARCH_PATHS have to be used to specify location of UI files

**Comment by buddhi1980** [comment]
Works! I will commit correct cmake file.

**Comment by mancoast** [comment]
Awesome! I will try to translate to Xcode. Estentially, the automoc functions, but autouic doesn’t work yet for Xcode.

**Comment by mancoast** [comment]
So the gameplan is to use cmake with -G xcode to make the app and the bundle with dmg.
However, I am still having issues REF: https://circleci.com/gh/mancoast/mandelbulber2/48
Any suggestions @buddhi1980 ?

```
AUTOGEN: error: The same ui_NAME.h file will be generated from different sources.
To avoid this error rename the source files.
ui_dock_animation.h : /Users/distiller/mandelbulber2/mandelbulber2/qt/dock_animation.ui
ui_dock_animation.h : /Users/distiller/mandelbulber2/mandelbulber2/src/dock_animation.ui
ui_dock_queue.h : /Users/distiller/mandelbulber2/mandelbulber2/qt/dock_queue.ui
ui_dock_queue.h : /Users/distiller/mandelbulber2/mandelbulber2/src/dock_queue.ui
make: *** [/Users/distiller/mandelbulber2/CMakeFiles/mandelbulber2_automoc] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **

```

**Comment by bermarte** [comment]
The installer would be something else than the .dmg file if I understood well.  I had a separate script to create the installer and one to create the xcode file and the .dmg file, but I din't use CMAKE.

**Comment by mancoast** [comment]
Can you please share your scripts?

**Comment by bermarte** [comment]
Unfortunately my laptop is broken, and I should buy another one (secondhand) in a few days, then for sure there will be lots to do.
I will share the scripts, no problem with that.

**Comment by mancoast** [comment]
@bermarte any updates? can you share the OSX packaging scripts?

**Comment by mancoast** [comment]
Resolved with circle ci
