### ISSUE TITLE
Modification of "Frames per Keyframe" parameter should recalculate the animation table headers

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#400]
See screenshot for details.

![image](https://user-images.githubusercontent.com/7040493/31945113-3713d1e6-b89c-11e7-9618-d0137b2770d3.png)

**Comment by buddhi1980** [comment]
Have you tried to press Refresh Table button?

**Comment by mancoast** [comment]
exactly, the table should automatically refresh when the slider is altered.  Do we want extra button press?

**Comment by buddhi1980** [comment]
Because refreshing of table sometimes takes a lot of time (if previews are enabled), I would like to avoid automatic refreshing.

**Comment by mancoast** [comment]
how about we compromise, auto-refresh the table if previews are disabled?
upon initial inspection, I did not notice the table refresh button until
mentioned here.

**Comment by mancoast** [comment]
not required
