### ISSUE TITLE
mesh enhance and information

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#401]
evaluate the following articles, if these could enhance the mesh export:
 
http://www.fractalforums.com/mandelbulb-3d/some-point-cloud-examples/msg103771/#msg103771
http://www.fractalforums.com/3d-fractal-generation/tips-for-freeware-to-mesh-point-clouds/msg103776/#msg103776

**Comment by buddhi1980** [comment]
I'm not sure what is the advantage in compare with out actual solution. Can you help me to understand this?

**Comment by zebastian** [comment]
No, i havent had the time to read the article and compare it to our code. Graeme told me about it so it may be interesting for the imlpementation. This issue is just so i wont forget about it.

**Comment by mancoast** [comment]
with initial skim/read seems very interesting, mentions discarding certain
points, simplification of point cloud, file size reduction, etc...
definitely worth a peak, downplays the mesh and favors the point cloud.
however, our mesh is unique to the mandelbulber system. as is the animation
engine and sound file integration.

**Comment by zebastian** [comment]
Can be reviewed, when we implement opencl support...
