### ISSUE TITLE
enable resources over internet

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#402]
allow selection of http ressources in misc static files (textures, audio, ...).
When the settings are loaded the URL is hashed and loaded from a local cache (~/mandelbulber/httpCache/aba87ebae7ba87a856ef.ogg)
When the file is not present yet it will be downloaded into the cache folder.

This will enable specifying resources only by an URL and leverages example file size and makes it easier to include online resources.
Example:
```
animsound_soundfile_fractal0_mandelbox_folding_min_radius https://upload.wikimedia.org/wikipedia/commons/c/ca/Modest_Mussorgsky_-_night_on_bald_mountain.ogg
```

**Comment by mancoast** [comment]
can we operate with youtube urls?  that would really take it to the next level because every song I know of already exists on youtube

**Comment by mancoast** [comment]
hope this helps!
https://github.com/rrooij/youtube-dl-qt/blob/master/src/youtubedl.cpp

**Comment by zebastian** [comment]
TODO: use cResourceHttpProvider  anywhere, where ressources like textures or audio are retrieived from serttings files...
