### ISSUE TITLE
Add 'Off' as an option in the OpenCL mode combobox

### ISSUE THREAD

**Issue by Andrew-H2O** [buddhi1980/mandelbulber2#404]
While the feature set for OpenCL rendering is not 100% complete, it would be convenient to be able to toggle OpenCL off using the combobox in the navigation pane, rather than having to go into the preferences menu.

**Comment by buddhi1980** [comment]
It's already implemented. Below RENDER button there is OpenCL mode selector. You can select "no OpenCL"

**Comment by Andrew-H2O** [comment]
I'm using version 2.12-alpha7, which has only "fast", "limited", and "full" selectable in the OpenCL mode combo box
If "no OpenCL" has subsequently been added, that's great :-)
