### ISSUE TITLE
Difference in image between c++ and openCL

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#406]
I do not know yet what is causing this difference

Steps to reproduce.  Copy paste in settings and render both ways

[test1.txt](https://github.com/buddhi1980/mandelbulber2/files/1420790/test1.txt)

**Comment by mclarekin** [comment]
I have just looked further at this specific problem.  I  do not recognise this problem.  It might be correct behaviour and just the results of the fractal maths, DE calc and floating point accuracy. But I think it is best that Krzysztof checks this out.

[test2.txt](https://github.com/buddhi1980/mandelbulber2/files/1424851/test2.txt)

**Comment by mclarekin** [comment]
Check code for  Bail out check in hybrid mode

**Comment by buddhi1980** [comment]
The problem disappears when "check for bailout condition" is disabled in first slot. I have to check logic for this in OpenCL code.

**Comment by mclarekin** [comment]
The problem *appears* when "check for bailout condition" is disabled in
first slot.

**Comment by buddhi1980** [comment]
It is already fixed.
