### ISSUE TITLE
slot weight bug

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#407]
I am guessing there is a diff between C++ and openCL in the weight code

load example       mandelbox_menger_morph

**Comment by mclarekin** [comment]
also Robs  sponged.  Nice to see Rob using the incredibly underused weight  control.

**Comment by mancoast** [comment]
I will double check this one, so opencl does not match cpu>

**Comment by mclarekin** [comment]
I think this has since been committed. I will check and close Issue

**Comment by mclarekin** [comment]
closed with commit aec1c98ea4d2b8d6f510248f1d6d131870911553
