### ISSUE TITLE
Julia mode preview problem

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#408]
Julia

I acn reload from clipboard and it is still the same.

Now load a random preset, and the preview is now correct. 

load origional settings from clipboard, preview is correct.

Undo back to the start, preview is still correct.

So can no longer reproduce it ,  just a glitch ??

 
![menger_mod1_001_8k](https://user-images.githubusercontent.com/12769564/32099152-aa0b1dea-bb6b-11e7-97d5-6e0331a021aa.jpg)
[menger 8k.txt](https://github.com/buddhi1980/mandelbulber2/files/1421667/menger.8k.txt)

**Comment by mancoast** [comment]
cannot replicate

**Comment by mclarekin** [comment]
I suspect nobody will be able to replicate this.

It may be part of a bigger picture.

- I feel I am getting slower response, 
- screen refreshing problem maybe more prevalent, 
- https://mail.google.com/mail/u/0/?tab=wm#sent/15f6c613c2515a9d
