### ISSUE TITLE
I think w needs to set up for openCL

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#409]
this is the c++ code

if (in.forcedFormulaIndex >= 0)
	{
		z.w = fractals.GetInitialWAxis(in.forcedFormulaIndex);
	}
	else
	{
		z.w = fractals.GetInitialWAxis(0);
	}

**Comment by buddhi1980** [comment]
Not now. This is only needed for booleans

**Comment by mclarekin** [comment]
OK, I am now guessing some other code is missing to get 'w' working.

example:   Mix Pinski 4D hybrid-CPU

On Sat, Oct 28, 2017 at 1:22 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
@mclarekin , you were right. It was partially missing. I'm commiting corrected code.

**Comment by mclarekin** [comment]
closed
https://github.com/buddhi1980/mandelbulber2/commit/e1534813c66938f9c79dcc6f2ccf4761940babf3

**Comment by mclarekin** [comment]
examples are not rendering correctly in cpu and openCL
example worked correctly in V2.11 but did not with alpha7 a month ago

a) menger-AddConstant4D.fract 
the transform maths is basic
z += fractal->transformCommon.additionConstant0000
I assume either the parameter is corrupt or a code change

 b) menger-FabsAddConstant4D
sames as above with a bit more maths

i will try and find the problem

**Comment by mancoast** [comment]
please add example settings for verify

**Comment by mclarekin** [comment]
I will add more later once I fully investiagte, it is a V2.11 to V2.12
issue that can be seen in    examples     menger-AddConstant4D-CPU and
menger-FabsAddConstant4D-CPU.

**Comment by mclarekin** [comment]
need some other issues to be fixed before investigating this further.

**Comment by mclarekin** [comment]
I note that     menger-AddConstant4D-CPU and menger-FabsAddConstant4D-CPU are no longer in esxamples folder.  So issue closed.

But I have just had a quick look at V2.11, and it would appear there was something wrong with the z.w parameter (it did not work correctly)
