### ISSUE TITLE
Yellow light more intense than blue

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#410]
Reproduce my changing custom light# 1 from deep blue to deep yellow
Not sure if this is the correct behaviour of the lights

[yellow light.txt](https://github.com/buddhi1980/mandelbulber2/files/1424040/yellow.light.txt)

**Comment by mclarekin** [comment]
difference was caused by having some blue fog turned on.

BTW chevk out the settings, "inside" a closed  BulbBox Quat hybrid

closed

**Comment by mclarekin** [comment]
Reoppened because I am still not sure.
 
With the attached: render settings, then change both the custom light and the fog from blue to yellow.
There should  be quite a difference beween the light intensity and the amount of background detail that can be seen.

[blue light.txt](https://github.com/buddhi1980/mandelbulber2/files/1424061/blue.light.txt)

**Comment by mancoast** [comment]
cannot reproduce, please be more specific with steps to replicate issue

**Comment by mclarekin** [comment]
It looks like Custom light #1 has yellow stronger than blue. It could be correct behavior ??
![yellow](https://user-images.githubusercontent.com/12769564/32255404-8b9606e6-bf0c-11e7-87db-7ebd039213fc.jpg)
![blue](https://user-images.githubusercontent.com/12769564/32255405-8d9d4760-bf0c-11e7-8f4d-701afc15cc8b.jpg)
[yellow.txt](https://github.com/buddhi1980/mandelbulber2/files/1432745/yellow.txt)

**Comment by mclarekin** [comment]
So mainly driven by the custom light effect, but it becomes worse if you have the same color iteration fog happening at the same time.

**Comment by mancoast** [comment]
interesting, with the yellow light the solid fractal isnt even visible.  It
looks good with the blue light

**Comment by buddhi1980** [comment]
It's because fractal color is yellow. Blue light cannot illuminate yellow surface, because all light is absorbed. When yellow light illuminates yellow surface then it is bright. Everything is all right here. 
Another thing is that yellow color is a mix of two colors: red and green so visual brightness of this color is higher.

**Comment by mclarekin** [comment]
,  Another thing is that yellow color is a mix of two colors: red and green
so visual brightness of this color is higher

Thanks  for explaining, this explains why when I turned off color palette
and had grey surface there was still a difference
