### ISSUE TITLE
mandelbulb4 openCL broken

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#413]
guessing	
current
	rotM = RotateX(rotM, angX * (fractal->bulb.power - 1.0f));
	rotM = RotateY(rotM, angY * (fractal->bulb.power - 1.0f));
	rotM = RotateZ(rotM, angZ * (fractal->bulb.power - 1.0f));
try
	rotM.x = RotateX(rotM, angX * (fractal->bulb.power - 1.0f));
	rotM.y = RotateY(rotM, angY * (fractal->bulb.power - 1.0f));
	rotM.z = RotateZ(rotM, angZ * (fractal->bulb.power - 1.0f));

**Comment by buddhi1980** [comment]
@zebastian, in mandelbulb4.cl there is missing initialization of matrix33. Can you add some code to auto-generate missing initialization.
Correct code should be folowing:

```
	matrix33 rotM;
	rotM.m1 = (float3){1.0f, 0.0f, 0.0f};
	rotM.m2 = (float3){0.0f, 1.0f, 0.0f};
	rotM.m3 = (float3){0.0f, 0.0f, 1.0f};
	
	rotM = RotateX(rotM, angX * (fractal->bulb.power - 1.0f));
	rotM = RotateY(rotM, angY * (fractal->bulb.power - 1.0f));
	rotM = RotateZ(rotM, angZ * (fractal->bulb.power - 1.0f));
```

**Comment by zebastian** [comment]
sure, i will look into this...

**Comment by zebastian** [comment]
done with latest commit

**Comment by buddhi1980** [comment]
Thanks.
