### ISSUE TITLE
DeltaDE pseudo klienian to be implemented

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#414]
Get error message if try to use in OpenCL

**Comment by mancoast** [comment]
example settings please

**Comment by mclarekin** [comment]
Here is the error message

Critical: OpenCl ERROR:  "program->build()"  ( -11 )
(C:\projects\mandelbulber2\mandelbulber2\msvc\../..//mandelbulber2\src\opencl_engine.cpp:77,
bool __cdecl cOpenClEngine::checkErr(int,class QString))
OpenCL Build log:
"C:\Users\Graeme\Downloads\mandelbulber-Release-x64-b9b2e4d3cf3d53f0542786c3cde3bef4450ed665\build-win\Release\x64\opencl\engines\
calculate_distance.cl", line 174: error:
          expected an expression
                out.distance = .... // TODO to be written later
                               ^
"C:\Users\Graeme\Downloads\mandelbulber-Release-x64-b9b2e4d3cf3d53f0542786c3cde3bef4450ed665\build-win\Release\x64\opencl\engines\
calculate_distance.cl", line 176: error:
          expected a ";"
        }
        ^

**Comment by zebastian** [comment]
@mclarekin should be done in latest commit, see above.
can you check again and also check the rendered image output?

**Comment by mclarekin** [comment]
All good
