### ISSUE TITLE
Example Mandelbox 58 issue.

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#415]
See if this is reproducable.

In OpenCL limited, the rendering seems to get stuck at times, and took longer than in c++ mode.

**Comment by mclarekin** [comment]
Disable fog and DOF and it is a bit faster but still stalls a few times. Some of the images is too close to the camera for single precision

**Comment by mancoast** [comment]
please paste settings with code block quotes

**Comment by mclarekin** [comment]
It is Example :  Mandelbox 58

**Comment by buddhi1980** [comment]
In these settings camera is much too close to the fractal (single precision problem). That's why rendering is not working properly.

**Comment by mclarekin** [comment]
Thanks for confirming that this is normal behaviour due to  single precision  limitations  

closed
