### ISSUE TITLE
Split fractal_formulas.cpp

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#418]
What are the team's thoughts regarding readability of this file?

**Comment by buddhi1980** [comment]
I know that this file is far too long. I'm going to split this file after release 2.12. Please do not do this now because all php scrips will need to be updated. We are close to release, so I want to not add work.

**Comment by mclarekin** [comment]
That will be great. :)

**Comment by zebastian** [comment]
IMHO it would be good to implement this in the following way:
add new folder: mandelbulber/formula/cpp
in this folder foreach formula add new file which subclasses a new basic FractalFormula class which has a ```virtual void Iteration``` and misc virtual methods for ```de type```, ```de function```, ...
- fractal_formulas.* can be completely erased and iteration functions moved to the Iteration implementation in each class
- fractal_list.* definitions can mostly be implemented in each formula class and only a list of pointers to each formula class be defined.

**Comment by buddhi1980** [comment]
I like your proposal. Looks very good. We can try to do this in 2.13. It could be good way to implement easier way to add new formulas.

**Comment by zebastian** [comment]
:+1:

**Comment by buddhi1980** [comment]
Here is my first attempt to split fractal formulas: https://github.com/buddhi1980/mandelbulber2/commit/91637f04e0e6e83c44912801c1aee37fae1dd03a
This first version probably far from complete. But could be used as a starting point.
I have tried to not make it complicated. 
Actually I have no solution for virtual methods for de type, de function. It have to be portable to OpenCL code.
Another problem is how to provide something like fractal::enumFractalFormula which will provide unique id number for formulas and will be visible as a list somewhere in the code (to be easy to find free, not duplicated  number) 
@zebastian what you think about it?

**Comment by zebastian** [comment]
Hey @buddhi1980,

this looks pretty much, how i thought it should be. Great!
What do you mean by "no solution for virtual methods for de type, de function."?
enumFractalFormula has the same relation to the formulas as any other attribute (internalName, nameInComboBox, ...), so it should probably be directly in the cFractalMandelbulb file. (Somewhere the magic number 2 just needs to be written).

When constructing the formula list in fractal_list we can assert, that every ID has to given and be unique among all formulas.
We can write some comment into the abstract_fractal.h regarding internalID which ranges are already in use, which to use for new formulas, etc 

On the crafting side i see 4 phases:
1. finishing the cAbstractFractal and one example of a concrete formula class
2. writing a porting script for all formulas to the new format
3. rewriting the maintenance script populateUiInformation.php to be based upon the new format
4. switch over to the new formula format in cpp

**Comment by buddhi1980** [comment]
About 

> no solution for virtual methods for de type, de function.

We cannot use function pointers in OpenCL code. For main formula code we use following workaround:

```
			switch (formulaIndex)
			{
				case 0: z = FORMULA_ITER_0(z, fractal, &aux); break;
				case 1: z = FORMULA_ITER_1(z, fractal, &aux); break;
				case 2: z = FORMULA_ITER_2(z, fractal, &aux); break;
				case 3: z = FORMULA_ITER_3(z, fractal, &aux); break;
				case 4: z = FORMULA_ITER_4(z, fractal, &aux); break;
				case 5: z = FORMULA_ITER_5(z, fractal, &aux); break;
				case 6: z = FORMULA_ITER_6(z, fractal, &aux); break;
				case 7: z = FORMULA_ITER_7(z, fractal, &aux); break;
				case 8: z = FORMULA_ITER_8(z, fractal, &aux); break;
			}
```
I'm not sure if can use something similar for all of these stuff. Every formula in hybrid sequence or in boolean mode can have different code. In C++ we can just call class method or use function pointers. In OpenCL it will not work.

**Comment by buddhi1980** [comment]
In general I think we should start with basic split. Then we can look how to make it better. I would avoid making to many changes in compute_fractal during this split. It would be too difficult to find potential errors. 
I will try to make one fully working example for formula class and you will look if you will be able to auto generate classes.

**Comment by zebastian** [comment]
Function pointer and other vars probably best to be auto-rewritten to define pragmas: these are simple and produce fast code without overhead.

**Comment by zebastian** [comment]
Right now i am quite busy, but at the end of june i can progress on this.

**Comment by mclarekin** [comment]
I think this can be closed?
