### ISSUE TITLE
malloc usage in lzo_compression.h C26408

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#419]
![image](https://user-images.githubusercontent.com/7040493/32252769-75df1e7c-be6d-11e7-9e6b-6f06a55fc776.png)

REF: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-mallocfree
`
malloc() and free() do not support construction and destruction, and do not mix well with new and delete.
`

Any suggestions? I am not sure how to correct this issue, but it impacts code quality.

Thanks,
coast

**Comment by mancoast** [comment]
Avoid malloc() and free(), prefer the nothrow version of new with delete.

**Comment by zebastian** [comment]
can be rewritten to use the raw pointer of the QByteArray directly. 
But this change would only be cosmetically.
