### ISSUE TITLE
Never transfer ownership by a raw pointer (T*) or reference (T&) C26400 C26401

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#420]
REF: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-raw
hundreds of cases exists within our code.  This will require case-by-case examination.

> Reason
> 
> If there is any doubt whether the caller or the callee owns an object, leaks or premature destruction will occur.
> 
> 

![image](https://user-images.githubusercontent.com/7040493/32252866-25045bba-be6e-11e7-9867-6b5005da6452.png)

**Comment by mancoast** [comment]
Additional 100 warnings C26401 exist:
![image](https://user-images.githubusercontent.com/7040493/32252988-e7a6f164-be6e-11e7-9819-a202aeac8e03.png)

**Comment by mancoast** [comment]
Warning	C26400	Do not assign the result of an allocation or a function call with an owner<T> return value to a raw pointer, use owner<T> instead.
Warning	C26401	Do not delete a raw pointer that is not an owner<T>.

**Comment by zebastian** [comment]
I dont mind adding a little "sugar icing" on the code, to make it more explicit for compiliers, but we should make sure we dont use any language constructs of too new cpp versions, so older cpp compilers still work.
I think the current minimal version is c++11.

**Comment by GordonHarley** [comment]
This is easily fixed with unique_ptr or shared_ptr (what Owner(T) is based on and interchangeable with) depending on needs,  which have been around since C++11.   They're not syntactic sugar, they're things that let you not worry about whether you forgot to delete something when working on a huge project.

**Comment by zebastian** [comment]
Hmm maybe i judged too fasted, since stray pointers is a problem which occassionally hits us on the project.

**Comment by buddhi1980** [comment]
Conversion on all allocations with "new" to smart pointers is still on-going. 
However allocation of Qt objects have to stay as it is, because Qt manages freeing of memory when parents of widgets are destroyed.

**Comment by buddhi1980** [comment]
Eliminated as many direct new/delete operators as it is possible. All new operator for QObjects are kept, because they are managed by object hierarchy (parents delete childs)
