### ISSUE TITLE
A raw pointer (a T*) is non-owning C26402

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#421]
REF:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-ptr

> Reason
> 
> There is nothing (in the C++ standard or in most code) to say otherwise and most raw pointers are non-owning. We want owning pointers identified so that we can reliably and efficiently delete the objects pointed to by owning pointers.
> 
> 

![image](https://user-images.githubusercontent.com/7040493/32253025-1621a3b8-be6f-11e7-882d-505de9233648.png)

**Comment by mancoast** [comment]
Return a scoped object instead of a heap-allocated if it has a move constructor.

**Comment by buddhi1980** [comment]
Eliminated as many direct new/delete operators as it is possible. Used smart pointes from std lib. All new operator for QObjects are kept, because they are managed by object hierarchy (parents delete childs)
