### ISSUE TITLE
Avoid calling new and delete explicitly C26409

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#422]
REF: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-newdelete
~600 cases of new/delete exists within the codebase.  These instances require deeper analysis and recommendations.  Any input is appreciated.

> Reason
> 
> The pointer returned by new should belong to a resource handle (that can call delete). If the pointer returned by new is assigned to a plain/naked pointer, the object can be leaked.
> 
> 

![image](https://user-images.githubusercontent.com/7040493/32253158-d77b7ae8-be6f-11e7-979e-30f4d367b29d.png)

**Comment by mancoast** [comment]
Avoid calling new and delete explicitly, use std::make_unique<T> instead.

**Comment by buddhi1980** [comment]
Partially done in commit https://github.com/buddhi1980/mandelbulber2/commit/1d30b32d507f98491370ba73b49c932507bd6c0e

**Comment by buddhi1980** [comment]
Eliminated as many direct new/delete operators as it is possible. Used smart pointes from std lib. All new operator for QObjects are kept, because they are managed by object hierarchy (parents delete childs)
