### ISSUE TITLE
qInfo() Is missing for some QT versions

### ISSUE THREAD

**Issue by MysaaJava** [buddhi1980/mandelbulber2#425]
##### System information (version)
I'm on Debian Jessie and I compile with gcc

##### Detailed description

With the versions of QT < 5.5, the qInfo() method used in audio_track.cpp around lines 108-110 is not defined and makes the compilation crash.
I personally resolved the problem by adding at the file top :
`#if QT_VERSION < QT_VERSION_CHECK(5, 5, 0)
#define qInfo qDebug
#endif`
It worked for me and I ask you to add it to a future version
Thanks for listening to me and sorry for my bad English (I'm French)

**Comment by zebastian** [comment]
looks reasonable, thanks @MysaaJava 
I just added it in latest release: https://github.com/buddhi1980/mandelbulber2/commit/e9c647123c7f11a7f474fe4e9848eafb12476af1
