### ISSUE TITLE
Differences between V2.11 and dev V2.12

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#426]
- mandelbulber2 =>dev v2.12
- Operating System / Platform => Windows 64 Bit
- Compiler => Appveyor

 Detailed description

 differences in rendering between v2.11 and dev v2.12
 v2.11 and dev v2.12  renders are the same for c++ deltaDE
all other combinations are broken i.e
a) deltaDE openCL
b) analytical DE c++
c) analtyical DE openCL
there is more than one issue involved here and I have not been able to find them

```
# Mandelbulber settings file
# version 2.12
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 8.67158259190073 -14.85117454702644 9.173615182314192;
camera_distance_to_target 1.097372174263004;
camera_rotation 47.35365558311759 -40.36771108775869 -31.63459596881792;
camera_top -0.7609527632409318 -0.01220387374116063 0.6486924984780542;
DE_factor 0.7;
delta_DE_function 1;
delta_DE_method 1;
flight_last_to_render 0;
formula_1 90;
fov 0.3;
hdr true;
keyframe_last_to_render 0;
linear_DE_offset 1.98;
mat1_coloring_palette_offset 1.6;
mat1_is_defined true;
target 8.056595941882053 -14.28474659126287 8.462857502035588;
[fractal_1]
info true;
transf_function_enabledAx_false true;
transf_function_enabledBx_false true;
transf_function_enabledy_false true;
transf_scaleB_1 0.503978;
```

**Comment by buddhi1980** [comment]
I have found the problem. In many places you use fractal->transformCommon.constantMultiplierB111 in a sum instead of multiply. Default value for constantMultiplierB111 is {1,1,1,1} so if you write:
z = constantMultiplierB111 + sometning, then z.w = 1 !!!

I will correct all formulas where there is this problem

**Comment by buddhi1980** [comment]
Formulas affected: TransfPwr2PolynomialIteration, CollatzModIteration, MengerPwr2PolyIteration

Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/390c1e09241af0e35bee56afc384c8677b4b888c

Now works the same like in 2.11-1 and also works in OpenCL mode.
