### ISSUE TITLE
anti-aliasing setting doesnt seem to do anything when rendering with openCL

### ISSUE THREAD

**Issue by aombk** [buddhi1980/mandelbulber2#428]
##### System information (version)

- mandelbulber2 => mandelbulber2-win64-2.12-alpha7
- Operating System / Platform => Windows 10 64 Bit

##### Detailed description

anti-aliasing setting doesnt seem to do anything when rendering with openCL

**Comment by buddhi1980** [comment]
It's not a bug. Antialiasing is not implemented yet. 
However I forgot to add info in Preferences dialog.

**Comment by aombk** [comment]
alright, thanks. i thought i should let you know, just in case :)

**Comment by buddhi1980** [comment]
Fully implemented in commits: https://github.com/buddhi1980/mandelbulber2/commit/ae1390d1cd76d3faea8629c6a58f65815438ac26 https://github.com/buddhi1980/mandelbulber2/commit/53778fe330cf5f60def88326440df1c146246d61 https://github.com/buddhi1980/mandelbulber2/commit/9c9ee424bad1d8277a7539ef8274809bdee0fdfb
