### ISSUE TITLE
Update MSVC Version of binary for 2.12

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#429]
https://github.com/buddhi1980/mandelbulber2/blob/95b9ef1f7edcd05ca0282881ebc51cd1bbefc2f7/mandelbulber2/msvc/mandelbulber2.rc#L87

**Comment by mancoast** [comment]
@buddhi1980 when we do the actual version tag, we also need to update the msvc resources

**Comment by buddhi1980** [comment]
I'm going to release the proram as soon as possible. Correct version number of the program should be just 2.12.0 (without alpha). So please correct version in msvc configuration files.
I have just changed version number in system.hpp
Version tag on Github will be updated when I will create release.

**Comment by buddhi1980** [comment]
By the way I forgot to update README files

**Comment by mancoast** [comment]
resolved https://github.com/buddhi1980/mandelbulber2/commit/774a66662930d9c45b8c2c29ca521f39e887a1f9
