### ISSUE TITLE
checkbox to always rebuild opencl kernel

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#434]
this is useful for testing modified opencl files. (ex. formula experiments)

**Comment by mancoast** [comment]
if (!(hashProgram == lastProgramHash && hashBuildParams == lastBuildParametersHash))

==> always rebuild Boolean?

**Comment by buddhi1980** [comment]
It could not work properly because of graphics driver build cache. Even if
you change OpenCL code, you need to flush cache manually. If we want to
have this option we need to figure out how to flush this cache from the
program.

05.12.2017 4:40 PM "mancoast" <notifications@github.com> napisał(a):

**Comment by mancoast** [comment]
ok thanks for the hint, i will research this cache flush for opencl.  If we
get this rolling, it offers a quick way to edit formulas and redraw object
within the app without recompile

On Tue, Dec 5, 2017 at 10:46 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
By the way this will be very needed when we implement built-in editor for fractal formulas

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/a4325fe4dd8df494bf2ccb8383c17e81ef122391

All we need now is the checkbox on GUI

**Comment by mancoast** [comment]
Confirmed with three major platforms [NVIDIA, AMD, INTEL]
![image](https://user-images.githubusercontent.com/7040493/33669104-8c101908-da6f-11e7-8373-a778398939f9.png)
