### ISSUE TITLE
Tiff export broken

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#436]
Saving of TIFF images under Windows produces following error:
"Deflate compression support is not configured"

http://www.fractalforums.com/bug-reporting-b231/tiff-export-broken/new/#new

@mancoast Is it possible that there was something wrong in configuration when tiff library was compiled in msvc?

**Comment by mancoast** [comment]
I am not sure, need to investigate.

**Comment by mancoast** [comment]
TIFF library was not compiled with ZIP support.

**Comment by mancoast** [comment]
resolved https://github.com/buddhi1980/mandelbulber2/commit/33a5d0332e2615fd0c1f95796a9ab37a20757666

**Comment by rikardfalkeborn** [comment]
Could this have been found by Appveyor if there was a test case that tried saving an image in all the supported formats?

**Comment by mancoast** [comment]
It would be good addition to generate test cases using CLI scripts.
Perhaps create another GH note to serialize suggested feature?

**Comment by zebastian** [comment]
we should incorporate this into the mandelbulber internal test cases:
```mandelbulber --test```
see
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/test.hpp
