### ISSUE TITLE
Add tests for saving images

### ISSUE THREAD

**Issue by rikardfalkeborn** [buddhi1980/mandelbulber2#437]
In #436, it was reported that tiff export was broken on Windows.

I propose to add a test that saves images in all supported formats and verifies that everything goes ok (ideally, it would save the image, read it back and compare that the images are the same).

**Comment by TasMania17** [comment]
I suggest the more widely used formats like PNG and JPG produce better results. I'm wondering why you would export in a format developed for image scanners? I put EXR in the same category. How can they be published online without EXR capabilities implemented on the web server?

**Comment by zebastian** [comment]
EXR and TIFF can save more precision values and in case of EXR the format can save arbitrary image channels (like z-buffer and normal buffer). This is the professional industry standard for image processing pipelines (for example post production with after effects or NATRON).

**Comment by zebastian** [comment]
basic tests added in this commit: https://github.com/buddhi1980/mandelbulber2/commit/8904f25102d803fef51b886f9e7c67695dca0205

**Comment by zebastian** [comment]
there are more types of image specific tests which could be added to validate the mandelbulber internal save mechanism but the general problem about broken library should be covered with latest commit.

**Comment by mancoast** [comment]
Thanks z!

**Comment by TasMania17** [comment]
Thanks zebastian, I got it wrong.
