### ISSUE TITLE
Cast out of range in ConvertNormalTo8Bit

### ISSUE THREAD

**Issue by rikardfalkeborn** [buddhi1980/mandelbulber2#438]
Consider the following code in `cimage.cpp`:

```c++
quint8 *cImage::ConvertNormalTo8Bit() const
{
	if (!opt.optionalNormal) return nullptr;
	for (quint64 i = 0; i < quint64(width) * quint64(height); i++)
	{
		normal8[i].R = quint8(normalFloat[i].R * 255.0f);
		normal8[i].G = quint8(normalFloat[i].G * 255.0f);
		normal8[i].B = quint8(normalFloat[i].B * 255.0f);
	}
	return reinterpret_cast<quint8 *>(normal8);
}
```
If any of normalFloat[i].{R,G,B} are above 1.0, this will have undefined behaviour since the cast will be outside the range of quint8.
normalFloat is set in cImage::PutPixelNormal(), which is for example called in render_worker.cpp, where normalFloat is calculated as follows:

```c++
CVector3 normalRotated = mRotInv.RotateVector(normal);
normalFloat.R = (1.0 + normalRotated.x) / 2.0;
normalFloat.G = (1.0 + normalRotated.z) / 2.0;
normalFloat.B = 1.0 - normalRotated.y;
```
If normalRotated.y is negative normalFloat.B will be larger than one, and the subsequent calls to cImage::ConvertNormalTo8Bit() will trigger the undefined behaviour. I didn't find a guard for this, and it can be triggered by running `Test::testImageSaveWrapper()` (that's how I found it).

Is this a real problem? Potentially yes, the following test program prints 255 with Gcc 7.2.1 and 0 with Clang 5.01:
```
#include <iostream>

int main(void)
{
        std::cout << (int)(unsigned char)256.0f << "\n";
}
```
I wasn't able to figure out if the generated image was different or not though.

**Comment by buddhi1980** [comment]
There is no way for normalFloat to be higher than 1.0 as it is a normalized vector. Correct me if I'm wrong.
```
					CVector3 normalRotated = mRotInv.RotateVector(normal);
					normalRotated.Normalize();
					normalFloat.R = (1.0 + normalRotated.x) / 2.0;
					normalFloat.G = (1.0 + normalRotated.z) / 2.0;
					normalFloat.B = (1.0 - normalRotated.y) / 2.0;
```
