### ISSUE TITLE
setting first and last frame to render parameter problems

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#445]
there may be still some random problem  with setting first and last frame to render parameter.  It was when I entered a start at 30   (it automatically changed back to 3), and I could not enter a number greater than 100 for stop. Unfortuatelly I cannot remember the exact settings and order of steps that produced it. I was changing a lot of things. This bug is not new, it was happening back when we were implementing audio-anim, and I had mistakenly thought it had been fixed. 

Steve Sinks comments
Graeme, yes I have that problem constantly. As soon as you add more keyframes, it won’t let you increase the range past what it was before. It happens constantly, so I think it’s reproducible. I’ve had to restart several times to fix it.

**Comment by mclarekin** [comment]
One symptom is that, say, i enter 800 and it changes back to 400 automatically, but I can get the correct setting by rolling the spinbox, and I think with the new  sliders I can double OK. I will have a closer look  when I am back in Ubuntu

**Comment by buddhi1980** [comment]
@mclarekin . Check if now works properly. I have found the problem.

**Comment by mclarekin** [comment]
"reset to default" will correctly update parameter

**Comment by mclarekin** [comment]
and after the reset, the  last_frame_to-render updates correctly  when
frames_per_keyframe is adjusted.

I note that the tootip says default value: 9999999.   If I
remove keyframe_last_to_render 0; from the  settings file, it will still
load being set to 0. BUT now it update as i add keyframes, so I am
wondering if this problem is because of "keyframe_last_to_render 0" being
in the preset settings file.  h'mmmm

**Comment by buddhi1980** [comment]
Even when it is zero, all frames will be rendered (this value is treated as ALL frames)

**Comment by mclarekin** [comment]
also "keyframe_last_to_render 0" has been removed from all standard
presets, so they will no longer load as 0

On Sun, May 27, 2018 at 8:55 PM, Krzysztof Marczak <notifications@github.com
