### ISSUE TITLE
Odd implementation of vectorMod in opencl_algebra.h

### ISSUE THREAD

**Issue by GordonHarley** [buddhi1980/mandelbulber2#446]
##### Type
Optimization. 

##### System information (version)
Mandelbulber 2 Current Release Version

##### Detailed description
vectorMod(float3 vector1, float3 vector2) is defined to return the dividend if the divisor is < 0 in this function.  However, this is not the behavior of the modulus operator or  fmod function in C, and alternate behavior isn't mentioned in the OpenCL standard that I could find.  The modulus operator produces identical results for mod in C.   Results from C11 are below.   I want to make sure this is intentional, because just doing fmod(vector1, vector2) would be faster via being a built-in and avoiding the branching for <0 checks, which are a performance hit in OpenCL, as well as up to 2 fmod calls.   

##### Steps to reproduce in C  (MSVC, Clang 5.0 release)
_Included since OpenCL is based on C standard_
> clang mod.c -o mod.exe
> cl mod.c /TP

#include <stdio.h>
#include <math.h>

int main(void)
{
	printf("Integer: %d\n", 7 % -4);
	printf("Double: %e", fmod(7.0f, -4.0f));
}

##### Ouput
Integer: 3
Double: 3.000000e+00

**Comment by mancoast** [comment]
Great topic for a PR 😎

**Comment by buddhi1980** [comment]
It is specialized function needed for Repeat() function. It cannot be used standard fmod function.
