### ISSUE TITLE
Memory leaks in ImageFileSaveExr::SaveEXR

### ISSUE THREAD

**Issue by rikardfalkeborn** [buddhi1980/mandelbulber2#448]
In `ImageFileSaveExr::SaveEXR()` there are a couple of buffers allocated that are never freed. The lines typically look like
```
char *buffer = new char[uint64_t(width) * height * pixelSize];
```
The solution is obviously to add `delete[]` buffer but I was unsure how long the buffers needs to be valid (else I'd send a PR). Can the buffers be deleted after the call to `frameBuffer.insert()` or do they have to be valid until they had been written in `file.writePixels()` (I would have assumed the latter case, but neither address sanitizer or Valgrind complained when I tried deleting right after the call to `frameBuffer.insert()`).

The memory leaks can be seen by running `Test::testImageSaveWrapper()`.

**Comment by buddhi1980** [comment]
Fixed. Now there are used std::vector instead of new operators.
