### ISSUE TITLE
Double dot in exported file 

### ISSUE THREAD

**Issue by maaw123** [buddhi1980/mandelbulber2#452]
##### Steps to reproduce
Run the following command from command line
$mandelbulber2 -n materials/diamond.fract -f jpg

Output produced:
Mandelbulber 2.12-1
Log file name: /home/xxx/.mandelbulber_log.txt
Detected 4 CPUs
Default data hidden directory: /home/xxx/.mandelbulber/
Default data public directory: /home/xxxx/mandelbulber/

Saving JPG: Finished [#############################################################################################################################]
Image saved to: /home/xxx/mandelbulber/images/diamond..jpg

The double dots in diamond..jpg are a bit problematic.

-->

**Comment by buddhi1980** [comment]
Thanks for the report, but this problem was already fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/27cf4cc766bda8c5a0a300d511997790cadaffd0

@maaw123 Try to compile actual code from repository
