### ISSUE TITLE
Enable AppImage Distribution

### ISSUE THREAD

**Issue by ElCoyote27** [buddhi1980/mandelbulber2#453]
Hi,
I was trying to locate a mandelbulber2 AppImage but it seems the archives were removed from the SuSE servers. Is there anywhere else to obtain an AppImage from?
Thanks,
Vincent

**Comment by zebastian** [comment]
@lachs0r the link to the appimage of mandelbulber is dead: https://software.opensuse.org//download.html?project=home%3Alachs0r%3Amandelbulber2&package=mandelbulber2
Can you have a look / is this intended?
Best, sebastian

**Comment by probonopd** [comment]
Can you please build one (e.g., using Travis CI) and put it on https://github.com/buddhi1980/mandelbulber2/releases? Let me know if you'd like a pull request.

**Comment by buddhi1980** [comment]
@probonopd, pull request for automatic building using TravisCl will be very appreciated. Linux users will be very happy

**Comment by probonopd** [comment]
Hi @buddhi1980, I tried to create a PR but I am running into an issue where it seems that `make install` does not work on Linux:

```
make: Nothing to be done for `install'.
```

Would you be able to enable  `make install` as outlined [here](https://github.com/probonopd/linuxdeployqt#fix-for-make-nothing-to-be-done-for-install)? 

Alternatively, we need a directory with this structure:

```
appdir/usr/bin/mandelbulber2
appdir/usr/share/applications/mandelbulber2.desktop
appdir/usr/share/icons/hicolor/256x256/mandelbulber2.png
...
```

Thanks.

**Comment by buddhi1980** [comment]
I will implement make install

**Comment by buddhi1980** [comment]
Just added install option in commit https://github.com/buddhi1980/mandelbulber2/commit/52981d7f82415ba9202ef69e197a9aad4dca3a1b

Let me know if it works for appimage

**Comment by probonopd** [comment]
Thank you very much 👍 it's almost working, but one thing doesn't seem correct:

```
install -m 644 -p /home/travis/build/probonopd/mandelbulber2/mandelbulber2/deploy/share/mandelbulber2/icons/mandelbulber.png appdir/usr/share/icons/hicolor/256x256/apps/mandelbulber2.png/
(...)
appdir/usr/share/icons/hicolor/256x256/apps/mandelbulber2.png/mandelbulber.png
```

https://travis-ci.com/probonopd/mandelbulber2/jobs/186594809#L8110
https://travis-ci.com/probonopd/mandelbulber2/jobs/186594809#L9399

The name of the icon can either be `mandelbulber.png` or `mandelbulber2.png`, as long as the desktop file has `Icon=mandelbulber` or `Icon=mandelbulber2`, respectively.

But there must not be a subdirectory inside `appdir/usr/share/icons/hicolor/256x256/apps/`.

**Comment by buddhi1980** [comment]
Just corrected installation of mandelbulber icon file.

**Comment by buddhi1980** [comment]
I have updated README file with information about compilation options and "make install" (section 5.). 
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/deploy/README
It can help you to prepare appimage packages in correct way. The program need to be configured to look for data files in correct location (absolute or relative).

**Comment by probonopd** [comment]
> The program need to be configured to look for data files in correct location (absolute or relative).

Couldn't you always look in relative paths? Or first look in absolute and then in relative paths as a fallback? Hence, it would work everywhere without the need to specifically configure anything.

**Comment by probonopd** [comment]
Now there is `appdir/usr/share/icons/hicolor/256x256/apps/mandelbulber.png` but `Icon=mandelbulber2`... either have the "2" in both places or in none.

**Comment by buddhi1980** [comment]
Under Linux recommended locations to store program files are /usr/share, /usr/local/share. Executable files should be in /usr/bin or /usr/local/bin. It is a good practice for system administrators because you can limit access rights for these folders (to not allow to run executables from share folder, or to make bin folder as read only). It allows to have different versions of programs in the same system (official version instaled from .deb in /usr, custom build in /usr/local, testing version in /tmp/test, etc..., and each instance will use own file set)
Some users will prefer to use standalone programs, which is popular under Windows and starts to be more popular also under Linux (for unskilled users or for java applications). 
In mandelbulber you can configure from where files will be loaded.
Looking for the files always in ten different locations makes loading of files much longer. This is one of main reasons why some applications need so much time to start.
You can configure the program to work with relative paths by defining SHARED_DIR_IS_APP_DIR or with option SHARED_PATH="." (or SHARED_PATH="anyOtherChildFolde")

I will correct icon name in next minutes.

**Comment by buddhi1980** [comment]
Corrected icon name in https://github.com/buddhi1980/mandelbulber2/commit/429fecc7a17cd4f1f476d34f943bde0bb47bc59a

**Comment by probonopd** [comment]
Assume the main binary is in `/usr/bin/`. Then the resources are in `/usr/share`. Which means that they are in `../share/` relative to the main binary.

Now assume  the main binary is in `/usr/local/bin/`. Then the resources are in `/usr/local/share`. Still, this means that they are in `../share/` relative to the main binary.

Now assume  the main binary is in `/some/location/wherever/bin/`. Then the resources are in `/some/location/wherever/bin/`. Still, this means that they are in `../share/` relative to the main binary.

See what I mean?

**Comment by buddhi1980** [comment]
Thanks for this idea. I will implement it as a default option. The program at start will check path for binary file (will determined by QCoreApplication::applicationDirPath()) and then generate paths for share files. This will be only for Linux. Under Windows everything still have to be different.

**Comment by probonopd** [comment]
Exactly 👍

**Comment by probonopd** [comment]
Yes, we have an AppImage https://github.com/probonopd/mandelbulber2/releases
Although I couldn't test it yet.

**Comment by probonopd** [comment]
Currently getting

```

Default data hidden directory: /home/travis/.mandelbulber/
Default data public directory: /home/travis/mandelbulber/
Error: Can't open file /usr/share/mandelbulber2/formula/ui/mandelbulb.ui
Fractal ui file can't be loaded
File /usr/share/mandelbulber2/textures/grid.png not found. Looking for the file in alternate locations
Looking for the file at grid.png
Looking for the file at /home/travis/textures/grid.png
Looking for the file at /usr/share/mandelbulber2/textures/grid.png
Looking for the file at /home/travis/mandelbulber2/textures/grid.png
Looking for the file at /usr/share/mandelbulber2/mandelbulber2/textures/grid.png
Looking for the file at /home/travis/.mandelbulber/textures/grid.png
Looking for the file at /home/travis/.mandelbulber/grid.png
Looking for the file at /home/travis/.mandelbulber/settings/grid.png
Warning: "Substitute path for /usr/share/mandelbulber2/textures/grid.png not found anywhere"
(../src/files.cpp:447, QString FilePathHelper(const QString&, const QStringList&))
```

How can I specify SHARED_DIR_IS_APP_DIR and/or SHARED_PATH so that instead of `/usr/share/mandelbulber2` it looks in `<wherever the main binary is>/../share/mandelbulber2`? Note that "wherever the main binary is" changes every time the AppImage runs.

**Comment by buddhi1980** [comment]
Today afternoon I will change it in the code to look for shared files relatively to bin/mandelbulber2. Then it will make everything easier.

**Comment by buddhi1980** [comment]
Changes implemented in https://github.com/buddhi1980/mandelbulber2/commit/284b1db10279cf1e4f6c78af8a811487fc3a9d8a Now it should run from appimage without any special qmake options. It looks for program data files in ../share

**Comment by ElCoyote27** [comment]
I just tested https://github.com/probonopd/mandelbulber2/releases on Fedora 28.. Looks very promising: The GUI came up but it complained about a missing /usr/share reference and closed afterwards. Please keep up the good work. THANK YOU!
Regards,

**Comment by probonopd** [comment]
Please retest, the latest build now includes https://github.com/buddhi1980/mandelbulber2/issues/453#issuecomment-475710271.

**Comment by buddhi1980** [comment]
It works very well! Thanks a lot! Pleas send pull request. It will go to master branch. I'm going to configure it to use Cron Job in travis ci and it will do weekly appimage builds.
When TRAVIS_EVENT_TYPE = cron the it will create appimage and upload to releases (as you did)

**Comment by buddhi1980** [comment]
By the way I have tested it with OpenCL and also works great.

**Comment by probonopd** [comment]
Please ping me once it is available for download, thanks.

**Comment by buddhi1980** [comment]
Works. It appeared in Releases
