### ISSUE TITLE
Rendering with OpenCL results in Purple Fractals

### ISSUE THREAD

**Issue by ProgrammingCube** [buddhi1980/mandelbulber2#455]
##### System information (version)

- mandelbulber2 => 2.13
- Operating System / Platform => Windows 10
- Compiler => Executable
- Vega 56 w/ OpenCL enabled
- 512Mb memory set aside for OpenCL

##### Detailed description

Quite simply, when I enable OpenCL rendering and choose the gpu as the opencl device, I do get the fractals rendered. But the textures are all purple. Not solid, but as if the surface is purple.

##### Steps to reproduce

Enable OpenCL with a Vega 56 running the latest drivers

**Comment by mclarekin** [comment]
A common question

Change to limited or full mode.

We need to add an image to the manual  showing the three modes in the
manual (and /or a tooltip pop up),

**Comment by buddhi1980** [comment]
Nobody reads user manulal. It's already written there about rendering nodes and there is a screenshot.

**Comment by ProgrammingCube** [comment]
I am sorry about this, I feel pretty dumb now.

Changing it to full or limited worked (once my computer didn't crash).

**Comment by mclarekin** [comment]
"Changing it to full or limited worked (once my computer didn't crash)."

Just checking that you have edited the registry (which is required for
Windows openCL)

If not, check in the openCL section of the manual on how to do this. This
is the common cause of win10 crashes when using GPU.

**Comment by zebastian** [comment]
@ProgrammingCube please reopen, if you still experience crash problems after @mclarekin suggestion.
