### ISSUE TITLE
two digit numbers

### ISSUE THREAD

**Issue by taurus66** [buddhi1980/mandelbulber2#456]
This is about an old annoyance, I mentioned some time before and were ignored. The "issue" is the length of fractal constant factor (>objects>global parameters and maybe some other parameters too). It is restricted to two (!) digits I think since v2. The funny fact is, that while animating this parameter (such as 0.95-1.05 in 100 frames) mb renders the finer steps (0,001 in this example). But when you try to use the result of such a step (yes, I do this frequently) you get reset to the according two digits number. This is a little ridiculous. We are working with fractals and such objects react pretty sensible on changing parameter sets in some cases. So please correct this - lets call it mismatch - for the next version.

**Comment by taurus66** [comment]
I saw the mandelbox coloring works also with two digits. This has lower priority, but should also be fixed soon.

**Comment by mclarekin** [comment]
Krzysztof, I have self assigned this. I will have a  look for remaining
decimal place issues, (boolean mode const mult, old in-line box fold and
sphere fold need updating too)

**Comment by mclarekin** [comment]
@ taurus,  do not assume it was ignored, it has simply just been missed. He successfully updated a huge number of parameter fields, (what would have taken me months), the amount missed are very few. 

But, as always,  thanks for bringing it to our attention.

**Comment by mclarekin** [comment]
commit 1b30808bf036ec3148a5b949097e6d98abf233ff should be the last of these issues relating to aux.color and const multiplier. However there will be other places in the program where decimal places and/or max parameter input will need to be updated
