### ISSUE TITLE
Enhancement to primitive groups

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#457]
Evaluate 
a) scaling of primitive group (mostly for animation)
b) primitive group locked at a position relative to the camera (for animation)

**Comment by mclarekin** [comment]
c) place center of primitive group by mouse

**Comment by mclarekin** [comment]
d) option of locking  some lights to primitive group

**Comment by mclarekin** [comment]
e)     "link scale to zoom"

**Comment by mclarekin** [comment]
we now have boolean operators :)
we have the ability to add  more complex primitives based on what has been learnt with difs. 
current thoughts are Primtives Tab displays existing basic primitives, then a sub-menu to display a selection of more complex primitives

**Comment by buddhi1980** [comment]
Primitives has to be primitives. Off course we can add more shapes bat they have to be primitive. We can add octahedron, dodecahedron, icosahedron, prism, spiral, lens,

**Comment by mclarekin** [comment]
yes  we can add more basic primitives. But how  would you like more complex primitives added, in a sub-menu?

e.g  main primitive menu :    cylinder with    length and radius parameters
sub menu:   cylinder with a lot more parameters for deforming shape, (or do we keep these types in  T>DIFS and use boolean mode)

**Comment by buddhi1980** [comment]
Then they wont be primitives and will be big mess. I think it's better to keep them as DIFS formulas and use boolean mode.
Primitives need to be as simple as it is possible. 
But as I wrote we can add more simple shapes.

**Comment by mclarekin** [comment]
cool, complex primitives will remain as T>DIFS

any new basic primitive T>DIF shapes can eventually be added to primitives. low priority

i will close this issue
