### ISSUE TITLE
Please distribute updated macOS release dmgs

### ISSUE THREAD

**Issue by pected70** [buddhi1980/mandelbulber2#458]
i cannot build the macOS app myself. Please provide updated binaries to Github. Thank You! :-)

**Comment by mclarekin** [comment]
Currently being tested :)

**Comment by mancoast** [comment]
Yea it’s definitely ready.

**Comment by mclarekin** [comment]
@ pected70, any feedback??

This may be relavent to macOS re GPU time out:
https://stackoverflow.com/questions/19632401/how-to-work-around-gpu-watchdog-timer-limitation-on-cuda-code-in-os-x?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

On Mon, Apr 16, 2018 at 2:18 AM, Krzysztof Marczak <notifications@github.com

**Comment by pected70** [comment]
@ mclarekin yes it works fine but thats not an official release. please distribute it on your website and not on a random github issue.

**Comment by mclarekin** [comment]
another tester is having problems.

currently no openCL

some instability in normal c++ mode.

Did you need to do anything extra to make it work?

What GPU do you have?

**Comment by buddhi1980** [comment]
@pected70 , it's not released officially, because we haven't finished testing. That's why the link for packages is only here.
We are getting different feedback from users and not for all it works properly.
By the way, @pected70 have you tested it with OpenCL?

**Comment by mancoast** [comment]
I tested OpenCL with success. Requires macOS 10.11 or newer.

**Comment by bermarte** [comment]
Hallo Krzysztof, I have tried the app on my mac.

I want to give you a quick impression.


First of all, mac users should be happy, it's quite positive that there's a new build at their disposal.

I wasn't able to render using openCL.

I am not sure but it seems that it is not working, is it maybe?


There is no more the installer, which I think is a good thing, it's nice that everything is packed inside the app, but the user doesn't know immediately where to find the various files that the sw needs, maybe? Anyway the approach is surely positive: everything goes inside the .dmg file.


Regarding openCL, this is what I get from my terminal (this mac is compatible with openCL 2):


ooking for the file at /Users/x/.mandelbulber/textures/grid.png

Looking for the file at /Users/x/.mandelbulber/grid.png

Looking for the file at /Users/x/.mandelbulber/settings/grid.png

Warning: File not found anywhere

(../mandelbulber2/src/files.cpp:448, QString FilePathHelper(const QString &, const QStringList &))


Critical: OpenCl ERROR:  "kernel->setArg(1) for output-buffer"  ( -38 )

(../mandelbulber2/src/opencl_engine.cpp:78, static bool cOpenClEngine::checkErr(cl_int, QString))


libc++abi.dylib: terminating

Abort trap: 6

logout

Saving session...

...copying shared history...

...saving history...truncating history files...

...completed.



Despite of what I had in mind, I wasn't able to help you guys.

I couldn't do anything else than just being busy with my stuff.

Also now is quite complicated, this month and the next one I will be very busy; nonetheless it is my intention to come back to help as soon as I will have more free time (I think in a couple of months).

It's a very, annoying and complicated situation, mine, I must say.

Best regards

B.
________________________________

**Comment by zebastian** [comment]
Issue was solved by providing release of latest version.Bugs with macos should be put in another issue, if (when) they occur...
