### ISSUE TITLE
error by compiled under linux

### ISSUE THREAD

**Issue by BogusCurry** [buddhi1980/mandelbulber2#462]
Hello ;D
I would under Linux Mint 18.3 - 64bit install mandelbulb2 2.13, but I become this error message

mv: Aufruf von stat für 'makefiles/mandelbulber2' nicht möglich: Datei oder Verzeichnis nicht gefunden
Executable file does not exist. Probably the program was not compiled properly.

I hope you can fix it ;D

Greetings
Bogus

**Comment by BogusCurry** [comment]
I have write this command ./install and here the output
https://paste.md-5.net/cifetujevi.md
and I have found in the output this error
----
dock_navigation.cpp
../qt/dock_image_adjustments.cpp: In member function ‘void cDockImageAdjustments::InitResolutionPresets()’:
../qt/dock_image_adjustments.cpp:365:52: error: no matching function for call to ‘QAction::QAction(QString)’
   QAction *action = new QAction(tr("Change preset"));

**Comment by zebastian** [comment]
Your qt version is outdated, see here for recent user with the same problem : https://fractalforums.org/mandelbulber/14/compile-errors-with-release-2-2-13/1129/msg5856#msg5856

**Comment by mclarekin** [comment]
BogusCurry. Did you get it to run?

**Comment by BogusCurry** [comment]
@mclarekin No, I have install the new version qtcreator 5.9.1, then I have install mandelbulb2, but I becomes the same error message. I not know, what I make wrong ;(

**Comment by zebastian** [comment]
@BogusCurry can you run the following in terminal and give the output?
```qmake -v```

**Comment by buddhi1980** [comment]
@BogusCurry , you have to update not only Qt Creator but also Qt libraries. I'm not sure what are correct package names on Mint, but for Debian or Ubuntu they are:
qt5-default qttools5-dev qttools5-dev-tools qtmultimedia5-dev libqt5multimedia5-plugins

**Comment by BogusCurry** [comment]
Thanks @buddhi1980, but is very difficult is to found the right libarys. But in next days comes a new version of Linus Mint, Version 19. I hope there is the new libarys in the version ;D

**Comment by rdcklinux** [comment]
add menu QObject has second parameter:

QAction *action = new QAction(tr("Change preset"), menu); 

for QT version Qt 5.5.1


Documentation: http://doc.qt.io/qt-5/qaction.html#public-functions

**Comment by zebastian** [comment]
@BogusCurry we actually added the second parameter recently, so this should be compilable with qt5. 5 now
Please reopen if still present
