### ISSUE TITLE
Global Parameters "Initial w axis value"  damages primitive sphere in c++ and openCL 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#463]
Global Parameters "Initial w axis value"  damages primitive sphere in c++ and openCL ( maybe an old thing that had not been noticed.)  4D r somewhere??

**Comment by buddhi1980** [comment]
I cannot reproduce this problem. Maybe it's already corrected.
@mclarekin can you provide settings where it is visible?

**Comment by mclarekin** [comment]
H'mmmmm

I cannot reproduce the image i remembered,   but I do note that i had my
maxiter was set wrong which caused one problem.

I will close this issue.

(And do some more 4D testing in the future)

On Wed, May 23, 2018 at 5:58 AM, Krzysztof Marczak <notifications@github.com
