### ISSUE TITLE
openCL on intel platform, HD4600 GPU: Investigate performance.

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#465]
Krzysztof : "About Intel GPU, I have never been able to run something more sophisticated than "fast" engine"

 In V2.13.2 I had not tested it with anything other than simple stuff. However using my intel HD4600 GPU, I can render in limited and full.

Dev V2.14 currently seems to perform worse than V2.13.2. It can use up to 4GB compiling, then drops back to under 400MB

Investigate performance once all openCL features have been implemented.

**Comment by mclarekin** [comment]
Uses large amount of memory with the initial compile once I have changed preference to that GPU.
Boolean was possibily enabled ???  I would guess that boolean was possibly on, but I cannot be sure.
I will  do some testing.

**Comment by mclarekin** [comment]
various notes from testing win10 64 dev v2.14 with Intel Platform Intel HD4600.

Using c++ and AMD openCL everything works correctly. AMD compiles fast. 
While  program is stationary there are some random 0.1% CPU events.
It may take a couple of minutes on my computer for the memory fluctuations to stop after render complete ( openCL AMD.)

a) intel platform HD4600 takes a long time to compile, and uses a lot of memory up to 4GB maybe  alot of the time averaging 2500MB. When it finally compiles, the memory usage drops back to normal, and the program renders fast and correctly. Each time I change between fast,limited and full the long compiling is reproduced.

b) enable boolean, then the HD4600 will cause Windows to advise that the program has stopped working.

c) if a user pushes render before the openCL is compiled, memory use goes to 4 -5 GB , and the computer may freeze.

**Comment by buddhi1980** [comment]
Boolean mode generates a lot of branches in the code. This is the reason why OpenCL compiler consumes a lot of memory. Probably AMD and NVidia compilers are better optimized and use less memory. With my NVidia it needs 1500MB RAM to compile kernels in boolean mode.

**Comment by mclarekin** [comment]
I will investigate more in the future.  Current openCL status on this laptop with dev V2.14:
tested on Full with a simple MengerMbulb boolean
- AMD platform and card  works correctly
- intel platform i7 CPU  works correctly
- intel platform HD4600 takes a long time to compile but then works , but enabling Boolean will freeze program

**Comment by mclarekin** [comment]
Rechecking, for any change in behavior.  I did not save previous test settings, these settings are probably require less compiling.

- AMD platform and card continues to work correctly (except possible issue with fast relaxed maths unchecked)

- intel platform i7 CPU behavior change, now crashes program.  Expect random behavior = normal.

- intel platform HD4600 as expected takes a long time to compile but then works ,  enabling Boolean did not freeze program. Assume change is new settings (compile memory only went up to 1GB)


# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operators true;
camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
camera_distance_to_target 2.761725137257712;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 70;
formula_2 119;
formula_position_2 2 0 0;
formula_scale_2 0.125;
keyframe_last_to_render 0;
mat1_fractal_coloring_algorithm 2;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_i_start_value 1;
mat1_fractal_coloring_iter_group_enabled_false true;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_rad_div_de_squared_false true;
mat1_fractal_coloring_rad_div_log_de_false true;
mat1_is_defined true;
mat2_is_defined true;
mat2_name blue plastic;
mat2_surface_color 0000 0000 ff00;
mat2_use_colors_from_palette false;
primitive_sphere_1_enabled true;
primitive_sphere_1_material_id 2;
raytraced_reflections true;
[fractal_1]
transf_addition_constant -0.7 0 0;

**Comment by zebastian** [comment]
@mclarekin can you check again?
@buddhi1980 Maybe add the list of tested gpus to the Readme?

**Comment by mclarekin** [comment]
I  tried it the other day, 4GB ram in compiling HD4600, but I ended process  before it finished compiling.
Next time I am in win10 i will do all the combinations to see if there is any change in behavior, i suspect there will be no change

**Comment by buddhi1980** [comment]
@zebastian We can add such a list to README. 
@mclarekin In general Intel OpenCL drives is not so good. On my system it also compiles OpenCL programs much longer than NVidia driver. On most of settings it crashes. It is only possible to render simple settings (e.g. default Mandelbulb)

**Comment by Toys0125** [comment]
So just to say that I have an old system that has a GT 220 and it shows up in OpenCL tab (only version 1.1 of OpenCL and SM 2.2) and it tries to compile but it will keep eating RAM until it runs out spitting out of memory allocation. Just want to say that.

**Comment by mclarekin** [comment]
@Toys0125.  a long time ago, you have probably figured it out by now. Mandelbulber requires openCL ver 1.2, as a minimum

**Comment by mclarekin** [comment]
This is now very out of date,  and  it is unlikely that I will ever use this old hardware again
