### ISSUE TITLE
There is not possible to select image format for queue in GUI mode

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#47]
There is missing widget to select image format.

**Comment by zebastian** [comment]
also add override option?
if not selected, use filetype given by keyframe / flight animation.
what about default filetype for still?

**Comment by buddhi1980** [comment]
For animation it's not a problem, because it's defined in animation settings file. Overwrite is not needed.
For still frames we need combobox similar like we have for animation.

**Comment by buddhi1980** [comment]
Done by commit a430556
