### ISSUE TITLE
distance fog - a volumetric effect?

### ISSUE THREAD

**Issue by taurus66** [buddhi1980/mandelbulber2#470]
Here's annother observation. In first alpha with custom de step muliplier for volumetric effects it seemed to change/enhance distance fog as well. I was pretty happy, because I have several parameters where distance fog falls into stripes. Lowering de step in general might solve this for the cost of increased rendering times. The custom de step almost costs nothing, so mybe you can reactivate this function?
Cheers
taurus

**Comment by buddhi1980** [comment]
Are you referring to the problem visible in this settings?:
There is reduced custom DE step and stripes are visible - when it is 1 and main DE multiplier is reduced there is no stripes.
If this is what you mean, I have to look why stripes are visible.

```
# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
background_color_1 0000 0000 0000;
background_color_2 0000 0000 0000;
background_color_3 0000 0000 0000;
camera 1,208160086551804 -3,75263930668849 2,369782789541913;
camera_distance_to_target 3,294371008872985;
camera_rotation 21,3872787710714 -26,33122833110827 1,706062416538669;
camera_top -0,133959442688985 0,4236886787912361 0,8958475155843172;
delta_DE_function 2;
fake_lights_enabled true;
fake_lights_intensity 0,776247;
fake_lights_max_iter 3;
fake_lights_min_iter 0;
fake_lights_orbit_trap 2,5 0 0;
fake_lights_visibility 2,95121;
fake_lights_visibility_size 7,5;
flight_last_to_render 0;
formula_1 7;
glow_enabled false;
keyframe_last_to_render 0;
mat1_coloring_palette_offset 8,210000000000001;
mat1_is_defined true;
target 0,1314488066710412 -1,003399311571039 0,9085324300459983;
view_distance_max 6,633346777152619;
volumetric_fog_colour_1_distance 0,930943564331112;
volumetric_fog_colour_2_distance 1,861887128662224;
volumetric_fog_density 15,83821665564294;
volumetric_fog_distance_factor 1,861887128662224;
volumetric_light_DE_Factor 0,0625;
[fractal_1]
alpha_angle_offset 90;
beta_angle_offset 90;
IFS_rotation_enabled true;
mandelbox_scale -2;
power 2;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;
```
![image](https://user-images.githubusercontent.com/11696990/39971040-ea30acda-56f4-11e8-8071-7dc416a045de.png)

**Comment by taurus66** [comment]
No, not exactly. I'll have a look at the archives.

**Comment by taurus66** [comment]
This is a synthetic one, as I incresed de step afterwards and the fractal does not render proper too. But I have some, with de step up to 4 that render nice for animations, but the fog does not. In animations, reduced render times, can easily spare you one day. Or was I wrong with my assumption, that alpha did use custom de step for distance fog?

`# Mandelbulber settings file
# version 2.13
# only modified parameters
[main_parameters]
ambient_occlusion 1,55;
ambient_occlusion_enabled true;
ambient_occlusion_quality 5;
aux_light_position_1 3 -3 -3;
aux_light_position_4 0 -1 3;
aux_light_volumetric_intensity_1 100;
aux_light_volumetric_intensity_2 100;
aux_light_volumetric_intensity_3 100;
aux_light_volumetric_intensity_4 100;
background_color_1 0e0e 0404 0000;
background_color_2 0e0e 0404 0000;
background_color_3 0e0e 0404 0000;
basic_fog_color ffff 0000 185d;
basic_fog_visibility 1,023292992280754e-16;
camera -2,117080451539587 -1,852030540282977 -1,229310559766034;
camera_distance_to_target 0,03749999999999995;
camera_rotation -86,07919281880378 -75,26600698743651 -35,11447552516405;
camera_top 0,7499228200495813 0,6279595887193464 0,2080445118341566;
DE_factor 2,5;
DE_thresh 1,2;
delta_DE_function 2;
detail_level 1,8;
DOF_focus 1,230268770812381e-12;
DOF_radius 21,4;
file_lightmap C:\Users\taurus\mandelbulber\textures\DH-445LL.jpg;
flight_last_to_render 0;
fog_color_1 ff3c ffff da65;
fog_color_2 dccf bc3d 7a7a;
fog_color_3 586f 3228 253c;
formula_1 8;
fov 0,8;
fractal_constant_factor 0,9 0,9 0,9;
glow_color_1 bfec 4093 00af;
glow_color_2 d0d0 8888 3838;
glow_intensity 0,9453125;
image_height 2048;
image_width 1536;
iteration_fog_color_1 ff3c ffff da65;
iteration_fog_color_1_maxiter 115;
iteration_fog_color_2 dccf bc3d 7a7a;
iteration_fog_color_2_maxiter 231;
iteration_fog_color_3 586f 3228 253c;
julia_c -1,90425973890175 -1,67208875880457 -1,15419895795856;
keyframe_last_to_render 500;
legacy_coordinate_system true;
limit_min -10 -1,85210383854708 -10;
main_light_alpha -60;
main_light_beta -35;
main_light_volumetric_intensity 100;
mat1_coloring_palette_offset 104,1;
mat1_coloring_palette_size 255;
mat1_coloring_random_seed 212071;
mat1_coloring_speed 100;
mat1_is_defined true;
mat1_surface_color_palette 992d07 992d07 992d07 9a2e08 9a2d07 9a2e07 9a2e07 9a2e07 9b2f08 9b2f08 9c3009 9d310a 9d310a 9d310a 9e320b 9e340c 9f350c a0360c a1370d a3390f a3390f a43a10 a63d10 a63f12 a74013 a94215 ab4515 ac4817 ae4a18 b04c1a b24e1c b4501c b4531e b75621 b85921 bb5b24 be5f25 c06127 c4672a c86b2e cb7231 cf7835 d47d38 d8813a da863e dd8b41 e29046 e49347 e7984b e99a4b eb9c4d ec9f4d eda04f eea14f eea14f eca04e eba150 e8a151 e3a252 dda053 d8a156 d0a058 c8a05a bfa05d b8a060 aea063 a5a064 9d9f66 959f69 8e9f6b 879f6d 7f9f6e 7b9f71 749e72 709f74 6c9f76 689f77 669e77 659f77 659f77 649e76 649e78 629c76 629a75 5f9772 5c9471 5a906e 568c6c 538667 4f8164 4b7c62 47775e 42725a 3f6c57 3c6753 376251 335d4c 2f5848 2f5548 2c5245 294f44 274b41 254841 23463f 20433c 1e403b 1e3e39 1c3c37 1a3a35 193735 173533 163432 153331 143232 123030 112f2d 102e2e 102c2d 102c2d 0f2b2c 0f2b2e 0d292c 0d292c 0d292c 0c282b 0c282b 0c282b 0c282b 0c282b 0c282b 0c282b 0c282b 0c282b 0d292c 0d292c 0e2a2b 0e2a2b 0f2b2c 0f2c2d 102d2d 102e2e 112f2f 123030 143232 153331 163432 173533 193936 1a3a35 1c3c37 1e3e39 1f413b 20433c 23463f 254841 274b41 294f44 2c5245 2f5548 2f5849 335c4c 376250 3c6753 406d58 42725a 47775f 4b7d62 508265 528868 568c6c 5a906e 5c9471 5f9772 629a75 639c76 649e77 649e76 659f77 669e77 669e77 689f77 6c9f76 709f75 749e72 7b9f71 7f9f70 879f6d 8e9f6b 959f69 9d9f66 a5a064 aea061 b7a05f bfa05d c7a05a d0a058 d8a156 dea053 e3a252 e7a151 eaa250 eda04f eea14f eea14f eca04e ec9f4e eb9c4d e99a4b e6974a e49347 e18f44 dd8b41 da863e d5813a d37c37 cf7735 cb7132 c86b2e c4672a c06127 be5f26 bb5c24 b85921 b75621 b4531e b4501e b24e1c af4b19 ae4a19 ac4817 ab4515 a94215 a84114 a63f12 a63d10 a53c0f a3390f a2380e a1370d a0360c 9f350b 9e340c 9e320b 9e320b 9c3009 9c3009 9c3009 9c3009 9b2f08 9a2e08 9a2e08 9b2e08 9a2c07 9a2c07 9a2e07 992d07;
mat1_transparency_index_of_refraction 0;
mat1_transparency_of_interior 1e-10;
N 350;
penetrating_lights false;
random_lights_intensity 1;
random_lights_number 0;
shadows_cone_angle 2;
smoothness 3;
target -2,107565332415517 -1,851378392940442 -1,265577448409787;
volumetric_fog_colour_1_distance 0,0005;
volumetric_fog_colour_2_distance 0,001;
volumetric_fog_density 0,3;
volumetric_fog_distance_factor 0,002;
volumetric_fog_enabled true;
[fractal_1]
IFS_rotation_enabled true;
mandelbox_color 0 0,2 0;
mandelbox_color_Sp1 0,3;
mandelbox_color_Sp2 0,1;
mandelbox_folding_min_radius 0,4;
mandelbox_generalized_fold_type fold_cube;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main 12,96 4,74 3,67;
mandelbox_scale -1,186;
mandelbox_vary_scale_vary 0,1;
power 2;
[fractal_2]
IFS_rotation_enabled true;
mandelbox_color 0 0,2 0;
mandelbox_color_Sp1 0,3;
mandelbox_color_Sp2 0,1;
mandelbox_folding_min_radius 0,4;
mandelbox_generalized_fold_type fold_cube;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main 12,9570060979732 4,73859899372437 3,67293641075188;
mandelbox_scale -1,1857861666;
mandelbox_vary_scale_vary 0,1;
power 2;
[fractal_3]
IFS_rotation_enabled true;
mandelbox_color 0 0,2 0;
mandelbox_color_Sp1 0,3;
mandelbox_color_Sp2 0,1;
mandelbox_folding_min_radius 0,4;
mandelbox_generalized_fold_type fold_cube;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main 12,9570060979732 4,73859899372437 3,67293641075188;
mandelbox_scale -1,1857861666;
mandelbox_vary_scale_vary 0,1;
power 2;
[fractal_4]
IFS_rotation_enabled true;
mandelbox_color 0 0,2 0;
mandelbox_color_Sp1 0,3;
mandelbox_color_Sp2 0,1;
mandelbox_folding_min_radius 0,4;
mandelbox_generalized_fold_type fold_cube;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main 12,9570060979732 4,73859899372437 3,67293641075188;
mandelbox_scale -1,1857861666;
mandelbox_vary_scale_vary 0,1;
power 2;
[keyframes]
![xchange](https://user-images.githubusercontent.com/27865473/39971769-a30a5cea-5701-11e8-86a7-999ca3b5e8b8.jpg)
`

**Comment by taurus66** [comment]
better this one
![xchange](https://user-images.githubusercontent.com/27865473/39971781-002a844a-5702-11e8-8ae5-272fc0103621.jpg)

**Comment by taurus66** [comment]
Ok I can't verify right now. I've found one, that renders below 0.1% wrong de @ de factor 5.25, but there are no significant artefacts in v 2.13-2. Maybe previous versions did lower fog quality or whereever this observation came from. It has been a while... sorry!

**Comment by taurus66** [comment]
`# Mandelbulber settings file
# version 2.13
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 6;
anim_keyframe_dir D:\taurus\Bilder\animations\search_only\2nd_iter\;
aux_light_colour_1 b200 d100 e800;
aux_light_colour_2 b200 d100 e800;
aux_light_enabled_1 true;
aux_light_enabled_2 true;
aux_light_intensity_1 1,5e-05;
aux_light_intensity_2 2e-05;
aux_light_position_1 0,675 3,142183997413782 0,09835028846060388;
aux_light_position_2 0,675 3,145836064260083 0,05601403245968092;
background_color_1 0000 0000 0000;
background_color_2 0000 0000 0000;
background_color_3 0000 0000 0000;
camera 6,2485234507 3,0959387776 0,291137618;
camera_distance_to_target 0,1509966887073566;
camera_rotation 110,4898076571985 -57,77533414988319 -104,0606132687394;
camera_top 0,532075983 -0,8367269487 -0,1295498423;
contrast 1,1;
DE_factor 5,25;
detail_level 5,120000000000001;
dont_add_c_constant_1 true;
dont_add_c_constant_3 true;
flight_last_to_render 0;
fog_color_1 0000 3000 2800;
fog_color_2 4000 8f00 8200;
fog_color_3 cd00 ff00 f700;
formula_1 73;
formula_2 1005;
formula_3 1023;
formula_iterations_1 2;
formula_start_iteration_2 24;
fov 1,5;
frames_per_keyframe 40;
gamma 0,9;
glow_color_1 a000 ae00 c100;
glow_enabled false;
glow_intensity 2;
hybrid_fractal_enable true;
image_height 720;
image_width 1280;
iteration_fog_color_1 ea00 ef00 f500;
iteration_fog_color_1_maxiter 60;
iteration_fog_color_2 8400 9f00 c100;
iteration_fog_color_2_maxiter 68;
iteration_fog_color_3 1300 2200 3500;
iteration_fog_opacity 3000;
iteration_fog_opacity_trim 52;
julia_c 0,6522607193 3,2738204273 0,1311850635;
julia_mode true;
keyframe_last_to_render 0;
limit_max 0,6805902801065935 10 10;
main_light_intensity 1,2;
mat1_coloring_palette_size 4;
mat1_coloring_random_seed 949600;
mat1_coloring_speed 5;
mat1_fractal_coloring_algorithm 3;
mat1_fractal_coloring_sphere_radius 0,01;
mat1_is_defined true;
mat1_specular_color e700 ff00 cf00;
mat1_specular_width 0,1;
mat1_surface_color 2400 2c00 3500;
mat1_surface_color_palette 5b8d38 61702b 9e1205 61712a;
N 130;
spherical_folding true;
target 6,1730998843 3,0677543533 0,1633999029;
view_distance_max 60,26443101466434;
volumetric_fog_colour_1_distance 0,003;
volumetric_fog_colour_2_distance 0,004;
volumetric_fog_density 0,1;
volumetric_fog_distance_factor 0,004;
volumetric_fog_enabled true;
[fractal_1]
mandelbox_scale 1,2;
transf_addition_constant 0 0 0,8;
transf_addition_constant_111 1,016579 1,124766 1;
transf_minimum_radius_05 0,001;
transf_offsetA_000 0,045823 -0,09107800000000001 -0,022248;
transf_scale_1 0,9492119999999999;
[fractal_2]
analyticDE_scale_1 -2,254902;
mandelbox_scale 1,2;
transf_addition_constant_111 1,4 1,4 1;
transf_function_enabledCx_false true;
transf_minimum_radius_05 0,001;
transf_offset_000 0,2 0,2 0,2;
transf_offset_111 0,5 1 1;
transf_offset_200 1 0 0;
transf_offsetA_000 0,086035 0,169835 -0,33266;
transf_scale3D_222 1,1 1,1 1,1;
transf_scale3D_444 2 2 2;
transf_start_iterations_250 0;
transf_start_iterations_A 15;
[fractal_3]
analyticDE_scale_1 -2,254902;
transf_addition_constant 0,004984 0,7405 0,033053;
transf_offset_000 0,2 0,2 0,2;
transf_offset_111 0,5 1 1;
transf_offsetA_000 0,086035 0,169835 -0,33266;
`
