### ISSUE TITLE
Mousewheel zoom-scroll-problem

### ISSUE THREAD

**Issue by michaelsteffen1982** [buddhi1980/mandelbulber2#474]
##### System information (version)
- mandelbulber2 => 2.14 dev
- Operating System / Platform => Windows 64 Bit

##### Detailed description
New mousezoom and scroll work at the same time. When zooming in or out with mouse, scroll up/down has to be locked.

##### Steps to reproduce
Open any picture large enough that scrollbars appear and then watch them while zooming in/out with mousewheel

**Comment by buddhi1980** [comment]
If I lock scrolling of image by mouse wheel, will be this OK?

**Comment by buddhi1980** [comment]
Where you would locate this option?

**Comment by michaelsteffen1982** [comment]
Not sure, I would say it fits best beside the "mouse-button-function" in de middle of the main window if possible...

**Comment by michaelsteffen1982** [comment]
Thats also a good idea I think

**Comment by mclarekin** [comment]
my two cents:

I nearly always work in "fit to window",  therefore I do not scroll.

In Fragmentarium:  mouse wheel -> zoom, this mouse action would be my
preffered choice

**Comment by michaelsteffen1982** [comment]
Mine are often larger...but thats not the ony thing to think of, one wrong wheel-movement at the wrong position and you have completely changed the cam-position...how often to press undo to get back to where you were (in an animation for example)?  Pressing CTRL to use scroll could easily prevent that.

**Comment by mclarekin** [comment]
Yep, i would be happy with
in render image window -
mouse wheel = zoom
ctrl+ mouse wheel = scroll


all other windows : mouse wheel = scroll

**Comment by michaelsteffen1982** [comment]
Only that you would be happy with is not a very good argument. Possibly there are reasons that (almost) no program like browsers, graphic-editors etc zoom when using the mousewheel as standard. All of them scroll. 

But its not my program. Buddhi asked on FB - and my answer is mouse-wheel = scroll. Its proven many times, works fine...why invent the wheel new? Zoom on mousewheel only cause problems in my opinion - and using zoom with CTRL + mousewheel could easily being made and is convenient (enough).

**Comment by zebastian** [comment]
IMHO: michaels idea is the more convenient one:
ctrl+ mouse wheel = zoom 
mouse wheel = scroll
I rendered a couple really big images over longer time and needed to be hellish cautious not to scroll accidentially in the render window to lose the position and restart the render.

We could put the information about ctrl + mouse wheel under hotkeys, still intuitive for me.

**Comment by buddhi1980** [comment]
It looks like a plan. Now we need to implement it.

**Comment by mclarekin** [comment]
I misread, yes, proposed plan is good.  And some things get lost with my
New Zealand use of english :)  We often use happy as a comment rather than
an argument.

@ Sebastian.   hellishly cautious

On Mon, May 28, 2018 at 5:59 AM, Krzysztof Marczak <notifications@github.com

**Comment by zebastian** [comment]
there we go, latest commit does it:
ctrl+ mouse wheel = zoom
mouse wheel = scroll
@all Please check if ok...

**Comment by buddhi1980** [comment]
Works very well

**Comment by michaelsteffen1982** [comment]
Many thanks

**Comment by zebastian** [comment]
issue was solved with this commit: https://github.com/buddhi1980/mandelbulber2/commit/0cb235e9c728e8d5d3df73a558e5319aa8499213
