### ISSUE TITLE
Animation-dock slider at wrong position 

### ISSUE THREAD

**Issue by michaelsteffen1982** [buddhi1980/mandelbulber2#475]
##### System information (version)
- mandelbulber2 => 2.14 dev
- Operating System / Platform => Windows 64 Bit

##### Detailed description
If the animationdock is moved out from main window into its own window and then "first renderframe" is being pressed, its slider (which should appear directly under the box) appears somewhere else / outside the window

**Comment by buddhi1980** [comment]
@michaelsteffen1982 , the problem should be fixed. When new exe file will be available (on Appveyor), please check if now it works as you expected.

**Comment by michaelsteffen1982** [comment]
Sure, please provide a link when its done here or on Facebook

**Comment by buddhi1980** [comment]
It is ready
https://ci.appveyor.com/api/buildjobs/74fbtamfehdjxh4v/artifacts/build-win%2FSetup%2FRelease%2Fx64%2FMandelbulber2-v2.14.0.0-Setup.exe

**Comment by michaelsteffen1982** [comment]
Hi, it does not work, link shows me the following text. Not sure what it is, to me it looks like a server-problem maybe, I just try it again later. Many thanks already anyway.




"Server Error in '/' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".




<configuration>
<system.web>
<customErrors mode="Off"/>
</system.web>
</configuration>


Notes: The current error page you are seeing can be replaced by a custom error page by modifying the "defaultRedirect" attribute of the application's <customErrors> configuration tag to point to a custom error page URL.




<configuration>
<system.web>
<customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>
</system.web>
</configuration>"
> Krzysztof Marczak <notifications@github.com> hat am 25. Mai 2018 um 17:06 geschrieben: > > > It is ready > https://ci.appveyor.com/api/buildjobs/74fbtamfehdjxh4v/artifacts/build-win%2FSetup%2FRelease%2Fx64%2FMandelbulber2-v2.14.0.0-Setup.exe > > > -- > You are receiving this because you were mentioned. > Reply to this email directly or view it on GitHub: > https://github.com/buddhi1980/mandelbulber2/issues/475#issuecomment-392087607

**Comment by mancoast** [comment]
please try the download again.  I am able to download from [here](https://ci.appveyor.com/api/buildjobs/74fbtamfehdjxh4v/artifacts/build-win%2FSetup%2FRelease%2Fx64%2FMandelbulber2-v2.14.0.0-Setup.exe)

**Comment by michaelsteffen1982** [comment]
Hello, I still get the same error...
> mancoast <notifications@github.com> hat am 25. Mai 2018 um 18:47 geschrieben: > > > please try the download again. I am able to download from [here](https://ci.appveyor.com/api/buildjobs/74fbtamfehdjxh4v/artifacts/build-win%2FSetup%2FRelease%2Fx64%2FMandelbulber2-v2.14.0.0-Setup.exe) > > -- > You are receiving this because you were mentioned. > Reply to this email directly or view it on GitHub: > https://github.com/buddhi1980/mandelbulber2/issues/475#issuecomment-392116481

**Comment by buddhi1980** [comment]
Have you tried to use some another web browser? I can also download this file without any problems.

**Comment by michaelsteffen1982** [comment]
Same error on a Raspberry with Chromium (Desktop uses Firefox)
> Krzysztof Marczak <notifications@github.com> hat am 25. Mai 2018 um 22:50 geschrieben: > > > Have you tried to use some another web browser? I can also download this file without any problems. > > -- > You are receiving this because you were mentioned. > Reply to this email directly or view it on GitHub: > https://github.com/buddhi1980/mandelbulber2/issues/475#issuecomment-392183408

**Comment by michaelsteffen1982** [comment]
Tried it, problem with the slider seems to be solved.
