### ISSUE TITLE
Standard window layout (suggestion)

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#479]
##### System information (version)

- mandelbulber2 => 2.14
- Operating System / Platform => Windows 64 Bit

##### Detailed description

Every startup of Mandelbulber I have to rearrange its layout (or click in the menu) - is it maybe possible to load a user-saved layout on startup of MB?

**Comment by mclarekin** [comment]
under View there are options.

**Comment by michaelsteffen1982** [comment]
Does not work for me (2.14dev). I have saved one with a name and also a "standardlayout" set. But every startup it looks different frokm what I have set, it does not use my setting.
Only if I press view and then Standardlayout it jumps to the layout I have saved.

**Comment by mclarekin** [comment]
better English:

In Ubuntu dev v2.14,  clicking "default window layout" retrieves the saved
default layout

**Comment by michaelsteffen1982** [comment]
Yes clicking on it works...but I have to click it every time I start the program. Would be better if the program starts with user-saved "standard"layout from alone, without clicking on it

**Comment by mclarekin** [comment]
In Ubuntu it get  my default every time I start the program.

Confirming

View _tick  Show statistics
View _Save window layout as default

close and restart program, and the statistics dock is showing.

**Comment by buddhi1980** [comment]
I also cannot reproduce this problem. I have tested this under win10 and Linux Debian. In both cases it saved default layout when I used "Save window layout as default"

**Comment by michaelsteffen1982** [comment]
On my Raspberry (MB 2.13.2) it also works.

But not on my Win-PC, I actually have the last 2.14dev in use (installed) and the previous dev-version 2.13.2 standalone.

**Comment by mancoast** [comment]
I can confirm that default window layout on windows 10 is a little funky. However, if you rearrange and then save the window state, it will restore automatically next time.

**Comment by buddhi1980** [comment]
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/d1a844444875bf876b9a75cb0967e08f8546dfa0
