### ISSUE TITLE
Strange camera-jumps

### ISSUE THREAD

**Issue by michaelsteffen1982** [buddhi1980/mandelbulber2#480]
##### System information (version)

- mandelbulber2 => 2.14dev (but I think older versions doing the same)
- Operating System / Platform => Windows 64 Bit

##### Detailed description

Camera doing some strange movements sometimes

##### Steps to reproduce
Open "Collatz" from object-pulldown, set coordinates with R (x: 3, y: -6, z: 2) and target too (xyz=0), then render.
Then set camera-step to 2 and press "move-back" 3 times - the fractal has gone. 

Values for camera now should be 
camera:
x: 52,25251565803689
y: -104,5050313160737
z: 34,8350104386913

and target:
x: 49,2525156580369
y: -98,50503131607374
z: 32,8350104386913

If I now press forward one time it does not bring back the fractal as I assume, instead the values jump to
camera:
x: -704,5049363328196
y: 1409,009872665632
z: -469,6699575552143

and target:
x: -707,5049363328196
y: 1415,009872665632
z:- 471,6699575552143

Furthermore, if I start this from the beginning and set movement-step to 6 - shouldn´t the fractal then disappear after one step backward (same as 3 clicks with step:2)? Instead it disappears after 2 clicks...and also produces other values than step:2 and 3 clicks backward...is this normal? Seems a bit curious to me.

**Comment by mclarekin** [comment]
i am guessing :   interpolation with cubic function  :)

cubic = catMulRom or akima

**Comment by michaelsteffen1982** [comment]
I dont know...I just see it behaves 'strange' 

Here is another example, just press the forward-button one step (0.25) and the cam 'jumps' to a complete different angle.

```
# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 4,228257489209911 -10,09066102201893 8,683945548600686;
camera_distance_to_target 0,009120430202670929;
camera_rotation -58,4046741149632 -13,93580597354868 -1,190799672739941e-11;
camera_top 0,2051356329262774 0,126177216174555 0,9705661658137354;
flight_last_to_render 99999;
formula_1 103;
keyframe_last_to_render 0;
mat1_coloring_palette_size 5;
mat1_coloring_random_seed 272576;
mat1_is_defined true;
mat1_surface_color_palette aaaa6b c3c29f ebe38b d9de75 8f8a5d;
raytraced_reflections true;
target 4,235797338187066 -10,0860233238251 8,681749033190668;
[fractal_1]
analyticDE_scale_1 1,4;
analyticDE_tweak_005 0,2;
transf_addition_constant_0777 0,6 0,6 0,7;
```
[PseudoKleinian.zip](https://github.com/buddhi1980/mandelbulber2/files/2041275/PseudoKleinian.zip)

**Comment by mclarekin** [comment]
OK it is not the cubic thing, I was guessing you were animating

When loading your setting I  see that you are in Relative Step Mode with
the step set  at 0.5. Green forward arrow works correctly for me.


general comments on your settings
a) render engine. generally with these types of fractal you reduce the
Maxiter from 250 down to  somewhere between 1 and 30 (maybe more if it is a
hybrid). You can watch the effect of the increasing the maxiter,  with
every extra iteration producing an extra layer of detail.
b)  render engine.  Raymarching step multiplier of 1.0 is OK. Most other
fractal types require this to be reduced
"
c) pseudoKleiinan tab.  DEadd (tweak). Increasing this just "fattens"  the
fractal and you lose detail. Optimum = 0.0, but often it needs to be
tweaked up a bit if the image starts to deteriorate..
d) pseudoKelinian tab .  DE factor, drop below 1.0 to make "holes".  In
standard case, increasing above 1.0 does nothing so it is generally set at
1.0 or less..

**Comment by michaelsteffen1982** [comment]
No, its no animation.
Try step 0.25

**Comment by buddhi1980** [comment]
You use relative step mode for camera movements. This is the reason. Change to absolute step mode.
If somebody reduce your salary by 25% and next day will rise it by 25%, will you get the same many as before?

**Comment by michaelsteffen1982** [comment]
No, that makes sense...and I was in relative - but it also happens with absolute mode here for the Kleinian:
![kleinian1absolut](https://user-images.githubusercontent.com/29848666/40573310-d14c1e50-60bf-11e8-8d23-e49ed748ed8b.png)
![kleinian2absolut](https://user-images.githubusercontent.com/29848666/40573309-d12cc0b4-60bf-11e8-96aa-cb293173b0d1.png)

**Comment by michaelsteffen1982** [comment]
And here is the next one...one step (0,104852522341218) forward in absolute mode and camera jumps here:
![mengercrosskifs1](https://user-images.githubusercontent.com/29848666/40573330-5884ea50-60c0-11e8-8e89-46588d7bfa7b.jpg)
![mengercrosskifs2](https://user-images.githubusercontent.com/29848666/40573329-5867fd96-60c0-11e8-8907-21aa8927e0f0.jpg)
[MengerCrossKifs.zip](https://github.com/buddhi1980/mandelbulber2/files/2041396/MengerCrossKifs.zip)

**Comment by buddhi1980** [comment]
Because you move only the camera without target. This is the reason why the camera is rotated. Change to "Move camera and target" (Camera und Ziel bewagen)
Watch this video tutorial (https://youtu.be/mucsJ51ZINE) and check User Manual to get familiar with camera movement modes.

**Comment by michaelsteffen1982** [comment]
I see that my step is larger than the target-distance....(but it looks so far away^^)...I think this could be the reason...I´ll check this also with the Kleinian...

**Comment by buddhi1980** [comment]
@michaelsteffen1982 , can I close this issue?

**Comment by michaelsteffen1982** [comment]
Yes I think this can be closed
