### ISSUE TITLE
AMD OpenCL fast_relaxed_maths unchecked artifacts

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#487]
Problem, Vertical line artifacts on image
Reproducible on this laptop
i7-4710HQ @2.5GHz 8.00 GB AMD Radeon R9 M265X    openGL 4.5 openCL 1.2

This problem appears to be an AMD GPU thing and related to having use_ fast_relaxed_maths unchecked

last good build  1981a219 -   17 May 2018
It seems problem first appeared  between 17 and 25 May 2018 

So it is probably a minor thing because i expect that most AMD card users will have  use_fast_relaxed_maths checked.

I also note, that I have yet to come across any unexpected behavior related to using fast maths (but I have not tried).

reproducible behavior

 i)  fast maths unticked = artifacts , tick fast maths, click "OK", artifacts go away without having to restart program for change in fast maths option. This is not reversible as problem stays  gone

ii)  restart program, now loads with fast maths ticked = no artifacts , untick fast maths, click "OK". artifacts appear,  this is not reversible as artifacts remain

iii) with fastmaths unchecked
reproduce,   turn off color by numbers artifacts disappear
reproduce,  move formula from slot#3 to slot# 1 or #2 and artifacts disappear

Also tested  with this  AMD A8-7600 10 compute cores + 6G 3.10GHZ (APU)radeon R7 200 series VEN 1002  Dev1313 Kaveri steamroller  (APU???) and could not reproduce the prolem

# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
anim_keyframe_dir C:\Users\Graeme\mandelbulber\animation\de\;
background_color_1 3400 0000 0000;
camera -1.230094393426701 -1.710708000467806 2.233653008588877;
camera_distance_to_target 0.004241329617798319;
camera_rotation -9.885709393266426 16.41788741739769 -14.62415923678664;
camera_top -0.2956813270024242 -0.2260773431852327 0.9281495503206323;
DE_factor 0.9;
DE_thresh 1e-05;
detail_level 4;
file_background /home/graeme/mandelbulber/my textures/background.jpg;
file_envmap /home/graeme/mandelbulber/my textures/envmap.jpg;
file_lightmap /home/graeme/mandelbulber/my textures/lightmap.jpg;
flight_last_to_render 0;
formula_1 0;
formula_3 119;
fractal_constant_factor 0.9 0.9 0.9;
hybrid_fractal_enable true;
julia_c 2 2 -0.440437589554615;
keyframe_last_to_render 0;
limit_min -10 0 -10;
main_light_alpha -23;
mat1_coloring_palette_offset 15.61;
mat1_coloring_palette_size 32;
mat1_coloring_random_seed 788238;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_i_start_value 19;
mat1_fractal_coloring_ic_xyz_enabled_false true;
mat1_fractal_coloring_iter_add_scale 0;
mat1_fractal_coloring_iter_scale 0.0053;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_orbit_trap_weight 5.5;
mat1_fractal_coloring_xyz_000 0 2222 0;
mat1_fractal_coloring_xyzC_111 0 0 5.4;
mat1_is_defined true;
mat1_specular 0.8;
mat1_specular_width 0.7;
mat1_surface_color ba00 c300 5000;
mat1_surface_color_palette 34eb40 543131 006855 7b4022 984396 42065d 00a700 ffbc6b 4dc43a 0c620a 4d5e5f 3b851f 506e72 925ec7 00003e 79d7c3 969696 acacac 005500 f794aa b8b8b8 b8b8b8 b8b8b8 aa6a4a 005500 005500 005500 005500 005500 005500 c6bc32 780000;
target -1.229395917969258 -1.706700014518768 2.234851781959648;
view_distance_max 56.72892120903543;
volumetric_fog_colour_1_distance 0.1412726696295308;
volumetric_fog_colour_2_distance 0.2825453392590616;
volumetric_fog_density 0.1;
volumetric_fog_distance_factor 0.2825453392590616;
[fractal_2]
fold_color_aux_color_enabled false;
mandelbox_scale -1.5;
transf_rotation 6.997914 6.997914 6.997914;
[fractal_3]
fold_color_aux_color_enabled false;
mandelbox_scale -1.5;
transf_rotation 6.997914 6.997914 6.997914;
[fractal_4]
fold_color_aux_color_enabled false;
mandelbox_scale -1.5;
transf_rotation 6.997914 6.997914 6.997914;
[fractal_5]
fold_color_aux_color_enabled false;
mandelbox_scale -1.5;
transf_rotation 6.997914 6.997914 6.997914;
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;fractal2_transf_addition_constant_111_x;fractal2_transf_addition_constant_111_y;fractal2_transf_addition_constant_111_z;main_DE_factor;fractal2_transf_rotation_x;fractal2_transf_rotation_y;fractal2_transf_rotation_z
0;-3.515153507184379;-3.28028106641379;1.571375328016513;-2.438673684223112;-2.326728344073314;0.8318075686962733;0.3121633641629601;0.336623142239221;0.8883911830851637;1;1;0;0.45;0;0;57
1;-5.724891775826913;-5.116227217649509;3.17352319780913;-2.173580385379322;-2.176606556700799;1.237853345328943;0.2586658671728848;0.2935035894673203;0.9202975671648266;1;1;1;0.9;0;0;0
2;-2.464912266244685;-2.452121892846027;2.208201116967652;-2.058964406817686;-2.075768411069975;2.074215116478724;0.1343694572744196;0.200546710595087;0.970425610658163;1;1;1;.9;0;0;0
3;-1.905683878492648;-2.113018716920674;2.120618383237623;-1.801147625040707;-2.077453286298416;2.113876180864421;0.01753040835889014;0.1362480520371514;0.990519637916812;1;1;1;.9;0;0;0
4;-1.324273458463103;-2.062432765404524;2.250326588039518;-1.273196102919669;-2.033540169040412;2.257256307069249;-0.2201017344784014;0.158240103642114;0.9625566456468586;1;1;1;0.9;7;7;7
interpolation;morphAkima;morphAkima;morphAkima;morphLinear;morphLinear;morphAkimaAngle

**Comment by mclarekin** [comment]
It would be nice to understand what is happenning. However it  seems to only to happen with the aboxmod11 formula, in slot#3 or greater. weird

**Comment by zebastian** [comment]
@mclarekin you could start as a debugger at AMD, they could surely use some more  :)

I tried on AMD RX480 with newest 18.20 pre-release driver for ubuntu 18 and your example settings --> no visual difference in the output images. 
I think you also installed the pre-release driver, maybe this is something associated with your very combination of device, driver and usage. I dont think this is a general problem with all AMD cards.
If it was a quick fix i would say we find the problem, but i think it is caused by using fast-relaxed-maths, which is just to awesome to deactivate it again.

IMHO: we should just release v 2.14 and see what the feedback brings on this topic?

**Comment by mclarekin** [comment]
![abox11 no fast maths](https://user-images.githubusercontent.com/12769564/41263855-a03f5774-6e3d-11e8-9738-00751b6ead5b.jpg)
For the record this is what it looks like.

 i think it is caused by **NOT** using fast-relaxed-maths.
 Steps to reproduce is render settings in openCL full, then uncheck fast maths in Preferences, render again = artifacts.

It may be two issues, **as I find it unusual that it does not happen with similar formulas.**

"IMHO: we should just release v 2.14 and see what the feedback brings on this topic?"

Yep,  Marc Stein is  ready with an AMD Radeon HD 6670.

**Comment by mclarekin** [comment]
a)i think i remember Marc Stein tested with  AMD Radeon HD 6670. and had no problem. 

b) last time i had these artifacts, they disappeared when i changed from flat to equirectangular

I will continue to monitor.

**Comment by mclarekin** [comment]
I can no longer reproduce this weird problem with the settings above :) 
Assume some code change, has fixed this.
