### ISSUE TITLE
Tooltips for keyframe animation and flight animations docks has to be re-edited.

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#49]
Some of sentences doesn't make sense.

**Comment by mclarekin** [comment]
Krzysztof make changes and I will watch for commit and check English.

Or show me what needs to be fixed.


I also note a "Fligt" instead of "Flight"

Cheers

On Mon, Nov 16, 2015 at 2:14 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
oh i see you have committed , I will fix typos
