### ISSUE TITLE
Test fails with opencl - examples/boolean001.fract

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#491]
This crashes in full mode on AMD card
@buddhi1980 / @mclarekin can you reproduce?

**Comment by zebastian** [comment]
This is the stack trace:

```
LLVM ERROR: Cannot select: 0x55f5041c0a40: ch = store<ST1[%1562+10]> 0x55f503fa3780, 0x55f504bb5dc0, 0x55f5051026d0, undef:i32
  0x55f504bb5dc0: i8 = truncate 0x55f503ee8410
    0x55f503ee8410: i64 = srl 0x55f5041c0490, Constant:i32<16>
      0x55f5041c0490: i64,ch = CopyFromReg 0x55f5041c0500:1, Register:i64 %vreg517
        0x55f5041c0570: i64 = Register %vreg517
      0x55f505101be0: i32 = Constant<16>
  0x55f5051026d0: i32 = add 0x55f503ee7760, Constant:i32<47>
    0x55f503ee7760: i32,ch = CopyFromReg 0x55f505795420, Register:i32 %vreg786
      0x55f5044d0290: i32 = Register %vreg786
    0x55f50544f5e0: i32 = Constant<47>
  0x55f5054c66d0: i32 = undef
In function: CalculateDistance
```

**Comment by zebastian** [comment]
It is caused by this line in opencl/engines/calculate_distance.cl

case clBooleanOperatorOR:
					if (distTemp < dist)
					{
						outTemp.objectId = 1 + i;
						**out = outTemp;**
					}
					dist = min(distTemp, dist);
					break;

Even if i completely initialize the out and outtemp variables on creation this issue occurs:
```
formulaOut out;
        out.z = (float4)(0.0f, 0.0f, 0.0f, 0.0f);
        out.iters = 0;
        out.distance = 0.0f;
        out.colorIndex = 0.0f;
        out.orbitTrapR = 0.0f;
        out.maxiter = false;
        out.objectId = 0;
```
This will take some more investigation...

**Comment by buddhi1980** [comment]
I have found this: https://community.amd.com/thread/225293
Probably it is internal error of AMD driver

pon., 11 cze 2018 o 21:13 Sebastian Jennen <notifications@github.com>
napisał(a):

**Comment by buddhi1980** [comment]
What you can try to do is rewrite a little this part of the code. Try to move ```out = outTemp;``` outside the switch() statement. You can try different changes like use if instead if switch(). To copy members of struct member by member. It is possible that modified code which will work in the same will be compiled properly.

**Comment by mclarekin** [comment]
it does seem to take a while to compile but that might be normal for these settings.

**Comment by zebastian** [comment]
member by member works, thanks buddhi!
