### ISSUE TITLE
script for converting fractal_list.cpp data into a csv file. 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#492]
a script for converting fractal_list.cpp data into a csv file.

**Comment by zebastian** [comment]
I can look into this. This information is available when running the populateUiInformation.php script. What do you need this list for?

**Comment by mclarekin** [comment]
List is to show users  the list :)

There are somethings like DE function that I want to explain to users. In a
spreadsheet I can sort by the various fields.

also I can use in a  spreadsheet to keep a record of TODO's,  and some
other notes




On Mon, Jul 23, 2018 at 12:34 AM, Sebastian Jennen <notifications@github.com

**Comment by zebastian** [comment]
OK, i will add this :-)

**Comment by zebastian** [comment]
just added it, see latest commit...
@mclarekin can you check? Are there any more fields you need? What about the formatting?
Let me know, if i should adopt something...
Cheers!

**Comment by mclarekin** [comment]
That is perfect, thank again Sebastian ( and Mel for allowing Sebastian the
time).  I don't know when I will write some words explaining it's use, as
there is so many other things on my TODO list.
