### ISSUE TITLE
Unexpected lighting differences with Fast Relaxed Math enabled/disabled

### ISSUE THREAD

**Issue by RandomNadir007** [buddhi1980/mandelbulber2#495]
- mandelbulber2 => 2.14
- Windows 10 64 Bit
- AMD RX 480 8GB, Adrenalin 18,5,1 drivers, default settings

##### Detailed description

With the following settings, the lighting is quite different between enabled and disabled. It seems to only affect certain scenes and I haven't been able to find something in common.

```
# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion 4;
ambient_occlusion_enabled true;
ambient_occlusion_mode 1;
ambient_occlusion_quality 2;
background_color_1 0000 0000 0000;
background_color_2 0000 0000 0000;
background_color_3 0000 0000 0000;
camera 0.9826079678678419 -0.02036907812976813 -0.4583749585056648;
camera_distance_to_target 0.000374180176848257;
camera_rotation -164.9467482321149 -30.78953029861255 -153.6385925688576;
camera_top 0.3096742790612192 0.558239049041933 -0.7697213814184145;
DE_factor 0.0078125;
DE_thresh 5.750877837000424e-05;
detail_level 0.179829162295819;
DOF_blur_opacity 1;
DOF_focus 0.0005150031065568328;
DOF_number_of_passes 2;
DOF_radius 2;
file_lightmap C:\Program Files\Mandelbulber2\textures\lightmap3.jpg;
flight_last_to_render 0;
formula_1 131;
fov 1.5;
glow_color_1 8e00 9a00 ab00;
glow_intensity 9;
image_height 416;
image_width 624;
keyframe_last_to_render 0;
main_light_alpha 20;
main_light_intensity 0.8;
mat1_coloring_palette_size 13;
mat1_coloring_random_seed 290047;
mat1_coloring_speed 0.5;
mat1_fractal_coloring_add_max 1.8;
mat1_fractal_coloring_global_palette_false true;
mat1_fractal_coloring_i_start_value 1;
mat1_fractal_coloring_iter_add_scale_enabled_true false;
mat1_fractal_coloring_orbit_trap_weight 64;
mat1_fractal_coloring_rad_weight 512;
mat1_is_defined true;
mat1_specular_width 0.8;
mat1_surface_color_palette d34b11 545d5a 077041 c59195 947d77 aa55ff aaaaff ababab 4c4042 110f12 aa0000 d43500 277988;
N 175;
raytraced_reflections true;
smoothness 0.25;
target 0.9826914513986492 -0.02067948861532475 -0.4585664960614774;
view_distance_max 6.628593198185134;
[fractal_1]
alpha_angle_offset 0.1;
beta_angle_offset 0.2;
info true;

```

No Fast Relaxed Math
![test no relaxed](https://user-images.githubusercontent.com/40465832/41722590-2bc0bc2c-75a8-11e8-9c87-36b1a080e4c8.jpg)

Fast Relaxed Math
![test relaxed](https://user-images.githubusercontent.com/40465832/41722593-2bf657b0-75a8-11e8-9f50-4f2ddd2be6bd.jpg)

##### Steps to reproduce

Import provided settings above

File menu -> Program Preferences -> OpenCL -> disable Use fast relaxed math -> OK

Render

File menu -> Program Preferences -> OpenCL -> enable Use fast relaxed math -> OK

Render

**Comment by mclarekin** [comment]
My test on a AMD Radeon R9 M265X, both images look like the top one. With
some change in the areas  where the DE is less accurate.

What type of GPU card was used??

**Comment by mclarekin** [comment]
<https://www.facebook.com/jonathan.pearce.509?fref=gc&dti=851813331543501> AMD
RX 480?? Yep it  appears that there is more variation with AMD gpu's,
Sebastain has a AMD GPU but  we can not always reproduce each others
problems
