### ISSUE TITLE
"Image proportion" is never saved.

### ISSUE THREAD

**Issue by RandomNadir007** [buddhi1980/mandelbulber2#496]
##### System information (version)
- mandelbulber2.14
- Windows 10 x64

##### Detailed description

The **Image Proportion** setting is never saved. It will always reset to "Free" when settings are loaded. If it's desirable to change the resolution while keeping the same aspect ratio, the user must either remember what aspect ratio was used or quickly calculate it from the existing resolution. It would be easier if settings files retained this information.

##### Steps to reproduce

Create any scene.

Set **Image proportions** to something other than "free" (eg "16:9").

Set desired **Image height** (eg 720)

**Save Settings** to a test file

Close the program.

Open the program.

**Load settings**

**Image proportions** will always be set to "free"

-->

**Comment by mclarekin** [comment]
This could be added to be saved in settings

**Comment by zebastian** [comment]
I can look into this....

**Comment by mclarekin** [comment]
that would be good, because I would like to see where abouts in the code ,
plus how to do it :)
