### ISSUE TITLE
WASD shortcuts are wrong in another keyboard layouts than English

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#502]
There is needed to add options to customize shortcuts or find the way to make them independent from keyboard localization. 
Example: on German layout Y and Z are swapped so "backward" key is in wrong place.
Similar problem is with French layout (AZERTY) where A is swapped with Q.

**Comment by zebastian** [comment]
see #513, imho thats the way to go.
Can we close this issue?

**Comment by buddhi1980** [comment]
Now there is possible to define custom shurtcuts
