### ISSUE TITLE
test log - linear DeMix slider for log/linear hybrids

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#504]
float Log = 0.5*log(r)*r/Dd;
 float Lin =  abs(r-DeLinOff)/Dd;
	return mix(Log,Lin,DeMix);

**Comment by buddhi1980** [comment]
We need good mix() function for it which cannot be linear. It should provide smooth transform between logarithmic and linear function.

**Comment by mclarekin** [comment]
This has been implemented, in T>DE controls, albeit the transform is still a work in progress
