### ISSUE TITLE
Investigate use of .png alpha (where does the blue color come from?)

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#508]
I think I have turned off all  parameters that could produce the blue color, that you can see at the edges of the "tiles". H'mmm?

# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_quality 8;
background_color_1 ff00 ff00 ff00;
camera -0.1718353918021714 -0.7288972969839425 -0.2037048977554753;
camera_distance_to_target 1.134559607757701;
camera_rotation -4.80699538664228 -9.073543047067615 2.588640792853667;
camera_top 0.05820794686750164 0.1532022440671228 0.986479045562686;
DE_factor 0.7;
DE_thresh 0.0005;
flight_last_to_render 0;
formula_1 7;
glow_enabled false;
hybrid_fractal_enable true;
image_width 600;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
main_light_intensity 1.5;
mat1_file_color_texture /home/graeme/mandelbulber/my textures/alpha channel.png;
mat1_is_defined true;
mat1_specular 0;
mat1_specular_width 0.001;
mat1_surface_color ff00 ff00 ff00;
mat1_texture_fractalize true;
mat1_texture_mapping_type 1;
mat1_use_color_texture true;
mat1_use_colors_from_palette false;
target -0.0779495615563174 0.3875245395024164 -0.3826273319295665;
view_distance_max 29.1848855537916;

![alpha channel](https://user-images.githubusercontent.com/12769564/43434070-44b4fb7c-94ce-11e8-8d71-79cc359b7255.png)

**Comment by rconcept** [comment]
Hi, perhaps I misunderstood the question, but the blue color come from the blue pixels of color texture...
For a better appreciation, I colored the "guilty" pixels in red:
![43434070-44b4fb7c-94ce-11e8-8d71-79cc359b7255_red](https://user-images.githubusercontent.com/15924913/43455896-a652c1e6-94c1-11e8-9758-17cd029e70e9.png)

The same image with only the "guilty" pixels:
![43434070-44b4fb7c-94ce-11e8-8d71-79cc359b7255_guilty_pixels_only](https://user-images.githubusercontent.com/15924913/43455924-bf4fcc66-94c1-11e8-946b-3f3f5d21bd41.png)

**Comment by mclarekin** [comment]
Yeah it was something differenet, BUT you made me realize what was happening. We cannot currently use alpha channel.pngs for texture. The preview in the materials editor shows the alpha_channel png i.e. background is clear (white), but the pink color is the actual background color.
![alphach](https://user-images.githubusercontent.com/12769564/43492979-b51b7d9e-957f-11e8-8615-e549ca584d9d.PNG)

**Comment by mclarekin** [comment]
Not a bug, it is just the current state of the program.
The white areas in the screenshot are actually pink, they just look white under the rays of a strong white light.


Closed
