### ISSUE TITLE
implement "--GPU" for headless

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#517]
prior to release 2.15, please enable a new user friendly option.
this argument, when passed to the headless binary, will require no additional CLI options.
the system should automatically select the first GPU, and error/exit if no GPU is found.

**Comment by zebastian** [comment]
@mancoast implemented here: https://github.com/buddhi1980/mandelbulber2/commit/26d98d8bd78d2b62e21e05eab9b2f330517f05db
can you check?

**Comment by mancoast** [comment]
Thanks z, I will test it out today

**Comment by mancoast** [comment]
verified, thanks!
