### ISSUE TITLE
example settings wrong end frame

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#52]
In 
\examples\keyframe_anim_mandelbulb.fract
is
keyframe_last_to_render 1800;
but last frame can be maximal
keyframe_last_to_render 1700;
This causes the field to default to 0 on load (possibly undesired too, more appropiate to default to max, when max is exceeded?)
TODO: check other example settings of flight and keyframe animation.

**Comment by buddhi1980** [comment]
It was not a problem with too high number, but there was bug in setting limits for frame range. There weren't refreshed in proper time.
