### ISSUE TITLE
Different coloring in CPU and OpenCL mode for hybrid fractals

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#523]
There is significant difference in fractal colors between CPU mode and OpenCL in hybrid mode
It is visible for most of fractals.
It is needed to check of all changes in compute_fractal.cpp and fractal_coloring.cpp were copied to OpenCL equivalents. 

Example settings for testings:
```
# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 0,9781478165320964 -2,36507565399708 0,5400838756478107;
camera_distance_to_target 1,675122022628784;
camera_rotation 25,05150055126203 -12,63109573407259 -0,428477987805968;
camera_top -0,09936543914953455 0,1949296807394929 0,975770940881834;
flight_last_to_render 99999;
formula_2 7;
formula_iterations_2 2;
fractal_enable_3 false;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_is_defined true;
raytraced_reflections true;
target 0,2860126800641944 -0,8842636052727353 0,1737801493286319;
```

**Comment by mclarekin** [comment]
I think there will be more than one issue


This is the first issue (which in theory should not make a difference
between c++ and openCL):

* aux.r_dz => aux.DE, and effects historic term   r2*

For log formulas we were iterating  aux.r_dz

so *assuming* extendedAux.DE remained unchanged, then,
extendedAux.DE = initial condition of 1.0

        // aux.DE
        double mboxDE;
        mboxDE = extendedAux.DE;    =  1.0;
        double r2 = r / fabs(mboxDE);  =  r/1.0 = r;
        if (r2 > 20) r2 = 20;


result  r2 = r;    for  case analyticFunctionLogarithmic

        // summation = orbit trap  part  + aux.color part +  aux.DE part
        colorIndex = (minimumR * 1000.0 + mboxColor * 100 + r2 * 5000.0);

when using analytic log ,    r2 value is not influenced by iterating aux.DE
value.



*There are various ways to fix this issue with Hybrid Mode*

I  do not know the code required

fractal_coloring.cpp 272

    // Historic HYBRID MODE coloring
    else if (isHybrid)
    /*{
        double r2 = r;

        // aux.DE
        // if     (DE function from spinbox) != case
analyticFunctionLogarithmic)
        {
            double mboxDE = extendedAux.DE;
            double r2 = r / fabs(mboxDE);
            if (r2 > 20) r2 = 20;
        }

       //   OR          if  (version < v2.15 ) r2 = r;

        // orbit trap
        if (minimumR > 100) minimumR = 100;

        // aux.color (init cond = 1.0)
        double mboxColor;
        mboxColor = extendedAux.color;
        if (mboxColor > 1000) mboxColor = 1000;

        // summation
        colorIndex = (minimumR * 1000.0 + mboxColor * 100 + r2 * 5000.0);
    }*/

**Comment by mclarekin** [comment]
or a mix function with a tooltip

 r2 = mix( 1.0,     extendedAux.DE,     Old_DE_influence parameter)
note pre v2.15 settings files, use parameter = 0 with analytic logarithmic
DE

**Comment by mclarekin** [comment]
another consideration is that we have three color modes:

normal =         orbit traps
hybrid mode =    three parts , plus it  uses orbit traps
color_by_numbers , can do it all

 hybrid mode could be enhanced

 // summation
        colorIndex = (minimumR * 1000.0 * orbitTrapScale
       + mboxColor * 100  * aux.ColorScale
       + r2 * mix(DE) * 5000.0 *  "r/D_Scale );


each solution has "pros and cons."

**Comment by buddhi1980** [comment]
I'm just asking to eliminate differences between CPU and GPU code. There is needed to compare code line by line in compute_fractal and fractal_coloring files.

**Comment by mclarekin** [comment]
i am slowly doing it :), I just had to make some notes on the backwards
compatibility  problems i found while I was checking the code :)

**Comment by mclarekin** [comment]
compared code line by line in compute_fractal and fractal_coloring files.
Result  no differences found.

checking commits
6 july 18 7ed2            last good
7 july 18 879e            no appveyor  cannot check
7 july 18 c8df             issues start here

**Comment by buddhi1980** [comment]
Where the problem started? In CPU code or GPU? Your trace with checking commits will help us a lot.

**Comment by mclarekin** [comment]
a) finding issue on apperveyor 7 july may help, but that issue may have
since been fixed, then broken again

b) currently i am thinking it is related to aux.DE  used in  the r2
calculation,  and maybe in the c++ code.

c) I will go back to Win10 openCL and try to determine which code is
correct.

**Comment by mclarekin** [comment]
isolate problem in current build
settings :         mandelbulb and  transf_add_constant (no DE in this
transform)
procedure:     replicate hybrid mode in  color-by-numbers mode
result:   in color-by-numbers we get the same image as  Hybrid Mode c++

r2 calculation in  Hybrid Mode openCL code, appears to be what is not
working correctly.
either  r or aux.DE maybe causing problem

now i sleep :)

**Comment by mclarekin** [comment]
it is possible that  aux.r_dz to aux.DE  changes in 7 July commit, made a
pre-existing c++ difference much more obvious.

I will temporary hard code DE to 1 in hybrid color equation, and check
openCL appveyor build


*random notes*

standard mandelbulb,

Normal mode                     - c++ is the same as openCL

Color-by-numbers mode    - c++ is the same as openCL, except if i enable
r/DE.,
                                           -  plus minor backwards
compatability issue from aux.r_dz change

Hybrid mode                      -  maybe a  small difference when openCL
was first implemented,
                                          -  major difference is the  r/DE
problem.
                                          - plus backwards compatability
issue from aux.r_dz change, code required

**Comment by mclarekin** [comment]
The problem existed in V2.14.

And has been made noticable,   now that we are using only aux.DE

I am slowly figuring it out :)

**Comment by mclarekin** [comment]
hard coding the DE to 1.0   (so r2 = r/1.0;) removed the color difference
between c++ and openCL in hybrid mode

therefore DE is confirmed as the problem

 with equation  r / DE;    I would not expect DE being single or double
precision, to be causing such a difference.

investigations continue

**Comment by mancoast** [comment]
Great root cause discovery!

**Comment by mclarekin** [comment]
i am still only half way there.  I am now thinking "why is there a color
change in Hybrid mode when using DeltaDE?"

**Comment by mclarekin** [comment]
this would be explained if maybe aux.DE still goes into color equation
even though  Delta.DE is chosen, this does not need to be changed.

**Comment by mclarekin** [comment]
finally, it appears that casting r in c++ to single precision was the
soltution     :) :) :)

 a bit more testing,  then i will evaluate backwards compatability  issues

**Comment by buddhi1980** [comment]
It is very interesting catch that double/single precision makes big difference here.

**Comment by zebastian** [comment]
what is the performance hit on using double in opencl code?
Maybe the maths can be rewritten, to lower the precision loss?

**Comment by buddhi1980** [comment]
It will not help, because all previous calculation (input data for coloring) are single precision

**Comment by buddhi1980** [comment]
I have found new trace. The formula:
float r2 = min(r / fabs(extendedAux->DE), 20.0f);
in fractal_coloring for hybrids gives completely different results in OpenCL mode than in CPU. 
It is always 20.0 !!!

It is the reason of wrong total result for
colorIndex = (minimumR * 1000.0f + mboxColor * 100.0f + r2 * 5000.0f);

Now I have to find why this value is wrong.

**Comment by buddhi1980** [comment]
Found!!!
The problem was in compute_fractal. Bailout condition for calculating color caused big numeric errors and infinite results.
There was condition: if (aux.r > 1e15 || length(z - lastZ) / aux.r < 1e-15f) break;
When iteration loop was finished, then aux.r and aux.DE were huge numbers.

**Comment by buddhi1980** [comment]
@mclarekin, your discovery about differences between single and double precision was really helpful. In this way I have found important difference in calculation results. Because r2 was always 20, the result of
```
	colorIndex = (minimumR * 1000.0f + mboxColor * 100.0f + r2 * 5000.0f);
```
was always: very_small_number + 100000.0
It caused big numeric error in single precision

Thanks @mclarekin for debugging this topic.

**Comment by mclarekin** [comment]
i suspect your commit will remove a lot of minor color differences, that  i
had yet to explain and were bugging me.  :)
