### ISSUE TITLE
Re-evaluate Hybrid Mode coloring in respect to recent changes

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#527]
Hybrid Mode coloring is effected, to varying degrees, by recent changes to aux.DE and r. 

baisc hybrid color function is the addition of three parts

      outColor =  orbit trap + aux.color + r / aux.DE

**Before** when aux.r_dz was used, (log formulas) , "+ r / aux.DE" part had little effect.
 The orbitTrap created the color pattern and the other two parts often having very little effect.

**Now** with log formulas,   the third part has influence.

for backwards compatability we could control over the three parts, this would enhance Hybrid Mode color control,  (avoiding having to use the slower Color_By_Numbers)

**Comment by mclarekin** [comment]
There are a lot of combinations to check.   
testing with v2.14, and current build. Plus  6 july appveyor, which is the commit before the aux.r_dz change.

Test 1.  This is a Log formula (plus a "no DE" transform to force hybrid mode).

major color difference from v2.14 was fixed before 6 july appveyor. Since then, the changes to aux.r_dz  and r, produced a very small color change..

In dev2.15 with these settings  both Hybrid Mode and Normal mode color is correct, in both c++ and openCL, and can be reproduced in color by numbers.

![mbulb hybrid frf3](https://user-images.githubusercontent.com/12769564/44438406-faac0600-a612-11e8-92b3-ba67c30f4237.jpg)

**Comment by mclarekin** [comment]
test2.  Log and linear formula hybrid.  This is using analytic log. Dev v2.15 21_July shows the effect of the linear formulas DE now added to color.  
This is the backwards compatability issue to be evaluated.
![mbulb hybrid frf3a hybrid mode](https://user-images.githubusercontent.com/12769564/44442754-17066d80-a628-11e8-83f5-de648e15b83c.jpg)

**Comment by mclarekin** [comment]
test3. Log  with linear using DeltaDE. This is where users may like backwards compatability.

![mbulb hybrid frf3b deltde](https://user-images.githubusercontent.com/12769564/44444289-373a2a80-a630-11e8-9039-53f6671c489f.jpg)

**Comment by mclarekin** [comment]
Current feeling is I will introduce a pre-V2.15 color checkbox, that will enable backwards compatibility for most issues.  I  suggest that it removed in "say"  V2.17

It is complicated to explain, but  because there are backwards compatibility issues with V2.15 ,then I intend to make some more  color code changes.   I will do this in stages.

**Comment by mclarekin** [comment]
Normal coloring mode (single fractal),  backwards compatibility

ISSUE
- all minimumR values  are effected by bailout change, except Abox color when used with Standard Orbit trap,  as then minimumR = 0.0
- in Abox color,  the  r calc is effected by bailout change
- aux.DE changes did not effect Normal coloring mode.

SOLUTION
pre-2.15 checkbox enables old bailout
https://github.com/buddhi1980/mandelbulber2/commit/275699bd6aa2fd50d4ac84b85d1e6abeb77618e0

**Comment by mclarekin** [comment]
Now in V2.15 the Preset toobar thumbnails will load the same as old version.
 except mandelbox presets (changing bailout to 1e15 will make these appear the same)

**Comment by mclarekin** [comment]
NORMAL COLOR mode. coloringFunctionABox:

This code says
  "color = aux.color +  radius part +  minimumR part" 
with the exception that minimumR = 0 if STANDARD is selected.

(All other coloringFunctions only have a minimumR component)

ISSUE with the Abox type color, each part's value has changed to some degree because of bailout sequence. (e.g aux.color now stops earlier due to bailout change). Luckily there are no aux.DE components.

SOLUTION, to get old behaviour  enable Pre-V2.15 checkbox 

_There are some other issues with NORMAL COLOR mode that i will look at later._

**Comment by mclarekin** [comment]
aux.color limits

Normal mode (abox type only)    extendedAux.color * 100.0
Hybrid mode = min(extendedAux.color, 1000.0) * 100.0
Color_by_numbers has no aux.color limit.

I removed the limit from hybrid mode, and will see if there are any problems, if there are then  an aux.color limit parameter maybe installed.

https://github.com/buddhi1980/mandelbulber2/commit/2ad5c7bd783060cc0138d8591e90a54ddd2ec902

**Comment by mclarekin** [comment]
minimumR name changed to colorMin in c++, and parameter removed from color-by-numbers as it was for testing. Initial value of colorMin set as 1000.0 (can be increased later, but unlikely)

Maximum orbit trap iteration spinbox default now is 1.0.  I may install a checkbox for its use??
 
I am close to finishing color issues relating to the change in bailout. (then aux.DE issues next.) 
I still need to do some things with  the conditions   !standard and !mandelbox.

!mandelbox is a historic thing,  used to take the orbit trap bit out of Abox-color. Since then a lot more formulas use Abox color.

!standard I have yet to figure out exactly.

**Comment by buddhi1980** [comment]
Have you finished changes made to bring backward compatibility? I think the code need to be cleaned up.

**Comment by buddhi1980** [comment]
I have simplified code in compute_fractal.cpp. There was unnecessary spaghetti code.

**Comment by mclarekin** [comment]
Still a work in progress. A lot of spaghetti code was temporary.
I will look at what you have done

four color things I am working on, the first three are almost finished

- backwards compatibility, bailout sequence change
 - fix existing difference between C++ and openCL code
 -add enhancements
- backwards compatibility, aux.DE change

**Comment by mclarekin** [comment]
I will start my questions

a)  compute_fractal.cpp 360

if mandelbox or standard                     if (r > 1e15 || (z -
lastZ).Length() / r < 1e-15) break;
why not bailout sequence??

**Comment by mclarekin** [comment]
b) can (Mode == calcModeColouring) be the first escape condition ??

c) (Mode == calcModeCubeOrbitTrap) has no  bailout, is this correct  ??

**Comment by mclarekin** [comment]
d)  in v2.14 case fractalColoring_Standard:
we give len a value
but I cannot see where it is used after that???

colorMin = len; is what i have assumed was required in v2.14,

                if (fractal->formula != mandelbox
                        || in.material->fractalColoring.coloringAlgorithm
!= fractalColoring_Standard)
                {
                    if (len < colorMin) colorMin = len;
                    if (r > 1e15 || (z - lastZ).Length() / r < 1e-15)
break; // old, is updated v2.15
                    }
                }
                else
                {
                    // colorMin = len;
                    if (r > 1e15 || (z - lastZ).Length() / r < 1e-15) break;
                }

**Comment by mclarekin** [comment]
Next
 f)  Orbit trap calculation can be stopped before termination in a lot of
formulas. Running the calculation to 250 is unnecessary. So
max_orbit_trap_iterations parameter is being trialed.

g) We are missing the most common orbit trap,    which is    case
fractalColoring_Standard:  but with  minimum condition added;
         len = colorZ.Length();  if (len < colorMin) colorMin = len;

**Comment by mclarekin** [comment]
I see i am still not understanding exactly how this all works,  somewhere
in the program it says  color calc  goes to 5 * N.

In fragmentarium, max color iterations works as expected, hmmm??

However this is not required to work for backwards compatibility.

**Comment by buddhi1980** [comment]
a) because of backward compatibility. With GetBailut() it produces completely different colors.
b) Why? Coloring is not a main functionality of ComputeFractal() function.
c) It has a bailout
```
if (zz.x > -size && zz.x < size && zz.y > -size && zz.y < size && zz.z > -size && zz.z < size)
{
  ...
  return;
}
```

d) is used here ``` if (len < colorMin) colorMin = len;```
len is not used only in specialized mandelbox coloring

f) every coloring mode has escape condition. It runs as many iterations as it is needed. It mostly never run to 250 iteration

g) ```if (len < colorMin) colorMin = len;``` is executed later just before bailout condition. No need for modification.

> sorry to have to ask so many questions, but V2.15 is a good time to  tidy
> up this part of the code. :)

You are adding more mess instead of tidying up. Why you cannot keep it is the state as I proposed in commit https://github.com/buddhi1980/mandelbulber2/commit/ab5e2aeafe2557aa63c04ea42256cc5cbb2ad9b6 ?
It was simple and already provided backward compatibility

**Comment by mclarekin** [comment]
a) OK,

 but we do have a backwards compatibility checkBox.
The !mandelbox condition in used in the loop for only 1 formula out of 200.

b)  OK ( i was assumed coloring  was the most commonly called
function in ComputeFractal()
function, so should be first.)

c) OK i see now how it works

d) OK

 I read this code  as Standard ( the most commonly used color algorithm)
requires a  bailout of r >1e15 for all formulas.
As Standard uses r and not minimum r,  it may require a different sized
bailout  to the other orbitTraps

However there is a difference between c++ and openCL

                if (fractal->formula != mandelbox
                        || in.material->fractalColoring.coloringAlgorithm
!= fractalColoring_Standard)
                {
                    if (len < colorMin) colorMin = len;

                    if (!in.material->fractalColoring.colorPreV215False)
                    {
                        if (r > fractals.GetBailout(sequence) || (z -
lastZ).Length() / r < 1e-15) break;
                    }
                    else
                    {
                        if (r > 1e15 || (z - lastZ).Length() / r < 1e-15)
break; // old, is updated v2.15
                    }
                }
                else // for mandbox and  fractalColoring_Standard)
                {
                    if (r > 1e15 || (z - lastZ).Length() / r < 1e-15) break;
                }

whereas in openCL

                if (fractal->formula != 8) // mandelbox has no orbit trap
component
                {
                    if (len < colorMin) colorMin = len;
                    if (aux.r > consts->sequence.bailout[sequence] ||
length(z - lastZ) / aux.r < 1e-6f)
                        break;
                }
                else // for mandelbox
                {
                    if (aux.r > 1e15 || length(z - lastZ) / aux.r < 1e-15f)
break;
                }
f)  When i am not using the orbit trap for coloring,  I want disable the
unnecessary "len" computing  from the loop, I have been using orbit trap
max iters = 0.0 for this.
there are other effects that you can get by varying orbit trap iterations
(but this is still under  evaluation).

am i correct that all points that belong to the set are iterated until N,
and hence the len calculation is run until N.  (or is it actaually N *5)???

BTW I only temporary changed your code because I was going  to win10 OS and
I wanted an appveyor build.  My temporary code has now been removed. :)

**Comment by mclarekin** [comment]
"As Standard uses r and not minimum r,  it may require a different sized
bailout  to the other orbitTraps"  oops that did not make sense.

**Comment by mclarekin** [comment]
j) we have the opurtunity to change  aux.color initial value from 1.0 to
0.0.

At present when using Hybrid Mode, the color index changes by 1.0 *  100.0
for settings that don't have aux.color .

It is a very minor thing, but if you want make the change, I can do the
backwards compatiblility as part of the  pre-2.15 Hybrid color mode.

**Comment by buddhi1980** [comment]
J) it cannot be 0 because if any formula uses multiplication of aux.color, then the result will be always zero.

**Comment by mclarekin** [comment]
Hybrid Mode coloring is effected, to varying degrees, by recent changes to aux.DE and r.

basic hybrid color function is the addition of three parts

  outColor =  orbit trap + aux.color + r / aux.DE

Before when aux.r_dz was used, (log formulas) , the orbitTrap created the color pattern and the other two parts **most often having very little effect.**

The aux.DE change results in the "r / aux.DE" part can have influence with some hybrid combinations.

I need to check the new color on these hybrid combinations 


Mixing log and linear formulas using analyticDE is new to V2.15,  the only backwards compatibility is that in V2.14 this  combination would default to DeltaDE linear.
I was thinking of ignoring this backwards compatibility issue, and only adding it if it proves necessary in the future.

**Comment by mclarekin** [comment]
hybrid mode color still has a c++ vs openCL color  difference. Will fix on Monday

**Comment by mclarekin** [comment]
fixed the last problem,  now investigating yet another color diff

**Comment by mclarekin** [comment]
new issue #558  regarding 4D,  is the last remaining  problem.  Other than #558, Mandelbulber color is working as expected. So I will close this issue. 
There are some enhancements but I will evaluate them later
