### ISSUE TITLE
color difference, pseudo klienian c++,  

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#530]
Current dev2.15 has lost all  pseudo_detail = looks flat, 
6 july version has pseudo_detail  =  is flat but looks  3D.

This is weird as usual :) . Some months ago I had the same problem, and i could not find the cause.  Example  pseudoKleinianMod2 deep zoom.fract was where it was noticed.
![pseudokleinianmod2 deep zoom 214](https://user-images.githubusercontent.com/12769564/44656797-6f85a280-aa4e-11e8-8fda-e4eeb0d39b75.jpg)
![pseudokleinianmod2 deep zoom 215](https://user-images.githubusercontent.com/12769564/44656799-6f85a280-aa4e-11e8-9778-9deb6f96ae6e.jpg)

As that .fract was  zoomed to 1e-09, at the limit of double precision, I was never sure which was the "correct" image, but i  liked the strange pseudo_detail.  

Sometime since then, the detail came back by magic and I had not noticed this, and now it is gone again.
And this time I am only zoomed to 1e-06
![pk mod2 thp1 215](https://user-images.githubusercontent.com/12769564/44656174-ff761d00-aa4b-11e8-8b80-cce71357ca25.jpg)
![pk mod2 thp1](https://user-images.githubusercontent.com/12769564/44656175-ff761d00-aa4b-11e8-8e8f-41b692ec38d8.jpg)

# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 6;
aux_light_colour_1 a200 e800 8d00;
aux_light_intensity_1 1.618539650761645e-07;
aux_light_position_1 -5.406947046450814 2.734379313295701 1.428075419372787;
camera -5.404232822299426 2.739952751463306 1.427596448966547;
camera_distance_to_target 5.760933486875317e-05;
camera_rotation -41.11262668455316 6.03557812600737 -1.604473979823409;
camera_top -0.09020621595920862 -0.06077692531116911 0.9940669011450091;
check_for_bailout_1 false;
DE_factor 0.35;
DE_thresh 1e-15;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 117;
fov 0.5;
fractal_constant_factor 0 -0.05 0;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
main_light_alpha 45;
mat1_coloring_palette_size 34;
mat1_coloring_random_seed 134409;
mat1_fractal_coloring_aux_color_false true;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_max_color_value 6;
mat1_fractal_coloring_orbit_trap_true false;
mat1_is_defined true;
mat1_surface_color a500 c300 3900;
mat1_surface_color_palette ececec 0e5510 e7e7e7 000000 aa0000 e8ea43 e2e245 3b9fee d4ffd4 aba53c;
N 7;
SSAO_random_mode true;
target -5.404195151762026 2.739995914805287 1.42760250635749;
view_distance_max 23;
[fractal_1]
fold_color_aux_color_enabled_false true;
mandelbox_color 0 0 0;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0.9;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main -5 -3 2;
mandelbox_scale -1.1;
transf_addition_constant_111 1.2 1.5 1;
transf_function_enabledBx_false true;
transf_function_enabledBz_false true;
transf_function_enabledS_false true;
transf_minR2_p25 0.8;
transf_rotation -5 -3 2;
transf_stop_iterations_X 2;

**Comment by buddhi1980** [comment]
Now it works properly. There was a bug which caused differences line in issue #526 
The problem was in wrong calculation of surface normal vectors. This produced weird 3D-like artifacts on the surface. The surface was always flat, but diffused light was calculated wrong (like on non-flat surface)

**Comment by mclarekin** [comment]
Do you think that this is the same issue?

![juliabulb zoom 214](https://user-images.githubusercontent.com/12769564/44700381-ec5f5d80-aadc-11e8-8970-cabda9b5c5ba.jpg)
![juliabulb zoom 215](https://user-images.githubusercontent.com/12769564/44700382-ecf7f400-aadc-11e8-84ab-845542034344.jpg)
# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
bailout 12800;
camera -0.1002229402583703 -0.2063886160790259 0.5936642089317112;
camera_distance_to_target 2.615977064118251e-05;
camera_rotation -103.3720340902038 -79.19698503059919 -102.8347883305953;
camera_top 0.0132067462650691 0.999045537676344 -0.04163646841501759;
DE_factor 0.5;
detail_level 4;
DOF_focus 5.204795525060035e-05;
DOF_radius 5.07;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 70;
formula_3 15;
formula_start_iteration_3 5;
formula_stop_iteration_3 8;
fov 0.5;
fractal_enable_2 false;
fractal_enable_3 false;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_width 600;
julia_c 0.162685974081038 -0.2517140088088706 -0.4270112222962116;
keyframe_last_to_render 0;
limit_min -10 0 -10;
main_light_alpha 2;
main_light_beta 4;
main_light_colour fe00 ff00 c200;
mat1_coloring_palette_size 255;
mat1_coloring_random_seed 304980;
mat1_fractal_coloring_add_enabled_false true;
mat1_fractal_coloring_add_spread 0.1;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_global_palette_false true;
mat1_fractal_coloring_iter_add_scale_enabled_true false;
mat1_fractal_coloring_max_color_value 13;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_orbit_trap_weight 64;
mat1_fractal_coloring_rad_div_de_enabled_false true;
mat1_fractal_coloring_rad_div_de_weight 4;
mat1_fractal_coloring_rad_weight 4;
mat1_fractal_coloring_xyz_000 4 0 0;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_width 1;
mat1_surface_color a500 c300 3900;
mat1_surface_color_palette 7dcfc0 b025ba 128b19 280454 fe864b 5539e0 57e1ed 271152 d5564b bb0801 7e7a3a 0b51c2 00229a ffb053 ffba5b 04008b cc73a4 3bc78e 9e3e31 a0488f cb8284 913ed0 cdad71 a2b939 b88edd 5ef6ec e498a2 f4735a b2d0fb 6ea879 95f165 c1a6b4 740f41 1fbb00 1f1ce6 cac4e6 c079a7 805f40 52b393 f3ccff 5feea9 5447d2 4247e8 672828 b9d289 ff4cfb c0234a 42ddea a4c198 273f81 bd53cb 8d7a9a 001748 d6c5c8 38f2ff f0e72a 905c72 e6df9f 5a399b 33c839 5b4640 ffd8d5 dd7d76 1083b3 99922d 904cff b91b48 c228ff afc080 ffabff 003900 ed3a86 768550 6c86d3 003fa6 004600 43f497 d5c958 ff9e4a 4ddf3d 00003e 000073 4759cf 3dc80f 4d38e9 ff8c56 8ea889 61596c 7c5e96 3840cb 815183 c9ced1 df6860 e8c5fd 7dff87 3d895a c4d293 92a5fc 4369b8 f11f2d 9aa746 8bd7ec 37c236 ca4685 2dde8c bb9c2e 3034f1 13193b 2c009e 9759ff 840baf a10000 412b20 ff4c5e 704793 2d8092 910093 296a3a f83785 b131f6 bf2080 353baf 004871 2f05c8 ffbff3 00e57b e06a00 e46a87 be7d2a d0f7bc a84325 071d4a 9a91aa ffea60 c2ff45 a4fffe b3b9dc e5b0c8 ffcce3 ad48c3 31b673 c056ff 3b035c 4d5d16 001219 cc6ad8 0084ae 00916a 7e7477 7a8b4b 5975ff 002765 92f1ff d0c11f 5aeec1 ea5b9e a61d34 941d47 4ab63d 97ffeb c0c0da 5855b2 3effdc 50d3d2 6abb84 f5c467 00c5ac 6e1189 55bab1 6664c0 4606b0 7687a0 dc31a4 5d302d ab65ff 4d17e3 0f0088 e163c1 724d00 397ccf a2ff17 c18fca b94100 002a56 ff4eff dbe9bc 85939d 78a971 2f1900 5db4ef 18a300 abff58 208866 47d1ef 6bbb3a 2638cb 9593ff 88b905 5d1af8 e12fed 4e5aa9 d484ff 2b742b 925cf3 3b451a da9ab9 004374 6111c7 15325a 001fcd b9052f b73297 e7dffc 74c169 a69690 ff7c7b ffbbc5 c300d0 ff876d d6b1ea adf9ff f867c2 f3ffee bcfb1e 001488 813d00 561559 cf9aa0 b91c28 a8d175 2e9f42 1d8760 dbd4ae 925fb0 003000 fffff2 ae409a 493393 26f40a ab3b00 45f50b ea18ba 4a3c56 00a19d 7e1eb0 aad168 b6edf4 bfb5ef d8f000 8de6c3 83e0ff 718d0a 56711c d33503 36da9f;
mat2_is_defined true;
mat2_metallic false;
mat2_reflectance 1;
mat2_specular 1;
mat2_specular_width 1;
mat2_transparency_index_of_refraction 4;
mat2_use_colors_from_palette false;
N 20;
primitive_sphere_1_enabled true;
primitive_sphere_1_material_id 2;
primitive_sphere_1_position 10.58882974441656 -7.10049 -10.72640950659468;
primitive_sphere_1_radius 9.765625000000001e-05;
reflections_max 2;
target -0.1002181699853636 -0.2063897500581396 0.5936385127805051;
use_default_bailout false;
view_distance_max 16.4098445520446;
[fractal_1]
analyticDE_offset_1 0;
transf_addition_constant -0.8 0.1 0;
[fractal_2]
analyticDE_scale_1 0.8;
fold_color_aux_color_enabled_false true;
mandelbox_color 0 0.4 0;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0.1;
power 2.8;
transf_addition_constant_111 1.2 1.5 1;
transf_function_enabled_false true;
transf_minR2_p25 0.9;
transf_rotation -5 -3 2;
[fractal_3]
analyticDE_scale_1 0.8;
fold_color_aux_color_enabled_false true;
mandelbox_color 0 0.4 0;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0.1;
power 4;
transf_addition_constant_111 1.2 1.5 1;
transf_minR2_p25 0.9;
transf_rotation -5 -3 2;

**Comment by mclarekin** [comment]
issue fixed, so can be closed. 

But, I am wondering whether it is practical to have this 3D effect as an option. If it is practical then I will make an Issue# to evaluate in v2.20.
