### ISSUE TITLE
fix 32bit appveyor builds

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#532]
appveyor is failing for each 32-bit build with messages:
error C3615: constexpr function 'qCountLeadingZeroBits' cannot result in a constant expression 

REF: https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/1.0.1.0.0.7.1850-master/job/4d3hb8gvp51mxms3/messages

REF: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3615?view=vs-2017

**Comment by buddhi1980** [comment]
I would abandon creating 32-bit builds. This architecture is obsolete and provides not enough memory space for Mandelbulber program. 2GB is not enough for many cases.
I think almost nobody uses 32-bit systems for making graphics. New hardware doesn't work with 32-bit systems.

**Comment by mancoast** [comment]
sounds good to me!

**Comment by JanWerder** [comment]
I think this issue is obsolete now.
