### ISSUE TITLE
support alternate CUDA OpenCL Headers location

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#533]
The build systems requires support of alternate include path:
"/usr/local/cuda/include/CL/cl.hpp"

REF: https://fractalforums.org/mandelbulb3d/13/installing-mandelbulber3d-on-linuxmint-with-cuda-gpu-enabled

**Comment by buddhi1980** [comment]
Before running qmake script you can run following command:
[code]
export CXXFLAGS=-I/usr/local/cuda/include
[/code]

this will allow to not modify existing code and scripts.

/usr/local/cuda/include is not a standard location for c++ headers
