### ISSUE TITLE
automatic analytic DE function for log linear hybrid combination

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#534]
i have done more testing and it seems the behavior should be changed form linear to log for this combination.

Previously in V2.14 this would default to DeltaDE linear, because analyticDE mix was not possible.

If the algorithm is to be changed then it best to be done in V2.15.

I am not familiar with this part of the code

**Comment by buddhi1980** [comment]
I think it should not be general rule. See example below. It works better with linear DE.
In actual code there is used log or linear depending which formula is used more in hybrid sequence. 
If you use Menger Sponge 3 times and Mandelbulb 2 times, will be used linear DE
If you use Menger Sponge 2 times and Mandelbulb 3 times, will be used log DE
If equal number then used linear.
Maybe we can improve it. For instant it can consider which formula is used first in the sequence.

```
# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 0,7989188099654542 -2,498181754178393 0,7558166578073318;
camera_distance_to_target 1,789276242256164;
camera_rotation 24,48280297329628 -16,77234764942343 -0,6410953299683908;
camera_top -0,1297645549736842 0,2579698082206214 0,9573989441811066;
delta_DE_function 1;
flight_last_to_render 99999;
formula_1 7;
formula_2 3;
formula_iterations_1 2;
formula_iterations_2 2;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_is_defined true;
raytraced_reflections true;
target 0,08895151678309543 -0,9390607718295665 0,2394856824501626;
```

**Comment by mclarekin** [comment]
It is a minor thing, since posting I have found more instances where linear is best, but maybe still more often log.

With v2.15, the users will quickly learn to experiment with different color  functions and .methods
