### ISSUE TITLE
Program becoming unresponsive in openCL full

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#535]
Win10 64 openCL full.  Several occassions program gets stuck at the beginning of compile sources SSAO. Behaviour like endless calculation. 

 Same settings will not reproduce the problem.
  Requires End Process to quit program.
It currently appears to be random.  Possibly my computer, I will try and notice clues but it does not happen very often.
There has been one exception, where problem happened part way through rendering.
I have noticing it happening over the last few weeks
log does not tell me anything

PID: 1612, time: 1318.148, Note: Settings saved to clipboard
PID: 1612, time: 8904.200, Error: Unknown parameter: mat1_fractal_coloring_initial_minimumR
PID: 1612, time: 8908.659, Error: Error in settings file. Line: 33 (mat1_fractal_coloring_initial_minimumR 101;)
PID: 1612, time: 12874.128, Warning: DeleteParameter(): element ' "mat2_metallic" ' doesn't exists 
 (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:574, void __cdecl cParameterContainer::DeleteParameter(const class QString &)

**Comment by buddhi1980** [comment]
Which settings causes this problem? Random or one particular?

**Comment by mclarekin** [comment]
at the moment it seems random but there might be something in common. I am
going to save the settings when ever it happens. Once frozen it contiues to
use about 30% cpu, and the memory usage looks normal.
it happened with these settings, auto refresh on

# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion 0.64;
ambient_occlusion_enabled true;
ambient_occlusion_quality 6;
aux_light_colour_1 a200 e800 8d00;
aux_light_intensity_1 6.45654e-10;
aux_light_position_1 0.1628536359789992 -0.2518680590941453
-0.4270924723668907;
aux_light_volumetric_intensity_1 1.51356e-07;
camera -1.710197397910714 0.1162691575957353 -0.5929359897249614;
camera_distance_to_target 0.02231110446155075;
camera_rotation 17.79416290903314 18.6471599824939 -11.75474818750207;
camera_top -0.09831425473275608 -0.3603159148917226 0.9276350299509412;
check_for_bailout_1 false;
constant_DE_threshold true;
DE_factor 0.35;
DE_thresh 3e-05;
delta_DE_function 3;
delta_DE_method 2;
DOF_focus 5.204795525060035e-05;
DOF_radius 5.07;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 117;
formula_2 20;
formula_start_iteration_2 4;
formula_stop_iteration_2 21;
fractal_constant_factor 0 -0.05 0;
hdr true;
hybrid_fractal_enable true;
image_height 540;
image_width 960;
julia_c 0.162685974081038 -0.2517140088088706 -0.4270112222962116;
keyframe_last_to_render 0;
limit_min -10 0 -10;
limits_enabled true;
mat1_coloring_palette_offset 2.5;
mat1_fractal_coloring_aux_color_false true;
mat1_fractal_coloring_aux_color_weight 0.39;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_orbit_trap_weight 3.9;
mat1_fractal_coloring_rad_div_de_weight 19.5;
mat1_fresnel_reflectance true;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_width 1;
mat1_surface_color a500 c300 3900;
mat1_transparency_index_of_refraction 5.92;
N 11;
reflections_max 2;
SSAO_random_mode true;
target -1.716657714089296 0.1363977316292839 -0.5858022526578321;
volumetric_fog_colour_1_distance 8.435289968938831e-06;
volumetric_fog_colour_2_distance 1.687057993787766e-05;
volumetric_fog_density 0.0625;
volumetric_fog_distance_factor 1.687057993787766e-05;
volumetric_fog_enabled true;
[fractal_1]
fold_color_aux_color_enabled_false true;
mandelbox_color 0 0.4 0;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0.3;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main -5 -3 2;
mandelbox_scale -1.1;
transf_addition_constant_111 1.2 1.5 1;
transf_function_enabledBx_false true;
transf_function_enabledBz_false true;
transf_function_enabledS_false true;
transf_minR2_p25 0.8;
transf_rotation -5 -3 2;
transf_stop_iterations_X 2;

**Comment by mclarekin** [comment]
update
3 or 4 times today
 I think auto refresh was on everytime
Feels like it maybe caused by mouse clicking  while rendering.
I was probably   clicking  on Render or changing between full, medium and no openCL

**Comment by buddhi1980** [comment]
Does it happen with nVidia? Are you running the latest code? Have you tried
to "Disable OpenCL cache" for one run (to clear cache)?

niedz., 9 wrz 2018 o 11:33 mclarekin <notifications@github.com> napisał(a):

**Comment by mclarekin** [comment]
this is happening on my AMD card, latest appveyor build.

testing with my nVidia is a good idea, i will swap over to my other laptop
for a couple of days and see if the problem occurs.

**Comment by mclarekin** [comment]
In general I am noticing longer compile times, but this may be due to more OpenCL implementation

nVidia  gtx 960m,  latest appveyor build .
Have yet to have the original problem

I have a complete crash of program, and currently reproducible

PID: 2136, time: 1612.012, Critical: OpenCl ERROR:  "CommandQueue::enqueueReadBuffer() for output-buffer"  ( -5 ) (c:\projects\mandelbulber2\mandelbulber2\src\opencl_engine.cpp:73, bool __cdecl cOpenClEngine::checkErr(int,class QString)


**Is this log message tells users to "Disable OpenCL cache" for one run (to clear cache)**


Now I have  done that and it appears to be fixed



# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
aux_light_colour_1 0000 5500 ff00;
aux_light_colour_3 0000 5500 ff00;
aux_light_enabled_1 true;
aux_light_intensity_1 0.02886529193711786;
aux_light_intensity_3 3e-06;
aux_light_position_1 -1.109695193235089 -0.3609342946551908 0.02473488327111538;
aux_light_position_3 1.415822692462141 -5.95 6.784;
aux_light_volumetric_enabled_1 true;
camera -0.08334172878218893 -0.3600444169170662 0.009656399375115272;
camera_distance_to_target 0.074706457555294;
camera_rotation 90 0 0;
camera_top 0 0 1;
DE_factor 0.3;
delta_DE_function 2;
delta_DE_method 2;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_1 125;
formula_2 115;
formula_start_iteration_2 7;
hybrid_fractal_enable true;
image_width 900;
iteration_fog_color_1 ff00 ff00 7f00;
iteration_fog_color_2_maxiter 26;
iteration_fog_enable true;
iteration_fog_opacity_trim_high 17;
keyframe_last_to_render 0;
main_light_beta 0;
mat1_color_texture_intensity 4;
mat1_file_color_texture C:\Users\graeme\mandelbulber\my images colours\mona-lisa-on-instagram-3.jpg;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_width 1;
N 23;
primitive_rectangle_1_enabled true;
primitive_rectangle_1_material_id 2;
primitive_rectangle_1_position -0.366627494906881 -0.4470102400758636 0.00651817334215939;
raytraced_reflections true;
target -0.1580481863374829 -0.3600444169170662 0.009656399375115272;
volumetric_fog_colour_1_distance 0.003192682051074617;
volumetric_fog_colour_2_distance 0.006385364102149234;
volumetric_fog_density 0.1;
volumetric_fog_distance_factor 0.006385364102149234;
[fractal_1]
analyticDE_scale_1 1.2;
transf_addition_constant_111 0.4 1 1;
transf_function_enabledM_false true;
transf_maxR2_1 1.2;
transf_scale 0.97;
transf_scale_vary_0 0.1;
transf_scaleB_1 1.2;
transf_start_iterations_A 8;
[fractal_2]
transf_function_enabledM false;
transf_scale_2 1.7;

**Comment by mclarekin** [comment]
getting a big difference between  full and no OpenCL, with above settings

**Comment by mclarekin** [comment]
I think it is enabling fog based on iteration count, that thes big difference

**Comment by mclarekin** [comment]
another nVidia crash when hit render, program closed.


PID: 13876, time: 0.015, Prepare QApplication
PID: 13876, time: 0.019, Prepare translator
PID: 13876, time: 0.023, locale, value = en_NZ
PID: 13876, time: 0.030, Installing translator
PID: 13876, time: 0.058, CreateDefaultFolders()
PID: 13876, time: 0.062, Directory already exists, value = C:\Users\graeme\mandelbulber\
PID: 13876, time: 0.065, Directory already exists, value = C:\Users\graeme\mandelbulber\
PID: 13876, time: 0.069, Directory already exists, value = C:\Users\graeme\mandelbulber\images
PID: 13876, time: 0.072, Directory already exists, value = C:\Users\graeme\mandelbulber\thumbnails
PID: 13876, time: 0.076, Directory already exists, value = C:\Users\graeme\mandelbulber\toolbar
PID: 13876, time: 0.079, Directory already exists, value = C:\Users\graeme\mandelbulber\httpCache
PID: 13876, time: 0.082, Directory already exists, value = C:\Users\graeme\mandelbulber\customWindowState
PID: 13876, time: 0.085, Directory already exists, value = C:\Users\graeme\mandelbulber\settings
PID: 13876, time: 0.089, Directory already exists, value = C:\Users\graeme\mandelbulber\slices
PID: 13876, time: 0.092, Directory already exists, value = C:\Users\graeme\mandelbulber\materials
PID: 13876, time: 0.096, Directory already exists, value = C:\Users\graeme\mandelbulber\animation
PID: 13876, time: 0.102, Parameters initialization started: main
PID: 13876, time: 0.109, Parameters initialization finished
PID: 13876, time: 0.112, Fractal parameters initialization started: fractal0
PID: 13876, time: 0.117, Fractal parameters initialization finished
PID: 13876, time: 0.122, Fractal parameters initialization started: fractal1
PID: 13876, time: 0.127, Fractal parameters initialization finished
PID: 13876, time: 0.131, Fractal parameters initialization started: fractal2
PID: 13876, time: 0.135, Fractal parameters initialization finished
PID: 13876, time: 0.139, Fractal parameters initialization started: fractal3
PID: 13876, time: 0.144, Fractal parameters initialization finished
PID: 13876, time: 0.147, Fractal parameters initialization started: fractal4
PID: 13876, time: 0.151, Fractal parameters initialization finished
PID: 13876, time: 0.155, Fractal parameters initialization started: fractal5
PID: 13876, time: 0.159, Fractal parameters initialization finished
PID: 13876, time: 0.166, Fractal parameters initialization started: fractal6
PID: 13876, time: 0.171, Fractal parameters initialization finished
PID: 13876, time: 0.174, Fractal parameters initialization started: fractal7
PID: 13876, time: 0.180, Fractal parameters initialization finished
PID: 13876, time: 0.184, Fractal parameters initialization started: fractal8
PID: 13876, time: 0.189, Fractal parameters initialization finished
PID: 13876, time: 0.196, Loading settings started, value = C:\Users\graeme\mandelbulber\mandelbulber_215.ini
PID: 13876, time: 0.199, Settings loaded, value = # Mandelbulber settings file
# version 2.15
# application settings
[main_parameters]
alpha_enabled false;
alpha_postfix _alpha;
alpha_quality 0;
append_alpha_png true;
auto_refresh false;
auto_refresh_period 0.1;
auto_save_images false;
aux_light_manual_placement_dist 0.1;
camera_absolute_distance_mode relative;
camera_movement_mode fixed_distance;
camera_movement_step 0.5;
camera_rotation_mode rotate_camera;
camera_rotation_step 15;
camera_straight_rotation constant_top;
color_enabled true;
color_postfix ;
color_quality 0;
default_image_path C:\Users\graeme\mandelbulber\images;
default_settings_path C:\Users\graeme\mandelbulber\settings;
default_textures_path C:\Users\graeme\Downloads\mandelbulber-Release-x64-33e7e588ce1110036be7568ff13c6fcf055bfe49\build-win\Release\x64\textures;
description_popup_do_not_show_again false;
flight_animation_image_type png;
flight_sec_per_frame 1;
flight_show_thumbnails false;
grid_type 1;
image_detached false;
image_preview_scale 0;
jpeg_quality 95;
julia_preview_distance 3;
keyframe_animation_image_type png;
keyframe_auto_validate true;
language ;
limit_CPU_cores 8;
logging_verbosity 1;
mesh_color true;
mesh_file_mode 0;
net_render_client_IP 10.0.0.4;
net_render_client_port 5555;
net_render_server_port 5555;
netrender_client_remote_address localhost;
netrender_client_remote_port 5555;
netrender_mode 1;
netrender_server_local_port 5555;
normal_enabled false;
normal_postfix _normal;
normal_quality 2;
opencl_device_list 9630d7;
opencl_device_type gpu;
opencl_disable_build_cache false;
opencl_enabled true;
opencl_memory_limit 512;
opencl_mode full;
opencl_platform 1;
opencl_precision single;
opencl_use_fast_relaxed_math true;
queue_image_format png;
quit_do_not_ask_again false;
save_image_format 0;
show_camera_path true;
show_cursor true;
show_keyframe_thumbnails false;
show_light_path_1 true;
show_light_path_2 true;
show_light_path_3 true;
show_light_path_4 true;
show_queue_thumbnails false;
show_target_path true;
stereoscopic_in_separate_files false;
system_tray_notify false;
threads_priority 2;
toolbar_icon_size 64;
ui_colorize true;
ui_colorize_random_seed 12345;
ui_font_size 7;
ui_skin 4;
ui_style_type 3;
upgrade_do_not_ask_again false;
voxel_show_information true;
zbuffer_enabled false;
zbuffer_postfix _zbuffer;
zbuffer_quality 2;

PID: 13876, time: 0.203, cSettings::Decode(cParameterContainer *par, cFractalContainer *fractPar, cAnimationFrames *frames)
PID: 13876, time: 519.917, Warning: Get(): element ' "mat2_name" ' doesn't exists 
 (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:310, class QString __cdecl cParameterContainer::Get<class QString>(class QString) const
PID: 13876, time: 520.386, Warning: Get(): element ' "mat2_name" ' doesn't exists 
 (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:310, class QString __cdecl cParameterContainer::Get<class QString>(class QString) const
PID: 13876, time: 520.576, Warning: Get(): element ' "mat2_name" ' doesn't exists 
 (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:310, class QString __cdecl cParameterContainer::Get<class QString>(class QString) const
PID: 13876, time: 521.024, Warning: Get(): element ' "mat2_name" ' doesn't exists 
 (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:310, class QString __cdecl cParameterContainer::Get<class QString>(class QString) const
PID: 13876, time: 573.343, Critical: OpenCl ERROR:  "CommandQueue::enqueueReadBuffer() for output-buffer"  ( -5 ) (c:\projects\mandelbulber2\mandelbulber2\src\opencl_engine.cpp:73, bool __cdecl cOpenClEngine::checkErr(int,class QString)

**Comment by buddhi1980** [comment]
There are two problems here:

> PID: 1612, time: 12874.128, Warning: DeleteParameter(): element ' "mat2_metallic" ' doesn't exists
> (c:\projects\mandelbulber2\mandelbulber2\src\parameters.cpp:574, void __cdecl cParameterContainer::DeleteParameter(const class QString &)

This one I have just solved. "metallic" parameter was duplicated on parameters list

The last problem was probably caused by used material no. 2 which is not defined.

**Comment by mclarekin** [comment]
_The last problem was probably caused by used material no. 2 which is not defined_.
Possibly, although these warning element does not exists messages, do not normally crash the program for me.

I have not tested enough with Nvidia yet, but other then these type of crashes , it is working well. Anyway I can test these settings again later, with and without the bad mat2 in the settings file.

I am about to use my  AMD, and have another look at the problem i have there.

**Comment by mancoast** [comment]
I have a question here, if we hypothesize that a bad mat2 causes a crash, can we detect and warn the user before crash?

**Comment by buddhi1980** [comment]
@mancoast , you are right. There should be error handling for missing material. I will add separate issue for it.

**Comment by mclarekin** [comment]
AMD openCL no crashes lately? Hmmm?

**Comment by mclarekin** [comment]
update still lots of problems occurring, as usual it may be more than one issue.
The freezing at SSAO  also can happen without auto-refresh enabled 


Getting complete crashes of the program as well. This is AMD card Win10

PID: 2124, time: 0.022, Prepare QApplication
PID: 2124, time: 0.028, Prepare translator
PID: 2124, time: 0.033, locale, value = en_NZ
PID: 2124, time: 0.062, Installing translator
PID: 2124, time: 5.133, CreateDefaultFolders()
PID: 2124, time: 5.142, Directory already exists, value = C:\Users\Graeme\mandelbulber\
PID: 2124, time: 5.149, Directory already exists, value = C:\Users\Graeme\mandelbulber\
PID: 2124, time: 5.156, Directory already exists, value = C:\Users\Graeme\mandelbulber\images
PID: 2124, time: 5.163, Directory already exists, value = C:\Users\Graeme\mandelbulber\thumbnails
PID: 2124, time: 5.168, Directory already exists, value = C:\Users\Graeme\mandelbulber\toolbar
PID: 2124, time: 5.184, Directory already exists, value = C:\Users\Graeme\mandelbulber\httpCache
PID: 2124, time: 5.187, Directory already exists, value = C:\Users\Graeme\mandelbulber\customWindowState
PID: 2124, time: 5.190, Directory already exists, value = C:\Users\Graeme\mandelbulber\settings
PID: 2124, time: 5.193, Directory already exists, value = C:\Users\Graeme\mandelbulber\slices
PID: 2124, time: 5.197, Directory already exists, value = C:\Users\Graeme\mandelbulber\materials
PID: 2124, time: 5.200, Directory already exists, value = C:\Users\Graeme\mandelbulber\animation
PID: 2124, time: 5.204, Parameters initialization started: main
PID: 2124, time: 5.209, Parameters initialization finished
PID: 2124, time: 5.212, Fractal parameters initialization started: fractal0
PID: 2124, time: 5.216, Fractal parameters initialization finished
PID: 2124, time: 5.219, Fractal parameters initialization started: fractal1
PID: 2124, time: 5.224, Fractal parameters initialization finished
PID: 2124, time: 5.226, Fractal parameters initialization started: fractal2
PID: 2124, time: 5.231, Fractal parameters initialization finished
PID: 2124, time: 5.234, Fractal parameters initialization started: fractal3
PID: 2124, time: 5.238, Fractal parameters initialization finished
PID: 2124, time: 5.241, Fractal parameters initialization started: fractal4
PID: 2124, time: 5.245, Fractal parameters initialization finished
PID: 2124, time: 5.248, Fractal parameters initialization started: fractal5
PID: 2124, time: 5.252, Fractal parameters initialization finished
PID: 2124, time: 5.255, Fractal parameters initialization started: fractal6
PID: 2124, time: 5.259, Fractal parameters initialization finished
PID: 2124, time: 5.324, Fractal parameters initialization started: fractal7
PID: 2124, time: 5.339, Fractal parameters initialization finished
PID: 2124, time: 5.347, Fractal parameters initialization started: fractal8
PID: 2124, time: 5.357, Fractal parameters initialization finished
PID: 2124, time: 5.369, Loading settings started, value = C:\Users\Graeme\mandelbulber\mandelbulber_215.ini
PID: 2124, time: 5.379, Settings loaded, value = # Mandelbulber settings file
# version 2.15
# application settings
[main_parameters]
alpha_enabled false;
alpha_postfix _alpha;
alpha_quality 0;
append_alpha_png true;
auto_refresh false;
auto_refresh_period 0.1;
auto_save_images false;
aux_light_manual_placement_dist 8.966930000000001e-05;
camera_absolute_distance_mode absolute;
camera_movement_mode fixed_distance;
camera_movement_step 0.2166233575368364;
camera_rotation_mode rotate_camera;
camera_rotation_step 1;
camera_straight_rotation constant_top;
color_enabled true;
color_postfix ;
color_quality 0;
default_image_path C:\Users\Graeme\mandelbulber\images;
default_settings_path C:\Users\Graeme\mandelbulber\settings;
default_textures_path C:\Users\Graeme\Downloads\mandelbulber-Release-x64-9986fda54bfb3a5ad8a68e7914d241fabef8c0e2\build-win\Release\x64\textures;
description_popup_do_not_show_again false;
flight_animation_image_type png;
flight_sec_per_frame 1;
flight_show_thumbnails false;
grid_type 1;
image_detached false;
image_preview_scale 0;
jpeg_quality 95;
julia_preview_distance 3;
keyframe_animation_image_type png;
keyframe_auto_validate true;
language ;
limit_CPU_cores 8;
logging_verbosity 1;
mesh_color true;
mesh_file_mode 0;
net_render_client_IP 10.0.0.4;
net_render_client_port 5555;
net_render_server_port 5555;
netrender_client_remote_address localhost;
netrender_client_remote_port 5555;
netrender_mode 1;
netrender_server_local_port 5555;
normal_enabled false;
normal_postfix _normal;
normal_quality 2;
opencl_device_list 7c2a20;
opencl_device_type gpu;
opencl_disable_build_cache false;
opencl_enabled true;
opencl_memory_limit 512;
opencl_mode full;
opencl_platform 1;
opencl_precision single;
opencl_use_fast_relaxed_math false;
queue_image_format png;
quit_do_not_ask_again false;
save_image_format 0;
show_camera_path true;
show_cursor true;
show_keyframe_thumbnails false;
show_light_path_1 true;
show_light_path_2 true;
show_light_path_3 true;
show_light_path_4 true;
show_queue_thumbnails false;
show_target_path true;
stereoscopic_in_separate_files false;
system_tray_notify false;
threads_priority 2;
toolbar_icon_size 64;
ui_colorize true;
ui_colorize_random_seed 12345;
ui_font_size 7;
ui_skin 4;
ui_style_type 3;
upgrade_do_not_ask_again false;
voxel_show_information true;
zbuffer_enabled false;
zbuffer_postfix _zbuffer;
zbuffer_quality 2;

PID: 2124, time: 5.384, cSettings::Decode(cParameterContainer *par, cFractalContainer *fractPar, cAnimationFrames *frames)

**Comment by buddhi1980** [comment]
This commit https://github.com/buddhi1980/mandelbulber2/commit/f6d9d0603030df0bf4a5b47845c796b92257b219 probably fixes this bug
