### ISSUE TITLE
Loading textures from https (secured) web pages doesn't work

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#539]
OS: Debian Buster

cResourceHttpProvider probably doesn't use correct SSL configuration or it's a problem in my system

It produces folowing error:
```
Critical: Error when downloaded file! "Unknown error" "https://mandelbulber.com/img/underConstruction.png" (../src/resource_http_provider.cpp:116, void cResourceHttpProvider::loadOverInternet()
```

I have tried to load texture for instant from https://mandelbulber.com/img/underConstruction.png

Example settings:
```
# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
flight_last_to_render 99999;
keyframe_last_to_render 0;
mat1_file_color_texture https://mandelbulber.com/img/underConstruction.png;
mat1_is_defined true;
mat1_use_color_texture true;
raytraced_reflections true;
```

@zebastian can you check it it works on your PC?

**Comment by zebastian** [comment]
hmm, there is something else odd about the cResourceHttpProvider, the issue also occurs with http urls

**Comment by zebastian** [comment]
the solution with QEventLoop seems to be broken, if i use the previous construct instead:
```
	while (!reply->isFinished())
	{
		Wait(10);
		gApplication->processEvents();
	}
```
I get a file with some bytes, but only the top part of ther image (probably some buffer issue).

Seems like we need a streamable [QNetworkReply --> File] solution...
