### ISSUE TITLE
Mouse disappears

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#546]
Reported by Facebook william chang li

William's posts
a) 
2.15 alpha2 crashes on Ubuntu 18.04 Mate Desktop
Start program
set image to 480 x 270
hit render
set water primitive (no material!)
hit render
activate Light #1
activate "set light behind object"
click "set light by mouse"
if I now try to set the light in the Render Window , on click, the mouse disapears (only in mandelbulber window) and MB seems to do something in the background but never stops.
Is this known?

b)
If I follow the steps above it happens everytime, but if i do the "light things" before and then place the water primitive it works fine!

c)
Ahh . When "it" happens. I can close the program by right click on the windows bar, clicking close brings up the "close dialog" and in this dialog the mouse is there and works, but the "widget" is still running and I can only close it by end the MB-Process!

**Comment by mclarekin** [comment]
I  have occassionally had the mouse pointer dissappear.  I have never been able to reproduce, or any clues.
Assumed it may have been my mouse or computer

**Comment by Starmute** [comment]
Mouse pointer disappears quite frequently on macOS. It happens always in save settings menu but beyond that it's difficult to reproduce issue reliably.

**Comment by mclarekin** [comment]
"It happens always in save settings menu"

This definitely happens in Win10 64, but  randomly .

**Comment by buddhi1980** [comment]
The bug described in bug report is fixed. Another problems of disappearing mouse pointer are difficult to reproduce and should be reported in separate issue.
