### ISSUE TITLE
Long render time if texture file is not in c

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#547]
Reported Steve Sink
the main bits are in bold text 

The program closed down completely when I was starting a render. It did it three times actually, but each time was at one point in the render with a bunch of primitives. I switched to a higher power card for that frame and then it all worked again. I've had them crunching two days on all 4 cards of the scene that K made with the brick Menger world, doing a 4K animation with a flecked-marble cone stuck in the middle of the scene for no reason. Oh--I keep getting this error on the command line window: "libpng warning: iccp: known incorrect sRGB profile"

_Thanks,
a) what was the lower powered card
b) **"libpng warning: iccp: known incorrect sRGB profile**" is interesting, i do not think I have seen that before, hmmmm??_

 I get that warning on all 4 PCs and 4 videocards running the texture OpenCl render. But it otherwise works anyway!

further development: **that same 980 takes an hour to render an image that the OTHER 980 card does in 3-4 minutes.** Yet it is fully engaged, and at full hertz speed. And only seems to affect renders with textures. I’m going to play with it a bit more and then report back. Baffling to me so far.

Further experimentation, Carbuncle Grim and Krzysztof: the GTX 980 running on my Ryzen 1800x Windows system will not render an OpenCl texture without taking at least an hour, whereas the 980 on a different Windows system takes 3-4 minutes. The Ryzen 1800x/GTX980 system has the latest NVdia and Windows drivers and updates, and I pulled the latest build of 2.15 off Github. I opened an example file, and it rendered in normal time. Using the textures in OpenCl, it takes an hour per frame. **The only difference is that the Ryzen system is pulling the textures from the C drive that Windows is installed on (an SSD drive), whereas the other systems pull it from a separate D drive that is not an SSD.** Otherwise, both are MSI GTX 980s from the same model and even same batch. A very strange problem!

I switched out all the brick textures for the default texture, and everything runs normally on the Ryzen 1800x/GTX980 system. Add the brick or any other texture map/png back in, and it takes an hour (reportedly, I only ran it a few minutes). Yet the Ryzen 2990WX/GTX980 system runs smoothly on the brick texture, as well as a 1080 and a 1080TI. That one Ryzen PC will not run the textures without taking forever. Okay I'm going to use it to make other animations, since it can't render frames from the current BrickWorld animation.

**So, the only variable between working 980 and not-working 980 was the type of drive and location of the texture files. So I stuck the brick textures files in a different folder and remapped. The material icon at the top of the material pane will only show the default icon, but the texture icons within the pane all show the textures, and it renders at normal speed now. I'm using the same files--just mapping it to different locations on the C drive. Well, it's mostly-fixed now, although I still don't know what's going on. Why can it find a texture map HERE and take an hour, yet if I put it over here, it still works and looks the same but only takes 3 minutes now? Gotta be something with Windows explorer or files directories. Attached is the screenshot. Note the default icon yet the sub-icons below are showing**. I'll leave you alone now and keep playing with textures! And sorry, Faris Nasir for hijacking your post! Excellent picture, sir!

_I do not understand fully, but there is a part of the program that looks for your texture file if it is not where it is expected to be. I think it would be best if this can be be disabled by the user, because I have in the past had some major slow-downs when loading old toolbar presets, and watched and waited as the program searched for maybe 100 texture/background images. Krzysztof Marczak ??_

**Comment by mclarekin** [comment]
It happened occasionally for me in the past, but have since kept all my my  resources in users/graeme/mandelbulber. I think my past problems were when getting files from D:\.


It was a problem when loading old preset toolbars that had a lot of  files linked to D:\

**Comment by zebastian** [comment]
Interesting problem. Generally this is an issue with windows and drive handling (I think the D drive in this scenario may has the texture scattered fragmented on the disk and the OS is not capable of caching the file inteligentally for quicker access by itself)
Anyway: We cannot generally keep all loaded textures in memory but it might be interesting to have an option for animations to have an extra option to do that for quicker access. 
@buddhi1980 what do you think?

**Comment by buddhi1980** [comment]
I cannot reproduce problem with long loading of textures. I have tested it under Windows and located textures on different drives. 
It could be the problem with antivirus software or fragmentation of the drive.
About memory cache for textures actually I don't have idea how to implement it. It would consume a lot of memory and it is difficult to asses which texture is still needed in cache. Especially when on every frame of animation you can use different texture (image sequences)

**Comment by buddhi1980** [comment]
Is it still reproducible for any of you?

**Comment by mclarekin** [comment]
I have not noticed this behaviour for a long time. Would suggest close and
reopen if we get a reproducible setting
