### ISSUE TITLE
feature request - Add option for multiple orbit trap light sets

### ISSUE THREAD

**Issue by Starmute** [buddhi1980/mandelbulber2#549]
Hi,

I've been working pretty extensively with orbit trap lighting recently in Mandelbulber and it seems to me that having an option for multiple separate orbit trap light sets with different colors. This is probably trivial to implement so it should not be too difficult.

**Comment by mclarekin** [comment]
Thanks for posting. There are various lighting enhancements proposed, to be
evaluated once openCL implementation is complete.

BTW what operating system are you using?
Have you had any crashing or freezing of the program?
What I am looking for is users who can run in QT debug mode and produce
backtrace files after a crash

**Comment by buddhi1980** [comment]
It is not trivial to implement it. It will make fractal calculation algorithm much more complicated and redesign of user interface for orbit traps lights. I will keep this issue to remember this proposal of enhancement.

**Comment by mclarekin** [comment]
added to #574
