### ISSUE TITLE
Interpolate Next Keyframes Issue

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#55]
I have added three key frames, I then right clicked in the white space to the right of the keyframe parameters, and action  "Interpolate next keyframes", then program crashed.

Application Output from QT Creator
The program has unexpectedly finished.
/home/graeme/git/mandelbulber2/mandelbulber2/build-mandelbulber-Desktop-Debug/mandelbulber2 crashed

# Mandelbulber settings file
# version 2.06
# only modified parameters
[main_parameters]
ambient_occlusion 1.3;
ambient_occlusion_enabled true;
ambient_occlusion_quality 10;
background_color_1 0000 6700 ac00;
background_color_2 0000 6700 ac00;
background_color_3 0000 6700 ac00;
camera 0 -3.826271362488594 0;
camera_distance_to_target 3.831494817874653;
camera_rotation -2.992139279808613 0 0;
camera_top 0 0 1;
coloring_palette_size 255;
DE_factor 0.35;
flight_last_to_render 0;
formula_1 57;
frames_per_keyframe 25;
image_height 300;
image_width 300;
keyframe_last_to_render 50;
specular 0.4;
surface_color_palette ff0000 698403 fff59c f5bd22 0b5e87 c68876 ff0000 3b9fee d4ffd4 aba53c;
target 0.2 0 0;
[fractal_1]
transform_benesiFastPwr2PineTree1_enabled true;
transform_benesiFastPwr2PineTree1_start_iterations 1;
transform_benesiFastPwr2PineTree1_stop_iterations 3;
transform_benesiMagTransformOne2_enabled true;
transform_benesiMagTransformOne2_stop_iterations 5;
transform_coloringParameters1_stop_iterations 1;
transform_fabsFormulaAB1A 0 1 0;
transform_main_rotation2 0 90 0;
transform_main_rotation2_enabled true;
transform_main_rotation3 45 0 0;
transform_variableConstantMultiplier1_enabled true;
transform_variableConstantMultiplier1_variableConstantMultiplier 2 0 0;
[fractal_2]
[fractal_3]
[fractal_4]
[fractal_5]
[fractal_6]
[fractal_7]
[fractal_8]
[fractal_9]

**Comment by buddhi1980** [comment]
Fixed by commit 65d920c
