### ISSUE TITLE
size of GPU workgroup pixels query

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#551]
Michael Sblabla wrote

Can someone tell me on what the "workgroup pixels" in MB depend? In view of the mentioned speed I tried a driver-update for my GPU on my system. i am using a NVidia GTX 660ti and my driver was 391.24 (march 2018). Workgroup pixels in MB showed me "1024" while rendering Krzysztofs 'Cloud Computing'-settingsfile. After I updated to the latest NVidia-driver (411.63), the "workgroup pixels" shrinked to 256?! And estimated rendertime increased 10 Minutes (!) for the same picture. The value definately changed with the driver, I made no changes elsewhere - now I reverted it back to 391.24 and it shows 1024 workgroup-pixels again in MB and rendertime is back to normal. Why does the latest NVidia-driver shrink the "workgroup pixels" in MB and increase my rendertime so much? Edit: now I have installed version 399.07, workgrup pixels 1024. It seems in the actual driver changed something, but what? Should I report it to Nvidia? Is it possibly an issue?

**Comment by buddhi1980** [comment]
This is probably an issue of graphics driver. I need to check it under Windows. I can try to upgrade NVidia drivers and check what will happen.

**Comment by mclarekin** [comment]
initial test workgroup size using standard menger preset
old AMD gpu is 256 (and for every setting i tried)
nVidia 960m  is 512 for menger, and  KIF 384

**Comment by buddhi1980** [comment]
On NVidia GTX 1050 I'm getting the same numbers: 512 for menger and 384 for KIFS. 896 for Menger in fast mode.

**Comment by buddhi1980** [comment]
I have upgraded NVidia driver under Windows to version 411. I'm getting exactly the same problem as Michael. Workgroup size is always 256, even in fast mode. Rendering is much slower. It looks like this version of driver is broken.
