### ISSUE TITLE
Orbit trap lights never work with pure pseudo kleinian fractal

### ISSUE THREAD

**Issue by Starmute** [buddhi1980/mandelbulber2#552]
Hi,

This may not be an actual issue with the code specifically but for some reason orbit trap lights never work with pseudo kleinian fractals when there is no hybrid involved. This is on master branch.

**Comment by mclarekin** [comment]
I have not looked properly at that code before, 

a) have you got check for bailout condition ticked?

b) hmmm? it currently is not set up for 4D orbit trap

c) hmmmm?  There is a lot of new options to evaluate. I think a Transform_Orbit_trap_lights might be  evaluated

**Comment by Starmute** [comment]
(A) yes.

(B) is PK 4D??

**Comment by mclarekin** [comment]
I have never used orbit traps lights so I will try it out with a standard pseudoKleinian


a) When I read the code, I noticed  bailout was needed for orbit trap lights, even though you can run a pseudoK formula without bailout ( I learn something new everyday.)

  b) & c ) was just random notes to myself. 4D pseudoKleinian is possible, as are  a lot of interesting 4D stuff that may never reach the top of the "TODO list" 

4D is actually just pseudo-4D, as we seed the fourth dimension with a constant, or a "varying constant" that varys over iteration time. True 4D would have a proper w axis ( 0  to infinity). This calculation is possibly feasible now with GPU power  (and a very fast formula).

**Comment by mclarekin** [comment]
I can make light  but not control it at all.  It may be the type of formula?? I will have a look at boxBulbs and some others. And where and how out.orbitTrapR is used

# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 0000 0000 0000;
camera 120.9110049724631 -99.71183524993648 -110.9045540041811;
camera_distance_to_target 191.9941179078875;
camera_rotation 50.48857667455202 35.28511524366513 52.74859200458647;
camera_top 0.7761918773806116 0.391639480849833 0.4941099943616148;
DE_factor 0.5;
fake_lights_color ec00 0000 0000;
fake_lights_enabled true;
fake_lights_intensity 0.5;
fake_lights_orbit_trap 0 0 48;
fake_lights_visibility 12;
fake_lights_visibility_size 8.5;
flight_last_to_render 0;
formula_1 103;
keyframe_last_to_render 0;
mat1_coloring_palette_offset 8.210000000000001;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_width 1;
mat1_use_colors_from_palette false;
N 12;
raytraced_reflections true;
view_distance_max 519.7485785363717;
[fractal_1]
IFS_rotation_enabled true;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by mclarekin** [comment]
It works OK with boxbulb layers. Wow, i am beginning to understand orbit trap lights ( i was always put off by the tootip  " .... difficult ... have to try many".....).  Cool effects.


# Mandelbulber settings file
# version 2.14
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 8;
background_3_colors_enable false;
background_color_1 0000 0000 0000;
camera -0.1512989411688999 0.03907374713141454 -0.279737967376164;
camera_distance_to_target 0.1642552159847475;
camera_rotation -101.2877350584828 44.7498933419609 -28.22888617926792;
camera_top -0.5157010103425834 0.5852572677742363 0.6257207032287445;
DE_factor 0.5;
fake_lights_color 0000 0000 ff00;
fake_lights_enabled true;
fake_lights_intensity 8;
fake_lights_min_iter 0;
fake_lights_orbit_trap 0 0 8;
fake_lights_visibility 30;
fake_lights_visibility_size 7.5;
flight_last_to_render 0;
formula_1 125;
keyframe_last_to_render 0;
mat1_coloring_palette_offset 8.210000000000001;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_width 1;
mat1_use_colors_from_palette false;
raytraced_reflections true;
target -0.03690351959122395 0.01624075084477444 -0.1641000939054185;
[fractal_1]
IFS_rotation_enabled true;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by mclarekin** [comment]
It maybe the maths of the orbit trap lights does not suit the pseudoKleiinan fractal maths.
Orbit trap maths was implemented long before we had pseudoKleininan

@starmute You may have been the first to test this combination.

We have some existing Github Issues to look into enhancements for random lights and orbit trap lights, so we can have at making it work better then

# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion_quality 8;
background_3_colors_enable false;
background_color_1 0000 0000 0000;
bailout 96;
camera 3.4026214050062e-15 -108.06957727569 0;
camera_distance_to_target 46.77339930901486;
camera_rotation 0 0 0;
camera_top 0 0 1;
DE_factor 0.5;
fake_lights_color 0000 0000 ff00;
fake_lights_enabled true;
fake_lights_intensity 8;
fake_lights_max_iter 1;
fake_lights_min_iter 0;
fake_lights_orbit_trap 0 0 0;
fake_lights_visibility 64;
fake_lights_visibility_size 8.5;
flight_last_to_render 0;
formula_1 103;
fractal_constant_factor 0.5 1 1;
glow_enabled false;
image_proportion 1;
image_width 600;
keyframe_last_to_render 0;
limit_max 100 10 100;
limit_min 0 0 0;
limits_enabled true;
main_light_intensity 0.83;
mat1_coloring_palette_offset 8.210000000000001;
mat1_is_defined true;
mat1_specular 4;
mat1_specular_plastic_enable false;
mat1_specular_width 1;
mat1_use_colors_from_palette false;
N 96;
raytraced_reflections true;
target 8.061761623634605e-16 -61.29617796667517 0;
use_default_bailout false;
view_distance_max 126.6205864485805;
[fractal_1]
IFS_rotation_enabled true;
transf_minimum_radius_05 0.7;
transf_scale_3 2;
transf_scaleB_1 0.7;
transf_start_iterations_M 1;
transf_stop_iterations_M 12;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by buddhi1980** [comment]
Orbit traps which are used to generate lights doesn't work with pseudo kleinian fractals.

**Comment by buddhi1980** [comment]
I have no idea how to solve this problem. I have already tied may different configurations of orbit traps, but without any results with pseudo-kleinian

**Comment by mclarekin** [comment]
moved to new enhancement issue #574

**Comment by mclarekin** [comment]
an approximation based on "orbit trap planes"  could possibly work

I have started a new issue for orbit trap lights enhancements and closed
existing issues relating to this .
