### ISSUE TITLE
Interesting OpenCL bug in v2.15-alpha3

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#556]
Ubuntu 18.04 using Mandelbulber v2 2.15-alpha3.
I am able to use other materials with OCL enabled but only if OpenCL mode is on 'full'. (under 'Navigation')
If I switch the drop-down menu to 'fast' then it's back to the default material for rendering.

**Comment by mclarekin** [comment]
Only openCL full mode has multi-material options and hence is the slowest
mode.
 Medium is single material.
fast is default coloring only.

**Comment by TasMania17** [comment]
Thanks for the explanation mclarekin. I may leave open for awhile so other testers know where ocl is up to.
