### ISSUE TITLE
random lights position caching

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#56]
buddhi: lights position should be cached, because it takes time to calculate new positions of lights when you press render (in Mandelbulber v1 they were cached). When rendering was started it copied positions of lights from cache. New positions of lights should be calculated only when one of parameter of random lights is changed

**Comment by buddhi1980** [comment]
After test I see that cache is not needed. It works much faster than in old Mandelbulber.

**Comment by zebastian** [comment]
Thats great! Also thanks for the placement fix
