### ISSUE TITLE
Crash program when using DOF  Update Image, after resolution change.

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#561]
Issue from Steve Sink
_I get a total and complete instant shutdown when I apply DoF. So far: render image at smaller size w/o DoF. Turn DoF on, change image size, and hit update image. Crash. Yeah, you should rerender first when you change size, but I was using the q, and it would crash when I changed DOF. Not a big deal._

The first time i tried to reproduce the program became unresponsive,  all other tests  crashed completely out.

Reproduce:
Render a std preset
Enable DOF checkbox
Go and change Image Resolution
Go back to DOF controls and  click on Update Image

**Comment by luchansky** [comment]
Can confirm, I've had this issue many times on both Mac and Windows (Bootcamp).

**Comment by buddhi1980** [comment]
Fixed.
