### ISSUE TITLE
HDR Blur option does not work automatically

### ISSUE THREAD

**Issue by kubachrabanski** [buddhi1980/mandelbulber2#566]
- mandelbulber2 => 2.14
- Operating System / Platform => Ubuntu 18.04 64bit

I've enabled HDR Blur option from effects tab, but although it's enabled it won't get rendered automatically with the sequence until I press the "update" button on each and every frame. Is it a bug, or am I just missing something?

**Comment by buddhi1980** [comment]
HDR blur doesn't work yet when OpenCL is enabled (not implemented yet). Does it happen when OpenCL is enabled or disabled?

**Comment by Kubachrabanski** [comment]
Y, it happens when I’m using OpenCL, so as I understand, on „update” button press there is CPU involved to calculate post-effects. Is there any way to bypass it, I mean to let it render frame with GPU and hdr blur with CPU automatically?

**Comment by mclarekin** [comment]
covered by new issue   #612
