### ISSUE TITLE
Feature request - alpha (transparent) background option

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#567]
This could be useful for designers who often work on a foreground that will be put on a another background. Either static or animated.
There is a work-around using a 'textured background' that is actually a transparent PNG. This gives pretty good results but needs further cleaning-up to make it totally transparent.
I can accept that it maybe hard to implement with all of the maths. :)

**Comment by mclarekin** [comment]
the use of tranparency in alpha channel pngs,  would be useful for many things, see also issue #259

**Comment by TasMania17** [comment]
closing duplicate issue
