### ISSUE TITLE
random lights position wrong calculation

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#57]
buddhi: actually positions of lights are not calculated properly. They are not distributed around center point and they are in wrong distance from fractal surface

Here is documentation how lights should be distributed: http://wiki.mandelbulber.com/index.php?title=User_Manual#Random_lights_parameters

**Comment by buddhi1980** [comment]
Fixed bug by commit 25e396a

Tested with 500 random lights
![test-500lights](https://cloud.githubusercontent.com/assets/11696990/11819819/37181ffe-a362-11e5-83b0-4b0a9664c038.jpg)
