### ISSUE TITLE
Networking problem reported by jorge abalo

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#571]
By doing some animation tests with netrender, clients are dropped out very often.
"Material #1 is not defined. Will be substitubed by material #-231"
(../src/render_data.hpp:95, void sRenderData::ValidateObjects())
Violación de segmento (`core' generado)
and similar output
It is generated on linux and windows machines and no materials are default, with no maps or textures.

**Comment by buddhi1980** [comment]
Cannot reproduce the problem. Needed example settings.

**Comment by zebastian** [comment]
The -231 looks like an uninitialized var. so maybe substitution material id on client side points to uninitialized and crashes.

**Comment by buddhi1980** [comment]
Fixed problem with potentially uninitialized variable (getting item from empty QMap)

**Comment by buddhi1980** [comment]
NetRender problem was caused by using two different versions of prgram (2.15 alpha2 with 2.15 alpha3)

**Comment by zebastian** [comment]
Thanks, i missed the response on facebook...
