### ISSUE TITLE
Orbit trap lights enhancements

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#574]
a) option for multiple separate orbit trap light sets
from starmute "I've been working pretty extensively with orbit trap lighting recently in Mandelbulber and it seems to me that having an option for multiple separate orbit trap light sets with different colors. This is probably trivial to implement so it should not be too difficult."
Krzysztof "It is not trivial to implement it. It will make fractal calculation algorithm much more complicated and redesign of user interface for orbit traps lights. I will keep this issue to remember this proposal of enhancement."

b) investigate methods to produce pseudoKleinian

**Comment by luchansky** [comment]
WRT #552, there seems to be a very, very tiny amount of orbit trap light with pseudo kleinian when add-C-constant is enabled. You need to set vis. very high IIRC.

**Comment by mclarekin** [comment]
New Fake Light options in V2.18 are  a major enhancement.  Any further work in this area is of low priority
