### ISSUE TITLE
On master branch, macOS, program crashes as soon as preferences are opened

### ISSUE THREAD

**Issue by luchansky** [buddhi1980/mandelbulber2#578]
Title says it. Also, logs don't seem to show anything useful about what's going on. I think https://github.com/buddhi1980/mandelbulber2/commit/b153da07f6823b9387dacad79d839d0c79dd2e75 had something to do with this, as the issue started only after this commit.

**Comment by mancoast** [comment]
Thanks for reporting. Does the system render with CPU? This needs fixed before 2.15

**Comment by luchansky** [comment]
Renders fine with CPU

**Comment by mancoast** [comment]
I cannot reproduce this issue. The preference dialogue opens without issue.
![image](https://user-images.githubusercontent.com/7040493/47968520-2860f280-e039-11e8-9c6e-43b790c68c14.png)

**Comment by luchansky** [comment]
Very strange. Maybe I’m compiling wrong somehow??? I followed all instructions in readme but .app ends up being 9.2 MB. Then I have to move a bunch of folders into it. Maybe this could be why?

**Comment by mancoast** [comment]
Hmm, please take a look at the circleci config yaml for the exact build instructions. We probably need to update the readme, but the continuous integration has the correct build procedures.

**Comment by luchansky** [comment]
OK. deleting the directory worked. I then changed preferences to Dark theme / Fusion / 10 point font / enabled openCL. Now program crashes again when preferences are opened.

**Comment by luchansky** [comment]
Crash only happens when OCL is enabled.

**Comment by zebastian** [comment]
Can you try to run this in debugger? This way you can find the exact position on the code where this error is triggered.

**Comment by buddhi1980** [comment]
I had similar issue under Linux when I installed fresh system. The problem is probably with list of selected devices, which was empty for some time. It needs investigation, because the problem can happen on different systems.

**Comment by buddhi1980** [comment]
It could be caused by 	
```gMainInterface->mainWindow->slotPopulateToolbar(true);```
in ```cPreferencesDialog::on_buttonBox_accepted()```
which is before creating list of opencl devides. If user have a lot of toolbar presets, then the list of devices can be empty for some time

I will check it more, when I finish re-instalation of the system. Now I have no tools.

**Comment by mancoast** [comment]
Thanks for spotting the root cause. Is it possible to move opencl initialization before GUI gets initialized?

**Comment by buddhi1980** [comment]
The program crashes when in mandelbulber.ini parameter opencl_device_list is an empty string. Crash is when preferences dialog is opened or when RENDER is pressed. I will try to fix this problem.

**Comment by buddhi1980** [comment]
Empty device list problem was just solved in commit https://github.com/buddhi1980/mandelbulber2/commit/1252a1e657017ad153fe1ba3181e08c9c3d64fba
