### ISSUE TITLE
Save alpha layer jpegs in separate folder from base jpegs

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#580]
##### System information (version)

- mandelbulber2 => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

Feature request: could we save jpeg alpha-layer in a different folder than the regular jpegs? I have to sort by file size to separate manually. Adobe Premiere won’t treat the alpha layer jpegs separately from the main ones when you import unless they’re in separate folders. Maybe together in same folder as default, but an option to designate or browse to another folder for the alpha layer jpegs. Thanks!

**Comment by TasMania17** [comment]
It's a shock rendering to JPG and finding all of those alpha files. I just render to PNG which contains the alpha (transparent) information.
I think one of the reasons for using JPGs is smaller file size but if you include alpha layers then it is a large render size and hard to separate without a script. 
Not sure if Premier will accept PNG's as input.

**Comment by paigan0** [comment]
Premiere will absolutely take PNGs as input. When I want to use alpha layers, I’ll usually use PNGs with the alpha layer embedded. But jpegs are much much smaller file sizes and I’m compiling down to video anyway. Even with the alpha layer jpegs—which I can use as masks in Premiere—you’re looking at maybe 10 GB of jpeg files versus 22-25 GBs of PNGs. It will all get crunched down to a 500 MB H265 video file anyway, so why not just use JPegs. And putting the alpha layers in their own folder makes that easier to import and use as a mask.

**Comment by TasMania17** [comment]
paigan0. Here is a ridiculously simple work-around for Windows:
https://www.youtube.com/watch?v=9ASgtBwPynk
Exporting as JPGs is faster but then I need to the add layers masks/merge down/clear backgrounds etc without using expensive software.

**Comment by paigan0** [comment]
Will do! Thanks so much!

**Comment by paigan0** [comment]
I pronounce this extremely well-implemented. I've tried it now on 6 videos or so, using the JPEGS and the alpha channels in separate folders. I merely import both folders' contents into Adobe Premiere, set the main track with a "set Matte" effect (with the video track pointing to the track number that the alpha channel lives on, and set to "lightness" instead of "alpha layer,"), and then group or nest the two tracks together into one, and it works exactly like alpha-layer embedded PNGs, but at much, much smaller file sizes. 

The alpha layer images don't take up hardly any space, even at 4K. I had no problems or issues with the fix. Well done!
