### ISSUE TITLE
Add stereo rendering in OpenCL mode 

### ISSUE THREAD

**Issue by brunetton** [buddhi1980/mandelbulber2#584]
Hi, 

I'm waiting for this one like a child for christmas ! I want to generate 3D stereo images; and I've a decent graphic card. I'd love to be able to use the hardware acceleration for stereo rendering !

Thanks

**Comment by mancoast** [comment]
I second this feature request’s priority. 3D is very cool!

**Comment by buddhi1980** [comment]
Done

**Comment by brunetton** [comment]
OMG 
Thanks you SOOO MUCCHH :)
This is the most beautiful day of my life ;)
