### ISSUE TITLE
OSS-Fuzz Targets

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#586]
https://github.com/google/oss-fuzz/pull/1933

##### System information (version)

- mandelbulber2 => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by buddhi1980** [comment]
What is oss-fuzz?

**Comment by mancoast** [comment]
This is an excellent opportunity to harden the system and gain new users. I will handle the fuzzy targets.

**Comment by networkpanic** [comment]
this is out of scope and the fuzzy target maintainer is gone
