### ISSUE TITLE
mb 2.15 crashes after enabling OpenCL without selecting the GPU device (1° time only)

### ISSUE THREAD

**Issue by rconcept** [buddhi1980/mandelbulber2#589]
- mandelbulber2 => 2.15 release ([mandelbulber2-win64-2.15-standalone](https://github.com/buddhi1980/mandelbulber2/releases/download/2.15/mandelbulber2-win64-2.15-standalone.zip))
- Operating System / Platform => Windows 64 Bit
- GPU => GeForce GTX 960

##### Detailed description
Using the standalone release, I didn't test the setup release:
Mandelbulber crashes when clicking on RENDER after enabling OpenCL in the preferences without selecting the OpenCL Device. Any try to render with OpenCL will crash. You have to return to the preferences and make sure you select a GPU device. Once a GPU device a selected, you can not deselect it, so the bug does not appear anymore.

##### Steps to reproduce
1. Delete configuration directory for a fresh start ( %HOMEDRIVE%%HOMEPATH%/mandelbulber ).
2. Start mb and open the OpenCL (GPU) preferences.
3. Enable the "OpenCl enable" checkbox.
4. Confirm the preferences with the "OK" button, without selecting your GPU in the Devices list.
5. Click "RENDER" => crash

I modified the sources to preselect the 1st GPU device when the preferences open for the first time, check the (minimal) changes [on my commit](https://github.com/rconcept/mandelbulber2/commit/ae4277c09d75e13a0654d570bf76b825898852f2).
(a side question: For future source changes/bug fixes, do you prefer pull requests ? )

Dan.

PS: Thanks for all the time you all give for making this program so good!

**Comment by buddhi1980** [comment]
Thank you for testing it. I thought that this problem is already solved...but unfortunately not.

Pull requests will be perfect for such a patches.

**Comment by rconcept** [comment]
OK, just created the pull request.
I hope to have to the time to contribute more on this great project.

**Comment by mancoast** [comment]
thanks!

**Comment by mclarekin** [comment]
hi Dan, thanks,
every bit of contribution helps,
especially being able to notice a bug ,then find it in the code and fix it

**Comment by rconcept** [comment]
fixed by merging #590
