### ISSUE TITLE
Intermittent problem with loading file or preset

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#595]
Occasionally I have to click twice on loading a file or a preset. First click changes location but not the formula

**Comment by buddhi1980** [comment]
I think it happens when auto-refresh is on. It needs to be checked.

**Comment by mclarekin** [comment]
first click changes color as well as location
![click1](https://user-images.githubusercontent.com/12769564/56635090-6cfc4b00-66b8-11e9-8561-902fa9f5bc13.jpg)
![click2](https://user-images.githubusercontent.com/12769564/56635099-74bbef80-66b8-11e9-86af-adaf8410ef92.jpg)

**Comment by buddhi1980** [comment]
Probably commit https://github.com/buddhi1980/mandelbulber2/commit/860444bf2e83d487eec6532177e5d96e508c5b17 will solve the problem permanently

**Comment by mclarekin** [comment]
So far it seems to be  working OK
