### ISSUE TITLE
difference between openCl  and c++;  color texture from image

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#598]
![sincosabx11meng baa1 cl](https://user-images.githubusercontent.com/12769564/49574548-90db2080-f9a5-11e8-92e2-bd44a63b0332.png)
![sincosabx11meng baa1 cpp](https://user-images.githubusercontent.com/12769564/49574553-92a4e400-f9a5-11e8-8439-750f8609ed70.png)

**Comment by buddhi1980** [comment]
Everything is as is expected. The texture has very small scale in second settings. In CPU mode there is used mipmapping algorithm for textures (https://pl.wikipedia.org/wiki/Mipmapping) which eliminates aliasing of zoomed out textures (filters the texture) . In OpenCL code it is not implemented (very difficult code), but you can use MC rendering which will give almost the same final result.
To render it in correct way, you should increase scale of the texture (in material editor) or render image it in higher resolution on CPU (with reduction of detail level). Then the noise from texture will be visible.

**Comment by buddhi1980** [comment]
Rendered on CPU in higher resolution (then mipmapping has less effect)
![mckintexture](https://user-images.githubusercontent.com/11696990/49600593-d850b500-f983-11e8-829b-32dc2c89e3f4.jpg)

**Comment by mclarekin** [comment]
Thanks for  explanation.

**Comment by mclarekin** [comment]
BTW   That was the last issue on my Materials Editor list relating to
openCL versus c++ .   Everything has now been fixed or explained .
FINISHED ☺☺☺
