### ISSUE TITLE
When Program Settings is opened, it always switch to first UI style from the list

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#60]
To reproduce bug:
- switch to second UI style from list
- close Program Settings dialog
- open Program Settings dialog, then you will see that it changes UI style to first one.

**Comment by buddhi1980** [comment]
It works properly in 2.06, so it's new problem

**Comment by zebastian** [comment]
hmm, there was the change, to use autoconnect of signal slots.
Maybe some timing issue on load?
see https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/qt/preferencesdialog.cpp
  ui->setupUi(this);
gets called at the beginning, maybe on_comboBox_ui_style_type_currentIndexChanged gets called, before constructor cPreferencesDialog is ready and combobox is set correctly...

**Comment by zebastian** [comment]
was fixed with 7d8385eb58074aa40d2a9c4903db5ed814932cd6
