### ISSUE TITLE
Vicsek fractal

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#600]
Is it possible to implement this "snowflake" fractal in the system?

**Comment by buddhi1980** [comment]
Are you asking about this https://en.wikipedia.org/wiki/Koch_snowflake ?

**Comment by mancoast** [comment]
that is very similar, but I am actually looking for 3D versions of this:
https://en.wikipedia.org/wiki/Vicsek_fractal

**Comment by zebastian** [comment]
found randomly, guess thats the Vicsek 3d:
take the menger sponge and replace
```
	z.x -= 2.0;
	z.y -= 2.0;
	if (z.z > 1.0) z.z -= 2.0;
```
with
```
	if (z.x > 0.5) z.x -= 1;
	if (z.y > 0.5) z.y -= 1;
	if (z.z > 1.0) z.z -= 2.0;
```

**Comment by zebastian** [comment]
![settings](https://user-images.githubusercontent.com/7888201/49698067-29002200-fbbf-11e8-819e-24170b498d8f.png)

**Comment by mancoast** [comment]
It’s perfect! Do you want the honors of adding it to the formulas? If not I can add the new formula. Woohoo!

**Comment by zebastian** [comment]
You have my blessing :-)
Maybe add as a generalized menger sponge with the values parametrized

**Comment by mancoast** [comment]
Sounds great, thanks!

**Comment by zebastian** [comment]
@mclarekin 
maybe the following could be used for parametrization:
```
if (z.x > factal->swapThresh.x) z.x -= factal->swapVal.x;
if (z.y > factal->swapThresh.y) z.y -= factal->swapVal.y;
if (z.z > factal->swapThresh.z) z.z -= factal->swapVal.z;
```
with presets for:
 menger sponge (0, 0, 1) / (2, 2, 2)
 Vicsek 3d (0.5, 0.5, 1) / (1, 1, 2)

There is no background reference as far as i know.

**Comment by mclarekin** [comment]
Basic implementation complete,  hybrids well

**Comment by mclarekin** [comment]
@zebastian 
thresh to value ratio 1:2 appears to be important for z.y and z.z.

**Comment by mclarekin** [comment]
implemented
