### ISSUE TITLE
mouse camera movement issue

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#602]
Currently if i move mouse pointer in the render window, and pass over the non-image area the camera responds and i lose my position.

But weirder still. if i disable auto-refresh, then move mouse pointer into that area, then auto-refresh gets enabled automatically.

Also if i change mouse pointer function to no-action, mouse still  moves the camera

Can anyone reproduce this?

![mouse camera](https://user-images.githubusercontent.com/12769564/49709260-4d7bfd00-fc98-11e8-9fc8-d7a470950966.JPG)

**Comment by mclarekin** [comment]
mouse pointer is a cross, not an arrow head, when i pass over the grey area of the render window

**Comment by mclarekin** [comment]
OK, it is not reproducible.  I have reloaded program and it is now working correctly.

**Comment by mclarekin** [comment]
Very infrequent, but i had same issue yesterday.  I will continue to monitor.

**Comment by buddhi1980** [comment]
Fixed: Added additional check if no buttons are pressed during mouseReleaseEvent.
