### ISSUE TITLE
populateOpenCl.php - problem with regex

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#603]
Command ```./populateOpenCL.php warning``` produces following errors
```
...
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 39 in /home/krzysztof/git/mandelbulber2/mandelbulber2/tools/populateOpenCL.php on line 185
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 39 in /home/krzysztof/git/mandelbulber2/mandelbulber2/tools/populateOpenCL.php on line 185
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 39 in /home/krzysztof/git/mandelbulber2/mandelbulber2/tools/populateOpenCL.php on line 185
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 39 in /home/krzysztof/git/mandelbulber2/mandelbulber2/tools/populateOpenCL.php on line 185
...
```
Final result in files is wrong because there is no content in clCopy... functions line in folowing example:
![image](https://user-images.githubusercontent.com/11696990/50051517-08325200-0114-11e9-927b-5b4906e020df.png)

@zebastian I cannot find what is wrong in the script and running of the script is needed to update all .cl files before release of 2.16

**Comment by zebastian** [comment]
possibly fixed here: https://github.com/buddhi1980/mandelbulber2/commit/89bd465554f851e2b95cf6381262203de2d0b64a

The thing is: regex is not regex. Different programs implement regexes on different ways. even php handles regexes differently in different versions. php 7.1 was handling the old regex just fine, but your php version was having issues with it. The problematic regex was untidy and could have been misinterpreted. Is fixed now...

**Comment by zebastian** [comment]
@buddhi1980 can you try again?

**Comment by buddhi1980** [comment]
Now everything is all right. Thanks.

**Comment by mclarekin** [comment]
I have some problems:

Problem number 1
Mandelbulb 2 & mandelbulb Kali does not render in openCL

These settings are for mandelbulb testing, If you mouse scroll through the
mandelbulb formulas there should be a sphere.

# Mandelbulber settings file
# version 2.16
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
bailout 32;
camera 0 -3.713996353864262 0;
camera_distance_to_target 3.713996353864262;
camera_rotation 0 0 0;
camera_top 0 0 1;
DE_factor 0.4;
delta_DE_method 2;
dont_add_c_constant_1 true;
flight_last_to_render 0;
formula_2 1029;
formula_3 1021;
fractal_enable_2 false;
fractal_enable_3 false;
hybrid_fractal_enable true;
image_height 800;
image_proportion 1;
keyframe_last_to_render 0;
mat1_coloring_palette_offset 8.210000000000001;
mat1_fractal_coloring_aux_color_scale1 0;
mat1_fractal_coloring_extra_color_options_false true;
mat1_fractal_coloring_orbit_trap_scale1 2.6;
mat1_fractal_coloring_rad_div_de_scale1 0;
mat1_is_defined true;
mat1_specular_metallic 1;
mat1_specular_plastic_enable false;
mat1_surface_color_palette df3832 698403 000000 f5bd22 0b5e87 c68876 a51c64
3b9fee d4ffd4 aba53c;
raytraced_reflections true;
use_default_bailout false;
view_distance_max 10.05418471484806;
[fractal_1]
buffalo_preabs_x true;
buffalo_preabs_y true;
buffalo_preabs_z true;
mandelbox_rotation_main 0 0 90;
transf_function_enabledAy false;
transf_function_enabledAz false;
transf_function_enabledM false;
transf_function_enabledy false;
transf_function_enabledz false;
transf_rotation 0 0 -90;
transf_rotation_enabled true;
transf_start_iterations_R 1;
transf_start_iterations_S 1;
transf_stop_iterations_R 7;
[fractal_2]
buffalo_preabs_x true;
buffalo_preabs_y true;
buffalo_preabs_z true;
mandelbox_folding_fixed_radius 0.7999999999999999;
mandelbox_rotation_main 0 0 90;
transf_addition_constant -0.1 0 0;
transf_function_enabledAx false;
transf_function_enabledAy false;
transf_function_enabledAz false;
transf_function_enabledM false;
transf_function_enabledx false;
transf_function_enabledy false;
transf_function_enabledz false;
transf_rotation 0 0 -90;
transf_rotation_enabled true;
transf_start_iterations_R 1;
transf_start_iterations_S 1;
transf_stop_iterations_R 7;
[fractal_3]
transf_addition_constant 0.1 0 0;
transf_addition_constantA_000 0.5 0 -0.4;
transf_function_enabledAy false;
transf_function_enabledAz false;
transf_function_enabledy false;
transf_function_enabledz false;
transf_offset_000 0.7 0 0;
transf_offsetA_000 0.2 0 0;
transf_rotation 0 -91 0;

**Comment by mclarekin** [comment]
problem number 2 abs add multi not rendering correctly in openCL. I have
yet to look at the code, i am still testing in Win10


# Mandelbulber settings file
# version 2.16
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
camera_distance_to_target 2.761725137257712;
flight_last_to_render 0;
formula_2 1029;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_is_defined true;
raytraced_reflections true;
[fractal_1]
IFS_rotation_enabled true;
[fractal_2]
IFS_rotation_enabled true;
transf_function_enabledAx false;
transf_function_enabledx false;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by buddhi1980** [comment]
First problem: camera is located exactly on Y axis which produces division
by zero problems (this formula has this problem). Just move a camera a
little.
Second problem: looks like uninitialized variable. The code need to be
checked.

pon., 17 gru 2018 o 06:13 mclarekin <notifications@github.com> napisał(a):

> problem number 2 abs add multi not rendering correctly in openCL. I have
> yet to look at the code, i am still testing in Win10
>
>
> # Mandelbulber settings file
> # version 2.16
> # only modified parameters
> [main_parameters]
> ambient_occlusion_enabled true;
> camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
> camera_distance_to_target 2.761725137257712;
> flight_last_to_render 0;
> formula_2 1029;
> hybrid_fractal_enable true;
> keyframe_last_to_render 0;
> mat1_is_defined true;
> raytraced_reflections true;
> [fractal_1]
> IFS_rotation_enabled true;
> [fractal_2]
> IFS_rotation_enabled true;
> transf_function_enabledAx false;
> transf_function_enabledx false;
> [fractal_3]
> IFS_rotation_enabled true;
> [fractal_4]
> IFS_rotation_enabled true;
>
>
> On Mon, Dec 17, 2018 at 4:39 PM carbuncle grim <mclarekin@gmail.com>
> wrote:
>
> > I have some problems:
> >
> > Problem number 1
> > Mandelbulb 2 & mandelbulb Kali does not render in openCL
> >
> > These settings are for mandelbulb testing, If you mouse scroll through
> the
> > mandelbulb formulas there should be a sphere.
> >
> > # Mandelbulber settings file
> > # version 2.16
> > # only modified parameters
> > [main_parameters]
> > ambient_occlusion_enabled true;
> > bailout 32;
> > camera 0 -3.713996353864262 0;
> > camera_distance_to_target 3.713996353864262;
> > camera_rotation 0 0 0;
> > camera_top 0 0 1;
> > DE_factor 0.4;
> > delta_DE_method 2;
> > dont_add_c_constant_1 true;
> > flight_last_to_render 0;
> > formula_2 1029;
> > formula_3 1021;
> > fractal_enable_2 false;
> > fractal_enable_3 false;
> > hybrid_fractal_enable true;
> > image_height 800;
> > image_proportion 1;
> > keyframe_last_to_render 0;
> > mat1_coloring_palette_offset 8.210000000000001;
> > mat1_fractal_coloring_aux_color_scale1 0;
> > mat1_fractal_coloring_extra_color_options_false true;
> > mat1_fractal_coloring_orbit_trap_scale1 2.6;
> > mat1_fractal_coloring_rad_div_de_scale1 0;
> > mat1_is_defined true;
> > mat1_specular_metallic 1;
> > mat1_specular_plastic_enable false;
> > mat1_surface_color_palette df3832 698403 000000 f5bd22 0b5e87 c68876
> > a51c64 3b9fee d4ffd4 aba53c;
> > raytraced_reflections true;
> > use_default_bailout false;
> > view_distance_max 10.05418471484806;
> > [fractal_1]
> > buffalo_preabs_x true;
> > buffalo_preabs_y true;
> > buffalo_preabs_z true;
> > mandelbox_rotation_main 0 0 90;
> > transf_function_enabledAy false;
> > transf_function_enabledAz false;
> > transf_function_enabledM false;
> > transf_function_enabledy false;
> > transf_function_enabledz false;
> > transf_rotation 0 0 -90;
> > transf_rotation_enabled true;
> > transf_start_iterations_R 1;
> > transf_start_iterations_S 1;
> > transf_stop_iterations_R 7;
> > [fractal_2]
> > buffalo_preabs_x true;
> > buffalo_preabs_y true;
> > buffalo_preabs_z true;
> > mandelbox_folding_fixed_radius 0.7999999999999999;
> > mandelbox_rotation_main 0 0 90;
> > transf_addition_constant -0.1 0 0;
> > transf_function_enabledAx false;
> > transf_function_enabledAy false;
> > transf_function_enabledAz false;
> > transf_function_enabledM false;
> > transf_function_enabledx false;
> > transf_function_enabledy false;
> > transf_function_enabledz false;
> > transf_rotation 0 0 -90;
> > transf_rotation_enabled true;
> > transf_start_iterations_R 1;
> > transf_start_iterations_S 1;
> > transf_stop_iterations_R 7;
> > [fractal_3]
> > transf_addition_constant 0.1 0 0;
> > transf_addition_constantA_000 0.5 0 -0.4;
> > transf_function_enabledAy false;
> > transf_function_enabledAz false;
> > transf_function_enabledy false;
> > transf_function_enabledz false;
> > transf_offset_000 0.7 0 0;
> > transf_offsetA_000 0.2 0 0;
> > transf_rotation 0 -91 0;
> >
> >
> > On Mon, Dec 17, 2018 at 9:58 AM Krzysztof Marczak <

**Comment by buddhi1980** [comment]
From the first look into the code,  CVector4 tempA, tempB is wrong (in ans
multi formula). In OpenCL these variables will be uninitialized. In C++
code.
Should be:
CVector4 tempA = CVector4(0.0, 0.0, 0.0, 0.0);
CVector4 tempB = CVector4(0.0, 0.0, 0.0, 0.0);
Then after conversion to OpenCL code it will get zeros at start.

pon., 17 gru 2018 o 07:04 Krzysztof Marczak <buddhi1980@gmail.com>
napisał(a):

> First problem: camera is located exactly on Y axis which produces division
> by zero problems (this formula has this problem). Just move a camera a
> little.
> Second problem: looks like uninitialized variable. The code need to be
> checked.
>
> pon., 17 gru 2018 o 06:13 mclarekin <notifications@github.com> napisał(a):
>
>> problem number 2 abs add multi not rendering correctly in openCL. I have
>> yet to look at the code, i am still testing in Win10
>>
>>
>> # Mandelbulber settings file
>> # version 2.16
>> # only modified parameters
>> [main_parameters]
>> ambient_occlusion_enabled true;
>> camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
>> camera_distance_to_target 2.761725137257712;
>> flight_last_to_render 0;
>> formula_2 1029;
>> hybrid_fractal_enable true;
>> keyframe_last_to_render 0;
>> mat1_is_defined true;
>> raytraced_reflections true;
>> [fractal_1]
>> IFS_rotation_enabled true;
>> [fractal_2]
>> IFS_rotation_enabled true;
>> transf_function_enabledAx false;
>> transf_function_enabledx false;
>> [fractal_3]
>> IFS_rotation_enabled true;
>> [fractal_4]
>> IFS_rotation_enabled true;
>>
>>
>> On Mon, Dec 17, 2018 at 4:39 PM carbuncle grim <mclarekin@gmail.com>
>> wrote:
>>
>> > I have some problems:
>> >
>> > Problem number 1
>> > Mandelbulb 2 & mandelbulb Kali does not render in openCL
>> >
>> > These settings are for mandelbulb testing, If you mouse scroll through
>> the
>> > mandelbulb formulas there should be a sphere.
>> >
>> > # Mandelbulber settings file
>> > # version 2.16
>> > # only modified parameters
>> > [main_parameters]
>> > ambient_occlusion_enabled true;
>> > bailout 32;
>> > camera 0 -3.713996353864262 0;
>> > camera_distance_to_target 3.713996353864262;
>> > camera_rotation 0 0 0;
>> > camera_top 0 0 1;
>> > DE_factor 0.4;
>> > delta_DE_method 2;
>> > dont_add_c_constant_1 true;
>> > flight_last_to_render 0;
>> > formula_2 1029;
>> > formula_3 1021;
>> > fractal_enable_2 false;
>> > fractal_enable_3 false;
>> > hybrid_fractal_enable true;
>> > image_height 800;
>> > image_proportion 1;
>> > keyframe_last_to_render 0;
>> > mat1_coloring_palette_offset 8.210000000000001;
>> > mat1_fractal_coloring_aux_color_scale1 0;
>> > mat1_fractal_coloring_extra_color_options_false true;
>> > mat1_fractal_coloring_orbit_trap_scale1 2.6;
>> > mat1_fractal_coloring_rad_div_de_scale1 0;
>> > mat1_is_defined true;
>> > mat1_specular_metallic 1;
>> > mat1_specular_plastic_enable false;
>> > mat1_surface_color_palette df3832 698403 000000 f5bd22 0b5e87 c68876
>> > a51c64 3b9fee d4ffd4 aba53c;
>> > raytraced_reflections true;
>> > use_default_bailout false;
>> > view_distance_max 10.05418471484806;
>> > [fractal_1]
>> > buffalo_preabs_x true;
>> > buffalo_preabs_y true;
>> > buffalo_preabs_z true;
>> > mandelbox_rotation_main 0 0 90;
>> > transf_function_enabledAy false;
>> > transf_function_enabledAz false;
>> > transf_function_enabledM false;
>> > transf_function_enabledy false;
>> > transf_function_enabledz false;
>> > transf_rotation 0 0 -90;
>> > transf_rotation_enabled true;
>> > transf_start_iterations_R 1;
>> > transf_start_iterations_S 1;
>> > transf_stop_iterations_R 7;
>> > [fractal_2]
>> > buffalo_preabs_x true;
>> > buffalo_preabs_y true;
>> > buffalo_preabs_z true;
>> > mandelbox_folding_fixed_radius 0.7999999999999999;
>> > mandelbox_rotation_main 0 0 90;
>> > transf_addition_constant -0.1 0 0;
>> > transf_function_enabledAx false;
>> > transf_function_enabledAy false;
>> > transf_function_enabledAz false;
>> > transf_function_enabledM false;
>> > transf_function_enabledx false;
>> > transf_function_enabledy false;
>> > transf_function_enabledz false;
>> > transf_rotation 0 0 -90;
>> > transf_rotation_enabled true;
>> > transf_start_iterations_R 1;
>> > transf_start_iterations_S 1;
>> > transf_stop_iterations_R 7;
>> > [fractal_3]
>> > transf_addition_constant 0.1 0 0;
>> > transf_addition_constantA_000 0.5 0 -0.4;
>> > transf_function_enabledAy false;
>> > transf_function_enabledAz false;
>> > transf_function_enabledy false;
>> > transf_function_enabledz false;
>> > transf_offset_000 0.7 0 0;
>> > transf_offsetA_000 0.2 0 0;
>> > transf_rotation 0 -91 0;
>> >
>> >
>> > On Mon, Dec 17, 2018 at 9:58 AM Krzysztof Marczak <

**Comment by zebastian** [comment]
regex and both formula problems have been fixed
