### ISSUE TITLE
Copy / paste vector values

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#61]
Would be nice to have in context menu for every edit field an option to copy and paste 3D vector values.

**Comment by mclarekin** [comment]
Yes, I needed it yesterday.

BTW when right click on parameter field, we have the choice of "select
all", is there anywhere in the program that this is currently used?

On Wed, Dec 16, 2015 at 5:40 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
Done by commit https://github.com/buddhi1980/mandelbulber2/commit/c0f707efff970d7fb15e630f970cb2f8b55c7137
