### ISSUE TITLE
Measurement tool

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#62]
There is needed measurement tool to get position of fractal surface point remembered somewhere (in some dock) and to measure distance between two points of fractal.

**Comment by buddhi1980** [comment]
Mostly done. Still to do is hiding/showing of measurement dock

**Comment by mclarekin** [comment]
Would be good if when choose "Measure point coordinates" from mouse click
function drop down menu., then the measurement dock appears.


On Sun, Jan 31, 2016 at 4:24 AM, Krzysztof Marczak <notifications@github.com
