### ISSUE TITLE
difference fog based on distance. c++ vrs opencl

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#620]
# Mandelbulber settings file
# version 2.17
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
camera -0.2499999999999998 -3.278772619987453 -4.068797338282663;
camera_distance_to_target 2.102515079991635;
camera_rotation -5.75499024858822 62.53524115307064 50.04861922937565;
camera_top 0.7055928112895233 -0.6437628639194778 0.2961556342444607;
constant_DE_threshold true;
DE_factor 0.25;
DE_thresh 0.0003125;
detail_level 0.25;
flight_last_to_render 0;
fog_color_1 ff00 ff00 ff00;
fog_color_2 5500 0000 0000;
fog_color_3 0000 0000 0000;
formula_1 1089;
formula_2 118;
formula_stop_iteration_1 1;
hybrid_fractal_enable true;
image_height 3200;
image_width 3200;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
mat1_fractal_coloring_algorithm 1;
mat1_is_defined true;
mat1_luminosity 0.3;
mat1_specular 1;
mat1_specular_plastic_enable false;
mat1_specular_width 1;
mat1_surface_color_palette 000000 698403 fff59c f5bd22 0000ff 55ffff 0000ff 3b9fee 000000 aba53c;
mat2_is_defined true;
mat2_metallic false;
mat2_specular 0;
mat2_specular_width 0.001;
mat2_surface_color c300 b300 3400;
mat2_surface_color_palette fd6029 698403 fff59c f5bd22 871d0b c68876 a51c64 3b9fee d4ffd4 aba53c;
raytraced_reflections true;
target -0.1527649931073564 -2.313973889186947 -2.203246903672933;
view_distance_max 182.1354505789545;
volumetric_fog_colour_1_distance 0.8164668682617615;
volumetric_fog_colour_2_distance 0.8164668682617605;
volumetric_fog_distance_factor 1.632933736523521;
volumetric_fog_enabled true;
[fractal_1]
info true;
transf_function_enabledw false;
transf_function_enabledx false;
transf_function_enabledy false;
transf_offset_1111 0 1 0.8 1;
transf_scale_1 0.6;

**Comment by buddhi1980** [comment]
Very high maximum view distance causes the problem. It could be numeric error caused by single precision. Result is the same when maximum view distance is about 50
