### ISSUE TITLE
Crash if  disable palette 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#623]
While rendering, with auto-refresh on, no-openCL,  change single color sometimes = crash to desktop

**Comment by mclarekin** [comment]
Ok, disabling and enabling  the pallete can  also cause crash.  I cannot make it crash in openCL.

Feeling like it is mouse clicking to quickly, maybe while refreshing of the texture preview

**Comment by buddhi1980** [comment]
Does it happen under Windows or under Linux?

**Comment by mclarekin** [comment]
win10

**Comment by buddhi1980** [comment]
Not reproducible at all

**Comment by mclarekin** [comment]
@buddhi1980 . That is because you do not have a lot of bug-magnet DNA.:)

 I probably crashed 30 times within a couple of hours. I will try and and find out more.

**Comment by buddhi1980** [comment]
Can you send me your mandelbulber217.ini file?

**Comment by mclarekin** [comment]
[mandelbulber_217.txt](https://github.com/buddhi1980/mandelbulber2/files/2924227/mandelbulber_217.txt)

**Comment by buddhi1980** [comment]
Is this still reproducible on your PC?

**Comment by mclarekin** [comment]
Tried,and no crashes, but it was intermittent. I will close this issue as it is either fixed, or too hard to reproduce.   Will reopen if it happens again
