### ISSUE TITLE
Jos Leys DeltaDE broken in OpenCL

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#627]
maybe something i did, i will try and find it

```
# Mandelbulber settings file
# version 2.17
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 0000 0000 0000;
camera -0.3497615304715637 1.935824043354695 3.349010474846709;
camera_distance_to_target 8.700000000000001;
camera_rotation -90 -90 -180;
camera_top -1 6.123233995736764e-17 -6.123233995736765e-17;
check_for_bailout_3 false;
DE_factor 0.3;
delta_DE_function 4;
delta_DE_method 1;
detail_level 16;
file_background C:\Users\graeme\mandelbulber\my textures\background.jpg;
file_envmap C:\Users\graeme\mandelbulber\my textures\envmap.jpg;
file_lightmap C:\Users\graeme\mandelbulber\my textures\lightmap.jpg;
flight_last_to_render 0;
formula_1 122;
formula_2 1084;
formula_3 1038;
formula_start_iteration_3 5;
formula_stop_iteration_2 1;
formula_stop_iteration_3 6;
fov 0.7;
fractal_enable_2 false;
fractal_enable_3 false;
glow_enabled false;
image_proportion 2;
keyframe_last_to_render 0;
mat1_fractal_coloring_algorithm 3;
mat1_fractal_coloring_aux_color_scale1 0;
mat1_fractal_coloring_orbit_trap_scale1 89.59999999999999;
mat1_fractal_coloring_rad_div_de_scale1 0;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 1;
mat1_specular_plastic_enable false;
mat1_specular_width 1;
mat1_surface_color_palette fd6029 698403 fff59c 000000 550000 000000 550000 000000 550000 aba53c;
N 49;
raytraced_reflections true;
target -0.3497615304715631 1.935824043354695 -5.350989525153292;
[fractal_1]
transf_folding_value 1.99;
transf_function_enabled_false true;
transf_maxR2_1 0.4;
transf_offset_000 -0.2 -1.45 0.3;
transf_sphere_inversion_enabled_false true;
[fractal_2]
mandelbox_folding_fixed_radius 99;
mandelbox_folding_min_radius 1;
transf_constant_multiplier_111 0.8 0.5 0;
transf_function_enabled false;
transf_function_enabled_false true;
transf_maxR2_1 0.2;
transf_offset 0.11;
transf_offset_000 -0.3 1.5 0;
transf_sphere_inversion_enabled_false true;
[fractal_3]
info true;
mandelbox_folding_fixed_radius 99;
mandelbox_folding_min_radius 1;
transf_constant_multiplier_111 0.8 0.5 0;
transf_function_enabled false;
transf_maxR2_1 0.2;
transf_offset 0.11;
transf_offset_000 -0.3 1.5 0;
transf_sphere_inversion_enabled_false true;
```

**Comment by rconcept** [comment]
I played a bit with different parameters (of your example) and it seems that the "noisy" pixels (only in OpenCL) are directly related to the InverR2 parameter.

**Comment by mclarekin** [comment]
I have just been looking at this.  I find  three problems, hopefully fixing the first two will also fix the third (only a color thing).

The first is the JosLeysys Kleinian does not render correctly with DeltaDE JosLeys   with openCL, when the sphere inversion is enabled


![No_openCL with sphInversion](https://user-images.githubusercontent.com/12769564/56848449-4e5ab600-693d-11e9-950e-0b3a799e6f37.jpg)
![FULL with sphInversion](https://user-images.githubusercontent.com/12769564/56848454-59ade180-693d-11e9-803e-bf20a369c075.jpg)

**Comment by mclarekin** [comment]
so turn off sphereInv and no problem. Hmmm, so looks like problem in the  sphereInversion part of the openCL code (but maybe something else as well)
BACKGROUND info, I had made this change but this does not look like it is the cause.
  // aux.pseudoKleinianDE *= iR; // TODO remove after testing
  aux.DE *= fabs(iR);

![FULL](https://user-images.githubusercontent.com/12769564/56848563-b8278f80-693e-11e9-98a3-bead31e48e37.jpg)

![No_openCL](https://user-images.githubusercontent.com/12769564/56848568-c675ab80-693e-11e9-8a
06-8ddd2c022447.jpg)

**Comment by mclarekin** [comment]
So i will have a look at the code before recording the second problem

**Comment by mclarekin** [comment]
I cannot see any obvious difference between the c++ and openCL sphereinversion code

**Comment by buddhi1980** [comment]
No is better. DeltaDE for JosKleinian fractals was not implemented at all. I have no idea why I forgot about this.

**Comment by buddhi1980** [comment]
Test it and close issue if works with your different settings.

**Comment by mclarekin** [comment]
Thanks
