### ISSUE TITLE
number fields padding (intermittent)

### ISSUE THREAD

**Issue by TBeholder** [buddhi1980/mandelbulber2#628]
##### System information (version)
- mandelbulber2 => 2.16, no OpenCL
- Operating System / Platform => Linux, 2 CPU
- Compiler => qmake

##### Detailed description

Another input field problem. Possibly related to #594.
The bug interferes with typing into many number fields, since a field is padded by zeroes to maximum length. Normally, padding zeroes can be erased with Backspace/Del, but when the bug manifests they appear immediately after being deleted, thus the only way to type is to select and replace digits one by one.
Also, only "insert" input mode is supported, "overwrite" (that would trivially circumvent this) isn't.
It seems that the validator doesn't always wait until input is done?

##### Steps to reproduce
Typing into number fields (intermittent).
Last appeared after activity limited to: load a standard pre-set, change fractal type, enter new values into the fields.

**Comment by mclarekin** [comment]
Fixed by adding by adding event filter for menu shortcuts to disable buttonPressTimer

same as #682 and #594
