### ISSUE TITLE
minor error messages in terminal

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#633]
- mandelbulber2 => 2.17
- Operating System / Platform => Ubuntu 18.04
- Compiler => QtCreator

All in terminal and all related:

Warning: QWidget::repaint: Recursive repaint detected
((null):0, (null))

Warning: QWidget::paintEngine: Should no longer be called
((null):0, (null))

Warning: QPainter::begin: Paint device returned engine == 0, type: 1
((null):0, (null))

Warning: QPainter::setRenderHint: Painter must be active to set rendering hints
((null):0, (null))

**Comment by buddhi1980** [comment]
I also can see these messages from time to time. But I have no idea how to reproduce them.
