### ISSUE TITLE
possible bug  in openCL  multi-ray AO

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#634]
Menno Jansen reports .

Since version 2.14 (I believe) I have problems with settings I made with versions before that: whenever the Detail Level is lower then 1, the material gets black. See the attached image. On the left Detail Level is 1,0 and on the right 0,5. Maybe a bug that is there since 2.14? With new renders made in 2.17 this is not happening. Only with settings I load that are pre-2.14. Also, it doesn't matter if I load a 2.13 setting and then save it 2.17: the problem persists.
Below the settings for checking what might be wrong.

```
# Mandelbulber settings file
# version 2.17
# only modified parameters
[main_parameters]
ambient_occlusion 3,5;
ambient_occlusion_enabled true;
ambient_occlusion_mode 1;
ambient_occlusion_quality 7;
background_3_colors_enable false;
background_color_1 0000 0000 0000;
camera 0,500234542236686 -5,100669328425697 -1,27663495644978;
camera_distance_to_target 5,281747722792043;
camera_rotation 5,601218763271995 13,98730588242968 -0,4672856199860316;
camera_top 0,01547415219056539 -0,2413408622868837 0,9703170300497702;
DE_factor 0,25;
DOF_focus 0,03630476444959641;
DOF_radius 5;
DOF_samples 500;
file_lightmap C:\Program Files\Mandelbulber2\textures\envmap6.jpg;
flight_last_to_render 0;
formula_1 67;
formula_2 83;
glow_enabled false;
hybrid_fractal_enable true;
image_height 1080;
image_proportion 4;
image_width 1920;
iteration_threshold_mode true;
keyframe_last_to_render 0;
main_light_intensity 0,5;
mat1_is_defined true;
mat1_metallic false;
mat1_shading 2;
mat1_specular 1;
mat1_specular_width 1;
mat1_use_colors_from_palette false;
N 11;
saturation 3,5;
view_distance_max 14,29825507688695;
[fractal_1]
power 18;
[fractal_2]
transf_addCpixel_enabled_false true;
transf_pwr_8 4;
[fractal_3]
transf_addCpixel_enabled_false true;
```

**Comment by mclarekin** [comment]
image color is from lightmap, 
maxiter is set at 11, disable maxiter seems to remove problem

works ok in c++

**Comment by buddhi1980** [comment]
It is reproducible. I'm marking this issue as a bug.

**Comment by buddhi1980** [comment]
There is some problem related to maxiter and detail level. In both CPU and GPU code detail level has influence on shape when maxiter is used, which is totally wrong.

**Comment by buddhi1980** [comment]
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/79cc3df4d56574f551489dd9ff9fc34fe9641164
