### ISSUE TITLE
Loading & Deleting materials

### ISSUE THREAD

**Issue by TorIPi0** [buddhi1980/mandelbulber2#636]
##### System information (version)

Loading a pre-made material and deleting mat1 before rendering leads to a continual spam in mandelbulber text window of "Warning: Get(): element ' "mat1_name" ' doesn't exists" and slows the program UI to a standstill - rendering continues but at a very reduced pace.

**Comment by buddhi1980** [comment]
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/9bf18d14e5aa9fe5eedc98bce8402256d3cee677
