### ISSUE TITLE
Delete all Images doesn't empty Alpha folder

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#637]
##### System information (version)

- mandelbulber2 => 2.18 dev latest version
- Operating System / Platform => Windows Pro 64 Bit
- Compiler => :grey_question:

##### Detailed description
I've been using the new "alpha channel in its own folder" feature on almost every animation lately. The ability to keep using jpegs but also have the alpha channels frames (which are very small in file size) is awesome. And having them in their own folder is awesome. However, when you run a test batch, and then later hit "delete all images," it does NOT delete the alpha frames in their folder. Which is unfortunate, when you run the 4K size, and the alpha layer frames were already written at half HD, or you made changes to the keyframes, and then "deleted" out all the images before the final run.

Could we have all the folders delete when the "delete all images" button is pushed? Specular, Z buffer, etc., probably don't delete either but I haven't tried them yet.

**Comment by buddhi1980** [comment]
The same problem is with spercular and zbuffer folders.

**Comment by buddhi1980** [comment]
Fixed
