### ISSUE TITLE
 Warning: libpng warning: iCCP: known incorrect sRGB profile (:0,

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#639]
https://fractalforums.org/mandelbulber/14/opencl-issues-since-release-2-17/2760/new#new

**Comment by buddhi1980** [comment]
```libpng warning: iCCP: known incorrect sRGB profile``` is caused by some PNG files which has wrong color profile. It is correct behavior, that libpng produces this warning message.

The problem showed under link from FF was about different thing. It was caused my not enough GPU memory.
