### ISSUE TITLE
Denote active formula tabs

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#64]
It would be good if there was some way to show which fractal tabs are "active", meaning have a fractal chosen from the dropdown menu other than "none".   A user (me) could be busy tweaking a hybrid on Fractals  1 & 2 and had forgotten to clear Fractal 5, and confused why tweaking is not working as expected or it seems to be taking too long to render.  

So possibly denote "active" by colors or red /green lights or or simply by having enable checkBoxes

**Comment by buddhi1980** [comment]
Now tab names are formula names. Is it solve this issue? Try it and give me a feedback.

**Comment by mclarekin** [comment]
1)   Yes that is a good improvement and solves the specific issue.

2)   But even better is if there was an enable checkbox for each formula.
Then you can quickly try different variations. So have main formula in #1
and various other formulas #2 - #9, then can simply turn some on and some
off to try different combinations, instead  of having to  scroll up to
"none" then back down to your formulas.

This would then work as initial conditions before running iteration loop.:

is #1 enabled? yes, include   #1 in iteration loop

is #2 enabled? no, exclude  #2 from iteration loop

is #3 enabled? yes, include  #3 in iteration loop

  etc

is #9 enabled, no, exclude #9 from iteration loop

Now run iteration loop.


3) on the UI we have nine tabs (formulas #) * across*,  and four tabs *down*
(formula, options, hybrid, primitives). Could consider swapping them  to
four across and nine down



4) We are doubling up the formula  name. Could the formula tab incorporate
the drop down formula list

Cheers

**Comment by buddhi1980** [comment]
2) There is not possible to add checkbox to the tab. Only way to do this would be to add Groupbox with checkbox inside the tab. Other idea is to add "Exclude from computation" checkbox (by "Don't add c constant")
3) If I swap this, then I need to do the same change for effects tabs where tabs are also on the left. My primary idea was to use different orientation for docks tabs and regular tabs. 

4) It is not possible in Qt to incorporate them.

**Comment by mclarekin** [comment]
QT needs improvements.  LOL

**Comment by zebastian** [comment]
i got something on the way. the "left button" can be faked to use a widget containing the left arrow and additionally a checkbox...

**Comment by zebastian** [comment]
now also fully done with this commit https://github.com/buddhi1980/mandelbulber2/commit/9e264c9b7eb9d234afa899e6bd01cd47c24986e4
@buddhi1980 thanks for connecting the loose ends!
