### ISSUE TITLE
Wishlist: revert loading of preview from gpu back to cpu

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#642]
As written, I´d love to see loading preview is done by cpu again instead of graphic card:

in my opinion it takes very long / much too long to see something when you are clicking quickly through the list of .fract-files...it often takes several seconds (!) until "compile"-process is finished!

Thats much too long in my opinion for a preview. With cpu we have had much faster results...

**Comment by mclarekin** [comment]
I was going to mention this. Same here.  My i7 seemed to refresh faster.

 Also I have an embedded GPU and a dedicated GPU on my laptop, and i was
wondering if the program may have been using the slow emdedded GPU for
refreshing??

**Comment by michas0602** [comment]
I think the problem here is just the compiling-time for Ocl (which would also happen when using the onboard gpu).

Maybe worth a try to switch the preview back to cpu and lower the preview its resolution a bit, or remove time-intensive effects...not sure, needs to be tested...at least cpu-usage delivered faster previews at all

**Comment by buddhi1980** [comment]
I will add option in Preferences, so user will decide what to use. Default will be CPU

**Comment by buddhi1980** [comment]
Option added
