### ISSUE TITLE
Crashes with mouse movement

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#644]
##### System information (version)

- mandelbulber2 => 2.18 dev
- Operating System / Platform => Win 7 64bit

##### Steps to reproduce

Just press both buttons and move around 'quickly'/continuous for some seconds. After a while it does "strange movements" and the program is closing completely without any errormessage.
OpenCL-mode full. Tested with several different fractals, complex and very simple ones, crashing every time here if I move around with mouse long enough

**Comment by mclarekin** [comment]
is both buttons "ctrl mouse " or   "left and right buttons on mouse"?   I
just tried in openCL with the default image. and could not reproduce.

However i have suspected there may be something wrong with some
combinations of buttons. Hard to explain, but maybe it was something like
ctrl mouse sometimes still works after the ctrl button is released.  I
seldom use ctrl mouse so I miss these things

thanks for posting these issues at github, they needed to be recorded

**Comment by michas0602** [comment]
I just press both mousebuttons and moving mouse around, just a bit is enough, but constantly...when I do it long enough the program is closing

**Comment by mclarekin** [comment]
I managed to reproduce and the program crashed

**Comment by buddhi1980** [comment]
Maybe this https://github.com/buddhi1980/mandelbulber2/commit/6a54258f69e91815ae513401a3b9ebdcf2548a38 fixed this bug

**Comment by mclarekin** [comment]
nope.

  I am not sure what holding down both left and right mouse buttons is
supposed to do, but it wil eventually crash the porhram if you keep moving
the mouse around
