### ISSUE TITLE
Discussion about stereo renders

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#652]
I am exploring stereoscopic left-right with 3DTV and the distance between eyes constantly requires updates and adjustments.  

How does the distance between eyes relate to the camera and target positions?

**Comment by buddhi1980** [comment]
Read tooltip for "distance betwen eyes" :)

**Comment by buddhi1980** [comment]
General hint for animation: you should set one value for distance between eyes for whole animation. Changing it during animation gives weird feeling that depth is changing. 
Example how it looks like when distance is constant: https://www.youtube.com/watch?v=CUpi_yQyoh0

**Comment by mancoast** [comment]
Ok thanks, I see the tip from 1-5% of distance from camera to target. Finally verified the 3D stereo on 3DTV  with active shutter glasses and it does look incredibly 3D. The 4K stereo render with MC looks better than the SFX I see in movies!

Unfortunately I cannot view your 3D YouTube on my TV as it’s only available in anaglyph and I require SBS. Have you tested the 3D stereoscopic render with active shutter hardware?

Is it possible to animate and hold distance from camera to target constant?

**Comment by buddhi1980** [comment]
Just added (commit https://github.com/buddhi1980/mandelbulber2/commit/e3a906cedcb5447184b736b9c4a3d41828071427) button "Calculate optimal distance between eyes" which sets distance between eyes to 5% of estimated distance to the fractal. It should help.
Adding automatic calculation of distance between eyes in animation doesn't make sense. I have tested it and result is awful. User should decide what to do with distance.
I still think thank for whole animation should be used exactly the same distance.
