### ISSUE TITLE
Animation Panel broken when render window is detached.

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#654]
Windows 10, current nightly although has been like this as far back as I can recall. When you detach the render window, the keyframes all vanish from the animation panel and can only be retrieved by reattaching the render window and closing and reopening the animation panel. Which is fine..Until youve done it 400,000,000 times. :D

**Comment by mancoast** [comment]
I am getting weird animation dock results also. When I try to resize the dock, it also disappears in similar fashion with detached window.

**Comment by buddhi1980** [comment]
Fixed

**Comment by mancoast** [comment]
thanks!
