### ISSUE TITLE
Ubuntu build script - broken links in /usr/share

### ISSUE THREAD

**Issue by greytery** [buddhi1980/mandelbulber2#655]
##### System information (version)
- mandelbulber2 => 2.17
- Operating System / Platform => Mint 19.1 (aka Ubuntu)
- Compiler => n/a

##### Detailed description
(Minor - but annoying)

Links for /usr/share/mandelbulber2/doc and data are broken.
See Debian script also.

Fix in  /tools/prepare_for_dev_ubuntu.sh
{line 69 change to}
sudo ln -s ${PWD}/deploy/share/mandelbulber2/data $MANDELBULBER_SHARE/data
{line 76 change to}
sudo ln -s ${PWD}/deploy/doc $MANDELBULBER_SHARE/doc

##### Steps to reproduce
ls -la /usr/share/mandelbulber2

**Comment by buddhi1980** [comment]
Thanks for reporting it and providing correct code. I have just corrected it.
