### ISSUE TITLE
Why can't Mandelbulber 2.17 open fract files made by 2.18?

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#659]
I have both versions and wanted to do some render tests. I can test 2.17 fract files on both versions but not the other way.

**Comment by mclarekin** [comment]
just change 2.18 to 2.17  in a text editor, and you will be able to open
them unless it is using a new feature or formula that is only in v2.18

# Mandelbulber settings file
# version 2.18

**Comment by TasMania17** [comment]
Thanks mclarekin I already tried that.
I found once v2.18 is installed then v2.17 no longer opens any fract file with good graphics - just pixelated junk. (even if made with the same version)
I renamed the 2 mandelbulber folders and let it make new ones but same result. (Texture fracts also have version numbers)
For me v2.18 takes longer to render frames but unable to test it.

**Comment by TasMania17** [comment]
I think I know how to test MDBB versions for rendering.
2 folders should be renamed on linux - where you build Mandelbulber and the symbolic links folder. For me symlinks is /usr/share/mandelbulber2.
Otherwise the symlinks point to the wrong version.
Then install/build a newer version which makes a new Mandelbulber2 folder and a new symlinks folder.
Also need to test with an older fract file that has variables supported by both versions being tested.
The 2 user folders don't need to be changed.

**Comment by buddhi1980** [comment]
You can have many portable instances of Mandelbulber on Linux. 
Compile program in following way (example):
```
Compiling from source. PREFIX specifies where the program will be installed.
qmake PREFIX=/tmp/mymandelbulberinstance mandelbulber-opencl.pro
make -j4

installation in specified directory:
sudo make install

run:
/tmp/mymandelbulberinstance/bin/mandelbulber2
```

Every instance will use own shared files. In this way will not be mixed OpenCL source files. You got wrong results, because older version cannot use OpenCL source files from newer version.

**Comment by buddhi1980** [comment]
I forgot, that make install option was added March 20th. So 2.17 have to be compiled and installed in regular way. 2.18 can work as portable application.

**Comment by TasMania17** [comment]
Thanks buddhi1980. I note you have made some changes to the OCL engine in 2.18. 
I'm glad you are working on it because medium OCL mode is a lot faster than full OCL mode.

**Comment by mclarekin** [comment]
can this be closed?
