### ISSUE TITLE
special character issues

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#66]
TODO: check for support for special characters on user defined strings.
known issue: saving of image file with some characfters yields other characters ä -> Ã¤

**Comment by buddhi1980** [comment]
We have to check if in every place we use UTF-8 coding.

**Comment by zebastian** [comment]
i am always keep special characters out of my filenames to avoid these problems, so i did not recognize this problem.
But of course in our own program we should be most generous in supporting all kinds of characters.
Yes, we have to check all occurences...

**Comment by buddhi1980** [comment]
I cannot reproduce this problem on my PC. I have tried with file name: testóję2ÄÖÜäöüinormalneliterki and it works properly with JPG, PNG and saving settings. Probably my system configuration is different than yours.
My locale settings are pl_pl UTF-8

**Comment by buddhi1980** [comment]
There is possible that this part of code creates problem:

(files.cpp:56)
```
void SavePNG(QString filename, int width, int height, png_byte *image)
{
	/* create file */
	FILE *fp = fopen(filename.toUtf8().constData(), "wb");
...
```

Here is conversion to char format. Unfortunately I cannot check it.

**Comment by buddhi1980** [comment]
Have you observed this problem under Linux or under Windows?

**Comment by zebastian** [comment]
With Windows, Windows has some other default encoding than Linux, so this is probably the point

**Comment by zebastian** [comment]
Fixed with tolocal8bit
