### ISSUE TITLE
Auto refresh not working at times

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#664]
Has happened to others and me,  intermittant, and have no idea how to reproduce it.
Probably inked to recent commits

**Comment by mclarekin** [comment]
i am in ubuntu (C++) auto refresh is not working

**Comment by mclarekin** [comment]
and now it is,  so maybe does not work on initial loading, i will try again.

**Comment by mclarekin** [comment]
that is it, pull, load, render std mbulb, enable auto refresh,  change mbulb parameters = no auto refresh. Then I dragged mbulb with the mouse, and now auto refresh is working on the parameters

**Comment by buddhi1980** [comment]
Found the problem. One important variable about dragging by mouse state was uninitialized so application started with random state.

**Comment by mclarekin** [comment]
It seems to be fixed, so i will close. I have not checked in c++ but expect it to be OK

**Comment by buddhi1980** [comment]
If everything works, today evening I will release 2.18-1 which has this bug-fix
