### ISSUE TITLE
Typo on Program Settings/Image/"thumbnail"

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#665]
##### System information (version)

- mandelbulber2 => 2.18
- Operating System / Platform => Windows 64 Bit

- Compiler => 
##### Detailed description

Program Settings/Image tab: "render thubnails with OpenCL (if OpenCL enabled)"

Should be "thumbnails."

**Comment by buddhi1980** [comment]
Corrected
