### ISSUE TITLE
OpenCL DOF using only one GPU of two

### ISSUE THREAD

**Issue by artBoffin** [buddhi1980/mandelbulber2#669]
##### System information (version)

- mandelbulber2 => v2 2.18-1
- Operating System / Platform => Ubuntu
- Compiler => none

##### Detailed description

It appears OpenCL DOF is only using 1 out of 2 cards while the fractal rendering uses the 2

##### Steps to reproduce

Render fractal using DOF option and more than one GPU

**Comment by buddhi1980** [comment]
DOF won't be rendered with 2 GPUs, because this algorithm is very difficult to share between two cards.
