### ISSUE TITLE
PNG-16 and other image options missing from queue

### ISSUE THREAD

**Issue by artBoffin** [buddhi1980/mandelbulber2#671]
##### System information (version)

- mandelbulber2 => v2 2.18-1
- Operating System / Platform => Ubuntu
- Compiler => :grey_question:

##### Detailed description

PNG-16 and other image options are missing from output options in queue

**Comment by mclarekin** [comment]
I  do not use Queue , but have you tried setting what you want in Program
preferences  - image tab, before using queue?

**Comment by mancoast** [comment]
Hello Alex, thanks for getting involved with us here on Github. I have noticed that you have a lot of feedback regarding interesting corner cases and new features. Are you building the software from source? Do you have experience with C++? We need more people on our team.

**Comment by artBoffin** [comment]
Hello, no, not building from source.
I don't really know C++ at the level you would need, though happy to help somehow, can just keep on the lookout for things I find at a minimum.
