### ISSUE TITLE
 Bulber crashed by detaching main render window 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#675]
Jorge Abalo  : Bulber crashed by detaching main render window and resetting to default, after 3 hrs render 😧

**Comment by buddhi1980** [comment]
In last commit https://github.com/buddhi1980/mandelbulber2/commit/212c3aba70b535b4dbdf3b547111c98e2af32de8 I'm trying to fix this problem. Unfortunately I cannot reproduce it.

**Comment by mclarekin** [comment]
I got Jorge to check, but problem still there

"I just detached main windows and reset to default layout and program vanished without a warning. still same issue"

**Comment by mclarekin** [comment]
UPDATE    15/5/20   
Mclarekin : do you still have the detach main window issue?
Jorge: No, it seems solved. Never had this crash again :)

Will close this and reopen if it happens again
