### ISSUE TITLE
Add buttons to swap fractal slots

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#68]
Would be nice to have possibility to change order of formulas in hybrid sequence
We can add buttons with arrows on each fractal tab. It will swap parameters and formula settings between tabs.

I have already analyzed if we can use built-in functionality in Qt to swap tabs. Unfortunately it will generate a lot of problems with widget naming (it has numbers in names) and data synchronization.

**Comment by mclarekin** [comment]
It is possible to also do this in table format along with any special
iteration requirements for each fractal. But I would  like to be able to
drag & drop them. Any method will be good, and  also sometimes it is good
to have more than one method of doing things.





On Sat, Jan 2, 2016 at 10:23 PM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
Yes, lately I have needed the the possibility to change order of formulas in hybrid sequence when testing.   Example,  I set up a five slot hybrid and then decide I want to insert another transform at slot 2 and move the existing 2, 3, 4& 5 each one slot to the right, irequires too much work..
