### ISSUE TITLE
Batch Mode OpenCL Device Auto Selection

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#686]
Hi,
I am running Mandelbulber in OpenCL Mode on a Renderfarm.
(With RoyalRender Render Manager, not NetRender)

Basically all I do is create a command from the mandelbulber file that gets executed on the farm.
Something like:

`"C:\RR_localdata\renderer_exe\mandelbulber\win_x64\mandelbulber_2.18\mandelbulber2.exe" -n -K -s 494 -e 496   "C:\RR_localdata\cachedscenes\strandsofmind_030_Production\010_Shots\c93fb505\WORK\rooty_classic_flight_v004_am.fract"`

This works mostly fine.
One issue I have is that each Client Machine has a different GPU configuration.
I have a global mandelbulber_218.ini file with preferences set.

For instance
```
opencl_enabled true;
opencl_memory_limit 10000;
```

I left out the opencldevicelist as I cannot hardcode this, as I don't know the name of the GPU on the machine.

Luckily Mandelbulber does this:
```
Error: No OpenCL devices selected or selected unknown devices!
Selected first available GPU device
Check program preferences to select correct OpenCL devicefrom list of available GPU devices
```

But as I have a lot of clients with Multiple GPUs, it would be important that the default behaviour of Mandelbulber is not to only pick the first one but picks all available GPUs.

Also it would be handy if it automatically sets the opencl_memory_limit to a appropriate value.

Also it would be great if Mandelbulber detetcs from the .fract file if OpenCL should be enabled or not, and not have this set as a global option.
(As this forces me to hardcode the global .ini file if I want to change to CPU render or back)

Do you think that would be possible?
Would be a great help to get this running smooth and fast on the farm.

Thanks!
Adrian

**Comment by buddhi1980** [comment]
You can use option -g (--gpu) which uses first available GPU in computer or -G (--gpuall) option which utilizes all available GPUs. You don't need to specify them in ini file.

**Comment by MeyerAdrian** [comment]
ah awesome! thanks.
Is there a similar option for enabling / disbaling opencl?

**Comment by MeyerAdrian** [comment]
Do I understand right, that currently it is determined if OpenCL is used by the `opencl_enabled true; `setting in the global .ini file?

I think it would make a lot of sense to move that to the .fract file.
As well as `keyframe_animation_image_type jpg;` `flight_animation_image_type jpg;`
Because right now I always have to hardcode this in the global farm .ini.
I cannot say I want to render this scene, lets say as .EXR and OpenCL and the other in .JPG and CPU.
That would be great if I could read that info from the .fract file.

Or is there another workaround?

Thanks!

**Comment by coast77777777777** [comment]
These are some interesting ideas. I am also curious to see your final productions! Cheers 🍻

**Comment by MeyerAdrian** [comment]
> These are some interesting ideas. I am also curious to see your final productions! Cheers 🍻
> […](#)
> On Jul 16, 2019, at 8:15 AM, Adrian Meyer ***@***.***> wrote: Do I understand right, that currently it is determined if OpenCL is used by the opencl_enabled true; setting in the global .ini file? I think it would make a lot of sense to move that to the .fract file. As well as keyframe_animation_image_type jpg; flight_animation_image_type jpg; Because right now I always have to hardcode this in the global farm .ini. I cannot say I want to render this scene, lets say as .EXR and OpenCL and the other in .JPG and CPU. That would be great if I could read that info from the .fract file. Or is there another workaround? Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Sure, I will tell you when its finished and also soon post some pictures...

**Comment by MeyerAdrian** [comment]
Aha I see, so -g means use openCL and use first GPU combined in one argument right?

**Comment by buddhi1980** [comment]
-g uses first available GPU (no arguments needed). -G will use all available GPUs (also no additional arguments needed)

**Comment by MeyerAdrian** [comment]
alright thanks.

what do you think about the idea to move `keyframe_animation_image_type jpg; flight_animation_image_type jpg;` to .fract file instead of .ini ?

**Comment by buddhi1980** [comment]
I think it is not a good idea. In 99% you don't need to change format. If somebody prefer to work with PNG, then almost always use PNG. The same with JPG. If I move it to .fract file then user every time will need to remember to change saving format.

**Comment by MeyerAdrian** [comment]
alright, I guess I can live with it (-;

**Comment by MeyerAdrian** [comment]
I am struggling to select the correct GPU_Devices on the Renderfarm.
I want to set opencl_device_list in the commandline, but it only supports the GPU hash.
Every client machine has different GPUs and drivers etc.
So it would be important for us to set the GPU Device Index, not the hash in the commandline.

Is that possible or if not hard to implement?

Thanks!

**Comment by MeyerAdrian** [comment]
Ok we found a workaround by using CUDA_VISIBLE DEVICES and then using -G option

**Comment by zebastian** [comment]
Please reopen, anyone who requires something like this.
