### ISSUE TITLE
Wished feature - Shortcut for Image save as

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#688]
Hi,
it would be a very timesaving feature if there was a shortcut for the save as image command.
Do you think thats possible?

Maybe with a preference option which format the shortcut saves.

(as I work with the fractals in VR I save the VR Images sometimes many times a minute to be able to see them in the VR Headset.)

**Comment by zebastian** [comment]
sure, will look into this...

**Comment by zebastian** [comment]
done in this commit https://github.com/buddhi1980/mandelbulber2/commit/a72f64813f872e17e41d62c59e0849ab9fb13f71
