### ISSUE TITLE
Keyframe Animation Feature - Change Keyframe Time afterwards

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#689]
Hi,
it would be great if it was possible to change the time (frame number) of a keyframe after having set the keyframes initially.

So when I notice between two keyframes, I need more time, I can set one keyframe for instance from frame 600 to 800, getting 200 frames more in between.
Right now this is not possible, do I see that right?

Also It is mentioned that I can edit the Keyframes in a external .csv file.
Where do I find this?

Thanks!

**Comment by buddhi1980** [comment]
Now you cannot change change time between keyframes. It is something for future improvements. It is actually very simple keyframe editor. To make it much better (e.g like in Cinema 4D) there is needed huge development.
Now you can add keyframe in the middle of animation to increase number of frames.

To edit keyframes as csv file, you can load part of .fract in Libre Office Calc (or Excel)
In the file there is a section [keyframes] which is separated by semi-colons. Just copy/paste it to Calc.

example:
```
# Mandelbulber settings file
# version 2.19
# only modified parameters
[main_parameters]

...

[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;fractal0_transf_scale_3
0;1,72108224976709;-2,336699204249334;2,25167744184476;0,7156085599227537;-0,9770670601242546;1,036745317066262;-0,3233517823814001;0,4862634503038875;0,8117829030777444;3
1;1,287364097941304;-1,523145287034019;1,518555337489031;0,853645946115518;-0,7095913698187046;0,785433233133302;-0,3423201330037645;0,5216909899694019;0,7814444558156586;5
interpolation;morphAkima;morphAkima;morphAkima;morphAkima
```

**Comment by mclarekin** [comment]
@MeyerAdrian 
a)  https://mandelbulber.org/graemes-blog/  16th may 2018 example of csv
b) you can renumber frames in a batch renaming editor. that is how i have dealt with having to add in extra frames in the past.  If you are interpolating with akima or catmul rom, you need to redo a few keyframes either side for you interpolation to be smooth. There is info on this at facebook site, if you search akima or catmull .
As Krzysztof says, there are enhancements planned, but there is no time frame.
If you need more help just ask, if you have got it sorted, close issue :)

**Comment by MeyerAdrian** [comment]
Okay thanks I see.
I'll try to work my way around it (-;
