### ISSUE TITLE
Individual bailouts settings

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#69]
I have been recently started to code formulas that require low bailouts, and I notice that Aexion_Octopus is another with bailout 4 being OK.

It would be good if formulas could have individual default bailout settings.

Individual bailouts would be required to use these fractals in BooleanUnite

**Comment by buddhi1980** [comment]
We can add this parameter to each formula (in formula list).
I will add checkbox "Use default formula bailout" by bailout slider (will be enabled by default). This should be enough.

**Comment by buddhi1980** [comment]
Done by commit 15f8c34
