### ISSUE TITLE
Help Wanted - Fractal & Primitive Boolean

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#690]
Hey guys,
quick question.
Is it possible to do a boolean operation between say a sphere primitive and a Mandelbulb Fractal?

Could not find a way so far.

Thanks!

**Comment by mclarekin** [comment]
only like this with primitives, so union only, (does not need to be boolean
mode)

However intersection and complement should be possible using a bulb sphere,
i will have a look if you like?

**Comment by mclarekin** [comment]
So intersection worked,  but complement has got a cube in it

![ggg4](https://user-images.githubusercontent.com/12769564/61589571-0bd50c80-ac00-11e9-9b64-a026f5a99ff5.jpg)
![ggg3](https://user-images.githubusercontent.com/12769564/61589580-36bf6080-ac00-11e9-8ad5-ab579054e862.jpg)

**Comment by MeyerAdrian** [comment]
Cool,
thanks!
how did you do it?

**Comment by mclarekin** [comment]
which did you want?  here is intersection.  Note that in slot#2 i have a mandebulb with "Dont add global c" ticked, most mandelbulbs will revert to a sphere if you do this


# Mandelbulber settings file
# version 2.18
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
boolean_operator_1 0;
boolean_operators true;
camera 1.183596487396162 -2.367192974792324 0.7890643249307747;
camera_distance_to_target 2.761725137257712;
dont_add_c_constant_2 true;
flight_last_to_render 0;
formula_2 2;
keyframe_last_to_render 0;
mat1_is_defined true;
primitive_box_1_enabled true;
primitive_cylinder_1_caps false;
primitive_cylinder_1_empty true;
raytraced_reflections true;
[fractal_1]
IFS_rotation_enabled true;
[fractal_2]
IFS_rotation_enabled true;
[fractal_3]
IFS_rotation_enabled true;
[fractal_4]
IFS_rotation_enabled true;

**Comment by mclarekin** [comment]
BTW If  this is what you want, close the issue

**Comment by MeyerAdrian** [comment]
Ah I seee.
Thanks
