### ISSUE TITLE
High CPU use problem

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#691]
win 10 medium mode.  
these settings are causing high cpu use, with the result program becomes very slow, like very long calcualtion. Continues after rendering has finished. Need to restart program to fix
Is this reproducible by others?
# Mandelbulber settings file
# version 2.19
# only modified parameters
[main_parameters]
ambient_occlusion_mode 1;
ambient_occlusion_quality 3;
bailout 25;
basic_fog_color 7f00 4800 3700;
basic_fog_enabled true;
basic_fog_visibility 10;
brightness 1.7;
camera 12.68183942955356 -19.60897838577061 9.613220968552531;
camera_distance_to_target 25.25381361380527;
camera_rotation 32.89221807977107 -22.37482641312584 -2.753523957166602;
camera_top -0.2468234555269103 0.2931838135113749 0.923645729323036;
contrast 1.1;
DE_thresh 0.0025;
delta_DE_function 1;
delta_DE_method 2;
detail_level 0.5;
DOF_blur_opacity 1;
DOF_focus 1.17618727684021;
DOF_MC_global_illumination true;
DOF_number_of_passes 3;
DOF_radius 11;
dont_add_c_constant_1 true;
file_lightmap /usr/share/mandelbulber2/textures/lightmap2.jpg;
flight_last_to_render 0;
formula_1 119;
formula_2 61;
formula_iterations_1 20;
formula_material_id 3;
fov 0.7;
fractal_rotation 0 90 0;
gamma 1.2;
glow_enabled false;
hybrid_fractal_enable true;
image_height 1200;
image_width 1600;
julia_c -2.08 0 0;
julia_mode true;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
main_light_colour ff00 ff00 ff00;
mat1_is_defined true;
mat3_coloring_speed 1.2;
mat3_displacement_texture_height 0.025;
mat3_fresnel_reflectance true;
mat3_is_defined true;
mat3_name stone-1;
mat3_reflections_color e900 7200 f800;
mat3_specular 2.5;
mat3_specular_color ec00 ed00 ee00;
mat3_specular_metallic 8;
mat3_specular_width 0.025;
mat3_surface_color 2100 2100 2100;
mat3_surface_color_gradient 0 5f7a58 2000 b9466a 4000 67a275 6000 a88188 8000 f2ffcc;
mat3_texture_scale 16 16 2;
mat3_use_color_texture true;
mat3_use_colors_from_palette false;
N 31;
reflections_max 1;
repeat_from 2;
saturation 1.3;
use_default_bailout false;
[fractal_1]
mandelbox_scale 1;
transf_addition_constant -1.68 0 0;
transf_maxR2_1 0.7;
transf_minR2_p25 0;
transf_scale3D_000 0 1.8 1.1;
[fractal_2]
transf_addition_constant -0.1 0 0;
transf_addition_constantA_000 0 0 -0.7;
transf_constant_multiplier_111 1.4 0.7 1;
transf_function_enabledx_false true;
transf_offset 0.4;
transf_scale_3 2.5;

**Comment by mclarekin** [comment]
Now  the problem has stopped :), it might be my  computer or  how i was using the program. I will try and recreate problem

**Comment by buddhi1980** [comment]
Is it possible that toolbar icons were being refreshed?

**Comment by mclarekin** [comment]
No, unexplained excess CPU use  occassionally  happens for me,  it is very
rare.   Will continue to monitor.

**Comment by mclarekin** [comment]
After leaving the computer for 30minutes (auto refresh off, in full mode), cpu averaging 20%. 
This is a few hours after V2.20 refreshed thumbnails on loading.

But I am guessing that yes  it is related to having lots of toolbar presets, or maybe a preset running a near infinite calculation
I have removed them and now the idle program uses 0,1% of my CPU at random intervals  e.g  10 sec, 3 sec, 53 sec, this is normal behaviour.
Reinstated them and I am back to running at about 18% cpu,

A few hours later and it has stopped.  

I will continue to monitor, but i should really get rid of a few hundred presets :)

Minor issue

**Comment by taurus66** [comment]
I encountered this Problem, when changing julia constants (e.g. when grabbing constants). I guess it is the preview image. Additionally it uses almost 100% of CPU although I limit CPU cores to 6 of 8. You should consider removing this preview image entirely. It was a nice idea, but it is useless in many cases. In hybrid mode it obviously only uses slot 1. And all in all it only slows down workflow with very limited benefit. IMHO not that minor and above all annoying in daily use. System win10

**Comment by taurus66** [comment]
I found a practical fix. Set Julia mode preview distance to 1000. I encountered no unappropriate CPU usage, since I did that. Once again remove this or do something useful with it. In this condition Julia preview is ballast not benefit. Tim Ewing once suggested it and you did implement this in a hurry. Not a good idea...

**Comment by buddhi1980** [comment]
I will add option to disable it (will be disabled by default) and improve it to work with hybrids.

**Comment by buddhi1980** [comment]
Julia preview now can be disabled. Rendering of previews of hybrid fractals is corrected. 
When in preferences there is set to render thumbnails with OpenCL it works very fast and doesn't load CPU at all.
