### ISSUE TITLE
Travis CI Continuous Build Help

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#694]
Hey,
could anyone give me a helping hand with Mandelbulber Travis CI Continuous Build?

I would like to be able to get the current dev status of Mandelbulber.
How do I set this up with TRavis to Build Mandelbulber?
(I would prefer to build it whenever I chosse to, not automatic building by every update)

Would be awesome. Thanks!

Windows 10 64 Bit

**Comment by buddhi1980** [comment]
We already have Travis CL integrated with Github repository

https://travis-ci.org/buddhi1980/mandelbulber2

It produces daily AppImage builds for Linux which are here: 

https://github.com/buddhi1980/mandelbulber2/releases/tag/continuous

**Comment by buddhi1980** [comment]
For Windows build we use Appveyor platform:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2

which also makes executable files
- select one of builds
- select Release x64
- download package from Artifacts

**Comment by MeyerAdrian** [comment]
Wow,
thats so cool!!
thanks a lot!
Needed that Windows Appveyor thing. Didn't know about it
