### ISSUE TITLE
Azure Pipelines

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#696]
explore Azure Pipelines continuous integration

**Comment by coast77777777777** [comment]
@buddhi1980 can you please download/enable azure piplines from the marketplace for this repo? Only you have authentication and permissions as repo owner. It is not an easy process, and has many steps, but we only have to do it once.

I just discovered azure pipelines. IMO its probably safe to predict it might knock the other CI services out of the game, so might be a good idea to start developing our pipelines for azure.

**Comment by TasMania17** [comment]
Sounds good in theory - a cross compile platform for windows hosted by microsoft.
Some user feedback would be good. I found this:
https://news.ycombinator.com/item?id=18983586

If open source projects like MDBB are publicly available via github then why can't anybody fill out the forms and make a windows binary with azure?

**Comment by zebastian** [comment]
azure pipelines are now integrated:
https://dev.azure.com/buddhi19800328/Mandelbulber/_build?definitionId=1
Please reopen, if anything is missing...

**Comment by buddhi1980** [comment]
Ot looks like Rob deleted his GitHub account

**Comment by TasMania17** [comment]
I wonder if it's github security? They told me my password was weak and when I changed it I was locked out of the only repository I contribute to.

**Comment by mclarekin** [comment]
I have know i idea?? I  changed my weak password but can not remember
having any problem
