### ISSUE TITLE
Missing button to place centre of random lights by mouse pointer

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#70]
There is needed something like for placing positional light sources.
It should also calculate light distribution radius as a half of camera distance to centre of distribution.
Max distance from fractal surface should be about 10% of camera distance.

**Comment by mclarekin** [comment]
"It should also calculate light distribution radius as a half of camera
distance to centre of distribution
Max distance from fractal surface should be about 10% of camera distance"

possibly add as information in a  tooltip ??

**Comment by zebastian** [comment]
done with: f366ce62896fef2a12fca40fb4632b70782fb08e

@mclarekin the info is in the HUD when you are hovering over the rendered image while in according click mode.
@buddhi1980 works very well with your suggestion
