### ISSUE TITLE
Hard crash on GPU DOF memory failure

### ISSUE THREAD

**Issue by artBoffin** [buddhi1980/mandelbulber2#700]
##### System information (version)

- mandelbulber2 => 2.19
- Operating System / Platform => Ubuntu
- 2x RTX Titan GPUs

##### Detailed description

Hard crash on GPU mem error (does not switch to CPU)

Critical: Not enough GPU mem!
(../src/opencl_engine_render_dof.cpp:105, bool cOpenClEngineRenderDOF::RenderDOF(const sParamRender*, const cParameterContainer*, cImage*, bool*, cRegion<int>))

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by artBoffin** [comment]
Update:
I increased the GPU memory slider to maximum (around 24 GB) and while I did not get the GPU mem error, it still hard crashed with:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by buddhi1980** [comment]
What leads to this problem? Are you trying rendering image in enormous resolution?

**Comment by artBoffin** [comment]
Yep, large resolution for a 600dpi 44 inch print (have successfully done others at this size)
26500 x 20500
It renders fine, but seems to die on the DOF part
CPU is threadripper 2990 (64 threads) 64 GB RAM

**Comment by buddhi1980** [comment]
The program was never tested with such a high resolition, especially with DOF efect. 
DOF effect needs a lot of RAM at such a high resolution. From rough estimation you would need about 80GB RAM to render it at this resolution. DOF needs a lot of additional memory buffers.

**Comment by artBoffin** [comment]
Certainly understand that, probably pushing the limits hard here.
I think my motherboard supports up to 128 GB of RAM, so could try that at some point.
