### ISSUE TITLE
All OpenCL Renders are pink, low quality, and blocky

### ISSUE THREAD

**Issue by LulzRose** [buddhi1980/mandelbulber2#703]
- mandelbulber2 => 2.19
- Operating System / Platform => Windows 64 Bit 
- GPU => GTX 1060-6GB
I have been attempting to render using OpenCL since CPU usually takes a few hours but everytime I render any file (Examples, Custom, Random Internet) the outcome is low quality blocky and pink with a blue or pink background. This happens nomatter the resolution, material, color, or quality set . Rendering only takes max 10 seconds on opencl even when rendering in 8k

Edit: Some renders do not even show an object just a background, a huge glow, or a random color

![image](https://user-images.githubusercontent.com/33618233/64316180-b3708900-cf79-11e9-95f8-718c9f2e366f.png)
![image](https://user-images.githubusercontent.com/33618233/64316227-d733cf00-cf79-11e9-9889-4f55aed4c094.png)

**Comment by buddhi1980** [comment]
Change OpenCL mode to full. Selection is just below render button. Actualy you use fast mode which is designed for fast preview of fractal shape

**Comment by LulzRose** [comment]
Thank you I promis im not blind <3
