### ISSUE TITLE
[Request]Ability to invert Palettes in texture panel?

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#705]
The ability to copy/paste and then invert a palette in the texture panel would be useful imo. If your using a palette to make something shiny, You might use its inverse to lower roughness in the shiny area? Does that make sense?

**Comment by buddhi1980** [comment]
It is also good idea and easy to do.

**Comment by buddhi1980** [comment]
Button added in commit https://github.com/buddhi1980/mandelbulber2/commit/89d414e5a9d4171ba69f38b0f8194ac8988b07f5
