### ISSUE TITLE
[Suggestion] Denoising Algo?

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#710]
Blender now features a denoiser which essentially makes less intensive renders look good. Wondered if this might pair well with MC and also be good for those surfaces you just cant quite get right? This guy might know something https://github.com/DeclanRussell/NvidiaAIDenoiser

**Comment by buddhi1980** [comment]
I agree that it would be great to have good denoising algorithm. It would save a lot of rendering time

**Comment by b1tfl0w** [comment]
Here are some test I made in mandelbulber and intel open image denoise..might be easy to implement?
The process description is in the first post:

[post1](https://www.facebook.com/groups/mandelbulber/permalink/2755182731206542/)
[post2](https://www.facebook.com/groups/mandelbulber/permalink/2755379017853580/)

Also these:

![flobu](https://user-images.githubusercontent.com/30445498/71381255-0034aa00-25d3-11ea-96e4-a6c62e3d6cb0.png)
![output](https://user-images.githubusercontent.com/30445498/71381262-062a8b00-25d3-11ea-81a1-e1c39b27f7b5.jpg)

**Comment by buddhi1980** [comment]
Denoiser is already implemented
