### ISSUE TITLE
[Request] More options for Render Server

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#715]
Me again..
Currently, stopping a Netrender can leave the end of the rendered part in a mess due to the last batch of frames that were handed out no being completed. Would it be possible to limit/change the size of the work lists handed out and have an option to complete current bunch of frames before stopping? Couldnt figure out why the chunk of frames I was compiling was skipping :D

**Comment by buddhi1980** [comment]
Why you expect to have (semi)finished work when you press stop? Many other guys would expect to stop rendering immediately to be able to start next one. 
Even now you can stop any time and if you need to have complied some part of animation you can set "end frame" and render animation to this frame and have rendered all what is needed

**Comment by zebastian** [comment]
@buddhi1980 can we close this?
