### ISSUE TITLE
[Request] Patch hard-coded paths in mandelbulber2/deploy/share during install

### ISSUE THREAD

**Issue by KoviRobi** [buddhi1980/mandelbulber2#719]
Hi,

I am packaging mandelbulber2 for NixOS (see NixOS/nixpkgs#66390), which doesn't install mandelbulber in '/usr/share' (plug: see [here](https://nixos.org/nixos/nix-pills/why-you-should-give-it-a-try.html#idm140737316704928) for why). Also, some of the examples use "/home" or Windows directories (not sure if there are Mac paths, not sure how those go)

```sh
$ cd mandelbulber2/deploy/share/mandelbulber2/examples

$ grep -r '/home\|/usr'
Krzysztof Marczak collection - license Creative Commons (CC-BY 4.0)/Construct by Ectoplaz 2.fract:file_lightmap /usr/share/mandelbulber2/textures/lightmap2.jpg;
Sebastian Jennen collection - license Creative Commons  (CC-BY 4.0)/aexion blue-sky-two-suns.fract:file_background /usr/share/mandelbulber2/textures/envmap6.jpg;
gradients - reflectance and transparency.fract:file_background /usr/share/mandelbulber2/textures/background3.jpg;
gradients - specular highlights.fract:file_background /usr/share/mandelbulber2/textures/background3.jpg;
mandelbox_menger_with_textures.fract:mat4_file_displacement_texture /home/krzysztof/dane/3D/Tekstury/Public Domain/Uruktos/T_Tile_Sandstone_02_4096_H.png;
monte carlo global illumination.fract:mat1_file_diffusion_texture /home/krzysztof/dane/3D/Tekstury/Marble/Seamless marble texture (11).jpg;
monte carlo global illumination.fract:mat1_file_normal_map_texture /home/krzysztof/dane/3D/Tekstury/Marble/Seamless marble texture (11).jpg;
transparency reflectance roughness textures.fract:file_background /usr/share/mandelbulber2/textures/background3.jpg;

$ grep -r '[A-Z]:\\' 
Graeme McLaren  collection - license Creative Commons  (CC-BY 4.0)/mandelbulb_eye 001.fract:anim_keyframe_dir D:\mandelbulber\mbulbEye\mbulbEye\;
Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/box-deuce-deuce.fract:animsound_soundfile_fractal0_mandelbox_folding_min_radius D:\21LGv8Cf0us.ogg;
Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/box-deuce-deuce.fract:animsound_soundfile_main_mat1_coloring_palette_offset D:\21LGv8Cf0us.ogg;
Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/icoastahedron.fract:animsound_soundfile_main_camera_top_z D:\GIT\mandelbulber2\mandelbulber2\deploy\share\mandelbulber2\sounds\Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg;
Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/icoastahedron.fract:animsound_soundfile_main_mat1_coloring_palette_offset D:\GIT\mandelbulber2\mandelbulber2\deploy\share\mandelbulber2\sounds\Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg;
Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/menger-fatbackstrokin.fract:animsound_soundfile_main_mat1_coloring_palette_offset D:\dIOTV_ZtIwg.ogg;
```

Perhaps these could be patched up to SHARED_PATH during install?

**Comment by coast77777777777** [comment]
Greetings and welcome! The shared path could accept another case using preprocessing, or we could try to standardize. As for the examples, there is a helper function that searches the filename in a variety of places to support cross OS examples. No worries there. The shared folder needs some work. Do you have your patch ready for review?

**Comment by KoviRobi** [comment]
I don't have a patch yet, in the NixOS package I was just using regexp substitutions to where the examples get installed.

I feel that since binaries don't tend to be reused on different systems, perhaps it's simplest/neatest if we patch up the examples during the install phase, instead of having the program try different paths during runtime. (If I understood your comment about the helper function correctly.) Though perhaps something like interpreting "<SHARED_PATH>/...." (or "$SHARED_PATH/..." etc) in the runtime wouldn't be so bad, but still feels unnecessarily complex to me when a simple substitution during install would work.

I don't quite understand the whole qmake ecosystem, but if you could point me to somewhere where the patching up would be sensible, I would be happy to try and create a pull-request.

**Comment by coast77777777777** [comment]
were u able to make any progress with a pull request?

**Comment by KoviRobi** [comment]
No, I had a look at the qmake files, and have an idea of using envsubst for patching up the fract files, but not sure how exactly to add that to the qmake files

**Comment by coast77777777777** [comment]
Hello,

Ok sounds great. So you have a strategic method for handling the needed changes. If you make a pull request on this repo, then myself and others can see your changes to make suggestions. Your changes do not have to be finished or working for you to open the pull request. The pull request creates a new ”ticket in the queue” for our continuous integration services. Most importantly: you have unlimited chances/retries to experiment with different ways to patch it. So there is no pressure to have a working patch to open the pull request. After your done experimenting, your patch must pass all the continuous integration tests. Then myself or one of the other devs here will merge your pull request. At that point you will become an official code contributor to mandelbulber2. What do you think?

Thanks,
Coast

**Comment by KoviRobi** [comment]
I have made https://github.com/buddhi1980/mandelbulber2/pull/727 which seems to work for Linux, but has a few snags, and I don't know what to do for other platforms.

**Comment by buddhi1980** [comment]
What you think about different solution. Instead of preparing example files during installation wen can use similar way as you proposed but executed during running, Idea to replace path names in examples with string like SHARED_PATH is correct. The we could use extended FilePathHelper function (https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/files.cpp#L438) to replace SHARED_PATH with actual default path.

**Comment by KoviRobi** [comment]
That could work too, I think it has the advantage of being platform agnostic, and the disadvantage of then having to code up the substitution for the SHARED_PATH variable. Which could be as simple as a string replacement for "SHARED_PATH". Probably not too much of a hack, especially if we only do the replacement if the string begins with "SHARED_PATH", as that way absolute (or relative if they begin with "./") paths don't have "SHARED_PATH" substituted when they legitimately have that in the path.

**Comment by zebastian** [comment]
@KoviRobi can we close this?

**Comment by KoviRobi** [comment]
@zebastian I think so, thanks
