### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#72]
There are needed interesting example settings files for all new fractal formulas.

**Comment by mancoast** [comment]
This seems like an easy win.
Exactly which fractal formulas require examples?

**Comment by zebastian** [comment]
IMHO for every formula and every feature there should be an example file explaining the formula and the feature.
Additionally there can be as many nice looking formulas as we can find.
Graeme introduced a LOT new functions in the last couple of months, here it would be nice to have example settings for.

**Comment by zebastian** [comment]
Here is a list of all formulas, which not have any examples yet:
formula AboxModKaliEiffie 
formula Amazing_Surf_Multi 
formula Benesi Mag Transforms 
formula Benesi Pwr2 Mandelbulbs 
formula Collatz Fractal 
formula Collatz Fractal Mod 
formula Mandelbox Menger 
formula Mandelbulb_Bermarte 
formula Mandelbulb_Kali 
formula Mandelbulb_Kali_Multi 
formula Menger Cross KIFS 
formula Menger Cross Mod1 
formula Menger Pwr2 Polynomial 
formula Menger Middle Mod 
formula Menger - Prism Shape2 
formula MsltoeSym4_Mod 
formula Msltoe Toroidal Bulb 
formula Msltoe Toroidal Multi 
formula Riemann Bulb Msltoe Mod2 
formula Sierpinski 3D 
formula Imaginary scator Power 2 
formula Mandelbox Vary Scale 4D 
formula Menger 4D 
formula MixPinski 4D 
formula Sierpinski 4D 
formula Transform - Addition Constant 
formula Transform - Addition Constant VaryV1 
formula Transform - Add Cpixel 
formula Transform - Add Cpixel_Axis_Swap 
formula Transform - Add Cpixel_CxCy_Axis_Swap 
formula Transform - Add Cpixel_Symmetrical 
formula Transform - Add Cpixel_VaryV1 
formula Transform - Add exp2(z) 
formula Transform - Benesi_T1 
formula Transform - Benesi_T1Mod 
formula Transform - Benesi_T2 
formula Transform - Benesi_T3 
formula Transform - Benesi_T4 
formula Transform - Benesi_T5b 
formula Transform - Benesi_Mag_Forward 
formula Transform - Benesi_Mag_Backward 
formula Transform - Benesi_Cube_Sphere 
formula Transform - Benesi_Sphere_Cube 
formula Transform - Box_Fold VaryV1 
formula Transform - Box_Fold XYZ 
formula Transform - Box_Offset 
formula Transform - Fabs_Add_Constant 
formula Transform - Fabs_Add_ConstantV2 
formula Transform - Fabs_Add_Conditional 
formula Transform - Fabs_Add_Multi 
formula Transform - Fabs_Add_Neg 
formula Transform - Folding Tetra3D 
formula Transform - Iteration Weight 
formula Transform - Inverse Cylindrical 
formula Transform - Linear Combine Cxyz 
formula Transform - Menger Fold 
formula Transform - Multiple angle 
formula Transform - Octo Fold 
formula Transform - Platonic Solid 
formula Transform - Power2 Polynomial 
formula Transform - Quaternion Fold 
formula Transform - Reciprocal3 
formula Transform - Rotation 
formula Transform - Rotation_VaryV1 
formula Transform - Rotation Folding Plane 
formula Transform - Rotated Folding 
formula Transform - R^Power 
formula Transform - Rpow3 
formula Transform - Scale 
formula Transform - Scale VaryV1 
formula Transform - Scale VaryVCL 
formula Transform - Scale 3D 
formula Transform - Sphere_InvertC 
formula Transform - Spherical_Fold 
formula Transform - Spherical_Fold ABox 
formula Transform - Spherical_Fold VaryV1 
formula Transform - Spherical_Fold_VaryVCL 
formula Transform - Spherical_Pwr_Fold 
formula Transform - Spherical_Offset 
formula Transform - Spherical_OffsetVCL 
formula Transform -Surf Box_Fold 
formula Transform - Surf Fold Multi 
formula Transform - Zvector_Axis_Swap 
formula Transform - Addition Constant_4D 
formula Transform - Box_Fold_4D 
formula Transform - Fabs_Add_Constant_4D 
formula Transform - Fabs_Add_Tglad fold_4D 
formula Transform - Iteration Weight_4D 
formula Transform - Scale_4D 
formula Transform - Spherical_Fold_4D 

list generated with populateUiInformation.php, see also:
https://github.com/buddhi1980/mandelbulber2/commit/b66c5b3c7ce776d666fba12eb0510975fab3ddfa

**Comment by mancoast** [comment]
@zebastian What are your thoughts regarding an example file foreach formula included in next end user manual?   Do we currently have preview images foreach example in deploy folder?

**Comment by buddhi1980** [comment]
@zebastian Is this list actual? I can create these missing examples.

@mancoast, why you ask about preview images? We don't have any preview images for any formula.

**Comment by mancoast** [comment]
I want to get full 4k preview images hosted on official mandelbulber for each example. Then we can reference the examples in the end user manual with smaller preview images and a link to the main website for full HD resources.

**Comment by buddhi1980** [comment]
So this is another topic. Please create separate issue for it, because rendering of examples is not the same as creating of examples.

**Comment by zebastian** [comment]
Hi,

i rerendered all examples on 2017-02-05 (should be up to date), see here:
http://cdn.mandelbulber.org/thumbnail/2.10/
These are now downloadable with the version bump to 2.10, try it out:
Program preferences > Image >  Thumbnail options > Load

**Comment by zebastian** [comment]
@mancoast you can find some high def renderings of examples here: https://mandelbulber.org/examples/
but you are right, we should add way more examples there...

**Comment by buddhi1980** [comment]
@mancoast mancoast probably talked about high resolution images (some kind of image gallery) which we could put on mandelbulber.org page

@zebastian, do we already have to tool to generate list of missing example settings?

**Comment by zebastian** [comment]
Yes, its:
Program preferences > Image > Thumbnail options > Generate
This will generate missing and touch existing, this way all timestamps of current thumbnails will be updated and i can sync these into the webfolder at cdn.mandelbulber.org.
Then i just run the genFileList.sh in the image folder and the list of thumbnails is updated.

**Comment by buddhi1980** [comment]
But how we know which fractal formulas don't have any example file (.fract file) ?

**Comment by buddhi1980** [comment]
@zebastian zebastian, In commit yuo wrote: https://github.com/buddhi1980/mandelbulber2/commit/b66c5b3c7ce776d666fba12eb0510975fab3ddfa

How to get this list using this php script?

**Comment by zebastian** [comment]
its populateUiInformation.php: since we are showing which example files are "featuring" an formula, we can also determine which formulas are not used at all in any of the examples.
See getFormulaExampleUsage() in populateUiInformation.php, this scans the example folder and fills a lookup table with: formula index -> list of featuring examples

**Comment by zebastian** [comment]
Then we look up the  formula index in the list:
```
if(array_key_exists($formula['id'], $formulaExampleUsage)){
		$informationText .= '<br><b>Examples using this formula</b><br>';
		$exampleFilenames = $formulaExampleUsage[$formula['id']];		
		if(count($exampleFilenames) > 5){ // do not show more than 5 examples
			array_splice($exampleFilenames, 5);
			$exampleFilenames[] = '...';
		}
		$informationText .= implode('<br>', $exampleFilenames);
	}else{
		if(isWarning()){
			echo warningString('formula ' . $formula['name'] . ' is not used in any examples yet.') . PHP_EOL;
		}
	}
```

**Comment by buddhi1980** [comment]
so how to display this list of missing examples?

**Comment by buddhi1980** [comment]
I tried to run this script, but it doesn't display this list

**Comment by zebastian** [comment]
oh, yes, you need to append the warning flag:
```php populateUiInformation.php warning```
I deactivated it by default, since there is so much output...

**Comment by buddhi1980** [comment]
Thanks! This is what I needed.

**Comment by mclarekin** [comment]
If you need any help (due to time) I can provide examples, but I prefer the
concept of you guys doing it, in this way the formulas get tested by
someone other than me.

On Tue, Feb 14, 2017 at 7:35 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
@mclarekin , you can help me with Collatz fractals. I cannot get any interesting image.

**Comment by mclarekin** [comment]
Will do.   I know what you mean, it is almost as bad as the scator for
finding a reasonable image.

**Comment by zebastian** [comment]
you really need to use a low raymarcxhing step multiplier (0.1 and less) to get a result with a reasonable low DE value. maybe the used distance estimation method could be changed?

**Comment by mclarekin** [comment]
I cannot remember the collatz very well, but it did  evolve into the menger
polynomial, which is cool.

 DeltaDE I used on somethings. Collatz is best used for tweaking other
formulas.

I do wonder whether we should remove collatz, and only have collatz mod

Attached is two zips of  a dump of my collatz folder


These setting below are for pure collattz. Sebastian is correct, a DE step
.01 used.

Analytic linear had better DE than  delta linear with this image,

# Mandelbulber settings file
# version 2.07
# only modified parameters
[main_parameters]
ambient_occlusion 0.5;
ambient_occlusion_enabled true;
ambient_occlusion_quality 9;
background_color_1 0000 5900 9400;
background_color_2 0000 5900 9400;
background_color_3 0000 5900 9400;
bailout 7;
camera 0.01624397866521765 -7.736950912469377 2.323097903993481;
camera_rotation 0 0 0;
camera_top 0 0 1;
coloring_palette_offset 1;
DE_factor 0.01;
detail_level 0.25;
dont_add_c_constant_1 true;
formula_1 88;
formula_2 1008;
fractal_rotation 0 45 0;
glow_enabled false;
image_height 1600;
image_width 3200;
julia_c 0.8162379929390271 0.1901198935378687 -0.8296891206019565;
keyframe_last_to_render 0;
main_light_beta -3.9;
smoothness 0.00134896;
specular 0.7;
SSAO_random_mode true;
surface_color_palette 005500 000000 fff59c f5bd22 000000 c65f65 a51e2c
000000 d4ffd4 aba53c;
target 0.01624397866521765 -0.7369509124693767 2.323097903993481;
use_default_bailout false;
view_distance_max 12;
volumetric_fog_colour_1_distance 2.722445389221988;
volumetric_fog_colour_2_distance 5.444890778443975;
volumetric_fog_distance_factor 5.444890778443975;
volumetric_fog_enabled true;
[fractal_1]
[fractal_2]
[fractal_3]
[fractal_4]
[fractal_5]
[fractal_6]
[fractal_7]
[fractal_8]
[fractal_9]


On Wed, Feb 15, 2017 at 11:10 AM, Sebastian Jennen <notifications@github.com

**Comment by mclarekin** [comment]
I remember now why Collatz default is analytical linear DE,  it is because
it works well with menger and Mbox which are analytical linear.

Have a look in the zips for examples,the best examples are hybrids

**Comment by buddhi1980** [comment]
Hybrid will be also good. If you have some will be nice.

**Comment by mclarekin** [comment]
Mandelbox with no addCpixel, tweaked by Collatz Fractal. It is not very
artistic *so feel free to modify it*. But it demonstrates the influence,
which is quite strong considering that it is not being used  until 26
iterations into the loop.

( Note, Collatz Mod, can be used differently as it has some parameters.  It
is a bit easier to use nearer to the beginning of the loop, normally for
just 1 iteration.)

Collatz is yet another fractal that I have yet to fully explore the
possibilities, but I know that it is a cool fractal for making unique
looking hybrids.


# Mandelbulber settings file
# version 2.10
# only modified parameters
[description]
Collatz Fractal works best modifying a Mandelbox or Menger Sponge type
fractal. Here it is used briefly halfway through the iteration loop.

Add_global_C_constant has been unchecked for the Mandelbox and only used
for the short duration of the Collatz fractal. Uncheck
add_global_C_constant, then uncheck the slot2-Collatz
and you will see the subtle differences this tweak makes.
[main_parameters]
ambient_occlusion 0.7;
ambient_occlusion_enabled true;
ambient_occlusion_quality 10;
camera 6.175307470039711 -9.762199417127336 7.681930459480753;
camera_distance_to_target 0.04457388073205917;
camera_rotation -94.72337095136625 -17.88205736443923 44.3215639214709;
camera_top 0.1613996235439574 -0.7144012434862057 0.680867846814073;
DE_factor 0.9;
detail_level 8;
dont_add_c_constant_1 true;
dont_add_c_constant_2 true;
flight_last_to_render 0;
formula_1 8;
formula_2 88;
formula_start_iteration_2 25;
formula_stop_iteration_2 26;
hybrid_fractal_enable true;
julia_c -1 0 0;
keyframe_last_to_render 0;
main_light_alpha 33.69;
main_light_beta 13.32;
mat1_coloring_palette_offset 7.92;
mat1_coloring_random_seed 869227;
mat1_is_defined true;
mat1_specular 0.4;
mat1_surface_color_palette 79547a c96617 8d9958 466900 96682b d4b169 ac4a3b
3f987d 7e8af9 333a7b;
SSAO_random_mode true;
target 6.217583948506837 -9.765692538079055 7.668243665920859;
[fractal_1]
mandelbox_folding_min_radius 0.1;
mandelbox_main_rotation_enabled true;
mandelbox_rotation_main -10.44 4.33 14.04;
mandelbox_scale -1.3;
[fractal_2]
transf_scale_1 0;


On Thu, Feb 16, 2017 at 6:53 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
Thank you @mclarekin . Final result is very good

![image](https://cloud.githubusercontent.com/assets/11696990/23033857/f2351102-f479-11e6-85dc-1c0d7f31d80c.png)

**Comment by mancoast** [comment]
@buddhi1980 Do we want to include an example foreach formula/transform in 2.10 or 2.11?

**Comment by mancoast** [comment]
Line 6: formula Collatz - Mod is not used in any examples yet.
	Line 21: formula Abox 4D is not used in any examples yet.
	Line 25: formula Menger 4D Mod1 is not used in any examples yet.
	Line 27: formula Mix Pinski 4D is not used in any examples yet.
	Line 29: formula Sierpinski 4D is not used in any examples yet.
	Line 31: formula T>Add Constant is not used in any examples yet.
	Line 32: formula T>Add Constant VaryV1 is not used in any examples yet.
	Line 33: formula T>Add Cpixel is not used in any examples yet.
	Line 34: formula T>Add Cpixel - Axis Swap is not used in any examples yet.
	Line 36: formula T>Add Cpixel - CxCy Axis Swap is not used in any examples yet.
	Line 37: formula T>Add Cpixel - Symmetrical is not used in any examples yet.
	Line 38: formula T>Add Cpixel - VaryV1 is not used in any examples yet.
	Line 39: formula T>Add exp2(z) is not used in any examples yet.
	Line 40: formula T>Benesi T1 is not used in any examples yet.
	Line 41: formula T>Benesi T1 Mod is not used in any examples yet.
	Line 42: formula T>Benesi T2 is not used in any examples yet.
	Line 43: formula T>Benesi T3 is not used in any examples yet.
	Line 44: formula T>Benesi T4 is not used in any examples yet.
	Line 45: formula T>Benesi T5b is not used in any examples yet.
	Line 46: formula T>Benesi Mag Forward is not used in any examples yet.
	Line 47: formula T>Benesi Mag Backward is not used in any examples yet.
	Line 48: formula T>Benesi Cube>Sphere is not used in any examples yet.
	Line 49: formula T>Benesi Sphere>Cube is not used in any examples yet.
	Line 50: formula T>Box Fold VaryV1 is not used in any examples yet.
	Line 51: formula T>Box Fold XYZ is not used in any examples yet.
	Line 52: formula T>Box Offset is not used in any examples yet.
	Line 53: formula T>Fabs Add Constant is not used in any examples yet.
	Line 54: formula T>Fabs Add Tglad Fold is not used in any examples yet.
	Line 55: formula T>Fabs Add Conditional is not used in any examples yet.
	Line 56: formula T>Fabs Add Multi is not used in any examples yet.
	Line 57: formula T>Fabs Add Neg is not used in any examples yet.
	Line 58: formula T>Folding Tetra 3D is not used in any examples yet.
	Line 59: formula T>Iteration Weight is not used in any examples yet.
	Line 60: formula T>Inverse Cylindrical is not used in any examples yet.
	Line 62: formula T>Linear Combine CXYZ is not used in any examples yet.
	Line 64: formula T>Menger Fold is not used in any examples yet.
	Line 65: formula T>Multiple angle is not used in any examples yet.
	Line 66: formula T>Octo Fold is not used in any examples yet.
	Line 67: formula T>Platonic Solid is not used in any examples yet.
	Line 68: formula T>Power2 Polynomial is not used in any examples yet.
	Line 69: formula T>Quaternion Fold is not used in any examples yet.
	Line 71: formula T>Reciprocal3 is not used in any examples yet.
	Line 72: formula T>Rotation is not used in any examples yet.
	Line 73: formula T>Rotation VaryV1 is not used in any examples yet.
	Line 74: formula T>Rotation Folding Plane is not used in any examples yet.
	Line 75: formula T>Rotation Folding is not used in any examples yet.
	Line 76: formula T>R^Power is not used in any examples yet.
	Line 77: formula T>Rpow3 is not used in any examples yet.
	Line 78: formula T>Scale is not used in any examples yet.
	Line 79: formula T>Scale VaryV1 is not used in any examples yet.
	Line 80: formula T>Scale VaryVCL is not used in any examples yet.
	Line 81: formula T>Scale 3D is not used in any examples yet.
	Line 83: formula T>Spherical Invert C is not used in any examples yet.
	Line 84: formula T>Spherical Fold is not used in any examples yet.
	Line 85: formula T>Spherical Fold ABox is not used in any examples yet.
	Line 86: formula T>Spherical Fold VaryV1 is not used in any examples yet.
	Line 87: formula T>Spherical Fold VaryVCL is not used in any examples yet.
	Line 88: formula T>Spherical Pwr Fold is not used in any examples yet.
	Line 89: formula T>Spherical Offset is not used in any examples yet.
	Line 90: formula T>Spherical OffsetVCL is not used in any examples yet.
	Line 91: formula T>Surf Box_Fold is not used in any examples yet.
	Line 92: formula T>Surf Fold Multi is not used in any examples yet.
	Line 93: formula T>Zvector Axis Swap is not used in any examples yet.
	Line 95: formula T>Add Constant 4D is not used in any examples yet.
	Line 96: formula T>Box Fold 4D is not used in any examples yet.
	Line 97: formula T>Fabs Add Conditional 4D is not used in any examples yet.
	Line 98: formula T>Fabs Add Constant 4D is not used in any examples yet.
	Line 99: formula T>Fabs Add Tglad Fold 4D is not used in any examples yet.
	Line 100: formula T>Iteration Weight 4D is not used in any examples yet.
	Line 101: formula T>Reciprocal 4D is not used in any examples yet.
	Line 102: formula T>Rotation 4D is not used in any examples yet.
	Line 103: formula T>Scale 4D is not used in any examples yet.
	Line 104: formula T>Spherical Fold 4D is not used in any examples yet.

**Comment by mancoast** [comment]
@mclarekin wanna split up the rest of these transforms?
I will start from the Line 104: formula T>Spherical Fold 4D and work my way upwards.

**Comment by mancoast** [comment]
![image](https://cloud.githubusercontent.com/assets/7040493/23828458/335a522c-06a0-11e7-8590-45f8a745debd.png)

**Comment by mclarekin** [comment]
I would wait before doing the transforms,  as I will be doing some changes:

1) Update sphere Fold 4D to make it faster, which means that two parameters
are going to change.

2) The following list will be evaluated for applying  a DE factor which may
improve hybridizing with transforms

                case kaleidoscopicIFS:
                case mengerSponge:
                case mengerCrossKIFS:
                case mengerCrossMod1:
                case mengerPrismShape:
                case mengerPrismShape2:
                case collatz:
                case collatzMod:
                case mengerMod1:
                case mengerMiddleMod:
                case transfMengerFold: // hmmm, this issue again
                case mengerPwr2Poly:
                // case mixPinski4D:
                case sierpinski4d:
                case sierpinski3d:
                case menger4d:
                case menger4dMod1:
                case mengerSmooth:
                case mengerSmoothMod1:
                case mengerOcto:

**Comment by mancoast** [comment]
a good exploration of all these transforms is long overdue on my behalf.  so many options!

**Comment by mclarekin** [comment]
Rob, the options are incredibly infinite. You could spend years checking
out the possibilities. I have only tested very few of the  combinations.

spher fold 4D is updated.  Min r  is now min r^2  same with max  r,

also added offset

# Mandelbulber settings file
# version 2.10
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_brightness 0.17;
background_color_1 0000 5500 0000;
background_color_3 0000 5500 0000;
camera -0.004934914968715513 2.219539305389751 -0.1626916226454035;
camera_distance_to_target 2.255316541331842;
camera_rotation -179.7158863518206 3.639456100616836 -0.03194079123700501;
camera_top 0.0002426979572263547 0.06347975862999 0.9979830967215726;
DE_factor 0.5;
detail_level 2;
flight_last_to_render 0;
formula_1 109;
formula_2 1042;
fractal_rotation 0 135 0;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
main_light_alpha 26.57;
main_light_beta 18.43;
mat1_coloring_palette_offset 3.57;
mat1_is_defined true;
mat1_surface_color_palette 0000ff 698403 aa0000 aa0000 0b5e87 94aa98 8daa9b
3b9fee baa52b aba53c;
raytraced_reflections true;
target 0.006225965135046943 -0.0312011584685703 -0.01952912507302744;
textured_background_map_type 2;
view_distance_max 23.63321698000266;
[fractal_1]
analyticDE_scale_1 1.1;
transf_addition_constant_0000 -1 -1 -1 -1;
transf_addition_constant_111d5 1 1 1 1;
transf_start_iterations_M 250;
[fractal_2]
transf_maxR2_1 1.4;
transf_minR2_p25 0.55;
transf_offset_0000 -1.100013 0 0 -0.199999;

**Comment by mancoast** [comment]
nice example!
So I think we have working examples foreach formula.
I will close this issue and as the remaining void of examples is composed of transforms.
