### ISSUE TITLE
nine fractals difs logic

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#720]
if any slot = difs,  then analytic DE function automatic = difs

**Comment by buddhi1980** [comment]
OK. Will be.

**Comment by buddhi1980** [comment]
Done. Do you need to update OpenCL formulas? Or it is too early?

**Comment by mclarekin** [comment]
To early for difs work, but if possible other new formulas and changes
updated to openCL would be good for testing.  Or wait a week or two and i
should have difs Cylinder finished plus re worked the other existing difs
formulas to make them consistent.
