### ISSUE TITLE
Deleted second material is not really deleted and causes problems with Undo

### ISSUE THREAD

**Issue by Menno5** [buddhi1980/mandelbulber2#721]
Mandelbulber2 => 2.19
Operating System / Platform => Windows 10 Pro 64 Bit
Compiler => I have no idea what that means

##### Detailed description

When adding a second material, working with it and then deleting it, it somehow stays in the memory/code, giving a "Material is not defined". Resulting in a huge slow down or crash when doing a Undo step. No more work can be done or with great delays.
If possible to Save, close Mandelbulber and load the save: the Mat2 is gone, no "Material is not defined" tile. So the save is not affected.

##### Steps to reproduce

Load a scene, add a second new material, Mat2.
Use/alter the material Mat2 or not, doesn't matter.
Do some alterations in the Objects / Fractals tab.
Attach Mat1 to the object.
Remove the the new, second material.
Do 6 (just to be sure) alterations in the Objects / Fractals tab.
Use the Undo function once.
Mandelbulber is slowed down a LOT or crashes and a "Material is not defined" tile appears.
This is the culprit since the Mat2 was removed 6 steps back and not 1 step back.
No more work can be done on the scene

**Comment by buddhi1980** [comment]
This bug is reproducible. I got the problem which you described after Undo.
![image](https://user-images.githubusercontent.com/11696990/67413856-41541200-f5c2-11e9-98a5-a9de4a8d3fe9.png)
![image](https://user-images.githubusercontent.com/11696990/67413900-5c268680-f5c2-11e9-95cb-104af12788c9.png)

**Comment by buddhi1980** [comment]
Problem probably fixed. @Menno5 can you test it? For testing use fresh appveyour build

**Comment by Menno5** [comment]
> Problem probably fixed. @Menno5 can you test it? For testing use fresh appveyour build

Sure. But what do you mean? The latest beta? If so, where can I get that?

**Comment by buddhi1980** [comment]
You can download one of the most recent builds for Windows from here: https://ci.appveyor.com/project/buddhi1980/mandelbulber2/builds/28384591/job/rcoylp10i6d5lgss/artifacts

**Comment by Menno5** [comment]
Tested with latest beta and problem is gone.

**Comment by buddhi1980** [comment]
Thanks for test.
