### ISSUE TITLE
Stereo Pole Merging Question

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#723]
Hi,
I think you have implemented a Stereo Pole Merging Correction for LatLong Rendering if I rember corectly.

I'm trying to match this Pole Merging in Houdini, so I try to find how it is done in Mandelbulber.
Could you direct me there?
Is it maybe here?
cStereo::ViewVectorCorrection
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/stereo.cpp

Thanks!

**Comment by MeyerAdrian** [comment]
So guess I found it, its probably these two:

https://github.com/buddhi1980/mandelbulber2/blob/976f3e50b3612f7f9f0237a747265bfd7556486d/mandelbulber2/src/render_worker.cpp#L288

https://github.com/buddhi1980/mandelbulber2/blob/976f3e50b3612f7f9f0237a747265bfd7556486d/mandelbulber2/src/stereo.cpp#L210

Unfortunately I can't manage to see through the C++ :-P
Could you help me out a bit and describe what the actual math of the pole merging is?
Thanks!

**Comment by MeyerAdrian** [comment]
Okay, I think I might have got it :-P
Its:
1.0 - pow(imagePoint.y * 2.0, 10.0)

where imagePoint.y should range from 0.5 at the top to 0 in the middle to 0.5 at the bottom.
correct?

**Comment by buddhi1980** [comment]
Yes, you have found correct place in the code.

**Comment by buddhi1980** [comment]
It is the shape of this function 
![image](https://user-images.githubusercontent.com/11696990/66685204-1988b400-ec7c-11e9-99c4-785678585321.png)

**Comment by MeyerAdrian** [comment]
Cool, thanks!
