### ISSUE TITLE
some unexplained color differences

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#725]
standard orbitTrap mode color speed = 1.0

images:

c++,     medium
full,      full no fast maths

```
# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 aa00 ff00 ff00;
bailout 400;
camera 23.23925413847365 -8.762167032215626 15.15548659357945;
camera_distance_to_target 9.483982605706315;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
DE_factor 0.5;
DE_thresh 3.90625e-05;
delta_DE_function 2;
detail_level 2;
dont_add_c_constant_1 true;
dont_add_c_constant_2 true;
flight_last_to_render 0;
fog_color_1 ff00 ff00 ff00;
fog_color_2 ff00 ff00 ff00;
fog_color_3 ff00 ff00 ff00;
formula_1 133;
formula_2 2;
formula_3 1004;
formula_4 1001;
formula_5 1029;
formula_6 1004;
formula_iterations_1 9;
formula_start_iteration_2 9;
formula_start_iteration_3 10;
formula_start_iteration_4 8;
formula_stop_iteration_1 8;
formula_stop_iteration_2 10;
formula_stop_iteration_3 12;
formula_stop_iteration_4 42;
formula_stop_iteration_6 8;
fractal_enable_4 false;
fractal_enable_5 false;
fractal_enable_6 false;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
mat1_fractal_coloring_ic_xyz_enabled_false true;
mat1_fractal_coloring_init_cond_enabled_false true;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_xyzC_111 0 0 1;
mat1_is_defined true;
mat1_specular_metallic 0.5;
mat1_specular_plastic_enable false;
mat1_surface_color_gradient 0 fd6029 1000 698403 2000 fff59b 3000 aa0000 4000 ffff00 5000 c68876 6000 a51c64 7000 aa0000 8000 d4ffd4 9000 aba53c;
N 11;
raytraced_reflections true;
target 23.23925413847365 0.7218155734906926 15.15548659357945;
textured_background_map_type 2;
volumetric_light_DE_Factor 0.25;
[fractal_1]
info true;
mandelbox_color 0 0 0.07000000000000001;
mandelbox_scale 1;
transf_addition_constant_111 2.5 1 1;
transf_function_enabledCy_false true;
transf_function_enabledF_false true;
transf_minR2_p25 0;
transf_offsetA_000 1.4 0.4 0.2;
transf_scale3D_111 1.8 1.4 1.3;
transf_scale_vary_0 -0.1;
transf_stop_iterations_A 7;
transf_stop_iterations_B 7;
transf_stop_iterations_S 7;
transf_stop_iterations_X 1;
[fractal_2]
analyticDE_enabled_false true;
info true;
power 2.3;
transf_scale3D_111 1 1 5.868672;
[fractal_3]
analyticDE_enabled_false true;
power 2;
transf_function_enabled false;
transf_function_enabledM false;
transf_pwr_8 1.6;
transf_scale3D_111 1 1 5.868672;
[fractal_4]
analyticDE_enabled_false true;
power 2;
transf_pwr_8 2;
transf_scale 1.299999999999999;
transf_scale3D_111 1 1 5.868672;
[fractal_5]
analyticDE_enabled_false true;
analyticDE_scale_1 1.01;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 -0.1 0;
[fractal_6]
analyticDE_scale_1 2.3;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 0 0;
transf_function_enabledBy false;
transf_function_enabledBy_false true;
transf_scale3D_111 0.1 0.1 -4.5;
```
![bxblb std](https://user-images.githubusercontent.com/12769564/66697451-41d2ea00-ed32-11e9-85e9-379d88d93edf.jpg)

**Comment by mclarekin** [comment]
this a different issue, mainly why medium  has lateral coloring variation

vertical original point coloring , color speed = 32

images:

c++,     medium
full,      full no fast maths

# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 aa00 ff00 ff00;
bailout 400;
camera 23.23925413847365 -8.762167032215626 15.15548659357945;
camera_distance_to_target 9.483982605706315;
camera_rotation 0 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
constant_DE_threshold true;
DE_factor 0.5;
DE_thresh 3.90625e-05;
delta_DE_function 2;
detail_level 2;
dont_add_c_constant_1 true;
dont_add_c_constant_2 true;
flight_last_to_render 0;
fog_color_1 ff00 ff00 ff00;
fog_color_2 ff00 ff00 ff00;
fog_color_3 ff00 ff00 ff00;
formula_1 133;
formula_2 2;
formula_3 1004;
formula_4 1001;
formula_5 1029;
formula_6 1004;
formula_iterations_1 9;
formula_start_iteration_2 9;
formula_start_iteration_3 10;
formula_start_iteration_4 8;
formula_stop_iteration_1 8;
formula_stop_iteration_2 10;
formula_stop_iteration_3 12;
formula_stop_iteration_4 42;
formula_stop_iteration_6 8;
fractal_enable_4 false;
fractal_enable_5 false;
fractal_enable_6 false;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
mat1_coloring_speed 32;
mat1_fractal_coloring_extra_color_enabled_false true;
mat1_fractal_coloring_ic_xyz_enabled_false true;
mat1_fractal_coloring_init_cond_enabled_false true;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_xyzC_111 0 0 1;
mat1_is_defined true;
mat1_specular_metallic 0.5;
mat1_specular_plastic_enable false;
mat1_surface_color_gradient 0 fd6029 1000 698403 2000 fff59b 3000 aa0000 4000 ffff00 5000 c68876 6000 a51c64 7000 aa0000 8000 d4ffd4 9000 aba53c;
N 11;
raytraced_reflections true;
target 23.23925413847365 0.7218155734906926 15.15548659357945;
textured_background_map_type 2;
volumetric_light_DE_Factor 0.25;
[fractal_1]
info true;
mandelbox_color 0 0 0.07000000000000001;
mandelbox_scale 1;
transf_addition_constant_111 2.5 1 1;
transf_function_enabledCy_false true;
transf_function_enabledF_false true;
transf_minR2_p25 0;
transf_offsetA_000 1.4 0.4 0.2;
transf_scale3D_111 1.8 1.4 1.3;
transf_scale_vary_0 -0.1;
transf_stop_iterations_A 7;
transf_stop_iterations_B 7;
transf_stop_iterations_S 7;
transf_stop_iterations_X 1;
[fractal_2]
analyticDE_enabled_false true;
info true;
power 2.3;
transf_scale3D_111 1 1 5.868672;
[fractal_3]
analyticDE_enabled_false true;
power 2;
transf_function_enabled false;
transf_function_enabledM false;
transf_pwr_8 1.6;
transf_scale3D_111 1 1 5.868672;
[fractal_4]
analyticDE_enabled_false true;
power 2;
transf_pwr_8 2;
transf_scale 1.299999999999999;
transf_scale3D_111 1 1 5.868672;
[fractal_5]
analyticDE_enabled_false true;
analyticDE_scale_1 1.01;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 -0.1 0;
[fractal_6]
analyticDE_scale_1 2.3;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 0 0;
transf_function_enabledBy false;
transf_function_enabledBy_false true;
transf_scale3D_111 0.1 0.1 -4.5;

![bxblb original point](https://user-images.githubusercontent.com/12769564/66697650-2d8fec80-ed34-11e9-8fbb-2d42f32c59ab.jpg)

**Comment by buddhi1980** [comment]
It looks like some variable has no initial value

**Comment by mclarekin** [comment]
It is weird. Here I have reproduced with standard mandelboxbox and mandelbulb. Again it is OK in Medium but not in Full.  With autorefresh on, the left image is when changing itertations from 10 up to 11. The right image is when changing itertations from 12 down to 11.  See the difference in the middle of image.

# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 aa00 ff00 ff00;
bailout 400;
camera 23.23925413847365 -8.762167032215626 15.15548659357945;
camera_distance_to_target 9.483982605706318;
camera_rotation 29.99999999999996 0 0;
camera_top 0 0 1;
check_for_bailout_2 false;
DE_factor 0.5;
DE_thresh 3.90625e-05;
delta_DE_function 2;
detail_level 2;
dont_add_c_constant_1 true;
dont_add_c_constant_2 true;
flight_last_to_render 0;
fog_color_1 ff00 ff00 ff00;
fog_color_2 ff00 ff00 ff00;
fog_color_3 ff00 ff00 ff00;
formula_1 8;
formula_2 118;
formula_3 1004;
formula_4 1001;
formula_5 1029;
formula_6 1004;
formula_iterations_1 9;
formula_start_iteration_2 9;
formula_start_iteration_3 10;
formula_start_iteration_4 8;
formula_stop_iteration_1 8;
formula_stop_iteration_2 10;
formula_stop_iteration_3 12;
formula_stop_iteration_4 42;
formula_stop_iteration_6 8;
fractal_enable_3 false;
fractal_enable_4 false;
fractal_enable_5 false;
fractal_enable_6 false;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
mat1_fractal_coloring_ic_xyz_enabled_false true;
mat1_fractal_coloring_init_cond_enabled_false true;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_xyzC_111 0 0 1;
mat1_is_defined true;
mat1_specular_metallic 0.5;
mat1_specular_plastic_enable false;
mat1_surface_color_gradient 0 fd6029 1000 698403 2000 fff59b 3000 aa0000 4000 ffff00 5000 c68876 6000 a51c64 7000 aa0000 8000 d4ffd4 9000 aba53c;
N 11;
raytraced_reflections true;
target 18.49726283562049 -0.5487971666242188 15.15548659357945;
textured_background_map_type 2;
volumetric_light_DE_Factor 0.25;
[fractal_1]
info true;
mandelbox_color 0 0 0.07000000000000001;
mandelbox_scale 1;
transf_addition_constant_111 2.5 1 1;
transf_function_enabledCy_false true;
transf_function_enabledF_false true;
transf_minR2_p25 0;
transf_offsetA_000 1.4 0.4 0.2;
transf_scale3D_111 1.8 1.4 1.3;
transf_scale_vary_0 -0.1;
transf_stop_iterations_A 7;
transf_stop_iterations_B 7;
transf_stop_iterations_S 7;
transf_stop_iterations_X 1;
[fractal_2]
analyticDE_enabled_false true;
info true;
power 2.3;
transf_scale3D_111 1 1 5.868672;
[fractal_3]
analyticDE_enabled_false true;
power 2;
transf_function_enabled false;
transf_function_enabledM false;
transf_pwr_8 1.6;
transf_scale3D_111 1 1 5.868672;
[fractal_4]
analyticDE_enabled_false true;
power 2;
transf_pwr_8 2;
transf_scale 1.299999999999999;
transf_scale3D_111 1 1 5.868672;
[fractal_5]
analyticDE_enabled_false true;
analyticDE_scale_1 1.01;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 -0.1 0;
[fractal_6]
analyticDE_scale_1 2.3;
transf_addition_constant 0.1 0.1 0;
transf_addition_constantA_000 -0.1 0 0;
transf_function_enabledBy false;
transf_function_enabledBy_false true;
transf_scale3D_111 0.1 0.1 -4.5;
![test 10 11 12](https://user-images.githubusercontent.com/12769564/66725695-1b779080-ee91-11e9-8f20-b4debe7ce12b.jpg)

**Comment by buddhi1980** [comment]
The problem is not related to any formula. It happens in hybrid mode when stop at iteration is low. There is some variable in coloring algorithm which is uninitialized. I'm looking for it now.

**Comment by buddhi1980** [comment]
Simplified settings which reproduce this problem:
```
# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 aa00 ff00 ff00;
bailout 400;
camera 9,764116324287146 -9,567582789877948 9,5677826623738;
camera_distance_to_target 15,22290400075003;
camera_rotation 54,92398254692856 -35,6464842633936 12,12750838944821;
camera_top -0,3455695880050854 0,4993631255734093 0,7944923716836751;
DE_thresh 3,90625e-05;
delta_DE_function 2;
dont_add_c_constant_1 true;
flight_last_to_render 0;
fog_color_1 ff00 ff00 ff00;
fog_color_2 ff00 ff00 ff00;
fog_color_3 ff00 ff00 ff00;
formula_1 8;
formula_stop_iteration_1 13;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
main_light_alpha 0;
main_light_beta 0;
mat1_coloring_speed 32;
mat1_fractal_coloring_ic_xyz_enabled_false true;
mat1_fractal_coloring_init_cond_enabled_false true;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_xyzC_111 0 0 1;
mat1_is_defined true;
mat1_specular_metallic 0,5;
mat1_specular_plastic_enable false;
mat1_surface_color_gradient 0 b0db87 2755 0444b3 2787 0ddc8d 3344 c4c86c 5478 9dfe57 9190 36879c;
raytraced_reflections true;
target -0,3598314043039026 -2,458682070037196 0,6961413733982824;
textured_background_map_type 2;
volumetric_light_DE_Factor 0,25;
[fractal_1]
mandelbox_color 0 0 0;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0;
transf_offsetA_000 1,4 0,4 0,2;
transf_scale3D_111 1,8 1,4 1,3;
transf_stop_iterations_A 7;
transf_stop_iterations_B 7;
transf_stop_iterations_S 7;
transf_stop_iterations_X 1;
```

**Comment by buddhi1980** [comment]
@mclarekin check if now is all right.

**Comment by mclarekin** [comment]
thanks :)
