### ISSUE TITLE
windows build warning require rework

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#726]
The windows build generates many warnings. This has changed since the last time I checked in. I will resolve these.

TODO:
windows build warning require rework
Status	Code	File	Line	Column	Project	Read/Write
Confirmed reference	#define M_E        2.71828182845904523536   // e	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math_defines.h	17	13	mandelbulber2	Unknown
Cannot confirm reference	#ifndef M_E	D:\GIT\mandelbulber2\packages\gsl-msvc-x86.2.4.0.8788\build\native\gsl\gsl_math.h	41	9	mandelbulber2	Unknown
Confirmed reference	#define M_E        2.71828182845904523536028747135      /* e */	D:\GIT\mandelbulber2\packages\gsl-msvc-x86.2.4.0.8788\build\native\gsl\gsl_math.h	42	9	mandelbulber2	Unknown
Cannot confirm reference	#ifndef M_E	D:\GIT\mandelbulber2\packages\bulbqt-msvc-x86.5.9.4.10785\build\native\include\QtCore\qmath.h	152	9	mandelbulber2	Unknown
Confirmed reference	#define M_E (2.7182818284590452354)	D:\GIT\mandelbulber2\packages\bulbqt-msvc-x86.5.9.4.10785\build\native\include\QtCore\qmath.h	153	9	mandelbulber2	Unknown
Cannot confirm reference	#ifndef M_E	D:\GIT\mandelbulber2\packages\bulbqt-msvc-x86.5.12.4.10787\build\native\include\QtCore\qmath.h	154	9	mandelbulber2	Unknown
Confirmed reference	#define M_E (2.7182818284590452354)	D:\GIT\mandelbulber2\packages\bulbqt-msvc-x86.5.12.4.10787\build\native\include\QtCore\qmath.h	155	9	mandelbulber2	Unknown
	#define M_E 2.71828182845904523536	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math_defines.h	17	5

**Comment by zebastian** [comment]
Hello,
these warnings are caused by the library gsl (https://www.gnu.org/software/gsl/), which is used in mandelbulber, not by mandelbulber sources itself. 
IMHO: we can ignore warnings of external libraries.  
Please reopen, if fixable / circumventable by mandelbulber sources of if warnings are caused by mandelbulber itself.
