### ISSUE TITLE
Wished Enhancement- EXR Compression ZIP16 to ZIP1

### ISSUE THREAD

**Issue by MeyerAdrian** [buddhi1980/mandelbulber2#730]
Hey,
a small wish for enhancement.
It would be great if the EXR Compression could be changed to ZIP1 (1 Scanline) opposed to ZIP16 (16 Scanlines).
Because Compositing Apps like Nuke and After Effects read ZIP1 much faster.
And pretty much everybody who makes use of the EXR Output will most likely use Nuke or AE.

Thanks

**Comment by buddhi1980** [comment]
What is a difference between file size in ZIP1 and ZIP16 formats? How faster ZIP1 is?

**Comment by MeyerAdrian** [comment]
ZIP1 compresses the data in Blocks of 1 Scanline (Horizontal Line of Pixels across the image).
ZIP16 compresses the data in Blocks of 16 Scanlines (Horizontal Lines of Pixels across the image).

Compositing apps mostly have a scanline architecture, meaning the read and process images from top to bottom in pixel batches of 1 scanline.
Their FileIO System is optimized to read each scanline at a time and not in larger blocks (like 16).

Thus Read Performance with ZIP1 is much better. Often more than 2x. Which can be a lot when reading 500MB files that load 20s per frame.

**Comment by zebastian** [comment]
I just made a small test with the default settings:
 the zip 16 scanlines is: 11381590 bytes
 the zip 1 scanline is: 11916495 bytes
which is an increase of ~4-5%

IMHO: a fair trade off, if it really gives faster read rates (If you cared for filesize you would not be using exr images in the first place :-) )
@buddhi1980 what do you think?

```
	//compress each scan line on its own. This gives a good compression / read performance tradeoff
	header.compression() = Imf::ZIPS_COMPRESSION;
```
vs
```
	header.compression() = Imf::ZIP_COMPRESSION;
```

**Comment by buddhi1980** [comment]
Let's change it to zip1

**Comment by MeyerAdrian** [comment]
Nice.
Well yeah, true, don’t really care about file sizes. File IO Performance is the crucial thing for compositing.

**Comment by zebastian** [comment]
Done here: https://github.com/buddhi1980/mandelbulber2/commit/17cf435319f7bc91aa9bb243df2d1ac02d962fed
