### ISSUE TITLE
UI Thread causing whole PC to glitch.

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#735]
HI, Latest nightly causing my whole pc to stutter during a difs hybrid render. Went away when I minimised the program. Even made audio stutter.

**Comment by mclarekin** [comment]
2 or 3 days ago, i had the screen  "stuttering" when playing solitaire
while Mandelbulber was rendering in win10. It has only happened once.

**Comment by TBeholder** [comment]
Huh. Is it just CPU load? Did you try to reduce priority? Does reducing max number of CPU cores in preferences help?
Though sometimes _even on low priority and limited to one core_ CPU load may periodically spike with mini-freezes without a good reason, if a process just switches back and forth between cores. I have seen this on various applications. This goes away if _CPU affinity_ is set to one core (taskset on Linux). Maybe this?
