### ISSUE TITLE
Netrender Issue.

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#739]
If you start Rendering a project on one machine, then move to rendering on 2 machines, only every other frame is rendered.

**Comment by buddhi1980** [comment]
Can you explain this more precisely?

**Comment by degriz** [comment]
Well, if I decide to render with one machine. Then decide to stop, hook up the render box and use that as well only even numbered frames are rendered.

**Comment by buddhi1980** [comment]
I'm not completely understand the problem. Have you checked in the folder with images if there are all frames? It is normal that if you use two machines, the server will approximately render every second frame, but rest of them is rendered by client. 
I just checked it and it behaves properly.
