### ISSUE TITLE
Reset button enhancements

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#74]
Can reset button be enhanced to also reset  weight, iterations, etc

**Comment by zebastian** [comment]
This could be in the context menu of almost all parameters.
In the range of the parameter the Program tries to find the "optimal" setting, analog to reset view. The logic to do so could be a big heuristic rating the samples.

**Comment by buddhi1980** [comment]
I think @mclarekin mean something different here. When Reset button on fractal tab is pressed then also weight, start and end iteration should be set to default.

**Comment by mclarekin** [comment]
Yep

In fuutre maybe ---

  a RESET on global parameters tab

Also  effects - background,  maybe be able to set background to one colour
without having to change  three separate  colour parameters

On Sun, Feb 28, 2016 at 6:12 AM, Krzysztof Marczak <notifications@github.com

**Comment by buddhi1980** [comment]
Done. Now it additionality resets following parameters:
```
	QStringList listToReset = {"formula_iterations", "formula_weight", "formula_start_iteration",
		"formula_stop_iteration", "julia_mode", "julia_c", "fractal_constant_factor", "initial_waxis",
		"formula_position", "formula_rotation", "formula_repeat", "formula_scale",
		"dont_add_c_constant", "check_for_bailout"
```

@mclarekin, Is it what you expected?

**Comment by mclarekin** [comment]
That covers the global parameters.

There are other situations where implementing a reset could be an
enhancement (maybe lights tab). Basically if a tab or dock has a lot of
parameters to manually set back to default, then it is worth considering a
reset button.

I think we can consider this issue closed.
