### ISSUE TITLE
openCL full rendering problem

### ISSUE THREAD

**Issue by aombk** [buddhi1980/mandelbulber2#740]
i downloaded mandelbulber from here:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/builds/28798908/job/xd0gw66fjgvd7n62/artifacts

and the fractals still dont render properly while using openCL full
there seems to be a strange combination with hybrid/boolean mode, having fractals #2... #3... etc turned on and off and having fractals #2... #3... etc set to none or other fractals
i cant find a pattern though
*this does not occur when rendering with CPU, openCL medium and openCL fast

i could provide settings files and screenshots if the problem i have is not clear

- Operating System / Platform => Windows 10 64 Bit

**Comment by mclarekin** [comment]
please send example settings.  Save to Clipboard and paste here

**Comment by aombk** [comment]
# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 10;
antialiasing_enabled true;
antialiasing_size 3;
background_3_colors_enable false;
background_color_1 c300 c300 c300;
basic_fog_color c300 c300 c300;
basic_fog_enabled true;
basic_fog_visibility 4;
camera 1,136320010912101 -2,272640021824204 0,8707342227297893;
camera_distance_to_target 2,685943767585101;
camera_rotation 26,56505117707794 -18,91601506527932 0;
camera_top -0,1449785312601526 0,2899570625203059 0,9459947818927145;
DOF_focus 1,690479516983032;
file_background G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\lightmap2.jpg;
file_envmap G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\envmap6.jpg;
file_lightmap G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\lightmap2.jpg;
flight_last_to_render 0;
glow_enabled false;
hdr_blur_intensity 2;
image_height 540;
image_width 540;
keyframe_last_to_render 0;
main_light_colour c300 c300 c300;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 0;
mat1_specular_width 1;
mat1_surface_color c300 c300 c300;
mat1_use_colors_from_palette false;
N 333;
volumetric_fog_colour_1_distance 0,6636516656599969;
volumetric_fog_colour_2_distance 1,327303331319994;
volumetric_fog_distance_factor 1,327303331319994;

**Comment by aombk** [comment]
so the above does not render in openCL full
unless i enable hybrid fractals or i disable fog for example.
do you want more examples that have slightly different behavior?

**Comment by aombk** [comment]
# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 10;
anim_flight_dir G:\owncloud\compenc\fractals\animation\;
anim_keyframe_dir G:\owncloud\compenc\fractals\animation\;
animsound_enable_main_camera_z true;
antialiasing_enabled true;
antialiasing_size 3;
aux_light_colour_1 0000 aa00 ff00;
aux_light_intensity_1 1;
aux_light_position_1 0 0 0;
aux_light_visibility_size 0,7;
background_3_colors_enable false;
background_color_1 0000 ff00 0000;
basic_fog_color c300 c300 c300;
basic_fog_visibility 2;
camera 4,497284886060361 -2,47328131613242 -1,454181735537057;
camera_distance_to_target 4;
camera_rotation 55,78556794004133 21,91124964857855 99,74619289340087;
camera_top 0,5019371619782917 0,8505249389740371 -0,1570554475603715;
DE_factor 0,1;
DE_thresh 0,1;
DOF_focus 6,727782249450684;
file_background G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\lightmap2.jpg;
file_envmap G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\envmap6.jpg;
file_lightmap G:\owncloud\compenc\fractals\mandelbulber2-win64-2.13-2-standalone\textures\lightmap2.jpg;
flight_last_to_render 0;
flight_speed 1;
formula_1 101;
formula_2 98;
formula_3 80;
fractal_enable_2 false;
fractal_enable_3 false;
frames_per_keyframe 32;
glow_enabled false;
hdr_blur_intensity 2;
hybrid_fractal_enable true;
image_height 400;
image_width 400;
keyframe_frames_per_second 24;
keyframe_last_to_render 0;
limit_max 2,110842789362442 2,074349748311097 1,940045649124099;
limit_min -1,371117964537979 -1,788611695012979 -1,874268033372542;
limits_enabled true;
main_light_colour ff00 ff00 ff00;
main_light_enable false;
main_light_intensity 0,8;
main_light_visibility 0,1;
main_light_visibility_size 0,1;
mat1_is_defined true;
mat1_metallic false;
mat1_specular 0;
mat1_specular_width 1;
mat1_surface_color ca00 ca00 ca00;
mat1_transparency_index_of_refraction 1,1;
mat1_use_colors_from_palette false;
N 333;
penetrating_lights false;
target 1,428471372637132 -0,3865876070564904 0,03849806412994716;
view_distance_max 17,7228037812066;
volumetric_fog_colour_1_distance 0,6636516656599969;
volumetric_fog_colour_2_distance 1,327303331319994;
volumetric_fog_distance_factor 1,327303331319994;
[fractal_1]
transf_constant_multiplier_000 0,5 -0,1 0,5;
transf_constant_multiplierA_111 1,6 1,2 1;
transf_function_enabledR_false true;
transf_offset 1,1;
transf_offset_0 1,1;
transf_rotation 0 -2 -4;
transf_scaleA_1 0,6;
transf_scaleB_1 2,3;
[fractal_2]
mandelbox_offset 0,2 0,3 0,4;
mandelbox_rotation_main 9 0 0;
mandelbox_rotations_enabled true;
mandelbox_scale 1,3;
transf_addition_constant_111 1 0,4 1,4;
transf_minR2_p25 1,25;
[frames]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z
0;0;0;1;0;0;0;-1;0;0
1;0;0;0,9998716001157407;0;0;0;-1;0;0
2;0;0;0,9994936342592593;0;0;0;-1;0;0
3;0;0;0,998876953125;0;0;0;-1;0;0
4;0;0;0,9980324074074074;0;0;0;-1;0;0
5;0;0;0,9969708478009259;0;0;0;-1;0;0
6;0;0;0,995703125;0;0;0;-1;0;0
7;0;0;0,9942400896990741;0;0;0;-1;0;0
8;0;0;0,9925925925925926;0;0;0;-1;0;0
9;0;0;0,990771484375;0;0;0;-1;0;0
10;0;0;0,9887876157407407;0;0;0;-1;0;0
11;0;0;0,9866518373842592;0;0;0;-1;0;0
12;0;0;0,984375;0;0;0;-1;0;0
13;0;0;0,9819679542824075;0;0;0;-1;0;0
14;0;0;0,9794415509259259;0;0;0;-1;0;0
15;0;0;0,976806640625;0;0;0;-1;0;0
16;0;0;0,9740740740740741;0;0;0;-1;0;0
17;0;0;0,9712547019675926;0;0;0;-1;0;0
18;0;0;0,968359375;0;0;0;-1;0;0
19;0;0;0,9653989438657408;0;0;0;-1;0;0
20;0;0;0,9623842592592593;0;0;0;-1;0;0
21;0;0;0,959326171875;0;0;0;-1;0;0
22;0;0;0,9562355324074074;0;0;0;-1;0;0
23;0;0;0,953123191550926;0;0;0;-1;0;0
24;0;0;0,95;0;0;0;-1;0;0
25;0;0;0,9468768084490741;0;0;0;-1;0;0
26;0;0;0,9437644675925926;0;0;0;-1;0;0
27;0;0;0,940673828125;0;0;0;-1;0;0
28;0;0;0,9376157407407407;0;0;0;-1;0;0
29;0;0;0,9346010561342593;0;0;0;-1;0;0
30;0;0;0,931640625;0;0;0;-1;0;0
31;0;0;0,9287452980324075;0;0;0;-1;0;0
32;0;0;0,9259259259259259;0;0;0;-1;0;0
33;0;0;0,923193359375;0;0;0;-1;0;0
34;0;0;0,9205584490740741;0;0;0;-1;0;0
35;0;0;0,9180320457175926;0;0;0;-1;0;0
36;0;0;0,915625;0;0;0;-1;0;0
37;0;0;0,9133481626157407;0;0;0;-1;0;0
38;0;0;0,9112123842592593;0;0;0;-1;0;0
39;0;0;0,9092285156250001;0;0;0;-1;0;0
40;0;0;0,9074074074074074;0;0;0;-1;0;0
41;0;0;0,905759910300926;0;0;0;-1;0;0
42;0;0;0,904296875;0;0;0;-1;0;0
43;0;0;0,9030291521990741;0;0;0;-1;0;0
44;0;0;0,9019675925925926;0;0;0;-1;0;0
45;0;0;0,901123046875;0;0;0;-1;0;0
46;0;0;0,9005063657407407;0;0;0;-1;0;0
47;0;0;0,9001283998842593;0;0;0;-1;0;0
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z
0;0;0;1,1;0;0;0;-1;0;0
1;0;0;1;0;0;0;-1;0;0
interpolation;morphLinear;morphAkima;morphAkima

**Comment by aombk** [comment]
and the above doesnt render unless i disable hybrid fractals

**Comment by mclarekin** [comment]
I will be back in about  an hour.  But first one rendered OK for me. Are you talking about crashing, if so have you made the Windows  registry change?  Help - Manual - opencl trouble shooting

**Comment by aombk** [comment]
nope, no crashing
this is how the first one renders for me with hybrid disabled and enabled
![1 hybrid disabled](https://user-images.githubusercontent.com/8765458/68734782-39492a00-05e4-11ea-80c3-621c5b34dd07.JPG)
![1 hybrid enabled](https://user-images.githubusercontent.com/8765458/68734783-39e1c080-05e4-11ea-866d-72c243c8463b.JPG)

**Comment by aombk** [comment]
i will be back in a couple of hours

**Comment by mclarekin** [comment]
OK,  I am using the same dev version and Win10 64, and all is working ok for me.

Here are a couple of background questions
- have you used other versions and not had this problem?
- have you made the registry edit  (it is necessary for Windows , not for Linux)

BTW I have not seen this problrm before

**Comment by aombk** [comment]
i have been using mandelbulber for a long time without this problem
i dont get this with 2.19 for example or with the older 2.20 build i was using (unfortunately i dont remember which one)
i get this with the 2.20 of the last couple of days.

also about the registry edit, i may have done it but i dont remeber and i am not sure what you are referring to. can you send me a link?

i havent seen this problem before as well

**Comment by aombk** [comment]
![2a](https://user-images.githubusercontent.com/8765458/68768336-fe1e1980-062a-11ea-9ff6-298b51fcd763.JPG)
![2b](https://user-images.githubusercontent.com/8765458/68768337-fe1e1980-062a-11ea-9151-867efa702d4d.JPG)
![2c](https://user-images.githubusercontent.com/8765458/68768339-fe1e1980-062a-11ea-93b0-ca1729e62327.JPG)

**Comment by aombk** [comment]
ok i deleted:
Computer\HKEY_CURRENT_USER\Software\Mandelbulber from registry,

downloaded this:
https://ci.appveyor.com/project/buddhi1980/mandelbulber2/builds/28825951/job/sq0t2n4gxfotmo9j/artifacts

updated nvidia drivers with clean install
and reboot
and the problem is not there any more.

dont know what fixed it though. sorry for the fuss but maybe its worth looking into, since before doing all of the above, 2.19 was working fine and 2.20 had the problems i described.

thanks for your help

**Comment by aombk** [comment]
btw, what is the windows reigistry fix you are referring to?
deleting this? Computer\HKEY_CURRENT_USER\Software\Mandelbulber

**Comment by buddhi1980** [comment]
Computer\HKEY_CURRENT_USER\Software\Mandelbulb stores only geometry of program window and docks.

You problem was probably about NVidia compute cache. If we changed data structures since you rendered this hybrid fractal last time the program used different data structures than used when NVidia OpenCL compiled rendering kernels and stored them in cache. So the fractal data provided by program to OpenCL kernels was not compatible. This problem often happens in development version of the program and when used  NVidia gfx card. NVidia drivers use disk cache for kernels.
When we release next versions of the program we always change revision code for OpenCL programs and it forces OpenCL compiler to re-compile all kernels.
When you see this problem you should open Preferences in mandelbulber and on OpenCL tab tick "disable OpenCL cache". Then press Render. It will purge NVidia OpenCL compute cache. Then you can enable cache again (program will render faster).

**Comment by aombk** [comment]
ok great, nice to know, thanks a lot

**Comment by mclarekin** [comment]
The registry edit i talked about was the GPU timeout TDR thing. But if you
have been already using openCL then you probably have already done it.
From manual :
10.3.1 Driver crash under Windows
When Mandelbulber is run under Windows, the OS will monitor the GPU with a
watchdog. When the card becomes unresponsive for more than two seconds, the
driver will shutdown and crash with a message like: The NVIDIA OpenGL
driver lost connection with the display driver due to exceeding the Windows
Time-Out limit and is unable to continue.

**Comment by aombk** [comment]
thanks mclarekin, nice to know, i will check, just in case

**Comment by mclarekin** [comment]
also, very occasionally, win10 or driver updates can revert the registry
and you have to redo it
