### ISSUE TITLE
Problem with pseudoklienian in hybrid mode

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#743]
mage on left is mandelbulber-Release-x64-0bdef76a436a02a16133baa660d8f44f96f6157c
24 November

image on right is mandelbulber-Release-x64-5974d9dce8e703dba7ac3f9551e28850a4a2462f
27 November

Hybrid mode enabled, full openCL

# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 0000 aa00 ff00;
camera -0.721285304338675 -4.818733761278942 0.3812866615082037;
camera_distance_to_target 1.721461653709412;
camera_rotation -0.9784713988658056 -12.36778812482929 0;
camera_top 0.003657597306812026 0.2141549727466719 0.9767928488834331;
flight_last_to_render 0;
formula_1 2104;
formula_2 103;
formula_3 2104;
fov 0.5;
fractal_enable_1 false;
fractal_enable_3 false;
glow_enabled false;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
keyframe_last_to_render 0;
mat1_is_defined true;
N 31;
raytraced_reflections true;
target -0.69257060867735 -3.137467522557884 0.01257332301640735;
view_distance_max 1331.370849898476;
volumetric_fog_colour_1_distance 0.03125;
volumetric_fog_colour_2_distance 0.0625;
volumetric_fog_density 0.125;
volumetric_fog_distance_factor 0.0625;
[fractal_1]
boxfold_bulbpow2_z_factor 1;
fold_color_difs1 0.9;
mandelbox_color 0 1.85 0;
mandelbox_color_Sp1 0;
mandelbox_main_rotation_enabled true;
mandelbox_scale 1.2;
transf_addition_constant 0 0 0.3;
transf_addition_constant_0555 1 1 1;
transf_folding_limit 0.9;
transf_function_enabled_false true;
transf_function_enabledAz_false true;
transf_function_enabledB_false true;
transf_function_enabledBx false;
transf_function_enabledBy false;
transf_function_enabledBy_false true;
transf_function_enabledD_false true;
transf_function_enabledK_false true;
transf_function_enabledM false;
transf_function_enabledM_false true;
transf_function_enabledz_false true;
transf_minimum_radius_05 0;
transf_minR2_p25 0;
transf_offset_001 0 0 1.7;
transf_offset_002 0 0 1.7;
transf_offset_05 0;
transf_offset_1 2;
transf_offset_111 1 1 3;
transf_offset_2 1;
transf_offsetA_0 1.2;
transf_offsetA_1 1.5;
transf_offsetA_2 1.2;
transf_offsetE_2 0.7;
transf_offsetF_2 1.2;
transf_scale_2 1.2;
[fractal_2]
fold_color_difs1 0.2;
mandelbox_color 0 0 0.07000000000000001;
mandelbox_color_Sp1 0;
mandelbox_color_Sp2 0;
mandelbox_main_rotation_enabled true;
mandelbox_scale 1.1;
transf_addition_constant_0555 1 1 1;
transf_folding_limit 0.9;
transf_function_enabledAz_false true;
transf_function_enabledBx false;
transf_function_enabledBy false;
transf_function_enabledK_false true;
transf_function_enabledM false;
transf_function_enabledz_false true;
transf_minR2_p25 0;
transf_offset_001 0 0 3;
transf_offset_002 0 0 1.7;
transf_offset_05 0;
transf_offset_1 2;
transf_offset_111 1 1 3;
transf_offset_2 0.9999999999999997;
transf_offsetA_0 2.7;
transf_offsetA_1 1.5;
transf_offsetA_2 1.199999999999999;
transf_offsetB_0 2;
transf_scale_2 1.2;
transf_start_iterations_A 6;
transf_start_iterations_M 4;
transf_stop_iterations_A 7;
transf_stop_iterations_C 7;
transf_stop_iterations_X 7;
[fractal_3]
transf_function_enabledAx false;
transf_function_enabledAy false;
transf_function_enabledBz_false true;
transf_function_enabledG_false true;
transf_function_enabledM false;
transf_function_enabledR_false true;
transf_function_enabledSw_false true;
transf_function_enabledX_false true;
transf_offset_0005 0.01;
transf_radius_1 0.6;
transf_rotation 0 0 30
![pk col](https://user-images.githubusercontent.com/12769564/69846258-59f9cb00-12d8-11ea-92ea-ce9f9d3382a4.jpg)

**Comment by mclarekin** [comment]
From Krzysztof
Problem here is deeper. If you swap first two slots to have Pseudo Kleinian i first slot, then colors are like in 2.19. Also shape changes a little. When it is in first lot bailout works properly, when is in second slot, bailout doesn't work (there are calculated all iterations). It happens in 2.19 and 2.20

**Comment by mclarekin** [comment]
From Krzysztof

Try to swap slots here:

# Mandelbulber settings file
# version 2.19
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
flight_last_to_render 99999;
formula_1 0;
formula_2 103;
hybrid_fractal_enable true;
keyframe_last_to_render 0;
mat1_is_defined true;
mat1_surface_color_gradient 0 fd6029 999 698403 1999 fff59b 2999 f5bd22 3999 0b5e87 5000 c68876 5999 a51c64 7000 3b9fee 7999 d4ffd4 9000 aba53c;
N 50;
raytraced_reflections true;
I need to recheck how bailout is used in hybrid mode (especially when first slot is empty)

**Comment by mclarekin** [comment]
if i remove pseudoKl from this code I get the same image in slot 1 and in slot 2

if (isHybrid)
for (int f = 0; f < NUMBER_OF_FRACTALS; f++)
{
if (fractalList[GetIndexOnFractalList(fractals[f]->formula)].DEFunctionType
== fractal::pseudoKleinianDEFunction
|| fractalList[GetIndexOnFractalList(fractals[f]->formula)].DEFunctionType
== fractal::josKleinianDEFunction)
{
useAdditionalBailoutCond[0] = true;
}

**Comment by mclarekin** [comment]
there is a semi colon on line 83 nine fractals cpp??

{
return useAdditionalBailoutCond[formulaIndex];
}; // semi colon?

**Comment by buddhi1980** [comment]
here was a mistake. Should be
{
useAdditionalBailoutCond[f] = true;
}

f instead of 0

**Comment by mclarekin** [comment]
Difference between slots with  pseudoKleinian is fixed, so will close this issue

There is still cuts in color unique to pseudoKleinian maths, jest jak jest, 
maybe one day i will code a special color algorithm to remove them
