### ISSUE TITLE
		// r calculation

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#746]
I am thinking about removing the four non-standard cases from the r calculation, and  doing their r calculations in the formula and inputting into computeractal.cpp by using aux.dist.  i am assuming it should make all other formulas faster.

What do you think???

		switch (fractal->formula)
		{
			case scatorPower2:					// add v2.15
			case scatorPower2Real:			// add v2.15
			case scatorPower2Imaginary: // corrected v2.14
				// case testingLog:
				{
					CVector4 z2 = z * z;
					r = sqrt(z2.x + z2.y + z2.z + (z2.y * z2.z) / z2.x);
					// initial condition is normal r, becomes aux.r

					// r = sqrt(z2.x - z2.y - z2.z + (z2.y * z2.z) / (z2.x));
					break;
				}
			// scator magnitudes
			// magnitude in imaginary scator algebra

			// case pseudoKleinian:
			// case pseudoKleinianMod1:
			// case pseudoKleinianMod2:
			case pseudoKleinianStdDE:
			{
				r = sqrt(z.x * z.x + z.y * z.y);
				break;
			}

**Comment by buddhi1980** [comment]
If you move r calculation into the formula code (for formulas where is special one), you will still ned in computeFractal the condition which will check which formula is used to use default r calculation (and not override r calculated in the formula code)
Or I understand something wrong?

**Comment by mclarekin** [comment]
The global  r calculation in compute_fractals.cpp  would be used for bailout check of all formulas

The in-formula r calculation is used for aux.dist = r/DE,  then use case analyticFunctionDIFS:

It seems to work OK for case pseudoKleinianStdDE, but i have not checked the scator cases yet.

**Comment by mclarekin** [comment]
comit https://github.com/buddhi1980/mandelbulber2/commit/ed7b95a57c58d15af66e34ef2c6f675c27bf1a77
removed 
case pseudoKleinianStdDE.  r calc for DE is now in formula. Examples are OK
case scatorPower2Real: DeltaDE,  using normal r for bailout works OK
TODO test  what can be done with the remaining two cases

**Comment by mclarekin** [comment]
commit https://github.com/buddhi1980/mandelbulber2/commit/8d7ece0fa3f2257da2ec018de021996fbb4df120

all four cases of non standard  r calculations have been removed from main loop, all now use standard r for bailout check. This should produce a slight decrease in render time.

pseudoKleinianStdDE and Scator Power 2 now use aux.dist for analytic DE, the other two cases were delta DE

there are some minor effects on some scator fractals but not worth consideration
