### ISSUE TITLE
Cannot save from material editor

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#748]
Mandelbulber 2.21-dev
Xubuntu 18.04

Not sure why. Error message in terminal is:
Critical: cMultiVal::isEqual(const cMultiVal &m): undefined type of variable
(../src/multi_val.cpp:310, bool cMultiVal::isEqual(const cMultiVal&) const)

**Comment by TasMania17** [comment]
I found a workaround by using MDBB 2.20-dev. I can make a new material, save and then open with MDBB2.21-dev.
I make materials with 'Use color texture from an image'.  MDBB 2.21-dev does not find the image path for some reason. The earlier version does.

**Comment by mclarekin** [comment]
it appears that what is happening now, right click on gradient palette, choose "grab colors from image" 
it gets saved in settings file  as "mat1_surface_color_gradient 0 3a3436 908  ........"
i am testing in dev 2.21, win OS
I can not remember what use to happen, did the old settings file have a file path to image??

**Comment by mclarekin** [comment]
On material editor i can save   e.g  cMaterialEditor23, and then successfully load it  to use with a different fractal settings

**Comment by mclarekin** [comment]
Hmmm but not everytime, i need to do some more testing, but i am not getting any error message

**Comment by mclarekin** [comment]
that was something different,   cMaterialEditor**23**, needs to have a number at end cMaterialEditor**df** will not work

**Comment by TasMania17** [comment]
Using MDBB compiled today - I can save a material that uses 'color texture from an image' but only if I save the new material as part of a fractal.
If I save the material from material editor it saves but when reloaded it is all black with no color texture and the same error in terminal.

Critical: cMultiVal::isEqual(const cMultiVal &m): undefined type of variable
(../src/multi_val.cpp:310, bool cMultiVal::isEqual(const cMultiVal&) const)

For me this is a bug because materials should be able to be re-used.

**Comment by mclarekin** [comment]
what does your cMaterialEditor file look like?  This is mine from W1n 10 OS and i can reuse it with other fractals

# Mandelbulber settings file
# version 2.20
# only modified parameters
[main_parameters]
mat1_file_color_texture C:\Users\graeme\mandelbulber\my images colours\At the back of beyond -Kepler 16b.jpg;
mat1_fractal_coloring_aux_color_false true;
mat1_fractal_coloring_orbit_trap_scale1 0;
mat1_fractal_coloring_orbit_trap_true false;
mat1_fractal_coloring_orbit_trap_weight 3.9;
mat1_fractal_coloring_rad_div_de_scale1 0;
mat1_fractal_coloring_rad_div_de_weight 19.5;
mat1_specular 1;
mat1_specular_plastic_enable false;
mat1_specular_width 1;
mat1_surface_color ad00 ad00 ad00;
mat1_surface_color_gradient 0 fd6029 999 698403 1999 fff59b 2999 f5bd22 3999 0b5e87 5000 c68876 5999 00ffff 7000 3b9fee 7955 aa0000 9000 aba53c;
mat1_use_color_texture true;
mat1_use_colors_from_palette false;

**Comment by TasMania17** [comment]
Hi mclarekin
My material had 'mat2' in the first column. When I changed them all to 'mat1' the material opened straight away. That seems to have solved it but why only 'material1?

**Comment by mclarekin** [comment]
I do not know. Out of interest, were you in medium or full mode?

**Comment by buddhi1980** [comment]
Just to clarify this problem. What you use to save the material?
This (Save material as...)?
![image](https://user-images.githubusercontent.com/11696990/70866226-6f712500-1f67-11ea-808d-3cbf092754cd.png)

or this?
![image](https://user-images.githubusercontent.com/11696990/70866236-86b01280-1f67-11ea-9aa4-4ee60bbf49f1.png)

**Comment by TasMania17** [comment]
I'm using Full mode.

I think the problem is with the Material editor Save/Open (second image).
 It does not properly open a material that was saved by the Material Editor. 

The top image 'Load materials' can open materials saved by the Material editor.

If more than one material is already loaded Material editor cannot load another material. Maybe because the new material has to be called 'mat1'?
