### ISSUE TITLE
Will new FOV System break old Projects?

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#749]
Morning! With the introduction of FOV in degrees. Should there be a "Use old FOV system" option for loading older projects? Just a thought.

**Comment by buddhi1980** [comment]
Will not brake. DOF value is converted when settings are loaded (if settings were saved in version less equal 2.20)

**Comment by buddhi1980** [comment]
Here is the code for conversion:
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/settings.cpp#L1137
