### ISSUE TITLE
Mandelbulber opencl stops working when enabling volumetric light

### ISSUE THREAD

**Issue by b1tfl0w** [buddhi1980/mandelbulber2#753]
Mandelbulber with opencl enabled (full) stops working if I select Global illumintation by volumetric effects and light # as volumetric. It hangs on "Assigning kernel parameters". 
The GUI remains responsive claiming the rendering is done but its not, cpu remains at 100%, if I press the render button again I see in terminal "PID: 30087, time: 998.860225627, cInterface::StartRender(void) - image was used by another instance", 
this also happens randomly..sometimes I just have to restart Mandelbulber but not in this case.

##### System information (version)

Mandelbulber2 v2.20
Linux Ubuntu 18.04 Bionic Beaver
Dell Latitude intel core i5 4G Ram
Intel graphic card HD 5500
intel-opencl-icd/bionic,now 19.48.14977-1~ppa1~bionic1 amd64 [installed]
  Intel graphics compute runtime for OpenCL

Here is the log:
[mandelbulber_log.txt](https://github.com/buddhi1980/mandelbulber2/files/3996280/mandelbulber_log.txt)
and the settings file:
[aplace6oidn.txt](https://github.com/buddhi1980/mandelbulber2/files/3996298/aplace6oidn.txt)

**Comment by buddhi1980** [comment]
I would not expect too much from build-in Intel GPU. It works very unstable with OpenCL and cannot handle big OpenCL programs. When you enable GI by volumetric effects, then OpenCL program is very big. If you want to use OpenCL you need to have some good GFX card.

**Comment by buddhi1980** [comment]
By the way the settings which you tried to render are "killer" type. If you use reflectance together with MC Global Illumination it is very slow to render. What is more you selected fractals which uses DeltaDE distance estimation algorithm which makes everything 6 times slower. It uses enormous amount of GPU resources. Wow! I just found that you also enabled main light as volumetric. Sometimes you should decide which effects are really needed and find compromise between rendering speed (used resources) and input for image appearance.
In Nvidia GTX 1060 it took 6 minutes to calculate just one MC iteration.
![image](https://user-images.githubusercontent.com/11696990/71401595-a2cc4780-262a-11ea-8797-d22a3f8d622b.png)

**Comment by b1tfl0w** [comment]
So I was pretending too much from this integrated card..anyway I was impressed on the speed of opencl compared to cpu..I just have not to exagerate with settings! Thank you!
