### ISSUE TITLE
change difs to  customDE

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#754]
change all reference to analyticDIFS  to analyticInFormula

analyticFunctionDIFS
dIFSDEFunction
ANALYTIC_DIFS_DE
clAnalyticFunctionDIFS:
etc

**Comment by buddhi1980** [comment]
Why you are changing names from dIFS to In.. ? Is this some abbreviation?

**Comment by buddhi1980** [comment]
Will anybody know what it mean?

**Comment by mclarekin** [comment]
"Will anybody know what it mean?  "  probably not :)

"In Formula DE" (or maybe auxDistDE???)   is  when the entire distance
estimation calculation is in formula code.  This includes,( but not limited
to) , difs formulas. There are now 7 formulas that use aux.dist that are
not difs and there will be more.




# Mandelbulber settings file
# version 2.21
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 0 -1.278395357021704e-16 2.302952341406048;
camera_distance_to_target 2.302952341406048;
camera_rotation 0 -90 0;
camera_top 0 1 1.665334536937735e-16;
DE_factor 0.5;
flight_last_to_render 0;
formula_1 193;
formula_2 190;
fractal_enable_2 false;
hybrid_fractal_enable true;
image_height 800;
image_proportion 1;
keyframe_last_to_render 0;
mat1_fractal_coloring_extra_color_options_false true;
mat1_fractal_coloring_orbit_trap_scale1 0;
mat1_fractal_coloring_rad_div_de_scale1 0;
mat1_is_defined true;
mat1_specular 4;
mat1_specular_width 0.063;
mat1_surface_color_gradient 0 fd6029 999 698403 1999 fff59b 2999 f5bd22
3999 0b5e87 5000 c68876 5999 a51c64 7000 3b9fee 7999 d4ffd4 9000 aba53c;
raytraced_reflections true;
view_distance_max 6.234334263845343;

# Mandelbulber settings file
# version 2.21
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
camera 0.1915588810003375 -2.060772711975448 -0.07052179408649811;
camera_distance_to_target 2;
camera_rotation 5.81359458682975 12.90823053933102 -0.5246608996316185;
camera_top 0.01351692801439903 -0.223159385961308 0.9746882481667795;
DE_factor 0.5;
flight_last_to_render 0;
formula_1 192;
formula_2 190;
fractal_enable_2 false;
hybrid_fractal_enable true;
image_height 540;
image_width 960;
keyframe_last_to_render 0;
mat1_fractal_coloring_extra_color_options_false true;
mat1_fractal_coloring_orbit_trap_scale1 0;
mat1_fractal_coloring_rad_div_de_scale1 0;
mat1_is_defined true;
mat1_specular 4;
mat1_specular_width 0.063;
mat1_surface_color_gradient 0 fd6029 999 698403 1999 fff59b 2999 f5bd22
3999 0b5e87 5000 c68876 5999 a51c64 7000 3b9fee 7999 d4ffd4 9000 aba53c;
raytraced_reflections true;
target -0.005906324154761403 -0.121341125804039 0.3762584822392451;
view_distance_max 765.686688139087;
[fractal_1]
analyticDE_offset_0 1;
fold_color_aux_color_enabled_false true;
fold_color_difs1 3.6;
fold_color_difs_0000 1.2 0 0 0;
IFS_abs_x true;
IFS_abs_y true;
IFS_abs_z true;
IFS_direction_3 -2.62 1 1.62;
IFS_direction_4 1.62 -2.62 1;
IFS_enabled_3 true;
IFS_enabled_4 true;
IFS_offset 1 0 1.62;
IFS_rotation_enabled true;
transf_function_enabledA_false true;
transf_function_enabledR_false true;
transf_offset_001 0 0 0;
transf_offset_1 1.2;
transf_offset_3 2.6;
transf_offsetA_000 0.5 -0.2 0;
transf_offsetE_2 0;
transf_offsetF_2 0;
transf_rotation 0 15.185837 0;
transf_scale_2 3;
transf_scale_3 2.8;
transf_scale_4 2.8;
transf_stop_iterations 15;

**Comment by buddhi1980** [comment]
What you think to use "customDE" name?

**Comment by mclarekin** [comment]
I like it !!   it is perfect   !!

**Comment by mclarekin** [comment]
@buddhi1980 

could you do the find and replace work,   safer than me doing it :)
change all reference to analyticDIFS to analyticCustomDE


analyticFunctionDIFS
dIFSDEFunction
ANALYTIC_DIFS_DE
clAnalyticFunctionDIFS:
etc

**Comment by mclarekin** [comment]
@buddhi1980 

I  cannot find where  the DE function label comes from for statistics dialogue

label_used_distance_estimation

**Comment by mclarekin** [comment]
![function](https://user-images.githubusercontent.com/12769564/72233685-a6e9f480-362d-11ea-8c24-9e6a5f740c4d.JPG)

**Comment by mclarekin** [comment]
complete
