### ISSUE TITLE
Implement Randomize

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#757]
Made an issue  as a place for comments

Is    "  analyticDE_........."   removed  in the randomize  algortihm?

**Comment by buddhi1980** [comment]
I don't understand this. What analyticDE has in common with Randomizer?

**Comment by mclarekin** [comment]
all spinboxes for analytical DE controls and tweaks that are on the formula UI should be excluded  from the randomize algorithm

**Comment by mclarekin** [comment]
meaning consider excluding struct sFractalAnalyticDE.

struct sFractalAnalyticDE
{
	bool enabled;
	bool enabledFalse;
	double scale1;
	double tweak005;
	double offset0;
	double offset1;
	double offset2;
};

**Comment by buddhi1980** [comment]
Why these parameters should not be randomized?

**Comment by mclarekin** [comment]
Other parameters randomize shape whereas randomizing these parameters will produce unecessary bad DE.  They are tools to use only when the DE needs to be adjusted.

**Comment by buddhi1980** [comment]
Ok. They will be excluded.

**Comment by mclarekin** [comment]
Cool, 
- the worst case i had was 7 out of 12 randoms adversely effected by aux>DE controls
- Randomizer preview size = small,  works great with my laptop screen, thanks
- there are some other parameters  ( e.g intial w) that can adversly effect randoms, but these are not worth doing anything about
- randomizer is working really well,  a very useful addition
- we could consider a more advanced version, but that would be of low priority   compared to other improvements

**Comment by mclarekin** [comment]
it is good that we can exit randomizer, as sometimes it gets stuck on  a very long calculation :)

**Comment by buddhi1980** [comment]
fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/17b6b54df9b4ab9839cb39c231e637cf2d907418
