### ISSUE TITLE
Materials not shown correct on Linux (Mint Mate)

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#759]
As written on Fb,
latest Mb-dev-versions do not show up materials as they should:
 ![80970012_877465249323029_7472323229009313792_o](https://user-images.githubusercontent.com/29848666/72672113-caf66d00-3a55-11ea-816c-85fc485ae5bb.jpg)
![81602662_877387052664182_9107688943867920384_o](https://user-images.githubusercontent.com/29848666/72672114-caf66d00-3a55-11ea-94b7-a172bbcb7266.jpg)

##### System information (version)

Mint Mate x64

##### Detailed description

Materials do not show up as they should / compared to Windows

##### Steps to reproduce

Pull latest dev from git and build (with OCL) on latest Mint Mate-OS

**Comment by buddhi1980** [comment]
When you render image in CPU mode is everything looks properly (now I'm not asking about rendering of material thumbnails)?

**Comment by michas0602** [comment]
CPU + GPU-render both seem to be fine....it looks as if just the rendering of the material is broken.

Beside this it seems that anti-aliasing is also not working - it just does one render...but I do not know if this is another problem or whether it's coherent.

**Comment by buddhi1980** [comment]
Are sure that it is the latest dev version? There is no randomizer here.

**Comment by michas0602** [comment]
Yes, I did a fresh pull and build from Git yesterday with the same result. The images are 2-3 weeks old.

**Comment by michas0602** [comment]
To ensure its still there, this photo is from today with latest build:
![Bildschirmfoto zu 2020-01-25 17-13-15](https://user-images.githubusercontent.com/29848666/73124017-83606b80-3f96-11ea-9ae8-209692cdf55b.png)

**Comment by michas0602** [comment]
Has anyone maybe an idea what could cause this? Is there possibly a wrong dependency installed here? Where can I start to check if all necessary versions are fulfilled?

**Comment by buddhi1980** [comment]
Rendering previews of materials doesn't use any external library. I have no clue what could be wrong.

**Comment by buddhi1980** [comment]
I cannot reproduce this problem on any of my computers.

**Comment by TBeholder** [comment]
Same deal (on mandelbulber2-2.21-1) - materials seem to work properly on fractals, but thumbnails are mostly like this, shadowed glassy moons.
Material properties like luminosity texture or transparency still affect thumbnails, so it looks like the thumbnail scene gets screwed up somehow?

**Comment by michas0602** [comment]
Fixed yesterday by buddhi
