### ISSUE TITLE
[Request] Built-in theme or hardcoded colors for Linux

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#760]
Since a while I mention that Mandelbulbers colors in Linux are incomplete (the cursor-buttons for example):
![81602662_877387052664182_9107688943867920384_o](https://user-images.githubusercontent.com/29848666/72672176-bf577600-3a56-11ea-9c4c-a296ad5bc73c.jpg)

So would it be possible maybe to 'hardcode' some color to them or add some built-in-theme - so that they get some kind of color 'out of the box'?

**Comment by networkpanic** [comment]
this is an issue with your QT theme settings
please consult your distro documentation

for myself i use https://sourceforge.net/projects/qt5ct/ to configure my theme on archlinux
