### ISSUE TITLE
[Request] Long loadingtimes for textures

### ISSUE THREAD

**Issue by christianbecker3** [buddhi1980/mandelbulber2#761]
Hello everyone!

I dunno if it's possible, but is there a possibility to cache textures used in project somewhere instead of reload them everytime you start the renderingprocess?

Or at least, if it's not possible to implement something like that, to add a button where we can bypass textures (so previewing stuff would be much more comfortable).

**Comment by vbruhn** [comment]
Double this.
Even when unchecking all the textures, the renderer seems to load them 'just in case' ... making a 7 second preview render last 30 seconds or longer.

**Comment by buddhi1980** [comment]
Texture cache added in commit https://github.com/buddhi1980/mandelbulber2/commit/ea7b3b269cef285e2a3d2608070336c839626ee2
