### ISSUE TITLE
Some mandelbox formulas not working MacOS Mojave

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#762]
errors reported by fpsurgeon at fractalforums

https://fractalforums.org/mandelbulber/14/macos-opencl-not-working-for-mandelboxes-but-works-with-other-fractals/3312/msg18839#msg18839

current Mac system is a 27" iMac (2019) 3.7 GHz Intel Core i5, 24GB RAM, Radeon Pro 580X 8 GB GPU. Mandelbulber is the stable release 2.20. MacOS Mojave

only mandelbox ones that seem to work are "Mandelbox - Vary Scale 4D" and "Mandelbox - Smooth." All other mandelbox formulas error out. 

Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
Error returned by cvms_element_build_from_source

Even  "Mandelbox - Variable" errors out, but with a slightly different error:

Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
In file included from <program source>:39:
/Applications/mandelbulber2.app/formula/opencl/mandelbox_variable.cl:192:10: error: Cannot downconvert and widen scalar type 'double' to vector type '__float4'
                tempVC *= M_PI_180;
  ~~~~~~ ^  ~~~~~~~~

the Abox and Amazing Surf formulas I've tried so far all work and render fine under OpenCL,
and "Fold Box - Mod 1" works,

**Comment by mclarekin** [comment]
suspect mac openCL maths, i will look  for any common differences in  the maths functions between what works and what does not work

**Comment by mclarekin** [comment]
i am guessing two things:
a)with the Mandelbox  and Mandellbox -Menger,   it is in the code for   Rotation of Separate Planes

b) and the Mandlbox Variable is

Quote
/Applications/mandelbulber2.app/formula/opencl/mandelbox_variable.cl:192:10: error: Cannot downconvert and widen scalar type 'double' to vector type '__float4'
                tempVC *= M_PI_180;

**Comment by buddhi1980** [comment]
Fixed in build https://github.com/buddhi1980/mandelbulber2/commit/cd705a45007bdff94e3790c6090e589e1666c76e
