### ISSUE TITLE
Render-problems on Mint Mate 19.3

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#764]
Actually found another problem with latest MB on Linux Mint Mate 19.3:
Fractals wont be rendered if (custom) light 1 is disabled?! Tried it with several builds within the last days and the problem occurs all the time here.  

Fractals just render with (custom) light 1 on. 

On Windows eyerything seems to be fine.

##### System information (version)
- mandelbulber2 => 2.21dev
- Operating System / Platform => Mint Mate 19.3

##### Detailed description

Selecting any fractal from the shortcut-list and pressing "render" does not work as it should / producing just a colored screen.

##### Steps to reproduce
 Just select any fractal from shortcut-list and press render.

![Bildschirmfoto zu 2020-02-12 00-44-40](https://user-images.githubusercontent.com/29848666/74290274-a5494480-4d31-11ea-81ff-cf75b539f618.png)

**Comment by buddhi1980** [comment]
Run rendering once with disabled OpenCL chache (option in Mandelbulber preferences on OpenCl tab), or delete /home/username/.nv directiory (cache for NVidia OpenCL compiler)

This problem happens in development version when there are changed OpenCL data structures in OpenCL kernels without changing kernel code (or version number).

**Comment by michas0602** [comment]
Confirmed, deleting that folder solves this.

**Comment by buddhi1980** [comment]
I can reproduce this problem with material previews. It happens on PC with lower resolution display. I'm going to fix it asap.

**Comment by buddhi1980** [comment]
Fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/fee9463e6063bcfd2576e388a28aebc966aaca52

**Comment by michas0602** [comment]
Confirmed, now it is fine, many thanks! And the new form looks interesting / more useful than before

**Comment by michas0602** [comment]
@buddhi1980 Something got messed up here, this bug here is still actual and needs to be re-opened.
Commit "fee9463" fixed bug #759 - but this here is still actual.
