### ISSUE TITLE
[suggestion] plz change the readme of vfx_tools to include the following instructions on how to download.

### ISSUE THREAD

**Issue by NicTanghe** [buddhi1980/mandelbulber2#767]
plz change the readme of vfx_tools to include the following instructions on how to download.

1. Download SVN
 2. Run the following command. 
`svn export https://github.com/buddhi1980/mandelbulber2.git/trunk/contrib/vfx_tools`

**Comment by MeyerAdrian** [comment]
Hey,
sorry ,not quite sure what you mean.
Can you try explain a bit more detailed?
thx

**Comment by NicTanghe** [comment]
well if you want to download a subfolder from a project in github without downloading / pulling all the otherfiles from the server.
that's the fastest way to do it. it whould be hanndy if it's right there in the ready how to do it.

**Comment by MeyerAdrian** [comment]
done. also added some new features.
will send pullrequest
