### ISSUE TITLE
Wished Feature - Option to autosave image when rendering is finished

### ISSUE THREAD

**Issue by dluchansky** [buddhi1980/mandelbulber2#776]
Hi guys,

Sometimes when I am rendering my computer will crash after image is finished but before I can manually save it. It would be helpful to have a checkbox option to automatically save the image after rendering is finished, so it can be recovered in the event of a crash. This functionality should be relatively easy to implement given it is already used by the animation features.

Dan

**Comment by mclarekin** [comment]
Out of interest,  is it the program or your computer that is crashing?

**Comment by dluchansky** [comment]
Maybe crash was the wrong word, but a few times we have had power outages and my computer was forced to shut down as a result. I've never had Mandelbulber itself crash *after* finishing a render.

**Comment by mclarekin** [comment]
Thanks for clarification. Program seems really stable to me, although I do not use volumetics or MC.
