### ISSUE TITLE
 "CommandLine Error: Option 'limited-coverage-experimental' registered more than once!" - a solution

### ISSUE THREAD

**Issue by grattle** [buddhi1980/mandelbulber2#777]
On startup, the error in the title has been happening for the last month or so, followed by a crash.

That was compiled from master, had been working fine for years. The Appimage did the same.

A bit of googling eventually gave a clue, perhaps too many icd files installed. On my system that is various NVidia icd packages, plus the Mesa icd package.

I removed the package mesa-opencl-icd, and all is well again.

Why crashing now, rather than ages ago ? that mesa icd package has probably been there since I installed the system. No idea, but at least it works again.

Arthur

##### System information (version)
- mandelbulber2 => 2.21 Appimage, also same issue when compiled from master
- Operating System / Platform => Linux Debian Testing
- Compiler => gcc

**Comment by networkpanic** [comment]
wasnt able to reproduce, looks like a config issue with your environment, pls reopen if it still occurs
