### ISSUE TITLE
Ubuntu 18.04 no QTGamePad

### ISSUE THREAD

**Issue by gateway** [buddhi1980/mandelbulber2#778]
##### System information (version)
Ubuntu 18.04

##### Detailed description

doing a make all failes on ubuntu 18 with missing qt game pad..

```
teway/anaconda3/lib -lQt5UiTools -lQt5Widgets -lQt5Multimedia -lQt5Gamepad -lQt5Gui -lQt5Network -lQt5Test -lQt5Core -lGL -lImath -lHalf -lIex -lIexMath -lIlmThread -lpthread -ltiff -lsndfile 
/usr/bin/x86_64-linux-gnu-ld: cannot find -lQt5Gamepad
collect2: error: ld returned 1 exit status
Makefile:2089: recipe for target 'mandelbulber2' failed
make: *** [mandelbulber2] Error 1
```
Anyone got this to work, I cant seem to find a qt5 gamepad for Ubuntu 18, I see one for 19..

**Comment by gateway** [comment]
can I compile this w/o the need for game pad?

**Comment by gateway** [comment]
Anyone.. im sorta stuck on older version for ubuntu and want all the new features so I figured I would compile it myself.

**Comment by mclarekin** [comment]
i would not know :(
 try it and see

**Comment by TasMania17** [comment]
Why not use the appimage buddhi has developed? Appimages are cross platform for Linux. I use a Gimp appimage everyday.
https://github.com/buddhi1980/mandelbulber2/releases

**Comment by networkpanic** [comment]
You can either use AppImage or take a look into mandelbulber2/qmake/common.pri

it should be possible to disable it
unfortunately we cant give support on EOL versions of ubuntu
