### ISSUE TITLE
Arch issue

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#781]
reported as facebook by Jorge

since latest Arch update can't start Bulber :(
It gives me this output:
mandelbulber2: error while loading shared libraries: libIlmImf-2_4.so.24: cannot open shared object file: No such file or directory

**Comment by buddhi1980** [comment]
It was caused by missing library in the system

**Comment by Jakeukalane** [comment]
Comment. The library libIlmImf is present (at least now) but is a more recent version libIlmImf-2_5.so.25. 
I did:
sudo ln -s /usr/lib/libIlmImf-2_5.so.25 /usr/lib/libIlmImf-2_4.so.24
sudo ln -s /usr/lib/libHalf-2_5.so.25 /usr/lib/libHalf-2_4.so.24
sudo ln -s /usr/lib/libIex-2_5.so.25 /usr/lib/libIex-2_4.so.24

But there is still an error: mandelbulber2: symbol lookup error: mandelbulber2: undefined symbol: _ZTIN7Imf_2_49AttributeE

**Comment by buddhi1980** [comment]
Great news. I don't work with this Linux distribution (I use Debian), so I couldn't help you.
