### ISSUE TITLE
2.22 Mandelcup not rendering with OpenCL

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#786]
Fresh compile of 2.22 on Ubuntu 20.04.
New fract Mandelcup. Renders with No OpenCL but not with any OpenCL.

Message:
Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
<kernel>:37:10: fatal error: '/usr/share/mandelbulber2/formula/opencl/mandelcup.cl' file not found
#include "/usr/share/mandelbulber2/formula/opencl/mandelcup.cl"
         ^

**Comment by mclarekin** [comment]
Hi Tas, it has not been ported to openCL yet.  Same with spheretree and a few other things.
