### ISSUE TITLE
slot maxiter boolean mode

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#789]
I am assuming in boolean mode, that all slots run for same maxiter. Is it possible to have maxiter for each slot in boolean mode, because some formulas only need to run for one iteration

**Comment by buddhi1980** [comment]
It is a good point. It is worth to implement.

**Comment by mclarekin** [comment]
It is worth implementing soon :)  From my vague memory, there are some formulas that will need to have iterations limited to work  in boolean mode.   It will also   fit with a possible  "how to minimize Mandelbulber render time"  tutorial,   which will demonstrate converting hybrid formulas to single slot custom formulas, (with unused parameters removed)

**Comment by mclarekin** [comment]
GridV3 is an example of a  needing max iter in boolean mode, it only needs to run  for 1 iter

**Comment by mclarekin** [comment]
"It is worth to implement."      There a now a lot more formulas that  need only one or a few iterations

**Comment by buddhi1980** [comment]
In 2.29 there will be maxiter and number of iterations for each fractal slot

**Comment by buddhi1980** [comment]
I'm also thinking if there could be different detail level for each fractal slot. But this I'm not sure if will be possible.

**Comment by mclarekin** [comment]
Detail Level would be good if easy, it would get a bit more complicated with boolean union when using  a smooth transition function. 

Distance estimation function would also be useful in some cases.

**Comment by buddhi1980** [comment]
Just added maxiter control for each formula in boolean mode. Implemented in CPU code. For OpenCL will be soon.

**Comment by mclarekin** [comment]
https://github.com/buddhi1980/mandelbulber2/commit/63a9624fa290989329f7648ba61ac1bd8c4cb7a8
