### ISSUE TITLE
Open CL issue OSX for Equirectangular rendering

### ISSUE THREAD

**Issue by gateway** [buddhi1980/mandelbulber2#790]
##### System information (version)

- mandelbulber2 => 2.12
- Operating System / Platform => macOS Cataline
- Compiler =>

##### Detailed description

When enabling open CL on the latest release version and trying to render out a Equirectangular image it errors out.

```
Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
In file included from <program source>:59:
/Applications/mandelbulber2.app/opencl/engines/projection_3d.cl:57:29: error: Cannot downconvert and widen scalar type 'double' to vector type '__float2'
        float2 v = normalizedPoint * 0.5;
            ~~~~~~~~~~~~~~~ ^ ~~
```

![image](https://user-images.githubusercontent.com/519563/86043045-f6b25180-b9fc-11ea-88dd-70cd68448278.png)

OpenCL settings

![image](https://user-images.githubusercontent.com/519563/86043107-0c277b80-b9fd-11ea-8f54-9e40d9caec1a.png)

**Comment by buddhi1980** [comment]
Thanks for reporting this issue. I just corrected it (was easy and fast).

**Comment by gateway** [comment]
Sweet, any way to get a build or can I build this with xcode?

**Comment by buddhi1980** [comment]
Will be in few hours. I will give you a link tomorrow.

**Comment by buddhi1980** [comment]
Use this package for testing: https://1822-33041722-gh.circle-artifacts.com/0/~/mandelbulber2/build/artifacts/mandelbulber2-macOS-3e31ca3b70b7113b55c3a24d7f783b99e8efdc36.dmg

**Comment by gateway** [comment]
Works! Thank you.. btw any setting I can enable to use maybe 3/4s of the gpu so I can still do simple stuff on my mac? :) I have AMD RX 5700 XT with 8GB.  Also any combo fo gpu/cpu? thank you for fixing this.. will report more gpu issues as I see them if they come up!

**Comment by buddhi1980** [comment]
For GPU there is no way to control multitasking (like priorities for CPU). It will always use as much GPU as it is needed.

**Comment by gateway** [comment]
Thanks! ill just render at night! its nice to have the speed! cheers!

**Comment by gateway** [comment]
sorry to bug you.. but any chance we could get a updated ubuntu version.. i tried to compile it myself but fails on gamepad stuff.. I have version 2.21 while the mac one you built me is 2.2 and I used my ubuntu box for server rendering.

![image](https://user-images.githubusercontent.com/519563/86495776-98081300-bd2f-11ea-9f65-bf8ea8afe13f.png)

thoughts?

**Comment by buddhi1980** [comment]
I have replied in issue #792
