### ISSUE TITLE
/usr/bin/ld: cannot find -lQt5Gamepad Ubuntu 18

### ISSUE THREAD

**Issue by gateway** [buddhi1980/mandelbulber2#792]
##### System information (version)

- mandelbulber2 => 2.2.21
- Operating System / Platform => Ubuntu 18.x

##### Detailed description

Trying to compile the latest for Ubuntu 18, but keeps failing on .

```
iTools -lQt5Widgets -lQt5Multimedia -lQt5Gamepad -lQt5Gui -lQt5Network -lQt5Test -lQt5Core -lGL -lImath -lHalf -lIex -lIexMath -lIlmThread -lpthread -ltiff -lsndfile 
/usr/bin/ld: cannot find -lQt5Gamepad
collect2: error: ld returned 1 exit status
Makefile:2150: recipe for target 'mandelbulber2' failed
make: *** [mandelbulber2] Error 1

```
Any ideas, or how i can just compile w/o gamepad it seems optional

**Comment by buddhi1980** [comment]
Try to install  libqt5gamepad5-dev package and let me know if it works

**Comment by gateway** [comment]
```
(base) gateway@gateway-media:~/work/mandelbulber2/mandelbulber2/qmake$ sudo apt-get install libqt5gamepad5-dev
[sudo] password for gateway: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libqt5gamepad5-dev
```

Is their a way in to compile it w/o it? I really dont need it since im using this as a render server.

Cheers..

**Comment by buddhi1980** [comment]
From unknown reason you have this module partially installed in the system and qmake scrip sees this installed.
Go to mandelbulber/qmake folder 
delete (or comment out) following lines from ```common.pri``` file:
```
qtHaveModule(gamepad){
	QT += gamepad
	DEFINES += USE_GAMEPAD
	message("Use QtGamepad module")
}
```
run
```
make clean
qmake mandelbulber-opencl.pro
make
sudo make install
```

**Comment by buddhi1980** [comment]
Other way you can skip fighting with compilation from source and use AppImage package from daily builds: https://github.com/buddhi1980/mandelbulber2/releases/tag/continuous
It is already compiled and runs without any dependencies (it contains all libraries in the package)
