### ISSUE TITLE
Error: Error during compilation of OpenCL program

### ISSUE THREAD

**Issue by gateway** [buddhi1980/mandelbulber2#793]
##### System information (version)

- mandelbulber2 => 2.2
- Operating System / Platform => macOS Catalina

##### Detailed description

Tried example primitives001.fract with OpenCL enabled and it bailed out with this error.

```
Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
In file included from <program source>:53:
/Applications/mandelbulber2.app/opencl/engines/primitives.cl:211:34: error: call to '__cl_pow' is ambiguous
        float dist = LengthPow(pointDZ, pow(2.0, primitive->data.torus.tubeRadiusLPow))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4662:27: note: expanded from macro 'pow'
    #define pow(__x, __
```
![image](https://user-images.githubusercontent.com/519563/86502181-2fcc2800-bd55-11ea-894b-fff322d2cf0b.png)

**Comment by buddhi1980** [comment]
I'm very happy that you are testing the program deeply under OSX. Thanks a lot. OpenCL implementation on this system is different and only here these errors appear (under Windows and Linux these constants are automatically converted to single precision). I will fix this very soon.

**Comment by buddhi1980** [comment]
I found even more occurrences of double precision constants. All are corrected in commit https://github.com/buddhi1980/mandelbulber2/commit/20eaa470a8ddf781e4e1a15c9baf85c98be0a8b2

**Comment by gateway** [comment]
Sorry for the late reply! No Problem.. my main system is a mac and have been working on a project which I will turn into a 360 virtual tour where you can step inside some of the fractals people have made and ones I have.  Any chance to build this for Mac?  Also I use my 2 linux boxes as render nodes so if the version changes they need to match.. cheers! Ill keep plugging away.

**Comment by buddhi1980** [comment]
Just published new version of Mandelbulber. Fresh dmg file is here: https://github.com/buddhi1980/mandelbulber2/releases/tag/2.22
