### ISSUE TITLE
randomizer in animation dock

### ISSUE THREAD

**Issue by taurus66** [buddhi1980/mandelbulber2#797]
- mandelbulber2.22
win 10 64
##### Detailed description

I've an issue randomizing parameters in animation dock. The following randomizes In slight mode the included angles

- not at all, which is not a problem or
- somewhere around zero

especially gamma @ 32° is either untouched or destroyed to settings of +-2°. The same in medium and heavy randomization only stronger.
A quite special problem, but I've been waiting for this feature for quite some time, so I want to use. In this condition impossible.

##### Steps to reproduce

# Mandelbulber settings file
# version 2.22
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
ambient_occlusion_quality 10;
background_3_colors_enable false;
background_brightness 2,5;
background_color_1 0000 0000 0000;
bailout 16;
brightness 1,3;
camera 0,547572397632304 1,27927358555605 1,29884060735081;
camera_distance_to_target 1,59434836154903;
camera_rotation 148,827201640108 -34,7873718179426 3,35806371573278;
camera_top -0,344930463904733 -0,456995240516465 0,819864821306393;
contrast 1,4;
detail_level 2,4;
dont_add_c_constant_1 true;
fog_color_1 1300 1d00 2a00;
fog_color_2 2d00 3600 4200;
fog_color_3 4e00 5800 5e00;
formula_1 73;
formula_2 73;
formula_iterations_1 20;
formula_iterations_2 100;
frames_per_keyframe 15;
hdr true;
hybrid_fractal_enable true;
image_height 960;
image_proportion 3;
image_width 1440;
julia_c -0,59057836993267 0,202342571821498 0,0401737928603574;
julia_mode true;
keyframe_last_to_render 0;
limit_max 5 1,41378523456789 1,25;
limit_min -10 -5,72766899362268 -1,25;
limits_enabled true;
main_light_alpha 22,04;
main_light_beta 17,59;
main_light_intensity 0,9;
mat1_coloring_palette_offset 0,145;
mat1_coloring_speed 0,7;
mat1_fractal_coloring_algorithm 2;
mat1_fractal_coloring_i_start_value 10;
mat1_fractal_coloring_iter_add_scale 0,5;
mat1_fractal_coloring_iter_add_scale_enabled_true false;
mat1_fractal_coloring_iter_group_enabled_false true;
mat1_fractal_coloring_iter_scale 0,11;
mat1_fractal_coloring_iter_scale_enabled_false true;
mat1_fractal_coloring_orbit_trap_weight 1,2;
mat1_fractal_coloring_rad_weight 0,003907;
mat1_fractal_coloring_sphere_radius 0,5;
mat1_is_defined true;
mat1_specular 1;
mat1_specular_metallic 1;
mat1_specular_metallic_width 2;
mat1_specular_plastic_enable false;
mat1_specular_width 0,1;
mat1_surface_color_gradient 0 860000 908 c91600 1817 cf5213 2727 e7f38f 3635 94ffe5 4899 2e4b3d 5144 2e4b3d 6363 94ffe5 7271 e8f28f 8181 cf5213 9090 c91600;
N 125;
penetrating_lights false;
reflections_max 3;
smoothness 1,5;
target -0,130199534741149 0,15893907678024 0,389212939507045;
use_default_bailout false;
view_distance_max 39,9934197016334;
view_distance_min 1e-08;
volumetric_fog_colour_1_distance 0,129390929580717;
volumetric_fog_colour_2_distance 0,258781859161434;
volumetric_fog_density 0,608713087105624;
volumetric_fog_distance_factor 0,258781859161434;
volumetric_fog_distance_from_surface 1e-08;
volumetric_fog_enabled true;
[fractal_1]
mandelbox_folding_min_radius 0;
mandelbox_scale 1;
transf_addition_constant_111 0,985 0,985 1;
transf_minimum_radius_05 0;
transf_rotation 0 90 0;
[fractal_2]
mandelbox_folding_min_radius 0;
mandelbox_folding_value 4;
mandelbox_scale 1,2;
transf_addition_constant_111 1,5 1,5 1;
transf_rotation -2,980939 7,719664 32,549188;
[keyframes]
frame;main_camera_x;main_camera_y;main_camera_z;main_target_x;main_target_y;main_target_z;main_camera_top_x;main_camera_top_y;main_camera_top_z;fractal1_transf_rotation_x;fractal1_transf_rotation_y;fractal1_transf_rotation_z;main_julia_c_x;main_julia_c_y;main_julia_c_z
0;0,547572397632304;1,27927358555605;1,29884060735081;-0,130199534741149;0,15893907678024;0,389212939507045;-0,344930463904733;-0,456995240516465;0,819864821306393;-2,980939;7,719664;32,549188;-0,59057836993267;0,202342571821498;0,0401737928603574
interpolation;morphAkima;morphAkima;morphAkima;morphCatMullRomAngle;morphCatMullRom

**Comment by buddhi1980** [comment]
Just fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/a3f8300f9f4471b44d5ce818dc097a9d6f74dee6
