### ISSUE TITLE
error medium mode   openCL win64

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#799]
Error: Error during compilation of OpenCL program
Device #0
OpenCL Build log:
<kernel>:617:41: error: too few arguments to function call, expected 9, have 8
                                        &specular, &iridescence, &gradients);
                                                                           ^
C:\Users\graeme\Downloads\mandelbulber-Release-x64-31c5cc943e5dc68344d1f1f6e32258876cbc2fc3\build-win\Release\x64\opencl\engines\shader_object.cl:35:1: note: 'ObjectShader' declared here
float3 ObjectShader(__constant sClInConstants *cons

# Mandelbulber settings file
# version 2.23
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
basic_fog_color d900 ea00 e600;
basic_fog_visibility 6.73911190032959;
camera -7.33457722731322 -24.3980072791544 2.80179451704925;
camera_distance_to_target 2.010848286363;
camera_rotation -29.7839844042899 1.52701155885121 -4.0711099922733e-13;
camera_top -0.0132370093037287 -0.023128109564315 0.999644873008747;
constant_DE_threshold true;
DE_factor 0.5;
DE_thresh 0.000270000646584642;
flight_last_to_render 0;
formula_1 206;
formula_2 603;
formula_iterations_1 33;
formula_stop_iteration_2 49;
glow_enabled false;
hdr true;
hybrid_fractal_enable true;
image_proportion 3;
image_width 900;
julia_c 0 0 -1.9686215498225;
keyframe_last_to_render 0;
mat1_is_defined true;
mat1_specular_gradient 0 fd6029 1000 698403 1941 f5bd22 3000 f5bd22 4000 f5bd22 5000 aa0000 6000 005500 7009 aa0000 8000 d4ffd4 9000 aba53c;
mat1_specular_gradient_enable true;
mat1_surface_color_gradient 0 fd6029 1000 698403 1941 f5bd22 3000 f5bd22 4000 f5bd22 5000 aa0000 6000 005500 7009 aa0000 8000 d4ffd4 9000 aba53c;
mat2_is_defined true;
mat2_reflectance 0.8;
mat2_rough_surface true;
mat2_specular 1;
mat2_specular_metallic 1.7;
mat2_specular_metallic_roughness 0.8;
mat2_specular_metallic_width 0.8;
mat2_specular_plastic_enable false;
mat2_surface_color b600 a800 ae00;
mat2_surface_color_gradient 0 9418bb 1138 424857 5000 ad8484 8102 3f504a;
mat2_surface_roughness 0.02;
mat2_use_colors_from_palette false;
N 46;
repeat_from 2;
target -6.33608050300193 -22.653403108408 2.85538005355642;
volumetric_fog_colour_1_distance 0.253750487655379;
volumetric_fog_colour_2_distance 0.507500975310759;
volumetric_fog_distance_factor 0.507500975310759;
volumetric_fog_enabled true;
[fractal_1]
analyticDE_enabled_false true;
analyticDE_offset_0 0.0125;
analyticDE_offset_1 0;
mandelbox_folding_fixed_radius 0.9;
mandelbox_folding_min_radius 0;
mandelbox_scale 1;
transf_addCpixel_enabled false;
transf_addition_constant 0 0 -2.1;
transf_constant_multiplier_000 0.7 -0.7 -4.3;
transf_function_enabledAx_false true;
transf_maxR2_1 0.9;
transf_minR2_p25 0;
transf_offset 0.8;
transf_scale_0 2.1;
transf_scale_2 1;
transf_scale_vary_0 0.1;
transf_scaleB_1 0.4;
[fractal_2]
transf_addition_constantA_000 0 0 0.5;
transf_constant_multiplierA_111 1.5 1 1;
transf_function_enabledCy_false true;
transf_function_enabledx false;
transf_offset_000 -0.7 0 0;
transf_offset_001 0 0 1.1;
transf_offset_1 2.7;
transf_offset_1105 2 0.9 0.5;
transf_offset_111 2.1 1.85 0.8;
transf_offset_222 2.4 2 3.3;
transf_radius_1 0.9;
transf_scale_025 0.15;
transf_scale_2 1.8;
transf_scale_3 2.5;
transf_stop_iterations_1 20;
transf_stop_iterations_C1 24;

**Comment by buddhi1980** [comment]
Fixed
