### ISSUE TITLE
Randomizer crashes MDBB if 'select' button pushed

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#800]
MDBB 2.23-dev
Ubuntu Linux.

MDBB crashes with Randomizer if the first button pushed is a 'Select' button (nothing else was changed).

BTW. Nice addition to Mandelbulber.

**Comment by mclarekin** [comment]
Thanks it is reproducible in Win64 openCL. If i accidently click on a "select" button before choosing slight, medium or heavy, program crashes to desktop.

**Comment by buddhi1980** [comment]
Fixed
