### ISSUE TITLE
Depth buffer state not passed to network clients?

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#805]
A picture tells a thousand words. 1 rig is a third as fast as the other.
![whatswrong](https://user-images.githubusercontent.com/860491/92391823-38562b80-f115-11ea-85c6-94f7f0400be9.PNG)

**Comment by buddhi1980** [comment]
Probably you mean that configuration of z-buffer is not passed to network clients. I will check what is wrong.

**Comment by buddhi1980** [comment]
Problem fixed
