### ISSUE TITLE
Selecting HDR disables Auto Refresh

### ISSUE THREAD

**Issue by GuidoBartoli** [buddhi1980/mandelbulber2#811]
##### System information (version)
- mandelbulber2 => 2.22 (AppImage)
- Operating System / Platform => Linux Mint 20 (64 bit)

##### Detailed description
When HDR is selected, the auto-refresh option is disabled and needs to be manually re-enabled.

##### Steps to reproduce
1. Load an example fractal
1. Enable Auto-Refresh in the Navigation panel
1. Enable High Dynamic Range (HDR) in Image Adjustment
1. Auto-Refresh becomes disabled

**Comment by buddhi1980** [comment]
Auto-refresh is disabled, because enabling/disabling of HDR, changes of image brightness, saturation and gamma can be done after rendering of image is finished. Then you can adjust image and click Apply without repeated rendering of image.

**Comment by GuidoBartoli** [comment]
Ah ok, did not know about that... thanks for pointing it out! :)
