### ISSUE TITLE
Textures don't move properly on repeats

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#812]
##### System information (version)

- mandelbulber2 => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
Textures do not map properly to repeated sections of fractals. When you globally rotate the fractal, the main fractal's texture rotates correctly, but the repeated sections do not move with their fractals correctly. I've also noticed this in Boolean mode, when globally rotating the scene and the individual formula textures.

**Comment by buddhi1980** [comment]
Fixed. Now textures looks properly when objects are repeated

**Comment by paigan0** [comment]
I will try it out later today and report back. That's excellent news! Good
job!
