### ISSUE TITLE
file path to toolbar

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#813]
In preferences add default file path 

 C:\Users\graeme\mandelbulber\toolbar

 can then send folders to people to view contents as  toolbar preset thumbnails
can change it to C:\Users\graeme\mandelbulber\undo   to look backwards easier

**Comment by mclarekin** [comment]
i have been thinking :)
 alternative is to open a window  where there is a filepath to a  folder of settings, that can be rendered at a user defined resolution.  
 
additional possible options to use fast medium or full

ideally with any expensive effects disabled

**Comment by mclarekin** [comment]
initial idea of just being able to  tempoararily change directory filepath i think is best for now

**Comment by buddhi1980** [comment]
I just started adding option to change toolbar path

**Comment by buddhi1980** [comment]
Done. @mclarekin test if it is what you wanted

**Comment by mclarekin** [comment]
yep,  loaded  grid3 examples, then loaded undo folder, then changed back to toolbar folder. All working as expected. Thanks
