### ISSUE TITLE
Redundant data folder upgrade dialog on very first start

### ISSUE THREAD

**Issue by baryluk** [buddhi1980/mandelbulber2#815]
##### System information (version)
- mandelbulber2 => 2.10
- Operating System / Platform => Debian Linux, amd64

##### Detailed description

When I start mandelbulber2 for the very first time just after installing.

It shows me the dialog ("Data folder upgrade") that a data format in 2.10 changed.

##### Steps to reproduce

Remove all configs / data, start mandelbulber.

##### Expected behaviour

No upgrade dialog is presented if there is nothing to upgrade.

**Comment by buddhi1980** [comment]
Fixed.
