### ISSUE TITLE
image save thread

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#82]
move saving of image to own thread and show status of saving in progress bar (if image save lib supports update)
any cimage bufffer manipulation has to be blocked, before saving is finished.

**Comment by zebastian** [comment]
this could look something like this in files cpp:

```
void startSaving(cImage *image, enumImageFileType imageFileType)
{
	QThread *thread = new QThread; //deleted by deleteLater()
	cFileImage fileImage = new cFileImage(image, imageFileType);
	fileImage->moveToThread(thread);
	fileImage->setObjectName("fileImage");
	QObject::connect(thread, SIGNAL(started()), fileImage, SLOT(slotSaveImage()));
	QObject::connect(fileImage, SIGNAL(finished()), fileImage, SLOT(deleteLater()));
	if(gMainInterface->mainWindow){
		QObject::connect(fileImage, SIGNAL(updateProgressAndStatus(QString, QString, double)),
			gMainInterface->mainWindow, SLOT(slotUpdateProgressAndStatus(QString, QString, double)));
	}
	if(gMainInterface->headless){
		QObject::connect(fileImage, SIGNAL(updateProgressAndStatus(QString, QString, double)),
			gMainInterface->headless, SLOT(slotUpdateProgressAndStatus(QString, QString, double)));
	}
	QObject::connect(fileImage, SIGNAL(finished()), thread, SLOT(quit()));
	QObject::connect(thread, SIGNAL(finished()), thread, SLOT(deleteLater()));
	thread->setObjectName("Saving Image");
	thread->start();
}
```

**Comment by buddhi1980** [comment]
I would be careful with this solution. It is possible that during saving of image, the image can be modified by rendering thread.

**Comment by zebastian** [comment]
Yes, probably best would be
On Start save: disable whole GUI
In save thread finished: enable again
The only benefit woulb be to See the progress of saving and not freezing the gui

**Comment by buddhi1980** [comment]
The same effect we can get without creating new thread. If you find any way to save image line by line to get actual progress percentage, then you can call processEvents and updateProgress

**Comment by zebastian** [comment]
yes, but i feel processEvents is a bad workaround for a non trivial task that takes some time and locks certain resources.
even if the capsulation and threading of the saving is not necessary right now, this will make the code clearer. in regards to the growing image save system (new file formats, new saved resources like surface normals).

**Comment by zebastian** [comment]
image saving is now completely contained in file_image and broadcasts its status.
This solves this issue sufficiently
