### ISSUE TITLE
2.25 hangs up when you launch another instance

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#827]
##### System information (version)

- mandelbulber2 => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

https://github.com/buddhi1980/mandelbulber2/commit/6066fecbd8c606cf234e6df2078b96f157327d0f

When you launch another instance of MDBB when the first is rendering, both instances of the program will hang up and have to be force killed and restarted.

**Comment by buddhi1980** [comment]
I have just launched 4 instances of Mandelbulber and all rendered simultaneously (on Windows 10). I have no idea what could be wrong on your PC.

**Comment by paigan0** [comment]
I have sent your gmail a video of it. It is easily reproducible and happens
every time. You have to be rendering an animation, I think. But the second
Mandelbulber never opens and the first hangs up and stops working.
 2021-02-15 11-33-08.mp4
<https://drive.google.com/file/d/1IzmXIcwDL73oy5K_OI7KErhqWLIwOk7M/view?usp=drive_web>

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
