### ISSUE TITLE
Not working on MacOS 11,1 with a M1 chip.

### ISSUE THREAD

**Issue by Rihan96** [buddhi1980/mandelbulber2#829]
##### System information (version)
- mandelbulber2 => 2.24
- Operating System / Platform =>MacOS 11,1 MacBook Air (M1, 2020)

The last release of Mandelbulber2 doesn't launch on my MacbookAir 2020 with MacOS 11,1 (M1 Chip).

Could someone help me ?

Thanks !

**Comment by Rihan96** [comment]
Link to the Apple crash report : https://pastebin.com/xkyxe2Uu

**Comment by anotherfucker** [comment]
> ##### System information (version)
> * mandelbulber2 => 2.24
> * Operating System / Platform =>MacOS 11,1 MacBook Air (M1, 2020)
> 
> The last release of Mandelbulber2 doesn't launch on my MacbookAir 2020 with MacOS 11,1 (M1 Chip).
> 
> Could someone help me ?
> 
> Thanks !

I've had to use 2.23 to for Apple Silicon.  Many crashes. Haven't been able to get 2.24 to even open despite permissions being set and going through the usual. Eager to see suggestions and see this worked out myself.
have a nice day

**Comment by buddhi1980** [comment]
Did you tried with version 2.24 or 2.24-1? Version 2.24-1 includes patch which solved this problem.
Download link: https://github.com/buddhi1980/mandelbulber2/releases/download/2.24/mandelbulber2-macOS-2.24-1.dmg

**Comment by anotherfucker** [comment]
> Did you tried with version 2.24 or 2.24-1? Version 2.24-1 includes patch which solved this problem.
> Download link: https://github.com/buddhi1980/mandelbulber2/releases/download/2.24/mandelbulber2-macOS-2.24-1.dmg

thank you for your reply. initial attempt negative.

**Comment by networkpanic** [comment]
future tracking in #837
