### ISSUE TITLE
Can we pay for you to create a function?

### ISSUE THREAD

**Issue by SpotBR** [buddhi1980/mandelbulber2#831]
I would like that you create a tool to generate beautiful and perfect animations keyframes? Can i pay you to do it?

##### System information (version)

- mandelbulber2 => v2 2.24
- Operating System / Platform => Linux and Windows
- Compiler => :grey_question:

**Comment by mclarekin** [comment]
possibly
explain what you require

**Comment by SpotBR** [comment]
It is very simple today to make a beautiful fractal with a few clicks and render it in 4k. But making a long animation in these 4k is really complicated because you have to spend hours in flight animation if you want it to be a long animation with many frames.

If there was an intelligent code that auto generated a quality flight animation that would not disappoint the viewer, that would be great for me.

A quality animation strolls through the fractals, without colliding with its walls. Good animation would need to enter them, without losing the symmetry of their flights. Quality animation would open up the possibility to work even on fractals that change in real time. Perhaps it would be good if it worked by seed to try out varieties.

I would love to pay for it.

My final product is a great 10 hour animation in 4k.

**Comment by SpotBR** [comment]
So we could have great jobs without having to configure the application for a long time

**Comment by mclarekin** [comment]
Hmmm?? so you would like the program to automatically create, from a variable seed, flightpaths and test for ones that do not collide with the surface??   That is likely to take a VERY long time to compute, in respect to the near infinite possible flightpaths. Even with a set of user input rules to reduce the possibilities, it would still take along time.
What is slightly more feasible is to automatically adjust a given flightpath to remove collisions, this would require interrogating the 3D space around collisions and an iterative process of adjusting and retesting the flightpath. 

But maybe i am not understanding what you are asking for?

**Comment by SpotBR** [comment]
When I talked about seed, I meant being able to have several possibilities of movement, but not necessarily using the seed to find movement without collision ... I believe that in order to avoid collisions, you would have to use trigonometry against the fractal walls. To find the center of the deepest entrances or something ...

Perhaps, from where the camera starts, choose between several holes of the fractal to enter, the hole that is deeper ... The idea of the seed would be just to have more then one animation for every fractal.

Maybe the seed idea was a mistake.

**Comment by mclarekin** [comment]
BTW Keyframe Animation has a Validate option where it detects and lists all frames where there are collisions. A Flight Animation can be imported into Keyframe Animation and then validated.

Anyway i get what you are saying  _

define camera position and direction to target
program chooses a hole within FOV
navigate to the center of the hole
look for another hole
navigate to center
repeat  

eventually Validate to check that the cubic interpolation (akima or catmul_rom) between Keyframe(KF) positions does not create any collisions. (a  cubic interpolations between  KF6 and KF7 uses keyframe data from KF4, KF5, KF6, KF7, KF8 & KF9). So if you change KF7 it effects all frames from KF4 to KF10 ( from memory?? it has been a few years since i last had to think about this. I always used Keyframe Animation and validated).

Hmmm??  I think automating would be difficult and maybe slower than  trialling low resolution camera paths manually 

@buddhi1980.  Krzysztof,  any thoughts??

**Comment by SpotBR** [comment]
Do you think an automation like this would be slower even for those who need 10 hours of frames?

A possible idea maybe if you take the difference of all occupied space of fractal geometry, and work on the geometry of unoccupied space, to avoid collision logic.

**Comment by buddhi1980** [comment]
Few years ago I had some thinking about this kind of solution. It was about automatic control of flight path based on distance from fractal objects. It is challenging to write code which will look for the path joining two points in 3D space through the fractal shapes.
Maybe I will return to this topic in the future, but now there are completely different priorities. Even if you pay, it will not increase amount of time which I have for coding (during my free time after regular job).

**Comment by SpotBR** [comment]
@mclarekin and you?

**Comment by SpotBR** [comment]
So can i pay to you add OpenCL NetRender support?

**Comment by mclarekin** [comment]
I cannot implement automatic flightpath without a huge learning curve, as i do not work in that area of the code

OPenCL net rendering is already implemented, but all cards have to be of the  same manufacturer, ie all nVidia or all AMD.

you can support us with patreon

https://www.patreon.com/krzysztofmarczak

**Comment by mclarekin** [comment]
RE- netrendering, there are a few users that do this. Stephen Sink  at the Mandelbulber facebook group is good for advice, he has maybe 8 cards in his render farm  for making video animations

**Comment by SpotBR** [comment]
Is there a way for me to see some kind of LOG in case my netrender is not working with OpenCL?

**Comment by mclarekin** [comment]
is it not rendering?  did you control click each card (page 7 of manual)

**Comment by buddhi1980** [comment]
NetRender with OpenCL only works when animation is rendered
