### ISSUE TITLE
I create Flatpak package for mandelbulber

### ISSUE THREAD

**Issue by kevinsmia1939** [buddhi1980/mandelbulber2#832]
Hi,

I create Flatpak for mandelbulber, I would like to submit it to Flathub, what do you think?
https://github.com/kevinsmia1939/flathub/tree/com.github.buddhi1980.mandelbulber

Thanks

**Comment by buddhi1980** [comment]
Can I find somewhere this package or full list of files from package? I would like to see if directory structure is complete or what is wrong.

**Comment by buddhi1980** [comment]
It would help if you paste here console output produced by running of mandelbulber2
I have found one error in your script. From which directory did you launched the program?

**Comment by kevinsmia1939** [comment]
Hi,

Flathub need an icon 128x128, I see that there are only 256x256 in deploy/share/mandelbulber2/icons/.
Could you add the 128x128 icon?

**Comment by mclarekin** [comment]
@buddhi1980  i have added this, hope it is OK

**Comment by buddhi1980** [comment]
@mclarekin Thanks for adding this icon.

**Comment by kevinsmia1939** [comment]
> @buddhi1980 i have added this, hope it is OK

Hi,
How do I go about installing this new icon?

**Comment by kevinsmia1939** [comment]
Or should I install Mandelbubler with cmake instead?

**Comment by buddhi1980** [comment]
install -Dm0644 mandelbulber2/deploy/share/mandelbulber2/icons/mandelbulber128.png app/share/pixmaps/mandelbulber.png

**Comment by kevinsmia1939** [comment]
@buddhi1980 
Hi,
Is the name of this software Mandelbulber or Mandelbulber2 ?

**Comment by mclarekin** [comment]
Mandelbulber2

**Comment by kevinsmia1939** [comment]
Thanks @buddhi1980  and @mclarekin 
Do you have any screenshots that you want to be display in the store front?

**Comment by buddhi1980** [comment]
Use one which is on Github page: https://github.com/buddhi1980/mandelbulber2

**Comment by buddhi1980** [comment]
Do you need more screenshots?

**Comment by kevinsmia1939** [comment]
> Do you need more screenshots?

Thanks, but I already add them. 
There is no need to add more screenshots specifically, but it would be better if you show case some awesome features that you want to show off in the screenshots.

**Comment by kevinsmia1939** [comment]
Mandelbubler added to Flathub!!

https://flathub.org/apps/details/com.github.buddhi1980.mandelbulber2

**Comment by buddhi1980** [comment]
Thanks a lot. I will test it next week.
