### ISSUE TITLE
Req: Disable Use of CPU Code in Randomiser

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#834]
As title says. If frame reqs cpu code respin that frame.

**Comment by buddhi1980** [comment]
I understand what you mean. It is a good idea.

**Comment by buddhi1980** [comment]
It was quick to implement, so it was just done in commit https://github.com/buddhi1980/mandelbulber2/commit/3a68a70a0af74e14301ac17b2797c1de65aa2163
