### ISSUE TITLE
add unit testing of common regions

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#84]
unit testing could help to fast identify problems on new systems or on changes in the code.
Can also be used with a CI to check the codebase.
also could be interesting to use a monkey (random input) to find timing issues.

qt has a prebuild framework for that:
http://doc.qt.io/qt-5/qtest-overview.html

**Comment by zebastian** [comment]
started unit testing, more tests to come...

**Comment by buddhi1980** [comment]
Can we close this?

**Comment by zebastian** [comment]
no not yet, i will work in this issue the next couple of months and add more tests, so its good to have it as a reminder

**Comment by buddhi1980** [comment]
Actual set of tests is enough for now. I would close this issue.
