### ISSUE TITLE
OpenCL error on Ubuntu

### ISSUE THREAD

**Issue by YossiCohen** [buddhi1980/mandelbulber2#840]
##### System information (version)
- mandelbulber2 => 2.25 (appimage)
- Operating System / Platform => Ubuntu 20.04 and a GTX 1080 card.
- Compiler => :appimage:

##### Detailed description
When I Checking the "OpenCL enable" check box I get this error:
Error: There are no valid OpenCl platforms in the system

looking in the log file I can see this:
........
PID: 2943182, time: 46.614194234, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 46.633674055, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 49.326428377, Critical: OpenCl ERROR:  "cl::Platform::get"  ( -1 ) (../src/opencl_hardware.cpp:378, static bool cOpenClHardware::checkErr(cl_int, QString)
PID: 2943182, time: 49.326870462, Error: There are no valid OpenCl platforms in the system
PID: 2943182, time: 49.330153453, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 49.331770670, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 49.333404247, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 51.778677323, Critical: OpenCl is not available (../src/opencl_hardware.cpp:254, void cOpenClHardware::CreateContext(int, cOpenClDevice::enumOpenClDeviceType)
PID: 2943182, time: 56.226017873, Debug: XmbTextListToTextProperty result code -2
PID: 2943182, time: 56.227894025, Debug: XmbTextListToTextProperty result code -2
.......

**Comment by buddhi1980** [comment]
If you try version 2.24, do you observe the same problem?

**Comment by YossiCohen** [comment]
Thanks for the prompt response,
I've downloaded this release:
_Mandelbulber_v2-2.24-x86_64.appimage_

and I get the same error, this is what the console show:
> Debug: XmbTextListToTextProperty result code -2
> Critical: OpenCl ERROR:  "cl::Platform::get"  ( -1 )
> (../src/opencl_hardware.cpp:344, static bool cOpenClHardware::checkErr(cl_int, QString))
> 
> Error: There are no valid OpenCl platforms in the system
> Debug: XmbTextListToTextProperty result code -2
> Debug: XmbTextListToTextProperty result code -2
> 

Is there any prerequisite software that needs to be installed on the machine?
I am using Blender on the machine and it works fine with the GPU (Cuda)

BTW, It also happened when I've installed Mandelbulber2 from: dl.flathub.org via the Ubuntu Software center (like app store)
it was version 2.24

**Comment by YossiCohen** [comment]
Is there any prerequisite software that needs to be installed on the machine?

**Comment by buddhi1980** [comment]
You need to install GFX driver with OpenCL support like nvidia-opencl

**Comment by buddhi1980** [comment]
You can try to install ocl-icd-libopencl1
Here is instruction how to install nvidia driver: https://www.kali.org/docs/general-use/install-nvidia-drivers-on-kali-linux/

**Comment by networkpanic** [comment]
install opencl following your distro documentation.
