### ISSUE TITLE
Ability to export flight video

### ISSUE THREAD

**Issue by jcestep** [buddhi1980/mandelbulber2#841]
Please allow flights to be exported as video files.

##### System information (version)

N/A

##### Detailed description

Please modify the flight video player to allow a video to be exported as a video file.

Apologies if this is a duplicate issue.  I'm sure I'm not the first to ask for this.

Apologies if this is already possible.

##### Steps to reproduce

1. Create a flight
2. View the video of the flight.
3. Attempt to save the video to share outside the program.

**Comment by jcestep** [comment]
I would donate to help pay for this.

**Comment by mclarekin** [comment]
people convert the folder of frames to a video using external software of
their choice, like VirtualDub, blender etc'
These external software have a lot of options that would probably be too
much to add to Mandelbulber which is primarily a fractal renderer.
However it may be possible to incorporate a ffmpeg function (which can
already be run as a single command line outside Mandelbulber)

This issue will  bev best answered by Krzysztof (buddhi1980)

**Comment by jcestep** [comment]
Thank you.

**Comment by networkpanic** [comment]
implementing this in mandelbulber isnt planned

i suggest taking a look into ffmpeg
https://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/
