### ISSUE TITLE
2.25 incompatible to saved files?

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#842]
Is Mandelbulber 2.25 incompatible to saved files?
Any chance for some kind of "compatibility layer" for backward compatibility in future releases?

![MB25_Incompatibility](https://user-images.githubusercontent.com/29848666/117385464-77778f00-aee5-11eb-89dd-d26464a363d5.png)

##### System information (version)

- mandelbulber2 => 2.26_dev (build today)
- Operating System / Platform => Ubuntu Mate

##### Detailed description
Can't open many .fract-files anymore, see screenshot

##### Steps to reproduce
Just install 2.25 or later and open some saved .fract-files

**Comment by mclarekin** [comment]
did you create the settings file with a 2.25 dev version before backwards compatibility was implemented?
post your settings file and we can have a look

**Comment by michas0602** [comment]
Solved as most files work, only some (or one?) dev version were affected.
