### ISSUE TITLE
Move fractal formula icons out of qrc file

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#85]
Compilation of actual qrc file takes quite a lot time and consumes a lot of memory. I think would be better to load that icons directly from png files instead of resources (qrc file).

**Comment by zebastian** [comment]
or we can split the qrc file into:
formula_and_transform_images.qrc
tooltips_images.qrc
icons.qrc

**Comment by buddhi1980** [comment]
What if we have 1000 formulas? Then it consume 10GB to compile qrc file :)
It's not urgent change, but I would do this in 2.08 or 2.09
