### ISSUE TITLE
Compile Issue Ubuntu 20.04

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#856]
Using 'prepare_for_dev_ubuntu.sh' to build Mandelbulber 2.26 gives this error. Looks like a typo in data.cpp.
__________________________________________________________________
../src/system_data.cpp: In member function ‘QString sSystem::GetIniFile() const’:
../src/system_data.cpp:48:23: error: ‘round’ was not declared in this scope; did you mean ‘qBound’?
   48 |  int versionInt = int(round(version * 100));
      |                       ^~~~~
      |                       qBound
make: *** [Makefile:7047: system_data.o] Error 1
___________________________________________________________________

**Comment by TasMania17** [comment]
Thanks buddhi you fixed it :)

**Comment by buddhi1980** [comment]
@mclarekin fixed it.
