### ISSUE TITLE
v2.07 crashes on win64/win32 if sub-menu in "View" is de-selected.

### ISSUE THREAD

**Issue by rconcept** [buddhi1980/mandelbulber2#86]
Hi,
Small problem on version 2.07:
Mandelbulber2 crashes if a sub-menu of 'View' is de-selected.
Tested on Windows 7 x64, all versions (win64 & win32), standalone binaries and setup have the problem.

**Comment by buddhi1980** [comment]
Bug fixed. Now I need to repackage the program and release everything again. It's quite critical bug.

**Comment by rconcept** [comment]
Thank you for fixing it!
