### ISSUE TITLE
Issue Using AppImage for NetRender (Client)

### ISSUE THREAD

**Issue by austin-millan** [buddhi1980/mandelbulber2#860]
##### System information (version)

- mandelbulber2 => 2.25 (AppImage)
- Operating System / Platform => Linux 64bit (Ubuntu)

NOTE: compiler used as workaround to this issue

##### Detailed description

I am unable use the above system as a `Client` node for the NetRender functionality from the distributed appimage v2.25 (found [here](https://github.com/buddhi1980/mandelbulber2/releases/download/2.25/Mandelbulber_v2-2.25-x86_64.appimage)).

The following error occurs when jobs are sent to `Client` node:

```
$ Mandelbulber_v2-2.25-x86_64.appimage --stats --host 192.168.2.44 --port 5555
Detected 12 CPUs
Mandelbulber 2.25-dev
Log file name: /home/austinm/.mandelbulber_log.txt
Program data files directory /tmp/.mount_Mandelq7rdxS/usr/share/mandelbulber2/
Default data hidden directory: /home/austinm/.mandelbulber/
Default data public directory: /home/austinm/mandelbulber/
Settings file: /home/austinm/.mandelbulber/mandelbulber_225.ini
NetRender - Client Setup, link to server: 192.168.2.44, port: 5555 
NetRender - version matches (2250)
NetRender - Connection established, Server is 192.168.2.44:5555 [DESKTOP-HTMBKBU]
Warning: GetVarType(): element ' "all_lights_intensity" ' doesn't exists
(../src/parameters.cpp:503, parameterContainer::enumVarType cParameterContainer::GetVarType(QString) const)

Warning: GetVarType(): element ' "all_lights_size" ' doesn't exists
(../src/parameters.cpp:503, parameterContainer::enumVarType cParameterContainer::GetVarType(QString) const)

Warning: GetVarType(): element ' "all_lights_visibility" ' doesn't exists
(../src/parameters.cpp:503, parameterContainer::enumVarType cParameterContainer::GetVarType(QString) const)

Warning: GetVarType(): element ' "transf_scale_1p1" ' doesn't exists
(../src/parameters.cpp:503, parameterContainer::enumVarType cParameterContainer::GetVarType(QString) const)
```

After the warning logs nothing is rendered by `Client`. It remains connected to the `Server`, but subsequent render attempts fail with 0 renders sent to the `Server`, and Server displays 0 for the number of frames received from this client.

##### Steps to reproduce

1. On Client:
  1a. Download [appimage](https://github.com/buddhi1980/mandelbulber2/releases/download/2.25/Mandelbulber_v2-2.25-x86_64.appimage)
  1b. Make it executable.
  1c. Run mandelbulber2 as a client in NetRender mode, connecting to an existing server (e.g. `Mandelbulber_v2-2.25-x86_64.appimage --stats --host 192.168.2.44 --port 5555`)
2. On Server:
  2a. Ensure NetRender feature is started as server
  3a. Add 1 keyframe
  3b. Render animation (pushing work to client)

The above steps reproduce the issue on my machine. It made no noticeable difference if OpenCL is disabled.

The workaround is to compile mandelbulber2 from source (using [release](https://github.com/buddhi1980/mandelbulber2/releases/download/2.25/mandelbulber2-2.25.tar.gz))

When using the binary built locally everything works as expected.

Happy to do further testing/investigation if you have specific questions.

**Comment by buddhi1980** [comment]
I see that you use 2.25-dev for testing. It was development version of Mandelbulber, and could be not stable and has some critical bugs. Have you tried the same with stable version of the program (https://github.com/buddhi1980/mandelbulber2/releases/tag/2.25) or actual development version, which is already stable (https://github.com/buddhi1980/mandelbulber2/releases/tag/continuous)?
Remember to have the same version of the program on server and client side.

**Comment by austin-millan** [comment]
Thanks for getting back to me @buddhi1980, but I am unsure how this is a dev version. I downloaded from release 2.25 page: 
- https://github.com/buddhi1980/mandelbulber2/releases/tag/2.25

Basically it looks like included AppImage shows "dev" but all the other release files/zips show expected stable version of 2.25.

## AppImage (Linux)

```bash
$ wget https://github.com/buddhi1980/mandelbulber2/releases/download/2.25/Mandelbulber_v2-2.25-x86_64.appimage
--2021-08-03 08:18:00--  https://github.com/buddhi1980/mandelbulber2/releases/download/2.25/Mandelbulber_v2-2.25-x86_64.appimage
...
2021-08-03 08:18:03 (50.9 MB/s) - ‘Mandelbulber_v2-2.25-x86_64.appimage’ saved [127578152/127578152
$ chmod +x Mandelbulber_v2-2.25-x86_64.appimage
$ ./Mandelbulber_v2-2.25-x86_64.appimage --version
Detected 12 CPUs
Mandelbulber 2.25-dev
Log file name: /home/austinm/.mandelbulber_log.txt
Program data files directory /tmp/.mount_MandelxYioO9/usr/share/mandelbulber2/
Default data hidden directory: /home/austinm/.mandelbulber/
Default data public directory: /home/austinm/mandelbulber/
Mandelbulber 2.25-dev
```

## Built From Source (Linux)


```bash
mandelbulber2 --version
Detected 12 CPUs
Mandelbulber 2.25
Log file name: /home/austinm/.mandelbulber_log.txt
Program data files directory /usr/share/mandelbulber2/
Default data hidden directory: /home/austinm/.mandelbulber/
Default data public directory: /home/austinm/mandelbulber/
Mandelbulber 2.25

```

## Windows Installer (Windows)

I used the same release (2.25) on my Windows and it shows expected results (no dev):

```bash
"C:\Program Files\Mandelbulber2\mandelbulber2.exe" --version
Detected 16 CPUs
Mandelbulber 2.25
Log file name: C:\Users\austi\mandelbulber_log.txt
Program data files directory C:\Users\austi\
Default data hidden directory: C:\Users\austi\mandelbulber\
Default data public directory: C:\Users\austi\mandelbulber\
Mandelbulber 2.25
```

**Comment by buddhi1980** [comment]
Holy moly! I have no idea why Appimage doesn't contain the most recent version of 2.25. That time there was transition of TravisCI.org to TravisCI.com. Maybe building of Appimages was frozen for some time. This package contains build from Mar 19, 2021 instead of April 21!
By the way now I'm going to test (for sure) if NetRender works properly in headless mode in current dev build.

**Comment by buddhi1980** [comment]
In 2.26-dev it works from AppImage
![image](https://user-images.githubusercontent.com/11696990/128058564-46d41876-0fa2-4fd3-b47a-f53bbb165a40.png)

**Comment by austin-millan** [comment]
My Client uses Windows so seems like my current option is to simply use the non-AppImage options for Linux servers and wait until 2.26 for a Windows installer?

But if actual (stable) 2.25 AppImage works better than 2.25-dev it might make sense to upload the AppImage artifact to 2.25 release page.

**Comment by buddhi1980** [comment]
You can download fresh Windows installer (v2.26) from https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/job/s7t8xtmfan5bn2ua/artifacts

Unfortunately I don't have correct 2.25 Appimage file. This which I have on my PC is also wrong. This is the reason why I now recommend to use Applmage in version 2.26-dev. 

I will try to rebuild AppImage for 2.25 (fortunately I have branch on GitHub)

**Comment by buddhi1980** [comment]
AppImage packages for version 2.25 updated on Github and SourceForge.
Thanks a lot for pointing out this problem.

**Comment by austin-millan** [comment]
I will test if this new AppImage works w/ NetRender tonight. Closing for now. Thank you for your help!
