### ISSUE TITLE
Request: separate thread for saving files?

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#862]
Hi, just a thought:
Ive seen when rendering many images / a video, it takes around 1-2 seconds (sometimes more depending on file format) for every image to save.
So wouldn´t it be possible to outsource the save-process (or all hd activities?) to a different thread somehow to make the save-process running in parallel / background? 

Its not very important, but if easy to realize it could save some time for users who are creating videos often.

**Comment by buddhi1980** [comment]
It would be possible to implement, but I'm hesitating, because the program for a while will require about double amount of RAM

**Comment by buddhi1980** [comment]
I have just implemented saving of image frames by separate CPU thread.
