### ISSUE TITLE
Request: Save "first and last frame to render" to file, too

### ISSUE THREAD

**Issue by michas0602** [buddhi1980/mandelbulber2#863]
When I am not completely wrong, first and last frame to render in the animation tab is not saved to .fract-file.
Would it be possible to save these values, too?

Btw, when the file has 2400 frames for example and I enter a lower number to "last frame to render" and start the process, Mandelbulber shows "... of 2400" - but 2400 is wrong when the last frame to render is lower.

I also struggle often when I am entering these values - I always type the first value, then the second in animation tab - and every time I have to jump back to the first value as its getting deleted because the end of frames begin with a number smaller than the first...so a time-delay of 3-4 seconds would make sense here in my opinion ( - or completely stopping the end value automatic deleting the first renderframe value).

Many thanks in advance

**Comment by buddhi1980** [comment]
Just fixed both problems
