### ISSUE TITLE
Randomiser dosnt keep up with render mode changes. Latest Nightly.

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#867]
![randomiser](https://user-images.githubusercontent.com/860491/129441011-9ae6530b-4a23-4d22-b99e-695c97984ab6.PNG)

**Comment by degriz** [comment]
Possibly just the preview window ![preview](https://user-images.githubusercontent.com/860491/129441049-01efb02e-7232-4e45-bdcb-b86677ee4ec3.PNG)

**Comment by degriz** [comment]
Carried on using randomiser and evertually crash to desktop.

**Comment by buddhi1980** [comment]
Fixed
