### ISSUE TITLE
Error: Custom formula 1 has missing function name CustomIteration()!

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#868]
i have not had this before

# Mandelbulber settings file
# version 2.26
# only modified parameters
[main_parameters]
ambient_occlusion_enabled true;
background_3_colors_enable false;
background_color_1 5e00 6a00 9d00;
camera -2.47088597853726 -1.30666812866617 0.528768960726534;
camera_distance_to_target 2.8446890394614;
camera_rotation -62.1289610726053 -10.7124049564458 -20.4095597544753;
camera_top -0.00902213729055857 0.389717122262513 0.920890420003453;
constant_DE_threshold true;
DE_factor 0.25;
DE_thresh 0.0025;
delta_DE_function 2;
flight_last_to_render 0;
formula_1 220;
formula_2 10000;
hybrid_fractal_enable true;
image_height 800;
image_proportion 1;
keyframe_last_to_render 0;
light1_is_defined true;
linear_DE_offset 2.5;
mat1_is_defined true;
mat1_specular 4;
mat1_surface_color_gradient 0 fd6029 999 698403 1999 fff59b 2999 f5bd22 3999 2d5529 5000 797979 5999 1d4729 7000 1a551c 7999 0e2110 9000 aba53c;
raytraced_reflections true;
view_distance_max 112.822583521208;
[fractal_1]
beta_angle_offset 2.5;
transf_addition_constant_111 0.9 0.9 -0.05;
transf_addition_constantA_000 0 0 0.2;
transf_minR2_p25 0.2;
transf_rotation 0 1 21;
transf_rotation2 9 5 -53;
transf_rotation2_enabled_false true;
transf_scale_2 1.5;
[fractal_2]
analyticDE_offset_0 1;
analyticDE_scale_1 1.1;
formula_code AAAJy3japZVdj+I2FIavya84XWlWhI9kYNurIZFYCFukme5qdnpRaVepSZzBbYgj20wDw/S399hOujCdHUA1UjD2Oa+f8xHjdzoOdOCGFCnNF+t8QQU8DHtA4N0UMkESRXK4pwUVRHEBEF88PbHOyIN6xDjg2Yjt0LoTXm4Eu18qaE9cGF4OB4dH3VGy0h7h112w27GAjXpGwkcR+GK09cNM9Frsg691TxxfwhGq7oIwvHCtrK8VALV96MeunfhG1gLfLZmEjOUU8LskQgHPDpBt5O4oYMHXYIfAoTkoNmwePnCKh/hmgjP9sMIUSsH/oInS0jlLaCFpCmuUFvDh0/XDOx16fxSGwU5j735vovCtgqQUSC45TD5++m3+y4caswBlmHme1nR/dx/ZRbfbRSfjVy6pYAnWUdvAzXtefYuUi9U6J5DwQhFWSCDrykt4zoVzmI0lkbCgtEADxet+QPrFBhTnufRLXqKOor+yeaFFiWK88MplqWUywVdISa3Um7qtYiVIIbOYpGmclKyieWxQaaw5vaQs39joaB1cQ+unNGMF0ydo9RlE+LnGwGdwa+Y47uCj/opgCnP8YVZ+xulnMHZztI/gB3T3Hec2Gl//CHeGZpymE8Py2aDM8OC50sHiYW2nZU23PWxFTJlUpFAgZzaeSQ6dOrQeyKhSFEubjteV3sC8us5jI5A8QKBT3Q+NSpxc2R0QAjdSrtrJQw+tXFxH227QvIr9cGV7kVcezzJJ1ZXjtFgGbfQcfbOyqcV0TfhqhYVYseJ2WA5/cp0WQmjNTvCKNaluh+kAX5Sjggj45LRoLrETj1NY3XMhhLCn+D6seEqlDfi7jtm6SHS5ooIscpq+nxFN9/atTm4YnELXMvXRfNAeeJcZ9F85ruHso75raN2mJqciTv8X4jHrc2km59M8vpwz9O8fd3+tzSReW3TgmvqfF8XYRPEvm1chnWT3RVvPXaTEDm5nZCHtQu8Iw9hAaKHNntDmudDmDKHtntD2udD2RCGdFkx6/8gNsdV3yOvd0txnN+tcsTJnVAwGpnfwtRsXJN8olsA0AvUXJX8+qwWp96eRR236m+y3zC2HbvV9h7M9hj0/W2novrhpA7msaeqLU/9JHWLov4mJXvfQxEyiQ5rHBsh4m3u16QDEagr6gl7KMnmJw6uu/iOx514hv2mR08Q2V9/l2R7z3do7UVC1FgXgr6d/AFOtExs=;
transf_constant_multiplier_111 0 1 1;
transf_function_enabledA_false true;
transf_function_enabledB_false true;
transf_function_enabledD_false true;
transf_maxR2_1 1.36675555555556;
transf_minR2_p25 0;
transf_rotation2 0 -4.205357 3;
transf_scaleA_1 0.1;

**Comment by buddhi1980** [comment]
Should be 
```REAL4 CustomIteration(REAL4 z, __constant sFractalCl *fractal, sExtendedAuxCl *aux)```
instead of
```REAL4 TransfAddCpixelSphereFoldIteration(REAL4 z, __constant sFractalCl *fractal, sExtendedAuxCl *aux)```

**Comment by mclarekin** [comment]
must have copied formula to custom formulas,   rather than loaded formula
