### ISSUE TITLE
Removing variable from anim timeline issue

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#871]
OK so if you have a variable in the timeline, then remove it, then add it again with a different value, the original value is kept.

**Comment by degriz** [comment]
![de](https://user-images.githubusercontent.com/860491/130813778-169bf034-62b4-4989-a87e-2add93689df7.PNG)

**Comment by buddhi1980** [comment]
Steps to reproduce:
- use keyframe_anim_mandelbulb.example
- delete fractal0_power parameter
- modify this parameter on fractal formula (e.g. change to 3.0)
- add parameter again to the table. This parameter appears with value 7 (from where it comes?)

**Comment by buddhi1980** [comment]
Fixed.
