### ISSUE TITLE
Get Julia Constant 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#88]
Possible enhancement, Once mouse is used to Get Julia Constant, then mouse click function automatically resets to Move The Camera.  Currently I Get Julia Function then try and zoom in forgetting that I have to change back mouse click function, so I  lose my Julia Constant.

**Comment by zebastian** [comment]
hmm, i am not sure this is a good idea.
If I click on the image to get the julia constant and miss the correct point. i probably want to click again and will be confused if the mouse click function changed automatically.
Maybe it would be better to just highlight current mouse click function in some kind of way.
For example:
When function = move camera or function = no action -> no highlight
else -> highlight the combobox in some way

**Comment by buddhi1980** [comment]
In this topic I agree with @mclarekin. I would even do more. When point is selected rendering shoud start automatically. If something will be wrong, the user can use undo button.

**Comment by zebastian** [comment]
ok, when we change to program, so that the image rerenders when julia contant is set. 
do we also want to reset the combobox to 'move camera'? Since the user already knows that he has selected 'get julia constant' since the image just rerendered with new julia constant.

**Comment by zebastian** [comment]
just pushed a possible fix, what do you think about this behaviour?

**Comment by mclarekin** [comment]
Good is what i think about this behaviour

**Comment by zebastian** [comment]
great, than this is fixed
