### ISSUE TITLE
Recent Settings dosnt work

### ISSUE THREAD

**Issue by degriz** [buddhi1980/mandelbulber2#884]
Recent settings dosnt load anything.

**Comment by TasMania17** [comment]
Check the hidden .mandelbulber folder for the "files.recent" text file. Open a saved settings file then close MDBB and see if it appears in the files.recent.

**Comment by buddhi1980** [comment]
In which build this problem occurred?

**Comment by mclarekin** [comment]
reproducible in the win10 dev that i am using

**Comment by buddhi1980** [comment]
it could be caused by partial transition to Qt 6. Do you see any error messages in the console output?

**Comment by degriz** [comment]
Is nightly from last couple days. No error messages.

**Comment by mclarekin** [comment]
happens in ubuntu

Settings file: /home/mclaren/.mandelbulber/mandelbulber_227.ini

Error: No OpenCL devices selected or selected unknown devices!

Selected first available GPU device

Check program preferences to select correct OpenCL devicefrom list of
available GPU devices

Warning: QObject::connect: No such signal
QSignalMapper::mappedString(QString)

((null):0, (null))


Warning: QObject::connect: (receiver name: 'RenderWindow')

((null):0, (null))

**Comment by buddhi1980** [comment]
I know where is the problem. But for correct solution I need to know which Qt version do you have. You can check it with command: qmake --version

**Comment by mclarekin** [comment]
***@***.***:~/Desktop$  qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

**Comment by TasMania17** [comment]
I have MDBB 2.27-dev and I have QT 5.12.8 
Recent settings contain a list but cannot load any of them.

**Comment by buddhi1980** [comment]
Should work now. Problem fixed

**Comment by TasMania17** [comment]
re-compiled, tested, fixed.
