### ISSUE TITLE
Custom formula font size

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#886]
Program preferences

check this out

ubuntu versus win10 Custom formula font size default parameter is different
win10  parameter does not work
ubuntu does not have thread priority menu

![font win10](https://user-images.githubusercontent.com/12769564/135417894-804234cf-19fa-4b04-80a7-b44cbfe3ebe4.JPG)
![font](https://user-images.githubusercontent.com/12769564/135417938-4d203355-54f8-4c84-a888-4c4d504fb114.png)

**Comment by buddhi1980** [comment]
Default font size is system depended. The program uses default value which is reported by the system. Windows can report different size than Linux. Even different distributions of Linux can give different default size. Resolution of display can additionally affect this value on some systems (e.g. on macOS or Linux)

Rendering threads priority on applies to Windows. Linux and MacOS doesn't have thread priorities. They use "nice" levels which are managed much better than on priorities on Windows.

**Comment by mclarekin** [comment]
thanks for clarification

only problem now is that it does not seem to work as i am stuck with a tiny
font??

**Comment by buddhi1980** [comment]
This I'm going to check.

**Comment by mclarekin** [comment]
never mind, it is working ok on win10 now, maybe this option in Program
Preferences only works on the next reload of program

**Comment by mclarekin** [comment]
and is working ok in Ubuntu
