### ISSUE TITLE
Missing progressbar in cli mode

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#89]
After this commit https://github.com/buddhi1980/mandelbulber2/commit/3252bfb58612650b0a41291146a5d725ee66db9f there is no progressbar in cli mode.

**Comment by zebastian** [comment]
i could not reproduce this yet, if i invoke the cli with:
./mandelbulber2 -n /usr/share/mandelbulber2/examples/hybrid003.fract
the progressbar gets displayed correctly AFAI can see.
can you give me an example with broken output?

**Comment by buddhi1980** [comment]
This is what I get:
./mandelbulber2 --nogui settings.fract
![image](https://cloud.githubusercontent.com/assets/11696990/14024935/efcc6e10-f1eb-11e5-82ad-9496811b99af.png)

**Comment by zebastian** [comment]
fixed with  69b6003
