### ISSUE TITLE
crashing to desktop when deleting animation frame files (windows)

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#893]
Michael Benson reports
Bug: Mandelbuler still crashing to desktop when deleting animation frame files (windows). Is also completely failing to save animation setups after said crashes.

apparently bug may have been there for  two years

**Comment by buddhi1980** [comment]
Crashing when deleting is fixed in commit https://github.com/buddhi1980/mandelbulber2/commit/22ee30cc29c10d268443e6b569232dc6a1bcfcd5
