### ISSUE TITLE
Unexpected Behavior But Not A Bug

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#899]
I use this effect in animated fractals but have no idea what causes it. It's something to do with DE and looks like the fractal is animating itself.
To produce this I'm using hybrid fractals that include a number of transforms. I keyframe into a narrow consistent area and that makes it happen.
Please check this unlisted video to what I mean?
https://www.youtube.com/watch?v=x6AxOAYeK2g

If I knew what causes it I could possibly control it a bit more.

**Comment by mclarekin** [comment]
not sure what you mean.
Are you using Detail Level or Constant Detail Size?

**Comment by TasMania17** [comment]
Hi mclarekin. On the two clips in the video link above, detail level is 1.2 and 'connect fractal detail level to image resolution' and 'constant detail size' are not checked. That could be it. The fractals seem to be partly animating themselves with things opening and closing automatically and then disappearing.

**Comment by mclarekin** [comment]
constant detail size will stop things in the distance getting smaller as
you approach them and will reduce color fluctuation.  What are  min and max
view distance set at. It can also be a result of  some DE maths in the
formulas.

**Comment by buddhi1980** [comment]
I definitely looks like artifacts caused by variable DE defined by detail level. As Graeme wrote you should use constant DE threshold, gthen shapes will not change with distance from the camera.

**Comment by mclarekin** [comment]
so if you want to experiment with this effect,  open Advanced quality
settings on render engine tab

**Comment by mclarekin** [comment]
Off topic, can you access fractal forum at the moment?

**Comment by TasMania17** [comment]
Thanks buddhi and mclarekin. I will try the advanced render settings. From an animation perspective (if there is such a thing) you get a lot of free animation effects with some particular settings. I'm using the default material that I have re-colored a few times.
I'm thinking MDBB has unimagined properties waiting to be discovered.
BTW fractal forums working OK here 5pm EST.
I don't use the FB group because they track you too much with marketing. I like looking at it very creative people.

**Comment by mclarekin** [comment]
animating Max detail size could  be interesting


fractalforums.org gives me  the following. Oh well, I will check it again
tomorrow.
Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an
ErrorDocument to handle the request.

**Comment by mclarekin** [comment]
tas
could you message 3dickulus for me and ask him to email me at
***@***.***, it may be to do with my account


Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an
ErrorDocument to handle the request.

**Comment by TasMania17** [comment]
I PM'ed him just now.
My only suggestions - try a different browser or temporarily switch off anti-virus in on Windows. You probably tries that :)
Cheers

**Comment by mclarekin** [comment]
thanks

no i did not try anything,  other than I get the same message on another
laptop again with chrome but ubuntu not winOS, so not anti-virus

ok just tried microsoft bing, same error

**Comment by TasMania17** [comment]
apparently he fixed it and you can log in now

**Comment by mclarekin** [comment]
Thanks  for helping

**Comment by TasMania17** [comment]
Thank you for helping also. It should be OK to call this an alternate keyframing path.

So far the parameters needs are-
Hybrid fractal with transforms before main fractal.
No 'constant detail size' and no 'connect fractal detail level to image resolution'. 
Keyframe into the same area.
This results in Distance estimation morphing the fractal to some extent.

**Comment by FacundoMartinezCampos** [comment]
Hello!, what do you mean with Hybrid fractal with transforms before main fractal, you mean "Testing Transform" in fractal 1 and another fractal in the second slot?, i do need to change something in Transform?,

**Comment by mclarekin** [comment]
a) "Testing Transform" is in the section "experimental do not use", meaning
do not use as it will change and not be usable in future releases (when
finished it will be given a new name and a new formula number. Then I will
reuse Testing Transform to test something new.)

b) From memory, this post was about the difference between options "Detail
Level" versus "Constant Detail Size". How they affect fractal detail in the
distance
