### ISSUE TITLE
Segfault on opening specific file

### ISSUE THREAD

**Issue by jeroenrijckaert** [buddhi1980/mandelbulber2#9]
Current version of Mandelbulber crashes and gives a segmentation fault while opening the attached file. Created with the same version just some minutes ago. Did notice a warning/error:

Warning: slotLogLineEditChanged() error: value from  "logedit_aux_light_visibility"  is not greater zero

**Comment by jeroenrijckaert** [comment]
How do I attach the file ?!
Maybe just change the extension from .fract to .png ... ?
![min1-max2-size1 20-x2](https://cloud.githubusercontent.com/assets/4191197/7216338/1d33db24-e5fc-11e4-9beb-91c17fe5efec.png)

**Comment by buddhi1980** [comment]
How you edit UI files? In some regular text editor or with Qt Designer. 
fractal_buffalo.ui has an error, thats why this settings file doesn't work.

**Comment by jeroenrijckaert** [comment]
This time I used a text editor instead of the QT tools. I did find the mistake while testing, but only fixed the file in /usr/share/mandelbulber2/qt_data instead of the local GIT copy.

With the fixed fractal_buffalo.ui I also had seg fault yesterday. But today with the newest update it seems to be fixed. So I guess the segfault had different causes. Anyway, many thanks for fixing this issue.
