### ISSUE TITLE
netrender - connect clients while rendering

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#90]
when the server already started and a new client connects to the render it does not join the rendering.
Only when a new image is rendered the client receives the job from the server and joins in.

**Comment by buddhi1980** [comment]
I have just tested it. It works very well. I haven't thought that it would be so easy to implement it. It is very good idea to remember message for JOB.

**Comment by zebastian** [comment]
me, too. i had in mind that we already tried to implement this and that the hassle was so big that we abandoned the idea.
but this time it worked just like that. glad we got this from the list.
for the next release we should also check netrender, but i dont expect that much side effects.

**Comment by buddhi1980** [comment]
Now I'm rendering animation using NetRender so it will be intensively tested.

**Comment by zebastian** [comment]
Cool, drop me a link when animation is ready
