### ISSUE TITLE
revisit  case analyticFunctionLogarithmic:

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#917]
This is a reminder to look further into this. For now i will just add to this issue as i remember where  if (extendedAux.r > 1.0)  causes some problems
This has not been updated for hybrid mode.  THIS IS GOOD FOR NOW as it allows easy testing

					case analyticFunctionLogarithmic:
					{
						if (extendedAux.r > 1.0)
							out->distance = 0.5 * r * log(r) / extendedAux.DE;
						else
							out->distance = 0.0;
						break;
					}

**Comment by buddhi1980** [comment]
Thanks for showing me this. I forgot u update it for hybrids
