### ISSUE TITLE
I Broke About - news 

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#926]
making sure you do not miss this 

https://github.com/buddhi1980/mandelbulber2/commit/dceef6cc26cfc159524cb93de07c9f08c9d20034

**Comment by mclarekin** [comment]
I am going crazy , seems to be working now??

**Comment by mclarekin** [comment]
i know what is happening now. it works in Windows appveyor build but not in QT ubuntu where it is blank

**Comment by mclarekin** [comment]
also maybe??   move  save New and delete New down the list to between Program Preferences and Quit. As they probably not t used often

**Comment by buddhi1980** [comment]
The problem is in "perate to development" scrips which do not link NEWS file. So this problem is visible on your machine with Ubuntu. If I have a time I will correct these scripts.
