### ISSUE TITLE
Generate Thumbnail problem

### ISSUE THREAD

**Issue by MD55DM** [buddhi1980/mandelbulber2#928]
Mandelbulber 2.28 DEV (download date: 09  JUL 2022)
Win 11 64 bit

Issue:

Problem using the Thumbnail "Generate" option.

If I run the File > Program Preferences > Image TAB > Generate Thumbnail to save a preview image of the various scenes in the Settings folder, they are rendered but, after that, the attempt to load a settings using File > Load Settings most of the time require a new Thumbnail render to display the Settings preview image.

Tried by using Render Thumbnail using OpenCL

Thumbnails rendered using File > Load Settings are affectively saved and available for further loading.

This problem does not occur with version 2.27 and older.

**Comment by buddhi1980** [comment]
Thanks for reporting it. Probably I already know where is the problem in te code.

**Comment by buddhi1980** [comment]
Bug fixed. Thumbnails were rendered using wrong resolution.

**Comment by MD55DM** [comment]
Thanks for the quick fix. Problem solved using latest DEV release.
