### ISSUE TITLE
keyframe table add button to generate dummy frames

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#931]
for cubic interpolations

enable dummy keyframes button to populate animation table with keyframes -2 and -1

For keyframes animation 0 to n

1)  enable loop button automatically populates table  or  maybe just manually copy
 kf n   is a copy of   kf 0,
 kf n+1   is a copy of   kf 1,
  kf n+2   is a copy of   kf 2,
 kf  -2   is a copy of  kf  n-2
 kf  -1   is a copy of   kf  n-1

2) no loop,. control initial direction of cubic with keyframes -2 and -1

**Comment by buddhi1980** [comment]
Instead of button to add dummy keyframes, I have added an option for looping the animation internally in the morphing routines. At the first frames it takes keyframes from the end and at the end it takes frames from the start.
