### ISSUE TITLE
Material picking bug with OpenCL

### ISSUE THREAD

**Issue by bezo97** [buddhi1980/mandelbulber2#935]
##### System information (version)
- mandelbulber2 => 2.28
- Operating System / Platform => Windows 64 Bit
- OpenCL Device: nvidia gtx 970

##### Detailed description

Material picking with OpenCL mode does not work correctly. Selecting any material is not applied on the objects, they are rendered with the same default material. This applies to both the fractal and primitives. Seemingly the materials are assigned correctly in the editor, but the image is rendered incorrectly.

##### Steps to reproduce

- Load one of the default settings, such as the menger sponge
- Make sure OpenCL mode is enabled (medium)
- The fractal renders fine with the default material
- Now go to `Objects` / `Global Parameters`, click on the material image under `Material for fractal` to pick a new material
- In the material manager dialog, load one of the presets, such as base.fract
- Close the material manager, the selected material is assigned to the fractal
- Click on render to see the bug

Expected behaviour: The fractal should be rendered with the selected base material.
Actual behaviour: The fractal should be rendered with the default material which is not assigned.
![image](https://user-images.githubusercontent.com/26039350/193449448-6b313711-ba68-475a-9d05-965795f33080.png)

You can select cpu-only mode to see how it should look.

Thanks in advance for looking at this issue! -bezo

**Comment by bezo97** [comment]
A bit of further investigation, the same bug is present in previous verisons. I checked back until v2.25. Maybe a driver related thing?

**Comment by buddhi1980** [comment]
"Medium" OpenCL mode is a very simplified rendering engine (but faster). It uses only first material. To render scene with all materials you need to use "full" engine.

**Comment by bezo97** [comment]
Thanks for the clarification!
