### ISSUE TITLE
Background texture is mirrored

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#94]
Needed to check if the same problem was in older versions. If yes, then there is needed to provide compatibility.

**Comment by mclarekin** [comment]
Might be the same for old Environment mappring (mapping spellcheck in UI)

But again keep for backwards compatibility as the new Materials Manager
supersedes these old features

**Comment by buddhi1980** [comment]
If you find any spelling mistakes in UI, just correct them and commit changes.

**Comment by mclarekin** [comment]
I was surprised it existed, I had thought we had got all the old ones:)

**Comment by buddhi1980** [comment]
Fixed by commit https://github.com/buddhi1980/mandelbulber2/commit/c46255b68ddd34ac06e644ccdaa8376a18af551c
