### ISSUE TITLE
question about randomizer

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#951]
Not an issue but is there a basic explanation of how randomizer works?
I use it sometimes and have found it quite good but have no idea what it is doing. Last time I had it in heavy mode and the suggestion when used deleted the slot 1 fractal and substituted with 'testing.log'.

**Comment by mclarekin** [comment]
A short answer. Randomizes parameters of chosen tab. Slight will pick and randomize one parameter, medium 4 parameters chosen to randomize, heavy randomises a lot. So randomize parameters with random number generator, within some constraints. Hover mouse over one of the 12  rendered images and you can see what parameters were chosen and what values were changed to. It is a "basic" tool, it could be much more complex, but of low priority

**Comment by TasMania17** [comment]
Thanks mclarekin. It's good to have an understanding of what it does. I've been using the top randomizer that processes multiple slots. I now realize running it more than once will produce different results. I agree keep it low priority because it could become a bit of a monster. 
( change the dice icon for a poker machine icon  :) )
I should also use the 'Navi' tab more.
 Thanks guys for including randomizer.
