### ISSUE TITLE
Enhance window management

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#96]
Be good to be able to save more than one Window State, ie so I can have one for animation.

with increasing UI a more sophisticated window management would be great.
Under blender there are window presets like 'Default', 'Video Editing', 'Compositing'
Would be great to do something in that way.

**Comment by zebastian** [comment]
animation layout done here: cc9f9bd797097c40a12a25715993567e92ff1ed7
@all do you have ideas for more window presets?

**Comment by buddhi1980** [comment]
About animation layout: would be good if Image Adjustments, Effects, Rendering engine and Fractal docks will be stacked. Materials could below (this is small).
This would work better for lower resolution displays (more space for animation frames).

This can be achieved using QMainWindow::tabifyDockWidget http://doc.qt.io/qt-5/qmainwindow.html#tabifyDockWidget
Example:

![image](https://cloud.githubusercontent.com/assets/11696990/21690579/31250186-d375-11e6-88c5-60fa68cbc22d.png)

**Comment by buddhi1980** [comment]
Another approach for this problem would be to add option to load/save files with ui layouts. Then it will be customizable

**Comment by zebastian** [comment]
would be possible, but this makes it way more complicated:
- what about mandelbulber version upgrades, are the saved ui settings compatible?
- difficult for users to get used to (even in blender it feels complicated with user defined presets)

**Comment by zebastian** [comment]
anyway presets are very easy to implement and have a good learning curve for new users to see the full feature set of the program. I would first focus on implementing those and then add the ability for self defined window settings

**Comment by buddhi1980** [comment]
Now looks much better :) Thanks. 
About saved ui settings, they should be compatible. As I observe they doesn't need to be upgraded when we change ui files. They are already used to store window state.

**Comment by zebastian** [comment]
despite my complaining this wasn't so hard to implement after all and feels pretty much straight forward:
https://github.com/buddhi1980/mandelbulber2/commit/5746d4b55c39f7b4fdee79a40ac85e8e7ab8097d
Still we need some more good presets...

**Comment by buddhi1980** [comment]
This solution a good idea. However something doesn't work. I have tried to add some presets, but they doesn't appear in pull-down-menu. I can only see new files (with hash codes in filenames) in .mandelbulber/customWindowState/ folder. They also doesn't appear when I restart the application.

**Comment by buddhi1980** [comment]
It's funny, but I just haven't realized that it already works. The problem was in appearance of new menu items. They were grey, so they ware not so visible. Is it possible to make them appear like regular menu items?

![image](https://cloud.githubusercontent.com/assets/11696990/21760868/9782e63c-d64f-11e6-9fb0-3533aa3a2d1b.png)

**Comment by zebastian** [comment]
These are full line buttons in order to mess with the qaction system and allow two different actions (delete item / load item) on one. Now i further manipulated the QPushButton, so now it looks properly.

**Comment by zebastian** [comment]
nothing i can hide from you :)

**Comment by zebastian** [comment]
can we close this off?

**Comment by buddhi1980** [comment]
I think we can.
