### ISSUE TITLE
Debian experimental - upgrade of qtlibs

### ISSUE THREAD

**Issue by TasMania17** [buddhi1980/mandelbulber2#968]
Looks like Debian is pushing-out qt6 as a replacement for qt5.
Initial compile error:
'Package qtcreator is not available, but is referred to by another package.'
I looked at the deps of qtcreator and there are many. Would it be advisable to update these qt files?

**Comment by buddhi1980** [comment]
It is a transition time in Debian Testing. I also saw that qtcreator is not available now for instalation because of llvm-defaults package. I would wait few days until this issue will be solved. However 
QtCreator is not needed to run Mandelbulber. Just only for editing the code.
