### ISSUE TITLE
Background flat mapping controls

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#97]
Add controls for scaling and orientating flat map background

**Comment by mclarekin** [comment]
also ability to have a flat map  to the forefront with transparency  parameter
![mandelbox dreams 800](https://cloud.githubusercontent.com/assets/12769564/22129040/94c3c6de-df08-11e6-86ad-0ec3a61a70c9.jpg)

**Comment by buddhi1980** [comment]
@mclarekin, I have added scaling and rotation of background texture (also flat). Please check if this works for you

**Comment by mclarekin** [comment]
scale works well

gamma angle works well (this is for when the original photo is not aligned
parallel to the horizon which can make the clouds look wrong)

But is it possible to have horiz & vert shifts to move the  flat background
in respect to the  camera. Example,  using  mandelbulber set to 3200 x
2400,  with a 5472 x 3648 background, then being able to move the
background to choose which part of the 5472 x 3648 background will be seen
in my 3200 x 2400 image

**Comment by mclarekin** [comment]
I see that I can "kind of"use equirectangular mode to view different parts
of the background jpg

**Comment by buddhi1980** [comment]
@mclarekin Now you have more controls. There are additionally texture offset sliders. You should like it.

**Comment by mclarekin** [comment]
Successfully chose the area of the photo to be used in the background  :)

Successfully animated clouds slowly drifting in the background of the
fractal :)

there are also various tiling backgrounds effects that can now be done
using theses new controls :)


Other enhancements to Background Tab i know of :

- choose single color background  option

- enable  control of the 3 color option. i.e width of color bands and
orientation of color bands. Examples:
                being able to narrow the middle band and move the location
of the middle band  so it is closer to the top band and further away from
bottom band
                being able to scale, rotate, offset the 3 color background
on the Background tab, like it was an image

- there is more complicated effects as well.

**Comment by mancoast** [comment]
These special effects look really wonderful!
I would love to see an 8k EXR film of fractal clouds!

**Comment by mclarekin** [comment]
@ rob, my clouds are not realistic as they are a static image moving, BUT
clouds can be implemented some time in the future as well as some  cool
fog  effects.

@ krzysztof. my comments about bands may be  a bit confusing.

Example.Top color 1 is red, and the bottom color 3 is blue, and we want to
transition through middle color 2 (yellow).
There are various ways of controlling  the transition with logarithmic
algorithms.  Maybe for V2.16 or later. It is not important.

So I guess this is now another closed minor  issue :)
