### ISSUE TITLE
Enable locking of Detail Level settings to image resolution settings

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#98]
Taurus has been asking for this for sometime.

I  suggest a checkbox that allows the user to connect Detail Level  to image resolution so Detail Level change is proportion to image resolution,

There would be identical checkboxes on both Render_engine and Image_adjustment tabs, that update each other.

Not sure on label - lock, free, connect

**Comment by buddhi1980** [comment]
For this there will be some work to do. I would leave this for next release.

**Comment by mclarekin** [comment]
cool,
when user is ready for final render, 
go to Image_adjustments
Choose to enable "connect"
Increase resolution & render

Having identical checkbox in Rendering _engine next to Detail_level, will help user remember that the function has been enabled.
V2.09

**Comment by buddhi1980** [comment]
Partially implemented by commit https://github.com/buddhi1980/mandelbulber2/commit/bc4803527244812c8cdfeb4d69590b4bdbe2d277

**Comment by buddhi1980** [comment]
@mclarekin, this enhancement is already implemented. Could you check it and tell if it is what you wanted to have?

**Comment by mclarekin** [comment]
Yes that is it. Only comment would be move it above "constant detail size"
on the rendering engine dock

On Sat, Sep 17, 2016 at 6:17 AM, Krzysztof Marczak <notifications@github.com
