### ISSUE TITLE
A individual boolean tab & automatic hybrid mode

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#99]
Suggest give Boolean it's own tab between Hybrid and Primitives, as there is currently room. This will make it easier to locate.H'mm??

BTW.  We could also implement hybrid mode by the logic:-

```
         if (more than one slot is enabled ) mode == hybrid mode
```

and have a boolean/hybrid switch on the UI to  change between modes

**Comment by buddhi1980** [comment]
I have found another solution. It's implemented in latest commit:

https://github.com/buddhi1980/mandelbulber2/commit/dfada001835fafaacf1eeb4b3139d527511db184

Try to select any disabled tab. You will see what is done.

**Comment by mancoast** [comment]
CONFIRMED WIN64 WIN32 CENTOS7X64

Well done!
![image](https://cloud.githubusercontent.com/assets/7040493/23826621/f125a3de-066d-11e7-967d-95f885fe48b7.png)

**Comment by mclarekin** [comment]
It is a good solution

Here is a different solution to address this and  the w issue to consider
